import assert from "node:assert/strict";
import test from "node:test";
import { sha256 } from "../src/bundle.js";
import { auditMapping, catalogFingerprint, deterministicRows, jsonSafe, mappingSkeleton, snapshotId, validateSnapshot } from "../src/snapshot.js";

const columns=[{name:"id",data_type:"integer",udt_name:"int4",nullable:false,primary_key_position:1},{name:"occurred_at",data_type:"timestamp with time zone",udt_name:"timestamptz",nullable:false,primary_key_position:null}];
function snapshot(){const rows=deterministicRows([{id:2,occurred_at:new Date("2026-09-10T02:00:00Z")},{id:1,occurred_at:new Date("2026-09-10T01:00:00Z")}]),tables=[{table:"entries",disposition:"staged_for_mapping" as const,columns,row_count:rows.length,rows,sha256:sha256(rows)}],catalog_fingerprint=catalogFingerprint(tables),source_instance="ledger-fixture";return{protocol:"shadow.legacy-snapshot" as const,snapshot_id:snapshotId({source_instance,catalog_fingerprint,tables}),source_instance,exported_at:"2026-09-10T03:00:00Z",database:"postgresql" as const,isolation:"repeatable read read only" as const,catalog_fingerprint,excluded_tables:[],tables};}

test("PostgreSQL values become deterministic JSON without losing instants or bytes",()=>{assert.deepEqual(jsonSafe({at:new Date("2026-09-10T01:02:03Z"),counter:1n,bytes:Buffer.from("x")}),{at:"2026-09-10T01:02:03.000Z",counter:"1",bytes:{encoding:"base64",data:"eA=="}});assert.deepEqual(deterministicRows([{id:2},{id:1}]),[{id:1},{id:2}]);});
test("snapshot identity covers catalog, row counts and exact table hashes",()=>{const value=snapshot();assert.deepEqual(validateSnapshot(value),value);assert.throws(()=>validateSnapshot({...value,tables:[{...value.tables[0]!,rows:[{id:1,occurred_at:"changed"},{id:2,occurred_at:"2026-09-10T02:00:00.000Z"}]}]}),/table hash mismatch/u);assert.throws(()=>validateSnapshot({...value,catalog_fingerprint:"0".repeat(64)}),/catalog fingerprint/u);});
test("mapping skeleton is complete but remains honestly blocked",()=>{const value=snapshot(),review=mappingSkeleton(value,"fixture-v1"),audit=auditMapping(value,review);assert.equal(audit.coverage_complete,true);assert.equal(audit.ready,false);assert.equal(audit.blocked_tables,1);});
test("every included table and field needs an explicit native mapping",()=>{const value=snapshot(),review={protocol:"shadow.legacy-mapping-review" as const,snapshot_id:value.snapshot_id,source_instance:value.source_instance,mapper_version:"fixture-v1",tables:[{name:"entries",disposition:"native" as const,mapping_key:"ledger.entries.v1",reason:"Map the active ledger fact.",columns:[{name:"id",disposition:"source_identity" as const,target:"money_entries.id",reason:"Stable source identity."},{name:"occurred_at",disposition:"native_field" as const,target:"money_entries.occurred_at",reason:"Preserve the exact instant."}]}]},audit=auditMapping(value,review);assert.equal(audit.ready,true);assert.equal(audit.native_tables,1);const missing={...review,tables:[{...review.tables[0]!,columns:review.tables[0]!.columns.slice(0,1)}]};assert.equal(auditMapping(value,missing).ready,false);assert.match(auditMapping(value,missing).gaps[0]!,/occurred_at/u);});
