import assert from "node:assert/strict";
import test from "node:test";
import { sha256 } from "../src/bundle.js";
import { auditMapping, catalogFingerprint, deterministicRows, inspectSnapshot, jsonSafe, mappingSkeleton, snapshotId, validateSnapshot } from "../src/snapshot.js";

const columns=[{name:"id",data_type:"integer",udt_name:"int4",nullable:false,primary_key_position:1},{name:"occurred_at",data_type:"timestamp with time zone",udt_name:"timestamptz",nullable:false,primary_key_position:null}];
function snapshot(){const rows=deterministicRows([{id:2,occurred_at:new Date("2026-09-10T02:00:00Z")},{id:1,occurred_at:new Date("2026-09-10T01:00:00Z")}]),tables=[{schema:"public",table:"entries",disposition:"staged_for_mapping" as const,columns,row_count:rows.length,rows,sha256:sha256(rows)}],catalog_fingerprint=catalogFingerprint(tables),source_instance="ledger-fixture";return{protocol:"shadow.legacy-snapshot" as const,snapshot_id:snapshotId({source_instance,catalog_fingerprint,tables}),source_instance,exported_at:"2026-09-10T03:00:00Z",database:"postgresql" as const,isolation:"repeatable read read only" as const,catalog_fingerprint,excluded_tables:[],tables};}

test("PostgreSQL values become deterministic JSON without losing instants or bytes",()=>{assert.deepEqual(jsonSafe({at:new Date("2026-09-10T01:02:03Z"),counter:1n,bytes:Buffer.from("x")}),{at:"2026-09-10T01:02:03.000Z",counter:"1",bytes:{encoding:"base64",data:"eA=="}});assert.deepEqual(deterministicRows([{id:2},{id:1}]),[{id:1},{id:2}]);});
test("snapshot identity covers catalog, row counts and exact table hashes",()=>{const value=snapshot();assert.deepEqual(validateSnapshot(value),value);assert.throws(()=>validateSnapshot({...value,tables:[{...value.tables[0]!,rows:[{id:1,occurred_at:"changed"},{id:2,occurred_at:"2026-09-10T02:00:00.000Z"}]}]}),/table hash mismatch/u);assert.throws(()=>validateSnapshot({...value,catalog_fingerprint:"0".repeat(64)}),/catalog fingerprint/u);});
test("mapping skeleton is complete but remains honestly blocked",()=>{const value=snapshot(),review=mappingSkeleton(value,"fixture-v1"),audit=auditMapping(value,review);assert.equal(audit.coverage_complete,true);assert.equal(audit.ready,false);assert.equal(audit.blocked_tables,1);});
test("every included table and field needs an explicit native mapping",()=>{const value=snapshot(),review={protocol:"shadow.legacy-mapping-review" as const,snapshot_id:value.snapshot_id,source_instance:value.source_instance,mapper_version:"fixture-v1",tables:[{name:"entries",disposition:"native" as const,mapping_key:"ledger.entries.v1",reason:"Map the active ledger fact.",columns:[{name:"id",disposition:"source_identity" as const,target:"money_entries.id",reason:"Stable source identity."},{name:"occurred_at",disposition:"native_field" as const,target:"money_entries.occurred_at",reason:"Preserve the exact instant."}]}]},audit=auditMapping(value,review);assert.equal(audit.ready,true);assert.equal(audit.native_tables,1);const missing={...review,tables:[{...review.tables[0]!,columns:review.tables[0]!.columns.slice(0,1)}]};assert.equal(auditMapping(value,missing).ready,false);assert.match(auditMapping(value,missing).gaps[0]!,/occurred_at/u);});
test("schema-qualified tables remain distinct and visible to mapping review",()=>{const base=snapshot(),health={...base.tables[0]!,schema:"health",table:"entries"},tables=[base.tables[0]!,health],catalog_fingerprint=catalogFingerprint(tables),source_instance=base.source_instance;const value={...base,tables,catalog_fingerprint,snapshot_id:snapshotId({source_instance,catalog_fingerprint,tables})};const review=mappingSkeleton(value,"fixture-v2");assert.deepEqual(review.tables.map(table=>table.name),["entries","health.entries"]);assert.deepEqual(validateSnapshot(value).tables.map(table=>table.schema),["public","health"]);});
test("snapshot inspection reports schema and inclusion totals without row payloads",()=>{const base=snapshot(),excluded={...base.tables[0]!,schema:"health",table:"browser_sessions",disposition:"excluded_session_or_identity_secret" as const,row_count:0,rows:[],sha256:null},tables=[base.tables[0]!,excluded],catalog_fingerprint=catalogFingerprint(tables),source_instance=base.source_instance,value={...base,tables,catalog_fingerprint,snapshot_id:snapshotId({source_instance,catalog_fingerprint,tables})},report=inspectSnapshot(value);assert.deepEqual(report.totals,{tables:2,columns:4,rows:2,included_tables:1,included_rows:2,excluded_tables:1});assert.deepEqual(report.schemas.map(schema=>[schema.name,schema.included_tables,schema.excluded_tables]),[["health",0,1],["public",1,0]]);assert.deepEqual(report.tables.map(table=>table.name),["entries","health.browser_sessions"]);assert.equal(JSON.stringify(report).includes("occurred_at"),false);});
test("source-bound runtime tables are excluded explicitly and remain auditable",()=>{const base=snapshot(),runtime={...base.tables[0]!,schema:"health",table:"sync_cursors",disposition:"excluded_runtime_state" as const,row_count:0,rows:[],sha256:null},tables=[base.tables[0]!,runtime],catalog_fingerprint=catalogFingerprint(tables),source_instance=base.source_instance,value={...base,tables,catalog_fingerprint,snapshot_id:snapshotId({source_instance,catalog_fingerprint,tables}),excluded_tables:["health.sync_cursors"]},review=mappingSkeleton(value,"fixture-v3"),audit=auditMapping(value,review);assert.equal(review.tables[1]!.disposition,"excluded_runtime_state");assert.equal(review.tables[1]!.columns[0]!.disposition,"excluded_runtime_state");assert.equal(audit.coverage_complete,true);assert.equal(audit.ready,false);assert.equal(audit.excluded_tables,1);assert.equal(audit.blocked_tables,1);const invalid={...review,tables:review.tables.map(table=>table.name==="health.sync_cursors"?{...table,disposition:"historical_archive" as const,mapping_key:"unsafe.runtime.v1"}:table)};assert.equal(auditMapping(value,invalid).ready,false);assert.match(auditMapping(value,invalid).gaps.join("\n"),/runtime state table must remain excluded/u);});
