package com.shadow.life

import android.graphics.BitmapFactory
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.LocalDate
import kotlin.math.abs

private val healthTabs=listOf("overview" to "健康","body" to "身体","activity" to "运动","sleep" to "睡眠")
private val mealOrder=listOf("breakfast","lunch","dinner","snack","other")
private val ActivityGreen=Color(0xFF7CEB52)
private val ActivityBlue=Color(0xFF48A9FF)
private val ActivityPurple=Color(0xFFB285FF)
private val BodyOrange=Color(0xFFFF9F43)
private val SleepPurple=Color(0xFFA982FF)
private val MealCoral=Color(0xFFFF806F)

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun HealthWorkspaceScreen(
  overviewState:LoadState<WorkspaceOverview>,recordsState:LoadState<RecordPage>,deviceStatus:DeviceSyncStatus,queueState:LoadState<QueueSummary>,samsungAvailable:Boolean,
  onRetry:()->Unit,onLoadMore:()->Unit,onBack:()->Unit,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit,
  onHealthSync:()->Unit,onSamsungSync:()->Unit,onScale:()->Unit,onSettings:()->Unit,onMeals:()->Unit
){
  var tab by rememberSaveable{mutableStateOf("overview")}
  val overview=(overviewState as? LoadState.Ready)?.value as? WorkspaceOverview.Health
  Scaffold(containerColor=MaterialTheme.colorScheme.background,topBar={TopAppBar(
    title={Column{Text("健康");Text(healthSourceLine(overview),style=MaterialTheme.typography.labelMedium,color=healthSourceColor(overview))}},
    navigationIcon={IconButton(onClick=onBack){Text("‹",style=MaterialTheme.typography.headlineLarge)}},
    actions={IconButton(onClick=onSettings){Icon(Icons.Default.Settings,"健康数据与设备设置")}}
  )}){padding->
    LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(horizontal=20.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){
      item{Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){healthTabs.forEach{(key,label)->FilterChip(selected=tab==key,onClick={tab=key},label={Text(label)})};FilterChip(selected=false,onClick=onMeals,label={Text("饮食")})}}
      item{StateContent(overviewState,onRetry){} }
      if(overview!=null){
        when(tab){
          "body"->item{BodyMetricsWorkspace(overview.metrics,onDetail,onCapture)}
          "activity"->item{ActivityWorkspace(overview.history,onDetail,onCapture)}
          "sleep"->item{SleepWorkspace(overview.history)}
          else->{item{DailyActivityHero(overview.daily,onCapture)};item{HealthOverviewCards(overview,{tab=it},onMeals)};item{BodyCompositionStrip(overview.metrics){tab="body"}}}
        }
        item{CompactDeviceStatus(deviceStatus,queueState,samsungAvailable,onHealthSync,onSamsungSync,onScale,onSettings)}
      }
      if(tab=="overview"){
        item{Text("最近健康记录",style=MaterialTheme.typography.titleLarge)}
        item{StateContent(recordsState,onRetry){} }
        if(recordsState is LoadState.Ready){items(recordsState.value.items.take(8).size){index->val record=recordsState.value.items[index];RecordRow(record){onDetail(LifeDomain.Health,record.detailId?:record.id,record.title)}};if(recordsState.value.nextCursor!=null)item{TextButton(onClick=onLoadMore,Modifier.fillMaxWidth()){Text("加载更多健康记录")}}}
      }
      item{Spacer(Modifier.height(12.dp))}
    }
  }
}

@Composable private fun DailyActivityHero(daily:HealthDailyOverview?,onCapture:(CaptureKind)->Unit){HealthSurface{
  Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("今日活动",style=MaterialTheme.typography.titleLarge);Text(daily?.occurredOn?:LocalDate.now().toString(),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Workout)}){Icon(Icons.Default.Add,"记录训练")}}
  Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(18.dp)){TripleActivityRings(daily,Modifier.size(150.dp));Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(13.dp)){RingLegend("步数",daily?.steps?.toString()?:"—","步",ActivityGreen);RingLegend("活跃时间",daily?.activeMinutes?.toString()?:"—","分钟",ActivityBlue);RingLegend("活动热量",daily?.caloriesKcal?:"—","kcal",ActivityPurple)}}
  Text("圆环使用固定参考刻度：10,000 步、60 分钟、500 kcal；不是个人目标，也不补造缺失数据。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
}}

@Composable private fun TripleActivityRings(daily:HealthDailyOverview?,modifier:Modifier){
  val progress=listOf(((daily?.steps?:0L)/10_000f).coerceIn(0f,1f),((daily?.activeMinutes?:0L)/60f).coerceIn(0f,1f),((daily?.caloriesKcal?.toFloatOrNull()?:0f)/500f).coerceIn(0f,1f));val colors=listOf(ActivityGreen,ActivityBlue,ActivityPurple);val track=MaterialTheme.colorScheme.outline.copy(alpha=.24f)
  Box(modifier,contentAlignment=Alignment.Center){Canvas(Modifier.fillMaxSize()){colors.forEachIndexed{index,color->val inset=index*15.dp.toPx()+6.dp.toPx();val arcSize=Size(size.width-inset*2,size.height-inset*2);val stroke=Stroke(9.dp.toPx(),cap=StrokeCap.Round);drawArc(track,-90f,360f,false,Offset(inset,inset),arcSize,style=stroke);drawArc(color,-90f,360f*progress[index],false,Offset(inset,inset),arcSize,style=stroke)}};Column(horizontalAlignment=Alignment.CenterHorizontally){Text(daily?.workouts?.takeIf{it>0}?.toString()?:"—",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.SemiBold);Text("次运动",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
}

@Composable private fun RingLegend(label:String,value:String,unit:String,color:Color){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).clip(CircleShape).background(color));Spacer(Modifier.width(9.dp));Column{Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Row(verticalAlignment=Alignment.Bottom){Text(value,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.SemiBold);Spacer(Modifier.width(4.dp));Text(unit,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}

@OptIn(ExperimentalLayoutApi::class)
@Composable private fun HealthOverviewCards(overview:WorkspaceOverview.Health,onTab:(String)->Unit,onMeals:()->Unit){LifeSection("今天一眼看懂"){FlowRow(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp),maxItemsInEachRow=2){
  OverviewModule("睡眠",overview.daily?.sleepMinutes?.let(::minutesLabel)?:"尚未同步",overview.daily?.sleepSource?.let(::sourceLabel)?:"查看分期与近 7 天",SleepPurple,{onTab("sleep")},Modifier.weight(1f));val weight=overview.metrics.firstOrNull{it.key=="weight"}?.points?.lastOrNull();OverviewModule("身体",weight?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"尚未测量",weight?.occurredOn?:"体重与身体成分",BodyOrange,{onTab("body")},Modifier.weight(1f));OverviewModule("运动",overview.daily?.workouts?.takeIf{it>0}?.let{"$it 次"}?:"今日无记录","三星健康运动字段与名称",ActivityGreen,{onTab("activity")},Modifier.weight(1f));OverviewModule("饮食","餐照与营养","按早餐、午餐、晚餐查看",MealCoral,onMeals,Modifier.weight(1f))
}}}

@Composable private fun OverviewModule(title:String,value:String,note:String,tone:Color,onClick:()->Unit,modifier:Modifier=Modifier){Surface(modifier.heightIn(min=118.dp).clickable(role=Role.Button,onClick=onClick),shape=RoundedCornerShape(24.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(17.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Box(Modifier.width(28.dp).height(4.dp).clip(CircleShape).background(tone));Text(title,style=MaterialTheme.typography.labelLarge,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleLarge,maxLines=1,overflow=TextOverflow.Ellipsis);Text(note,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=2)}}}

@Composable private fun BodyCompositionStrip(metrics:List<HealthMetricTrend>,onSelect:()->Unit){val visible=bodySnapshotMetrics(metrics);LifeSection("身体成分",action={TextButton(onClick=onSelect){Text("完整分析")}}){if(visible.none{it.points.isNotEmpty()})ChartEmpty("体脂秤或 Samsung Health 同步后，在这里形成身体成分卡片") else Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(10.dp)){visible.forEachIndexed{index,metric->val latest=metric.points.lastOrNull();Surface(Modifier.width(152.dp).clickable(role=Role.Button,onClick=onSelect),shape=RoundedCornerShape(22.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(metric.label,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.labelLarge);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.titleLarge,maxLines=1);MiniTrend(metric.points,Modifier.fillMaxWidth().height(48.dp),bodyTone(index));Text(latest?.sourceKind?.let(::sourceLabel)?:"等待同步",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}}

@Composable private fun BodyMetricsWorkspace(metrics:List<HealthMetricTrend>,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){
  var metricKey by rememberSaveable{mutableStateOf("weight")};var days by rememberSaveable{mutableIntStateOf(30)};val available=metrics.filter{!it.unavailable};val metric=available.firstOrNull{it.key==metricKey}?:available.firstOrNull();val cutoff=LocalDate.now().minusDays(days.toLong()-1);val shown=metric?.points.orEmpty().filter{runCatching{LocalDate.parse(it.occurredOn)>=cutoff}.getOrDefault(true)};val latest=shown.lastOrNull()?:metric?.points?.lastOrNull();val first=shown.firstOrNull();val average=shown.map{it.value}.average().takeUnless{it.isNaN()}
  Column(verticalArrangement=Arrangement.spacedBy(18.dp)){
    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){available.forEach{item->FilterChip(metricKey==item.key,{metricKey=item.key},{Text(item.label)})}}
    HealthSurface(onClick=latest?.let{{onDetail(LifeDomain.Health,it.id,"${metric?.label}记录")}}){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("${metric?.label?:"身体指标"}变化",style=MaterialTheme.typography.titleLarge);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.SemiBold);Text(latest?.let{"${it.occurredOn} · ${sourceLabel(it.sourceKind)}"}?:"等待设备同步或手动补记",color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Health)}){Icon(Icons.Default.Add,"添加记录")}};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf(7,30,90).forEach{value->FilterChip(days==value,{days=value},{Text("$value 天")})}};if(shown.isEmpty())ChartEmpty("所选期间没有${metric?.label.orEmpty()}数据") else {TrendChart(shown,Modifier.fillMaxWidth().height(210.dp),BodyOrange);ChartDateRange(shown.first().occurredOn,shown.last().occurredOn)};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){SummaryFact("平均",average?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f));SummaryFact("最低",shown.minOfOrNull{it.value}?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f));SummaryFact("最高",shown.maxOfOrNull{it.value}?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f))};if(first!=null&&latest!=null&&first.id!=latest.id)Text("期间变化 ${signed(latest.value-first.value)} ${unitLabel(latest.unit)} · ${shown.size} 个真实测量点",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
    LifeSection("最近一次身体成分"){val snapshot=bodySnapshotMetrics(metrics);Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(10.dp)){snapshot.forEachIndexed{index,item->BodySnapshotCard(item,bodyTone(index)){item.points.lastOrNull()?.let{onDetail(LifeDomain.Health,it.id,"${item.label}记录")}}}}}
    LifeSection("测量历史"){if(shown.isEmpty())EmptyState("没有可显示的真实测量点") else shown.asReversed().take(12).forEach{point->Surface(Modifier.fillMaxWidth().clickable(role=Role.Button){onDetail(LifeDomain.Health,point.id,"${metric?.label}记录")},shape=RoundedCornerShape(18.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.42f)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(point.occurredOn,style=MaterialTheme.typography.titleMedium);Text(sourceLabel(point.sourceKind),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text("${point.valueText} ${unitLabel(point.unit)}",style=MaterialTheme.typography.titleMedium)}}};Text("变化只描述测量结果，不自动推断饮食、训练和体重之间的因果关系。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
  }
}

@Composable private fun BodySnapshotCard(metric:HealthMetricTrend,tone:Color,onClick:()->Unit){val latest=metric.points.lastOrNull();val previous=metric.points.dropLast(1).lastOrNull();Surface(Modifier.width(172.dp).heightIn(min=148.dp).clickable(role=Role.Button,onClick=onClick),shape=RoundedCornerShape(23.dp),color=tone.copy(alpha=.11f)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(metric.label,style=MaterialTheme.typography.labelLarge,color=tone);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.titleLarge);Text(if(latest!=null&&previous!=null)"较上次 ${signed(latest.value-previous.value)} ${unitLabel(latest.unit)}" else latest?.occurredOn?:"等待同步",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);MiniTrend(metric.points,Modifier.fillMaxWidth().height(44.dp),tone)}}}

@Composable private fun ActivityWorkspace(history:List<HealthDailyOverview>,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){
  var metric by rememberSaveable{mutableStateOf("steps")};val days=lastSevenDays(history);val workouts=history.flatMap{it.workoutItems}.sortedByDescending{it.startedAt?:it.occurredOn};val values=days.map{(_,day)->when(metric){"minutes"->day?.activeMinutes?.toDouble();"calories"->day?.caloriesKcal?.toDoubleOrNull();else->day?.steps?.toDouble()}};val total=values.filterNotNull().sum();val unit=when(metric){"minutes"->"分钟";"calories"->"kcal";else->"步"};val tone=when(metric){"minutes"->ActivityBlue;"calories"->ActivityPurple;else->ActivityGreen}
  Column(verticalArrangement=Arrangement.spacedBy(18.dp)){HealthSurface{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("近 7 天活动",style=MaterialTheme.typography.titleLarge);Text("已覆盖 ${values.count{it!=null}} 天 · 合计 ${number(total)} $unit",style=MaterialTheme.typography.bodyMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalButton(onClick={onCapture(CaptureKind.Workout)}){Text("记录运动")}};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("steps" to "步数","minutes" to "活跃时间","calories" to "活动热量").forEach{(key,label)->FilterChip(metric==key,{metric=key},{Text(label)})}};WeekBarChart(days.map{it.first},values,tone,Modifier.fillMaxWidth().height(180.dp))};LifeSection("运动记录"){Text("运动记录按 Samsung Health 的字段和命名习惯展示；经 Health Connect 聚合进入的数据会如实标注聚合来源，避免重复或伪装来源。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);if(workouts.isEmpty())ChartEmpty("近 7 天没有同步到运动明细") else workouts.forEach{workout->WorkoutCard(workout){onDetail(LifeDomain.Health,workout.id,"${workoutTypeUi(workout.sessionType)}记录")}}}}
}

@Composable private fun WorkoutCard(workout:HealthWorkoutSummary,onClick:()->Unit){val title=workoutTypeUi(workout.sessionType);val tone=workoutTone(workout.sessionType);HealthSurface(onClick=onClick){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Box(Modifier.size(48.dp).clip(CircleShape).background(tone.copy(alpha=.16f)),contentAlignment=Alignment.Center){Text(workoutGlyph(workout.sessionType),style=MaterialTheme.typography.titleLarge,color=tone)};Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleLarge);Text("${workout.occurredOn}${workout.startedAt?.takeIf{it.length>=16}?.substring(11,16)?.let{" · $it"}.orEmpty()}",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};workout.sourceKind?.let{SourcePill(sourceLabel(it),tone)}};val facts=listOfNotNull(workout.distanceKm?.let{"距离" to "$it km"},workout.durationMinutes?.let{"时长" to minutesLabel(it)},workout.caloriesKcal?.let{"热量" to "$it kcal"},workout.heartRateAvg?.let{"平均心率" to "$it 次/分"});if(facts.isNotEmpty())Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(20.dp)){facts.forEach{(label,value)->HealthFact(label,value)}} else Text("三星记录未提供距离、时长、热量或心率明细。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}

@Composable private fun SleepWorkspace(history:List<HealthDailyOverview>){val days=lastSevenDays(history);val latest=history.lastOrNull{it.sleepMinutes!=null};val values=days.map{it.second?.sleepMinutes?.toDouble()?.div(60)};Column(verticalArrangement=Arrangement.spacedBy(18.dp)){HealthSurface{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("睡眠",style=MaterialTheme.typography.titleLarge);Text(latest?.occurredOn?:"昨晚",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};latest?.sleepSource?.let{SourcePill(sourceLabel(it),SleepPurple)}};Text(latest?.sleepMinutes?.let(::minutesLabel)?:"尚未同步",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.SemiBold);SleepStageBar(latest);Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(18.dp)){HealthFact("深睡",latest?.deepMinutes?.let(::minutesLabel)?:"未提供");HealthFact("浅睡",latest?.lightMinutes?.let(::minutesLabel)?:"未提供");HealthFact("REM",latest?.remMinutes?.let(::minutesLabel)?:"未提供");HealthFact("清醒",latest?.awakeMinutes?.let(::minutesLabel)?:"未提供")};Text("设备没有提供的睡眠分期不会显示为 0，也不会根据时长臆造睡眠评分。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};HealthSurface{Text("近 7 天睡眠",style=MaterialTheme.typography.titleLarge);Text("按 Samsung Health 日汇总展示实际睡眠时长",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);WeekBarChart(days.map{it.first},values,SleepPurple,Modifier.fillMaxWidth().height(190.dp),"小时")}}}

@Composable private fun SleepStageBar(day:HealthDailyOverview?){val stages=listOf(day?.deepMinutes to Color(0xFF6257E8),day?.lightMinutes to Color(0xFF8C78F0),day?.remMinutes to Color(0xFFB991FF),day?.awakeMinutes to Color(0xFFFFA657));val total=stages.sumOf{it.first?:0L};Row(Modifier.fillMaxWidth().height(12.dp).clip(CircleShape)){if(total<=0)Box(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.outline.copy(alpha=.25f))) else stages.forEach{(minutes,color)->if(minutes!=null&&minutes>0)Box(Modifier.weight(minutes.toFloat()).fillMaxHeight().background(color))}}}

@Composable private fun CompactDeviceStatus(status:DeviceSyncStatus,queueState:LoadState<QueueSummary>,samsungAvailable:Boolean,onHealthSync:()->Unit,onSamsungSync:()->Unit,onScale:()->Unit,onSettings:()->Unit){val queue=(queueState as? LoadState.Ready)?.value;LifeSection("设备与同步",action={TextButton(onClick=onSettings){Text("管理")}}){HealthSurface{SyncRow("Samsung Health",if(!samsungAvailable)"当前包未包含 SDK" else status.samsungMessage,status.samsungState,onSamsungSync);HorizontalDivider(color=MaterialTheme.colorScheme.outline.copy(alpha=.32f));SyncRow("小米体脂秤",status.scaleLastWeight?.let{"最近 $it kg · ${status.scaleMessage}"}?:status.scaleMessage,status.scaleState,onScale);HorizontalDivider(color=MaterialTheme.colorScheme.outline.copy(alpha=.32f));SyncRow("Health Connect","读取系统已授权的聚合健康数据","idle",onHealthSync);queue?.let{Text("离线队列：${it.waiting} 待发送 · ${it.reconciling} 核对中 · ${it.failed} 需处理",style=MaterialTheme.typography.bodySmall,color=if(it.failed>0)MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant)}}}}

@Composable private fun SyncRow(title:String,subtitle:String,state:String,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(role=Role.Button,onClick=onClick).padding(vertical=7.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(10.dp).clip(CircleShape).background(if(state in setOf("complete","committed","queued","detected"))ActivityGreen else if(state in setOf("error","timeout","needs_permission","needs_config"))MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.outline));Spacer(Modifier.width(11.dp));Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleMedium);Text(subtitle,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=2,overflow=TextOverflow.Ellipsis)};Icon(Icons.Default.Refresh,"立即操作",tint=MaterialTheme.colorScheme.primary)}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun MealsWorkspaceScreen(overviewState:LoadState<WorkspaceOverview>,recordsState:LoadState<RecordPage>,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onRetry:()->Unit,onLoadMore:()->Unit,onBack:()->Unit,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){
  var selectedDate by rememberSaveable{mutableStateOf(LocalDate.now().toString())};var query by rememberSaveable{mutableStateOf("")};val allRecords=(recordsState as? LoadState.Ready)?.value?.items.orEmpty().filter{it.meal!=null};val selected=allRecords.filter{it.meal?.occurredOn==selectedDate};val dates=(0L..6L).map{LocalDate.now().minusDays(it).toString()}.reversed()+listOf(selectedDate);val records=allRecords.filter{record->query.isBlank()||listOf(record.title,record.meal?.note.orEmpty(),mealTypeUi(record.meal?.mealType.orEmpty())).any{it.contains(query.trim(),ignoreCase=true)}};val nutrition=mealNutrition(selected)
  Scaffold(containerColor=MaterialTheme.colorScheme.background,topBar={TopAppBar(title={Column{Text("饮食");Text("餐次、餐照与真实营养汇总",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}},navigationIcon={IconButton(onClick=onBack){Text("‹",style=MaterialTheme.typography.headlineLarge)}},actions={FilledTonalIconButton(onClick={onCapture(CaptureKind.Meal)}){Icon(Icons.Default.Add,"记一餐")}})}){padding->LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(horizontal=20.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){
    item{DateNavigator(selectedDate,{selectedDate=it},dates.distinct())};item{MealNutritionHero(selectedDate,selected,nutrition,onCapture)};item{MealWeekCard(allRecords)};item{MealDayGroups(selected,assetPreviews,onLoadAsset,onDetail,onCapture)}
    val planning=(overviewState as? LoadState.Ready)?.value as? WorkspaceOverview.Meals
    if(planning!=null)item{LifeSection("餐单与采购"){HealthSurface{Text("${planning.mealPlans} 份餐单 · ${planning.shoppingLists} 张购物清单",style=MaterialTheme.typography.titleMedium);Text(if(planning.openShoppingItems==0)"当前没有待采购食材" else "${planning.openShoppingItems} 项食材待采购",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
    item{LifeSection("查找饮食记录"){OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text("搜索食物、餐次或备注")},leadingIcon={Icon(Icons.Default.Search,null)});if(query.isNotBlank())Text("匹配 ${records.size} 条",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}};item{Text("最近记录",style=MaterialTheme.typography.titleLarge)};item{StateContent(recordsState,onRetry){} }
    if(recordsState is LoadState.Ready){items(records.size){index->val record=records[index];MealHistoryRow(record,assetPreviews,onLoadAsset){onDetail(LifeDomain.Meals,record.detailId?:record.id,record.title)}};if(records.isEmpty()&&query.isNotBlank())item{EmptyState("已加载记录中没有匹配内容")};if(recordsState.value.nextCursor!=null)item{TextButton(onClick=onLoadMore,Modifier.fillMaxWidth()){Text("加载更早记录")}}};item{Spacer(Modifier.height(12.dp))}
  }}
}

@Composable private fun DateNavigator(selected:String,onSelect:(String)->Unit,dates:List<String>){Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){OutlinedButton(onClick={onSelect(runCatching{LocalDate.parse(selected).minusDays(1).toString()}.getOrDefault(selected))}){Text("‹")};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Text(if(selected==LocalDate.now().toString())"今天" else selected,style=MaterialTheme.typography.titleLarge);Text(selected,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.labelMedium)};OutlinedButton(onClick={onSelect(runCatching{LocalDate.parse(selected).plusDays(1).coerceAtMost(LocalDate.now()).toString()}.getOrDefault(selected))},enabled=selected<LocalDate.now().toString()){Text("›")}};Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){dates.forEach{date->FilterChip(selected==date,{onSelect(date)},{Text(if(date==LocalDate.now().toString())"今天" else date.takeLast(5))})}}}}

private data class MealNutrition(val kcal:Double,val protein:Double,val fat:Double,val carb:Double,val knownItems:Int,val totalItems:Int,val estimated:Boolean)
private fun mealNutrition(records:List<RecordSummary>):MealNutrition{val foods=records.flatMap{it.meal?.foods.orEmpty()};return MealNutrition(foods.sumOf{it.energyKcal?.toDoubleOrNull()?:0.0},foods.sumOf{it.proteinG?.toDoubleOrNull()?:0.0},foods.sumOf{it.fatG?.toDoubleOrNull()?:0.0},foods.sumOf{it.carbG?.toDoubleOrNull()?:0.0},foods.count{it.energyKcal!=null||it.proteinG!=null||it.fatG!=null||it.carbG!=null},foods.size,foods.any{it.estimated})}

@Composable private fun MealNutritionHero(date:String,records:List<RecordSummary>,nutrition:MealNutrition,onCapture:(CaptureKind)->Unit){HealthSurface{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text(if(date==LocalDate.now().toString())"今日摄入" else "$date 摄入",style=MaterialTheme.typography.labelLarge,color=MealCoral);Row(verticalAlignment=Alignment.Bottom){Text(if(nutrition.knownItems>0)number(nutrition.kcal) else "—",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.SemiBold);Spacer(Modifier.width(6.dp));Text("kcal",style=MaterialTheme.typography.titleMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text("${records.size} 餐 · ${nutrition.knownItems}/${nutrition.totalItems} 个食物条目含营养",color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Meal)}){Icon(Icons.Default.Add,"添加餐次")}};if(nutrition.knownItems>0){NutrientBar(nutrition);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){NutrientChip("蛋白质",nutrition.protein,"g",ActivityGreen,Modifier.weight(1f));NutrientChip("碳水",nutrition.carb,"g",ActivityBlue,Modifier.weight(1f));NutrientChip("脂肪",nutrition.fat,"g",BodyOrange,Modifier.weight(1f))}};Text(buildString{append("只汇总已记录条目，不代表全天完整摄入");if(nutrition.estimated)append(" · 含估算值")},style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}

@Composable private fun MealWeekCard(records:List<RecordSummary>){val dates=(0L..6L).map{LocalDate.now().minusDays(it)}.reversed();val values=dates.map{date->val nutrition=mealNutrition(records.filter{it.meal?.occurredOn==date.toString()});nutrition.kcal.takeIf{nutrition.knownItems>0}};HealthSurface{Text("近 7 天摄入",style=MaterialTheme.typography.titleLarge);Text("仅统计有营养字段的食物条目",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);WeekBarChart(dates,values,MealCoral,Modifier.fillMaxWidth().height(180.dp),"kcal")}}

@Composable private fun NutrientBar(value:MealNutrition){val total=value.protein*4+value.carb*4+value.fat*9;Row(Modifier.fillMaxWidth().height(10.dp).clip(CircleShape)){if(total<=0)Box(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.outline)) else {Box(Modifier.weight((value.protein*4/total).toFloat().coerceAtLeast(.01f)).fillMaxHeight().background(ActivityGreen));Box(Modifier.weight((value.carb*4/total).toFloat().coerceAtLeast(.01f)).fillMaxHeight().background(ActivityBlue));Box(Modifier.weight((value.fat*9/total).toFloat().coerceAtLeast(.01f)).fillMaxHeight().background(BodyOrange))}}}
@Composable private fun NutrientChip(label:String,value:Double,unit:String,color:Color,modifier:Modifier){Surface(modifier,shape=RoundedCornerShape(18.dp),color=color.copy(alpha=.12f)){Column(Modifier.padding(12.dp)){Text(label,style=MaterialTheme.typography.labelMedium,color=color);Text("${number(value)} $unit",style=MaterialTheme.typography.titleMedium)}}}

@Composable private fun MealDayGroups(records:List<RecordSummary>,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){LifeSection("餐次与餐照"){mealOrder.forEach{type->val group=records.filter{it.meal?.mealType==type};if(type!="other"||group.isNotEmpty()){if(group.isEmpty())EmptyMealGroup(type,onCapture) else group.forEach{record->MealGroupCard(record,assetPreviews,onLoadAsset){onDetail(LifeDomain.Meals,record.detailId?:record.id,record.title)}}}}}}
@Composable private fun EmptyMealGroup(type:String,onCapture:(CaptureKind)->Unit){Surface(Modifier.fillMaxWidth().clickable(role=Role.Button){onCapture(CaptureKind.Meal)},shape=RoundedCornerShape(22.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.42f)){Row(Modifier.padding(17.dp),verticalAlignment=Alignment.CenterVertically){Text(mealTypeUi(type),style=MaterialTheme.typography.titleMedium,modifier=Modifier.weight(1f));Text("未记录  ＋",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun MealGroupCard(record:RecordSummary,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onClick:()->Unit){val meal=record.meal?:return;val nutrition=mealNutrition(listOf(record));HealthSurface(onClick=onClick){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(14.dp)){MealPhoto(meal.photoAssetVersionId,assetPreviews,onLoadAsset,Modifier.size(104.dp));Column(Modifier.weight(1f)){Row(Modifier.fillMaxWidth()){Text(mealTypeUi(meal.mealType),style=MaterialTheme.typography.titleLarge,modifier=Modifier.weight(1f));Text(meal.occurredAt?.takeIf{it.length>=16}?.substring(11,16)?:meal.occurredOn.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text(meal.foods.joinToString("、"){it.name}.ifBlank{"仅保存了餐照"},maxLines=3,overflow=TextOverflow.Ellipsis);if(nutrition.knownItems>0)Text("${number(nutrition.kcal)} kcal · 蛋白 ${number(nutrition.protein)} g",color=MealCoral,style=MaterialTheme.typography.bodySmall);meal.note?.let{Text(it,maxLines=2,overflow=TextOverflow.Ellipsis,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}};if(meal.foods.isNotEmpty())Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){meal.foods.forEach{food->AssistChip(onClick=onClick,label={Text(food.name)})}}}}

@Composable private fun MealHistoryRow(record:RecordSummary,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onClick:()->Unit){val meal=record.meal;if(meal==null){RecordRow(record,onClick);return};Row(Modifier.fillMaxWidth().clickable(role=Role.Button,onClick=onClick).padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){MealPhoto(meal.photoAssetVersionId,assetPreviews,onLoadAsset,Modifier.size(58.dp));Column(Modifier.weight(1f)){Text(mealTypeUi(meal.mealType),style=MaterialTheme.typography.titleMedium);Text(record.title,maxLines=1,overflow=TextOverflow.Ellipsis,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(meal.occurredOn,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};record.trailing?.let{Text(it,style=MaterialTheme.typography.labelMedium)}}}
@Composable private fun MealPhoto(versionId:String?,states:Map<String,LoadState<ByteArray>>,onLoad:(String)->Unit,modifier:Modifier){if(versionId==null){Surface(modifier,shape=RoundedCornerShape(20.dp),color=MealCoral.copy(alpha=.11f)){Box(contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("◇",style=MaterialTheme.typography.headlineMedium,color=MealCoral);Text("暂无餐照",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}};return};LaunchedEffect(versionId){onLoad(versionId)};when(val state=states[versionId]){is LoadState.Ready->{val bitmap=remember(state.value){BitmapFactory.decodeByteArray(state.value,0,state.value.size)?.asImageBitmap()};if(bitmap!=null)Image(bitmap,"餐次照片",modifier.clip(RoundedCornerShape(20.dp)),contentScale=ContentScale.Crop) else PhotoLoadFallback(modifier,"无法解码")};is LoadState.Failed->PhotoLoadFallback(modifier,"点击重试"){onLoad(versionId)};else->Surface(modifier,shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surfaceVariant){Box(contentAlignment=Alignment.Center){CircularProgressIndicator(Modifier.size(24.dp),strokeWidth=2.dp)}}}}
@Composable private fun PhotoLoadFallback(modifier:Modifier,label:String,onClick:(()->Unit)?=null){Surface(modifier.then(if(onClick!=null)Modifier.clickable(role=Role.Button,onClick=onClick) else Modifier),shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surfaceVariant){Box(contentAlignment=Alignment.Center){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}

@Composable private fun HealthSurface(modifier:Modifier=Modifier,onClick:(()->Unit)?=null,content:@Composable ColumnScope.()->Unit){val click=if(onClick!=null)Modifier.clickable(role=Role.Button,onClick=onClick) else Modifier;Surface(modifier.fillMaxWidth().then(click),shape=RoundedCornerShape(26.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp),content=content)}}
@Composable private fun TrendChart(points:List<HealthTrendPoint>,modifier:Modifier,color:Color){
  val values=points.map{it.value};val outline=MaterialTheme.colorScheme.outline;val surface=MaterialTheme.colorScheme.surface
  Canvas(modifier){
    val left=6.dp.toPx();val right=size.width-6.dp.toPx();val top=12.dp.toPx();val bottom=size.height-12.dp.toPx()
    repeat(4){index->val y=top+(bottom-top)*index/3f;drawLine(outline.copy(alpha=.35f),Offset(left,y),Offset(right,y),1.dp.toPx())}
    if(values.isEmpty())return@Canvas
    val min=values.minOrNull()?:0.0;val max=values.maxOrNull()?:min;val range=(max-min).takeIf{abs(it)>.000001}?:1.0
    fun pointOffset(index:Int,value:Double):Offset{
      val x=if(values.size==1)(left+right)/2 else left+(right-left)*index/values.lastIndex.toFloat()
      return Offset(x,bottom-(bottom-top)*((value-min)/range).toFloat())
    }
    if(values.size>1){val path=Path();values.forEachIndexed{index,value->val point=pointOffset(index,value);if(index==0)path.moveTo(point.x,point.y) else path.lineTo(point.x,point.y)};drawPath(path,color,style=Stroke(3.dp.toPx(),cap=StrokeCap.Round))}
    values.forEachIndexed{index,value->val point=pointOffset(index,value);drawCircle(surface,5.dp.toPx(),point);drawCircle(color,3.dp.toPx(),point)}
  }
}

@Composable private fun WeekBarChart(dates:List<LocalDate>,values:List<Double?>,color:Color,modifier:Modifier,unit:String?=null){val outline=MaterialTheme.colorScheme.outline;Column{Canvas(modifier){val maxValue=(values.filterNotNull().maxOrNull()?:0.0).coerceAtLeast(1.0);val gap=8.dp.toPx();val slot=(size.width-gap*(values.size-1))/values.size.coerceAtLeast(1);values.forEachIndexed{index,value->val left=index*(slot+gap);drawRoundRect(outline.copy(alpha=.2f),Offset(left,0f),Size(slot,size.height),cornerRadius=androidx.compose.ui.geometry.CornerRadius(slot/2));if(value!=null){val height=(size.height*(value/maxValue).toFloat()).coerceAtLeast(5.dp.toPx());drawRoundRect(color,Offset(left,size.height-height),Size(slot,height),cornerRadius=androidx.compose.ui.geometry.CornerRadius(slot/2))}}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){dates.forEachIndexed{index,date->Column(horizontalAlignment=Alignment.CenterHorizontally){Text(dayUi(date),style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant);values.getOrNull(index)?.let{Text(number(it),style=MaterialTheme.typography.labelSmall,color=color)}}}}}}
@Composable private fun MiniTrend(points:List<HealthTrendPoint>,modifier:Modifier,color:Color=MaterialTheme.colorScheme.primary){if(points.isEmpty()){Box(modifier,contentAlignment=Alignment.CenterStart){Text("等待数据",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}} else TrendChart(points.takeLast(20),modifier,color)}
@Composable private fun ChartEmpty(text:String){Box(Modifier.fillMaxWidth().height(150.dp).clip(RoundedCornerShape(20.dp)).background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.34f)),contentAlignment=Alignment.Center){Text(text,color=MaterialTheme.colorScheme.onSurfaceVariant,modifier=Modifier.padding(24.dp))}}
@Composable private fun ChartDateRange(from:String,to:String){Row(Modifier.fillMaxWidth()){Text(from.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.weight(1f));Text(to.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun SummaryFact(label:String,value:String,modifier:Modifier=Modifier){Column(modifier){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleMedium,maxLines=1,overflow=TextOverflow.Ellipsis)}}
@Composable private fun HealthFact(label:String,value:String,modifier:Modifier=Modifier){Column(modifier.padding(vertical=4.dp)){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleMedium)}}
@Composable private fun SourcePill(label:String,tone:Color){Surface(shape=CircleShape,color=tone.copy(alpha=.12f)){Text(label,Modifier.padding(horizontal=10.dp,vertical=6.dp),style=MaterialTheme.typography.labelMedium,color=tone)}}

@Composable private fun healthSourceColor(overview:WorkspaceOverview.Health?)=when{overview==null->MaterialTheme.colorScheme.onSurfaceVariant;overview.sourcesNeedingAttention>0->MaterialTheme.colorScheme.error;else->ActivityGreen}
private fun healthSourceLine(value:WorkspaceOverview.Health?)=when{value==null->"正在读取健康数据";value.sources==0->"尚未接入数据来源";value.sourcesNeedingAttention>0->"${value.sourcesNeedingAttention} 个来源需要处理";else->"Samsung Health 运动语义 · ${value.sources} 个来源 · ${value.streams} 条数据流"}
private fun bodySnapshotMetrics(metrics:List<HealthMetricTrend>):List<HealthMetricTrend>{val order=listOf("weight","bmi","body_fat","fat_mass","lean_mass","skeletal_muscle","muscle_mass","muscle_rate","body_water","body_water_rate","bone_mass","bone_rate","visceral_fat","bmr","heart_rate");val ordered=order.mapNotNull{key->metrics.firstOrNull{it.key==key}};return ordered.filter{it.points.isNotEmpty()}.ifEmpty{ordered.take(4)}}
private fun bodyTone(index:Int)=listOf(BodyOrange,ActivityGreen,MealCoral,ActivityBlue)[index%4]
private fun lastSevenDays(history:List<HealthDailyOverview>):List<Pair<LocalDate,HealthDailyOverview?>> = (0L..6L).map{LocalDate.now().minusDays(it)}.reversed().map{date->date to history.firstOrNull{it.occurredOn==date.toString()}}
private fun dayUi(date:LocalDate)=listOf("一","二","三","四","五","六","日")[date.dayOfWeek.value-1]
private fun sourceLabel(value:String)=mapOf("scale" to "小米体脂秤","xiaomi_scale" to "小米体脂秤","samsung" to "Samsung Health","samsung_health" to "Samsung Health","samsung_data_sdk" to "Samsung Health","health_connect" to "Health Connect","manual" to "手动记录","legacy_health" to "旧 Health 迁移","derived" to "由原始测量计算")[value.lowercase()]?:value
private fun unitLabel(value:String)=mapOf("level" to "级","kcal/day" to "kcal/天","bpm" to "次/分")[value.lowercase()]?:value
private fun workoutTypeUi(value:String):String{val key=value.trim().lowercase().replace(' ','_').replace('-','_');return mapOf("walking" to "步行","brisk_walking" to "健走","running" to "跑步","jogging" to "慢跑","treadmill" to "跑步机","treadmill_running" to "跑步机跑步","running_treadmill" to "跑步机跑步","walking_treadmill" to "跑步机步行","cycling" to "骑行","biking" to "骑行","stationary_biking" to "室内骑行","indoor_cycling" to "室内骑行","hiking" to "徒步","swimming" to "游泳","pool_swimming" to "泳池游泳","open_water_swimming" to "公开水域游泳","strength_training" to "力量训练","weight_training" to "力量训练","weightlifting" to "举重","weight_machine" to "器械训练","circuit_training" to "循环训练","hiit" to "高强度间歇训练","rowing" to "划船","rowing_machine" to "划船机","elliptical" to "椭圆机","stair_climbing" to "爬楼梯","yoga" to "瑜伽","pilates" to "普拉提","stretching" to "拉伸","dance" to "舞蹈","dancing" to "舞蹈","aerobics" to "有氧操","jump_rope" to "跳绳","football" to "足球","soccer" to "足球","basketball" to "篮球","badminton" to "羽毛球","tennis" to "网球","table_tennis" to "乒乓球","other" to "其他运动")[key]?:if(value.any{it.code>127})value else "其他运动 · ${value.replace('_',' ')}"}
private fun workoutTone(value:String):Color=when{value.contains("run",true)||value.contains("walk",true)||value.contains("hik",true)->ActivityGreen;value.contains("swim",true)||value.contains("row",true)->ActivityBlue;value.contains("strength",true)||value.contains("weight",true)||value.contains("circuit",true)->BodyOrange;else->ActivityPurple}
private fun workoutGlyph(value:String)=when{value.contains("run",true)->"↗";value.contains("walk",true)||value.contains("hik",true)->"↟";value.contains("swim",true)->"≈";value.contains("cycl",true)||value.contains("bik",true)->"◎";value.contains("strength",true)||value.contains("weight",true)->"◆";else->"●"}
private fun mealTypeUi(value:String)=mapOf("breakfast" to "早餐","lunch" to "午餐","dinner" to "晚餐","snack" to "加餐","other" to "其他")[value]?:"一餐"
private fun minutesLabel(value:Long)=if(value>=60)"${value/60} 小时 ${value%60} 分" else "$value 分钟"
private fun signed(value:Double)=(if(value>0)"+" else "")+number(value)
private fun number(value:Double):String=BigDecimal.valueOf(value).setScale(if(abs(value)>=100)0 else 1,RoundingMode.HALF_UP).stripTrailingZeros().toPlainString()
