package com.shadow.life

import android.graphics.BitmapFactory
import android.graphics.Paint
import android.graphics.Typeface
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.LocalDate
import kotlin.math.abs

private val healthTabs=listOf("overview" to "健康","body" to "身体","activity" to "运动","sleep" to "睡眠","release" to "起飞")
private val mealOrder=listOf("breakfast","lunch","dinner","snack","other")
private val ActivityGreen:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFF7CEB52) else Color(0xFF346A23)
private val ActivityBlue:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFF48A9FF) else Color(0xFF286899)
private val ActivityPurple:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFFB285FF) else Color(0xFF7454A1)
private val BodyOrange:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFFFF9F43) else Color(0xFF885C1A)
private val SleepPurple:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFFA982FF) else Color(0xFF70579C)
private val MealCoral:Color @Composable get()=if(MaterialTheme.colorScheme.background.luminance()<.5f)Color(0xFFFF806F) else Color(0xFFA54737)

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun HealthWorkspaceScreen(
  overviewState:LoadState<WorkspaceOverview>,recordsState:LoadState<RecordPage>,deviceStatus:DeviceSyncStatus,queueState:LoadState<QueueSummary>,samsungAvailable:Boolean,
  onRetry:()->Unit,onLoadMore:()->Unit,onBack:()->Unit,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit,
  onHealthSync:()->Unit,onSamsungSync:()->Unit,onScale:()->Unit,onSettings:()->Unit,onMeals:()->Unit,initialTab:String="overview",releaseState:LoadState<HealthReleaseHistoryResultDto>,onReleaseLoad:(String,String)->Unit
){
  var tab by rememberSaveable(initialTab){mutableStateOf(initialTab.takeIf{value->healthTabs.any{it.first==value}}?:"overview")}
  val overview=(overviewState as? LoadState.Ready)?.value as? WorkspaceOverview.Health
  Scaffold(containerColor=MaterialTheme.colorScheme.background,topBar={TopAppBar(
    title={Column{Text("健康");Text(healthSourceLine(overview),style=MaterialTheme.typography.labelMedium,color=healthSourceColor(overview))}},
    navigationIcon={IconButton(onClick=onBack){Text("‹",style=MaterialTheme.typography.headlineLarge)}},
    actions={IconButton(onClick=onSettings){Icon(Icons.Default.Settings,"健康数据与设备设置")}}
  )}){padding->
    LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(horizontal=20.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){
      item{Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){healthTabs.forEach{(key,label)->FilterChip(selected=tab==key,onClick={tab=key},label={Text(label)})};FilterChip(selected=false,onClick=onMeals,label={Text("饮食")})}}
      item{StateContent(overviewState,onRetry){} }
      if(tab=="release")item{ReleaseHistoryWorkspace(releaseState,onReleaseLoad,onDetail)}
      if(overview!=null){
        when(tab){
          "body"->item{BodyMetricsWorkspace(overview.metrics,onDetail,onCapture)}
          "activity"->item{ActivityWorkspace(overview.history,onDetail,onCapture)}
          "sleep"->item{SleepWorkspace(overview.history)}
          "release"->Unit
          else->{item{DailyActivityHero(overview.daily,onCapture)};item{HealthOverviewCards(overview,{tab=it},onMeals)};item{BodyCompositionStrip(overview.metrics){tab="body"}}}
        }
        item{CompactDeviceStatus(deviceStatus,queueState,samsungAvailable,onHealthSync,onSamsungSync,onScale,onSettings)}
      }
      if(tab=="overview"){
        item{Text("最近健康记录",style=MaterialTheme.typography.titleLarge)}
        item{StateContent(recordsState,onRetry){} }
        if(recordsState is LoadState.Ready){items(recordsState.value.items.size){index->val record=recordsState.value.items[index];RecordRow(record){onDetail(LifeDomain.Health,record.detailId?:record.id,record.title)}};if(recordsState.value.nextCursor!=null)item{TextButton(onClick=onLoadMore,Modifier.fillMaxWidth()){Text("加载更多健康记录")}}}
      }
      item{Spacer(Modifier.height(12.dp))}
    }
  }
}

@Composable private fun DailyActivityHero(daily:HealthDailyOverview?,onCapture:(CaptureKind)->Unit){HealthSurface{
  val isToday=daily?.occurredOn==LocalDate.now().toString()
  Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text(if(isToday||daily==null)"当天活动" else "最近活动",style=MaterialTheme.typography.titleLarge);Text(daily?.occurredOn?:LocalDate.now().toString(),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Workout)}){Icon(Icons.Default.Add,"记录训练")}}
  Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){
    Column(Modifier.weight(1f)){ActivityMetric("步数","steps",daily?.steps?.toDouble(),"步")}
    Column(Modifier.weight(1f)){ActivityMetric("活跃时间","active_minutes",daily?.activeMinutes?.toDouble(),"分钟")}
  }
  Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){
    Column(Modifier.weight(1f)){ActivityMetric("活动热量","active_calories",daily?.caloriesKcal?.toDoubleOrNull(),"kcal")}
    Column(Modifier.weight(1f)){RingLegend("运动",daily?.workouts?.toString()?:"—","次",ActivityGreen)}
  }
  daily?.caloriesSource?.let{Text("消耗采用${when(it){"workout_sum"->"运动明细合计";"equal"->"设备与运动一致的数值";else->"设备每日汇总"}}，避免重复叠加。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
  if(daily==null)Text("当天数据尚未同步",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
}}

@Composable private fun RingLegend(label:String,value:String,unit:String,color:Color){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp).clip(CircleShape).background(color));Spacer(Modifier.width(9.dp));Column{Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Row(verticalAlignment=Alignment.Bottom){Text(value,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.SemiBold,color=color);Spacer(Modifier.width(4.dp));Text(unit,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}

@OptIn(ExperimentalLayoutApi::class)
@Composable private fun HealthOverviewCards(overview:WorkspaceOverview.Health,onTab:(String)->Unit,onMeals:()->Unit){LifeSection("健康分类"){FlowRow(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp),verticalArrangement=Arrangement.spacedBy(10.dp),maxItemsInEachRow=2){
  OverviewModule("睡眠",overview.daily?.sleepMinutes?.let(::minutesLabel)?:"尚未同步",overview.daily?.sleepSource?.let(::sourceLabel)?:"查看分期与近 7 天",SleepPurple,{onTab("sleep")},Modifier.weight(1f));val weight=overview.metrics.firstOrNull{it.key=="weight"}?.points?.lastOrNull();OverviewModule("身体",weight?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"尚未测量",weight?.occurredOn?:"体重与身体成分",BodyOrange,{onTab("body")},Modifier.weight(1f));OverviewModule("运动",overview.daily?.workouts?.let{"$it 次"}?:"尚未同步","活动趋势与运动明细",ActivityGreen,{onTab("activity")},Modifier.weight(1f));OverviewModule("饮食","餐照与营养","按早餐、午餐、晚餐查看",MealCoral,onMeals,Modifier.weight(1f))
}}}

@Composable private fun OverviewModule(title:String,value:String,note:String,tone:Color,onClick:()->Unit,modifier:Modifier=Modifier){Surface(modifier.heightIn(min=118.dp).clickable(role=Role.Button,onClick=onClick),shape=RoundedCornerShape(24.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(17.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Box(Modifier.width(28.dp).height(4.dp).clip(CircleShape).background(tone));Text(title,style=MaterialTheme.typography.labelLarge,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleLarge,maxLines=1,overflow=TextOverflow.Ellipsis);Text(note,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=2)}}}

@Composable private fun BodyCompositionStrip(metrics:List<HealthMetricTrend>,onSelect:()->Unit){val visible=bodySnapshotMetrics(metrics);LifeSection("身体成分",action={TextButton(onClick=onSelect){Text("完整分析")}}){if(visible.none{it.points.isNotEmpty()})ChartEmpty("体脂秤或 Samsung Health 同步后，在这里形成身体成分卡片") else Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(10.dp)){visible.forEach{metric->val latest=metric.points.lastOrNull();val assessment=metricAssessment(metric.key,latest?.value,latest?.unit.orEmpty());Surface(Modifier.width(152.dp).clickable(role=Role.Button,onClick=onSelect),shape=RoundedCornerShape(22.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text(metric.label,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.labelLarge);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.titleLarge,maxLines=1,color=healthTone(assessment.tone));AssessmentLabel(assessment,false);MiniTrend(metric.points,Modifier.fillMaxWidth().height(48.dp),healthTone(assessment.tone));Text(latest?.let{"${it.occurredOn} · ${sourceLabel(it.sourceKind)}"}?:"等待同步",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}}

@Composable private fun BodyMetricsWorkspace(metrics:List<HealthMetricTrend>,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){
  var metricKey by rememberSaveable{mutableStateOf("weight")};var days by rememberSaveable{mutableIntStateOf(30)};val available=metrics.filter{!it.unavailable&&it.points.isNotEmpty()};val metric=available.firstOrNull{it.key==metricKey}?:available.firstOrNull();val cutoff=LocalDate.now().minusDays(days.toLong()-1);val shown=metric?.points.orEmpty().filter{runCatching{LocalDate.parse(it.occurredOn)>=cutoff}.getOrDefault(true)};val latest=shown.lastOrNull()?:metric?.points?.lastOrNull();val first=shown.firstOrNull();val average=shown.map{it.value}.average().takeUnless{it.isNaN()}
  val assessment=metricAssessment(metric?.key.orEmpty(),latest?.value,latest?.unit.orEmpty());val editReference=LocalEditHealthReference.current
  Column(verticalArrangement=Arrangement.spacedBy(18.dp)){
    ReferenceLegend()
    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){available.forEach{item->FilterChip(metric?.key==item.key,{metricKey=item.key},{Text(item.label)})}}
    HealthSurface(onClick=latest?.let{{onDetail(LifeDomain.Health,it.id,"${metric?.label}记录")}}){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("${metric?.label?:"身体指标"}变化",style=MaterialTheme.typography.titleLarge);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.SemiBold,color=healthTone(assessment.tone));Text(latest?.let{"${it.occurredOn} · ${sourceLabel(it.sourceKind)}"}?:"等待设备同步或手动补记",color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Health)}){Icon(Icons.Default.Add,"添加记录")}};AssessmentLabel(assessment);if(metric!=null&&latest!=null)TextButton(onClick={editReference(metric.key,metric.label,latest.unit,false)}){Text("设置参考范围")};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf(7,30,90).forEach{value->FilterChip(days==value,{days=value},{Text("$value 天")})}};if(shown.isEmpty())ChartEmpty("所选期间没有${metric?.label.orEmpty()}数据") else {TrendChart(shown,Modifier.fillMaxWidth().height(210.dp),healthTone(assessment.tone),metric?.key);ChartDateRange(shown.first().occurredOn,shown.last().occurredOn)};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){SummaryFact("平均",average?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f));SummaryFact("最低",shown.minOfOrNull{it.value}?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f));SummaryFact("最高",shown.maxOfOrNull{it.value}?.let{"${number(it)} ${latest?.unit?.let(::unitLabel).orEmpty()}"}?:"—",Modifier.weight(1f))};if(first!=null&&latest!=null&&first.id!=latest.id)Text("期间变化 ${signed(latest.value-first.value)} ${unitLabel(latest.unit)} · ${shown.size} 个真实测量点",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
    if(metric?.truncated==true)Text("仅显示最近 ${metric.coveragePoints} 个测量点，部分历史未包含。",style=MaterialTheme.typography.bodySmall)
    if(metric?.key?.startsWith("skin_temperature")==true)Text("这是手腕皮肤温度，用于观察同类测量变化。",style=MaterialTheme.typography.bodySmall)
    if(metric?.key?.startsWith("heart_rate_daily")==true)Text("全天极值包含睡眠和活动，不作为静息心率判断。",style=MaterialTheme.typography.bodySmall)
    LifeSection("各项最近测量"){val snapshot=bodySnapshotMetrics(metrics);Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(10.dp)){snapshot.forEach{item->BodySnapshotCard(item){item.points.lastOrNull()?.let{onDetail(LifeDomain.Health,it.id,"${item.label}记录")}}}}}
    LifeSection("测量历史"){if(shown.isEmpty())EmptyState("没有可显示的真实测量点") else shown.asReversed().take(12).forEach{point->Surface(Modifier.fillMaxWidth().clickable(role=Role.Button){onDetail(LifeDomain.Health,point.id,"${metric?.label}记录")},shape=RoundedCornerShape(18.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.42f)){Row(Modifier.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(point.occurredOn,style=MaterialTheme.typography.titleMedium);Text(sourceLabel(point.sourceKind),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};Column(horizontalAlignment=Alignment.End){val status=metricAssessment(metric?.key.orEmpty(),point.value,point.unit);Text("${point.valueText} ${unitLabel(point.unit)}",style=MaterialTheme.typography.titleMedium,color=healthTone(status.tone));AssessmentLabel(status,false)}}}};if(shown.size>12)Text("显示最近 12 次测量",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}
  }
}

@Composable private fun BodySnapshotCard(metric:HealthMetricTrend,onClick:()->Unit){val latest=metric.points.lastOrNull();val assessment=metricAssessment(metric.key,latest?.value,latest?.unit.orEmpty());val tone=healthTone(assessment.tone);val previous=metric.points.dropLast(1).lastOrNull();Surface(Modifier.width(172.dp).heightIn(min=148.dp).clickable(role=Role.Button,onClick=onClick),shape=RoundedCornerShape(23.dp),color=tone.copy(alpha=.11f)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(metric.label,style=MaterialTheme.typography.labelLarge,color=tone);Text(latest?.let{"${it.valueText} ${unitLabel(it.unit)}"}?:"未记录",style=MaterialTheme.typography.titleLarge,color=tone);AssessmentLabel(assessment,false);Text(if(latest!=null&&previous!=null)"较上次 ${signed(latest.value-previous.value)} ${unitLabel(latest.unit)}" else "等待更多测量",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(latest?.occurredOn?:"尚未测量",style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant);MiniTrend(metric.points,Modifier.fillMaxWidth().height(44.dp),tone)}}}

@Composable private fun ActivityWorkspace(history:List<HealthDailyOverview>,onDetail:(LifeDomain,String,String)->Unit,onCapture:(CaptureKind)->Unit){
  var metric by rememberSaveable{mutableStateOf("steps")};val days=lastSevenDays(history);val workouts=history.flatMap{it.workoutItems}.sortedByDescending{it.startedAt?:it.occurredOn};val values=days.map{(_,day)->when(metric){"minutes"->day?.activeMinutes?.toDouble();"calories"->day?.caloriesKcal?.toDoubleOrNull();else->day?.steps?.toDouble()}};val total=values.filterNotNull().sum();val unit=when(metric){"minutes"->"分钟";"calories"->"kcal";else->"步"};val tone=when(metric){"minutes"->ActivityBlue;"calories"->ActivityPurple;else->ActivityGreen}
  Column(verticalArrangement=Arrangement.spacedBy(18.dp)){HealthSurface{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("近 7 天活动",style=MaterialTheme.typography.titleLarge);Text(if(values.any{it!=null})"${values.count{it!=null}} 天有记录 · 合计 ${number(total)} $unit" else "近 7 天暂无记录",style=MaterialTheme.typography.bodyMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalButton(onClick={onCapture(CaptureKind.Workout)}){Text("记录运动")}};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("steps" to "步数","minutes" to "活跃时间","calories" to "活动热量").forEach{(key,label)->FilterChip(metric==key,{metric=key},{Text(label)})}};WeekBarChart(days.map{it.first},values,tone,Modifier.fillMaxWidth().height(180.dp),unit,when(metric){"minutes"->"active_minutes";"calories"->"active_calories";else->"steps"})};LifeSection("运动记录"){Text("按发生时间查看运动时长、距离与活动热量。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);if(workouts.isEmpty())ChartEmpty("近 7 天没有同步到运动明细") else workouts.forEach{workout->WorkoutCard(workout){onDetail(LifeDomain.Health,workout.id,"${workoutTypeUi(workout.sessionType)}记录")}}}}
}

@Composable private fun WorkoutCard(workout:HealthWorkoutSummary,onClick:()->Unit){val title=workoutTypeUi(workout.sessionType);val tone=workoutTone(workout.sessionType);HealthSurface(onClick=onClick){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Box(Modifier.size(48.dp).clip(CircleShape).background(tone.copy(alpha=.16f)),contentAlignment=Alignment.Center){Text(workoutGlyph(workout.sessionType),style=MaterialTheme.typography.titleLarge,color=tone)};Spacer(Modifier.width(13.dp));Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleLarge);Text("${workout.occurredOn}${localDateTime(workout.startedAt,workout.timeZone,includeDate=false)?.let{" · $it"}.orEmpty()}",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};Column(horizontalAlignment=Alignment.End,verticalArrangement=Arrangement.spacedBy(5.dp)){workout.sourceKind?.let{SourcePill(sourceLabel(it),tone)};workout.autoDetected?.let{SourcePill(if(it)"自动记录" else "手动记录",if(it)ActivityBlue else tone)}}};val facts=listOfNotNull(workout.distanceKm?.let{"距离" to "${healthValueText(it,"km")} km"},workout.durationMinutes?.let{"时长" to minutesLabel(it)},workout.caloriesKcal?.let{"热量" to "${healthValueText(it,"kcal")} kcal"},workout.heartRateAvg?.let{"运动平均心率" to "$it 次/分"},workoutPerformance(workout),workout.rpe?.let{"主观强度" to "$it / 10"});if(facts.isNotEmpty())Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(20.dp)){facts.forEach{(label,value)->HealthFact(label,value)}} else Text("这条运动记录没有更多指标。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}

@Composable private fun SleepWorkspace(history:List<HealthDailyOverview>){val days=lastSevenDays(history);val latest=history.lastOrNull{it.sleepMinutes!=null};val values=days.map{it.second?.sleepMinutes?.toDouble()?.div(60)};Column(verticalArrangement=Arrangement.spacedBy(18.dp)){HealthSurface{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text("睡眠",style=MaterialTheme.typography.titleLarge);Text(latest?.occurredOn?.let{"$it · 醒来日"}?:"近 7 天暂无睡眠记录",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};latest?.sleepSource?.let{SourcePill(sourceLabel(it),SleepPurple)}};Text(latest?.sleepMinutes?.let(::minutesLabel)?:"尚未同步",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.SemiBold);AssessmentLabel(metricAssessment("sleep_minutes",latest?.sleepMinutes?.toDouble(),"分钟",true));SleepStageBar(latest);Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(18.dp)){HealthFact("深睡",latest?.deepMinutes?.let(::minutesLabel)?:"未提供");HealthFact("浅睡",latest?.lightMinutes?.let(::minutesLabel)?:"未提供");HealthFact("REM",latest?.remMinutes?.let(::minutesLabel)?:"未提供");HealthFact("清醒",latest?.awakeMinutes?.let(::minutesLabel)?:"未提供")};Text("最长睡眠作为主睡眠；其他时段单独列出。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};if(latest!=null&&latest.napMinutes.isNotEmpty())HealthSurface{Text("其他睡眠时段",style=MaterialTheme.typography.titleLarge);latest.napMinutes.forEachIndexed{index,minutes->HealthFact("时段 ${index+1}",minutesLabel(minutes))};Text("各时段合计 ${latest.sleepTotalDayMinutes?.let(::minutesLabel)?:"—"} · 可能含重叠记录",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};HealthSurface{Text("近 7 天睡眠",style=MaterialTheme.typography.titleLarge);Text("按醒来日期查看睡眠时长",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);WeekBarChart(days.map{it.first},values,SleepPurple,Modifier.fillMaxWidth().height(190.dp),"小时")}}}

@Composable private fun SleepStageBar(day:HealthDailyOverview?){val stages=listOf(day?.deepMinutes to Color(0xFF6257E8),day?.lightMinutes to Color(0xFF8C78F0),day?.remMinutes to Color(0xFFB991FF),day?.awakeMinutes to Color(0xFFFFA657));val total=stages.sumOf{it.first?:0L};Row(Modifier.fillMaxWidth().height(12.dp).clip(CircleShape)){if(total<=0)Box(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.outline.copy(alpha=.25f))) else stages.forEach{(minutes,color)->if(minutes!=null&&minutes>0)Box(Modifier.weight(minutes.toFloat()).fillMaxHeight().background(color))}}}

@Composable private fun CompactDeviceStatus(status:DeviceSyncStatus,queueState:LoadState<QueueSummary>,samsungAvailable:Boolean,onHealthSync:()->Unit,onSamsungSync:()->Unit,onScale:()->Unit,onSettings:()->Unit){val queue=(queueState as? LoadState.Ready)?.value;LifeSection("设备与同步",action={TextButton(onClick=onSettings){Text("管理")}}){HealthSurface{SyncRow("Samsung Health",if(!samsungAvailable)"当前包未包含 SDK" else status.samsungMessage,status.samsungState,onSamsungSync);HorizontalDivider(color=MaterialTheme.colorScheme.outline.copy(alpha=.32f));SyncRow("小米体脂秤",status.scaleLastWeight?.let{"最近 $it kg · ${status.scaleMessage}"}?:status.scaleMessage,status.scaleState,onScale);if(HealthConnectSync.enabled()){HorizontalDivider(color=MaterialTheme.colorScheme.outline.copy(alpha=.32f));SyncRow("Health Connect","读取系统已授权的聚合健康数据","idle",onHealthSync)};queue?.let{Text("离线队列：${it.waiting} 待发送 · ${it.reconciling} 核对中 · ${it.failed} 需处理",style=MaterialTheme.typography.bodySmall,color=if(it.failed>0)MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant)}}}}

@Composable private fun SyncRow(title:String,subtitle:String,state:String,onClick:()->Unit){Row(Modifier.fillMaxWidth().clickable(role=Role.Button,onClick=onClick).padding(vertical=7.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(10.dp).clip(CircleShape).background(if(state in setOf("complete","committed","queued","detected"))ActivityGreen else if(state in setOf("needs_config","key_mismatch"))MaterialTheme.colorScheme.tertiary else if(state in setOf("error","timeout","needs_permission"))MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.outline));Spacer(Modifier.width(11.dp));Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.titleMedium);Text(subtitle,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=2,overflow=TextOverflow.Ellipsis)};Icon(Icons.Default.Refresh,"立即操作",tint=MaterialTheme.colorScheme.primary)}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun MealsWorkspaceScreen(overviewState:LoadState<WorkspaceOverview>,recordsState:LoadState<RecordPage>,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onRetry:()->Unit,onLoadMore:()->Unit,onBack:()->Unit,onDetail:(LifeDomain,String,String)->Unit,onMealCapture:(String,String)->Unit,onAddPhoto:(RecordSummary)->Unit,photoState:SubmitState,onStats:()->Unit){
  var selectedDate by rememberSaveable{mutableStateOf(LocalDate.now().toString())};var query by rememberSaveable{mutableStateOf("")};val allRecords=(recordsState as? LoadState.Ready)?.value?.items.orEmpty().filter{it.meal!=null};val selected=allRecords.filter{it.meal?.occurredOn==selectedDate};val dates=(0L..6L).map{LocalDate.now().minusDays(it).toString()}.reversed()+listOf(selectedDate);val records=allRecords.filter{record->query.isBlank()||listOf(record.title,record.meal?.note.orEmpty(),mealTypeUi(record.meal?.mealType.orEmpty())).any{it.contains(query.trim(),ignoreCase=true)}};val nutrition=mealNutrition(selected)
  Scaffold(containerColor=MaterialTheme.colorScheme.background,topBar={TopAppBar(title={Column{Text("饮食");Text("餐次、餐照与真实营养汇总",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}},navigationIcon={IconButton(onClick=onBack){Text("‹",style=MaterialTheme.typography.headlineLarge)}},actions={TextButton(onClick=onStats){Text("统计")};FilledTonalIconButton(onClick={onMealCapture(selectedDate,"other")}){Icon(Icons.Default.Add,"记一餐")}})}){padding->LazyColumn(Modifier.fillMaxSize().padding(padding),contentPadding=PaddingValues(horizontal=20.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){
    item{DateNavigator(selectedDate,{selectedDate=it},dates.distinct().sorted())};item{StateContent(recordsState,onRetry){}};if(recordsState is LoadState.Ready)item{MealNutritionHero(selectedDate,selected,nutrition){onMealCapture(selectedDate,"other")}};if(photoState is SubmitState.Sending)item{LinearProgressIndicator(Modifier.fillMaxWidth())};if(photoState is SubmitState.Rejected)item{Text(photoState.message,color=MaterialTheme.colorScheme.error)};if(photoState is SubmitState.Saved)item{Text(if(photoState.receipt.queued)"餐照已保存，正在同步" else "餐照已添加",color=ActivityGreen,style=MaterialTheme.typography.bodySmall)};if(recordsState is LoadState.Ready){item{MealWeekCard(allRecords)};item{MealDayGroups(selected,assetPreviews,onLoadAsset,onDetail,{type->onMealCapture(selectedDate,type)},onAddPhoto)}}
    val planning=(overviewState as? LoadState.Ready)?.value as? WorkspaceOverview.Meals
    if(planning!=null)item{LifeSection("餐单与采购"){HealthSurface{Text("${planning.mealPlans} 份餐单 · ${planning.shoppingLists} 张购物清单",style=MaterialTheme.typography.titleMedium);Text(if(planning.openShoppingItems==0)"当前没有待采购食材" else "${planning.openShoppingItems} 项食材待采购",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
    item{LifeSection("查找饮食记录"){OutlinedTextField(query,{query=it},Modifier.fillMaxWidth(),singleLine=true,placeholder={Text("搜索食物、餐次或备注")},leadingIcon={Icon(Icons.Default.Search,null)});if(query.isNotBlank())Text("匹配 ${records.size} 条",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}};item{Text("最近记录",style=MaterialTheme.typography.titleLarge)}
    if(recordsState is LoadState.Ready){items(records.size){index->val record=records[index];MealHistoryRow(record,assetPreviews,onLoadAsset,{onAddPhoto(record)}){onDetail(LifeDomain.Meals,record.detailId?:record.id,record.title)}};if(records.isEmpty()&&query.isNotBlank())item{EmptyState("已加载记录中没有匹配内容")};if(recordsState.value.nextCursor!=null)item{TextButton(onClick=onLoadMore,Modifier.fillMaxWidth()){Text("加载更早记录")}}};item{Spacer(Modifier.height(12.dp))}
  }}
}

@Composable private fun DateNavigator(selected:String,onSelect:(String)->Unit,dates:List<String>){Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){OutlinedButton(onClick={onSelect(runCatching{LocalDate.parse(selected).minusDays(1).toString()}.getOrDefault(selected))}){Text("‹")};Column(Modifier.weight(1f),horizontalAlignment=Alignment.CenterHorizontally){Text(if(selected==LocalDate.now().toString())"今天" else selected,style=MaterialTheme.typography.titleLarge);Text(selected,color=MaterialTheme.colorScheme.onSurfaceVariant,style=MaterialTheme.typography.labelMedium)};OutlinedButton(onClick={onSelect(runCatching{LocalDate.parse(selected).plusDays(1).coerceAtMost(LocalDate.now()).toString()}.getOrDefault(selected))},enabled=selected<LocalDate.now().toString()){Text("›")}};Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){dates.forEach{date->FilterChip(selected==date,{onSelect(date)},{Text(if(date==LocalDate.now().toString())"今天" else date.takeLast(5))})}}}}

@Composable private fun MealNutritionHero(date:String,records:List<RecordSummary>,nutrition:MealNutrition,onCapture:(CaptureKind)->Unit){
  val editReference=LocalEditHealthReference.current
  val completeEnergy=records.flatMap{it.meal?.foods.orEmpty()}.let{foods->foods.isNotEmpty()&&foods.all{it.energyKcal?.toDoubleOrNull()?.isFinite()==true}}
  val energy=if(completeEnergy)metricAssessment("meal_kcal",nutrition.kcal,"kcal") else HealthAssessment(HealthTone.Neutral,"数据不足","部分食物缺少热量")
  HealthSurface{
    Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f)){Text(if(date==LocalDate.now().toString())"今日已记录摄入" else "$date 已记录摄入",style=MaterialTheme.typography.labelLarge);Row(verticalAlignment=Alignment.Bottom){Text(nutrition.kcal?.let(::number)?:"—",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.SemiBold,color=healthTone(energy.tone));Spacer(Modifier.width(6.dp));Text("kcal",style=MaterialTheme.typography.titleMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text("${records.size} 餐 · ${nutrition.knownItems}/${nutrition.totalItems} 个食物条目含营养",color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton(onClick={onCapture(CaptureKind.Meal)}){Icon(Icons.Default.Add,"添加餐次")}}
    AssessmentLabel(energy);TextButton(onClick={editReference("meal_kcal","每日摄入热量","kcal",false)}){Text("设置热量参考范围")}
    ReferenceLegend()
    if(nutrition.knownItems>0){NutrientBar(nutrition);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){
      NutrientChip("蛋白质",nutrition.protein,"g",macroAssessment(nutrition,"protein"),Modifier.weight(1f))
      NutrientChip("碳水",nutrition.carb,"g",macroAssessment(nutrition,"carb"),Modifier.weight(1f))
      NutrientChip("脂肪",nutrition.fat,"g",macroAssessment(nutrition,"fat"),Modifier.weight(1f))
    }}
    Text("营养素颜色比较已记录食物的供能占比（成人参考），不是全天摄入量是否足够。热量只与自定范围比较。"+(if(nutrition.estimated)" 含估算值。" else ""),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
    Text("只汇总已加载条目，不代表全天完整摄入。",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
  }
}

@Composable private fun MealWeekCard(records:List<RecordSummary>){val dates=(0L..6L).map{LocalDate.now().minusDays(it)}.reversed();val values=dates.map{date->val nutrition=mealNutrition(records.filter{it.meal?.occurredOn==date.toString()});nutrition.kcal};HealthSurface{Text("近 7 天摄入",style=MaterialTheme.typography.titleLarge);Text("仅统计有营养字段的食物条目",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);WeekBarChart(dates,values,MealCoral,Modifier.fillMaxWidth().height(180.dp),"kcal")}}

@Composable private fun NutrientBar(value:MealNutrition){
  if(!value.completeMacros)return
  val parts=listOf(value.protein!!*4 to "protein",value.carb!!*4 to "carb",value.fat!!*9 to "fat")
  if(parts.sumOf{it.first}<=0)return
  Row(Modifier.fillMaxWidth().height(10.dp).clip(CircleShape)){parts.filter{it.first>0}.forEach{(amount,key)->Box(Modifier.weight(amount.toFloat()).fillMaxHeight().background(healthTone(macroAssessment(value,key).tone)))}}
}
@Composable private fun NutrientChip(label:String,value:Double?,unit:String,status:HealthAssessment,modifier:Modifier){val color=healthTone(status.tone);Surface(modifier,shape=RoundedCornerShape(18.dp),color=color.copy(alpha=.12f)){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(label,style=MaterialTheme.typography.labelMedium);Text("${value?.let(::number)?:"—"} $unit",style=MaterialTheme.typography.titleMedium,color=color);AssessmentLabel(status)}}}
@Composable private fun ActivityMetric(label:String,key:String,value:Double?,unit:String){val status=metricAssessment(key,value,unit,true);val edit=LocalEditHealthReference.current;Column(Modifier.clickable(role=Role.Button){edit(key,label,unit,true)},verticalArrangement=Arrangement.spacedBy(5.dp)){RingLegend(label,value?.let{healthValueText(it,unit)}?:"—",unit,healthTone(status.tone));AssessmentLabel(status,false);Text(if(LocalHealthReferences.current[key]==null)"点击设置目标" else status.basis,style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}

@Composable private fun MealDayGroups(records:List<RecordSummary>,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onDetail:(LifeDomain,String,String)->Unit,onCapture:(String)->Unit,onAddPhoto:(RecordSummary)->Unit){LifeSection("餐次与餐照"){mealOrder.forEach{type->val group=records.filter{it.meal?.mealType==type};if(type!="other"||group.isNotEmpty()){if(group.isEmpty())EmptyMealGroup(type,onCapture) else group.forEach{record->MealGroupCard(record,assetPreviews,onLoadAsset,{onAddPhoto(record)}){onDetail(LifeDomain.Meals,record.detailId?:record.id,record.title)}}}}}}
@Composable private fun EmptyMealGroup(type:String,onCapture:(String)->Unit){Surface(Modifier.fillMaxWidth().clickable(role=Role.Button){onCapture(type)},shape=RoundedCornerShape(22.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.42f)){Row(Modifier.padding(17.dp),verticalAlignment=Alignment.CenterVertically){Text(mealTypeUi(type),style=MaterialTheme.typography.titleMedium,modifier=Modifier.weight(1f));Text("未记录  ＋",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun MealGroupCard(record:RecordSummary,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onAddPhoto:()->Unit,onClick:()->Unit){val meal=record.meal?:return;val nutrition=mealNutrition(listOf(record));HealthSurface(onClick=onClick){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(14.dp)){MealPhoto(meal.photoAssetVersionId,assetPreviews,onLoadAsset,Modifier.size(104.dp),onAddPhoto);Column(Modifier.weight(1f)){Row(Modifier.fillMaxWidth()){Text(mealTypeUi(meal.mealType),style=MaterialTheme.typography.titleLarge,modifier=Modifier.weight(1f));Text(localDateTime(meal.occurredAt,meal.timeZone,includeDate=false)?:meal.occurredOn.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};Text(meal.foods.joinToString("、"){it.name}.ifBlank{"仅保存了餐照"},maxLines=3,overflow=TextOverflow.Ellipsis);if(nutrition.knownItems>0)Text(listOfNotNull(nutrition.kcal?.let{"${number(it)} kcal"},nutrition.protein?.let{"蛋白 ${number(it)} g"}).joinToString(" · ").ifBlank{"已记录部分营养"},color=MealCoral,style=MaterialTheme.typography.bodySmall);meal.note?.let{Text(it,maxLines=2,overflow=TextOverflow.Ellipsis,style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}}};if(meal.foods.isNotEmpty())Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){meal.foods.forEach{food->AssistChip(onClick=onClick,label={Text(food.name)})}}}}

@Composable private fun MealHistoryRow(record:RecordSummary,assetPreviews:Map<String,LoadState<ByteArray>>,onLoadAsset:(String)->Unit,onAddPhoto:()->Unit,onClick:()->Unit){val meal=record.meal;if(meal==null){RecordRow(record,onClick);return};Row(Modifier.fillMaxWidth().clickable(role=Role.Button,onClick=onClick).padding(vertical=8.dp),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){MealPhoto(meal.photoAssetVersionId,assetPreviews,onLoadAsset,Modifier.size(58.dp),onAddPhoto);Column(Modifier.weight(1f)){Text(mealTypeUi(meal.mealType),style=MaterialTheme.typography.titleMedium);Text(record.title,maxLines=1,overflow=TextOverflow.Ellipsis,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(meal.occurredOn,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};record.trailing?.let{Text(it,style=MaterialTheme.typography.labelMedium)}}}
@Composable private fun MealPhoto(versionId:String?,states:Map<String,LoadState<ByteArray>>,onLoad:(String)->Unit,modifier:Modifier,onAdd:(()->Unit)?=null){if(versionId==null){Surface(modifier.then(if(onAdd!=null)Modifier.clickable(role=Role.Button,onClick=onAdd) else Modifier),shape=RoundedCornerShape(20.dp),color=MealCoral.copy(alpha=.11f)){Box(contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("＋",style=MaterialTheme.typography.headlineMedium,color=MealCoral);Text("添加餐照",style=MaterialTheme.typography.labelMedium,color=MealCoral)}}};return};LaunchedEffect(versionId){onLoad(versionId)};when(val state=states[versionId]){is LoadState.Ready->{val bitmap=remember(state.value){BitmapFactory.decodeByteArray(state.value,0,state.value.size)?.asImageBitmap()};if(bitmap!=null)Image(bitmap,"餐次照片",modifier.clip(RoundedCornerShape(20.dp)),contentScale=ContentScale.Crop) else PhotoLoadFallback(modifier,"无法解码")};is LoadState.Failed->PhotoLoadFallback(modifier,"点击重试"){onLoad(versionId)};else->Surface(modifier,shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surfaceVariant){Box(contentAlignment=Alignment.Center){CircularProgressIndicator(Modifier.size(24.dp),strokeWidth=2.dp)}}}}
@Composable private fun PhotoLoadFallback(modifier:Modifier,label:String,onClick:(()->Unit)?=null){Surface(modifier.then(if(onClick!=null)Modifier.clickable(role=Role.Button,onClick=onClick) else Modifier),shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.surfaceVariant){Box(contentAlignment=Alignment.Center){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}

@Composable private fun HealthSurface(modifier:Modifier=Modifier,onClick:(()->Unit)?=null,content:@Composable ColumnScope.()->Unit){val click=if(onClick!=null)Modifier.clickable(role=Role.Button,onClick=onClick) else Modifier;Surface(modifier.fillMaxWidth().then(click),shape=RoundedCornerShape(26.dp),color=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.48f)){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp),content=content)}}
@Composable private fun TrendChart(points:List<HealthTrendPoint>,modifier:Modifier,color:Color,metricKey:String?=null){
  val colors=points.map{if(metricKey==null)color else healthTone(metricAssessment(metricKey,it.value,it.unit).tone)}
  val values=points.map{it.value};val outline=MaterialTheme.colorScheme.outline;val surface=MaterialTheme.colorScheme.surface;val textColor=MaterialTheme.colorScheme.onSurfaceVariant;val unit=points.lastOrNull()?.unit.orEmpty()
  val axisPaint=remember{textPaint(Paint.Align.RIGHT)}.apply{this.color=textColor.toArgb()}
  val pointPaint=remember{textPaint(Paint.Align.CENTER,true)}.apply{this.color=color.toArgb()}
  Canvas(modifier){
    val left=48.dp.toPx();val right=size.width-8.dp.toPx();val top=30.dp.toPx();val bottom=size.height-16.dp.toPx()
    if(values.isEmpty())return@Canvas
    val rawMin=values.minOrNull()?:0.0;val rawMax=values.maxOrNull()?:rawMin;val padding=((rawMax-rawMin)*.12).takeIf{it>.000001}?:maxOf(abs(rawMax)*.01,.5);val min=rawMin-padding;val max=rawMax+padding;val range=max-min
    repeat(4){index->val y=top+(bottom-top)*index/3f;val tick=max-range*index/3;drawLine(outline.copy(alpha=.35f),Offset(left,y),Offset(right,y),1.dp.toPx());drawContext.canvas.nativeCanvas.drawText(healthValueText(tick,unit),left-7.dp.toPx(),y+4.dp.toPx(),axisPaint)}
    fun pointOffset(index:Int,value:Double):Offset{
      val x=if(values.size==1)(left+right)/2 else left+(right-left)*index/values.lastIndex.toFloat()
      return Offset(x,bottom-(bottom-top)*((value-min)/range).toFloat())
    }
    if(values.size>1){val path=Path();values.forEachIndexed{index,value->val point=pointOffset(index,value);if(index==0)path.moveTo(point.x,point.y) else path.lineTo(point.x,point.y)};drawPath(path,color,style=Stroke(3.dp.toPx(),cap=StrokeCap.Round))}
    val stride=(values.size/8).coerceAtLeast(1);values.forEachIndexed{index,value->val point=pointOffset(index,value);drawCircle(surface,5.dp.toPx(),point);drawCircle(colors[index],3.dp.toPx(),point);pointPaint.color=colors[index].toArgb();if(index%stride==0||index==values.lastIndex)drawContext.canvas.nativeCanvas.drawText(healthValueText(value,unit),point.x,point.y-8.dp.toPx(),pointPaint)}
  }
}

private fun textPaint(align:Paint.Align,bold:Boolean=false)=Paint(Paint.ANTI_ALIAS_FLAG).apply{textAlign=align;textSize=31f;typeface=if(bold)Typeface.create(Typeface.DEFAULT,Typeface.BOLD) else Typeface.DEFAULT}

@Composable private fun WeekBarChart(dates:List<LocalDate>,values:List<Double?>,color:Color,modifier:Modifier,unit:String?=null,metricKey:String?=null){val tones=values.map{if(metricKey==null)color else healthTone(metricAssessment(metricKey,it,unit.orEmpty(),true).tone)};val outline=MaterialTheme.colorScheme.outline;Column{Canvas(modifier){val maxValue=(values.filterNotNull().maxOrNull()?:0.0).coerceAtLeast(1.0);val gap=8.dp.toPx();val slot=(size.width-gap*(values.size-1))/values.size.coerceAtLeast(1);values.forEachIndexed{index,value->val left=index*(slot+gap);drawRoundRect(outline.copy(alpha=.2f),Offset(left,0f),Size(slot,size.height),cornerRadius=androidx.compose.ui.geometry.CornerRadius(slot/2));if(value!=null){val height=(size.height*(value/maxValue).toFloat()).coerceAtLeast(5.dp.toPx());drawRoundRect(tones[index],Offset(left,size.height-height),Size(slot,height),cornerRadius=androidx.compose.ui.geometry.CornerRadius(slot/2))}}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){dates.forEachIndexed{index,date->Column(horizontalAlignment=Alignment.CenterHorizontally){Text(dayUi(date),style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant);values.getOrNull(index)?.let{Text(number(it),style=MaterialTheme.typography.labelSmall,color=tones[index])}}}}}}
@Composable private fun MiniTrend(points:List<HealthTrendPoint>,modifier:Modifier,color:Color=MaterialTheme.colorScheme.primary){if(points.isEmpty()){Box(modifier,contentAlignment=Alignment.CenterStart){Text("等待数据",style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}} else TrendChart(points.takeLast(20),modifier,color)}
@Composable private fun ChartEmpty(text:String){Box(Modifier.fillMaxWidth().height(150.dp).clip(RoundedCornerShape(20.dp)).background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.34f)),contentAlignment=Alignment.Center){Text(text,color=MaterialTheme.colorScheme.onSurfaceVariant,modifier=Modifier.padding(24.dp))}}
@Composable private fun ChartDateRange(from:String,to:String){Row(Modifier.fillMaxWidth()){Text(from.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.weight(1f));Text(to.takeLast(5),style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun SummaryFact(label:String,value:String,modifier:Modifier=Modifier){Column(modifier){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleMedium,maxLines=1,overflow=TextOverflow.Ellipsis)}}
@Composable private fun HealthFact(label:String,value:String,modifier:Modifier=Modifier){Column(modifier.padding(vertical=4.dp)){Text(label,style=MaterialTheme.typography.labelMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.titleMedium)}}
@Composable private fun SourcePill(label:String,tone:Color){Surface(shape=CircleShape,color=tone.copy(alpha=.12f)){Text(label,Modifier.padding(horizontal=10.dp,vertical=6.dp),style=MaterialTheme.typography.labelMedium,color=tone)}}

@Composable private fun healthSourceColor(overview:WorkspaceOverview.Health?)=when{overview==null->MaterialTheme.colorScheme.onSurfaceVariant;overview.sourcesNeedingAttention>0->MaterialTheme.colorScheme.error;else->ActivityGreen}
private fun healthSourceLine(value:WorkspaceOverview.Health?)=when{value==null->"正在读取健康数据";value.sources==0->"尚未接入数据来源";value.sourcesNeedingAttention>0->"${value.sourcesNeedingAttention} 个来源需要处理";else->"已接入 ${value.sources} 个数据来源"}
private fun bodySnapshotMetrics(metrics:List<HealthMetricTrend>):List<HealthMetricTrend>{val order=listOf("weight","bmi","body_fat","fat_mass","lean_mass","skeletal_muscle","muscle_mass","muscle_rate","body_water","body_water_rate","bone_mass","bone_rate","visceral_fat","bmr","heart_rate");val ordered=order.mapNotNull{key->metrics.firstOrNull{it.key==key}};return ordered.filter{it.points.isNotEmpty()}.ifEmpty{ordered.take(4)}}
private fun lastSevenDays(history:List<HealthDailyOverview>):List<Pair<LocalDate,HealthDailyOverview?>> = (0L..6L).map{LocalDate.now().minusDays(it)}.reversed().map{date->date to history.firstOrNull{it.occurredOn==date.toString()}}
private fun dayUi(date:LocalDate)=listOf("一","二","三","四","五","六","日")[date.dayOfWeek.value-1]
internal fun sourceLabel(value:String)=mapOf("scale" to "小米体脂秤","xiaomi_scale" to "小米体脂秤","samsung" to "Samsung Health","samsung_health" to "Samsung Health","samsung_data_sdk" to "Samsung Health","health_connect" to "Health Connect","manual" to "手动记录","legacy_health" to "旧 Health 迁移","derived" to "由原始测量计算")[value.lowercase()]?:value
internal fun unitLabel(value:String)=mapOf("level" to "级","kcal/day" to "kcal/天","bpm" to "次/分")[value.lowercase()]?:value
internal fun workoutTypeUi(value:String):String{val key=value.trim().lowercase().replace(' ','_').replace('-','_');return mapOf("walk" to "健走","walking" to "健走","brisk_walking" to "健走","run" to "跑步","running" to "跑步","track_running" to "田径跑","jogging" to "慢跑","treadmill" to "跑步机","treadmill_running" to "跑步机跑步","running_treadmill" to "跑步机跑步","walking_treadmill" to "跑步机健走","cycling" to "自行车","biking" to "自行车","stationary_biking" to "室内自行车","indoor_cycling" to "室内自行车","mountain_biking" to "山地自行车","hiking" to "徒步","backpacking" to "旅行徒步","swimming" to "游泳","pool_swimming" to "游泳","open_water_swimming" to "户外游泳","strength_training" to "力量训练","weight_training" to "力量训练","weightlifting" to "举重","weight_machine" to "器械训练","circuit_training" to "循环训练","hiit" to "高强度间歇训练","rowing" to "划船","rowing_machine" to "划船机","elliptical" to "椭圆机","stair_climbing" to "爬楼梯","stair_climbing_machine" to "登阶机","step_machine" to "踏步机","yoga" to "瑜伽","pilates" to "普拉提","stretching" to "拉伸","dance" to "舞蹈","dancing" to "舞蹈","aerobics" to "有氧操","jump_rope" to "跳绳","football" to "足球","soccer" to "足球","basketball" to "篮球","badminton" to "羽毛球","tennis" to "网球","table_tennis" to "乒乓球","other" to "其他运动")[key]?:if(value.any{it.code>127})value else "其他运动 · ${value.replace('_',' ')}"}
@Composable private fun workoutTone(value:String):Color=when{value.contains("run",true)||value.contains("walk",true)||value.contains("hik",true)||value.contains("backpack",true)->ActivityGreen;value.contains("swim",true)||value.contains("row",true)->ActivityBlue;value.contains("strength",true)||value.contains("weight",true)||value.contains("circuit",true)->BodyOrange;else->ActivityPurple}
private fun workoutGlyph(value:String)=when{value.contains("run",true)->"↗";value.contains("walk",true)||value.contains("hik",true)||value.contains("backpack",true)->"↟";value.contains("swim",true)->"≈";value.contains("cycl",true)||value.contains("bik",true)->"◎";value.contains("strength",true)||value.contains("weight",true)||value.contains("circuit",true)->"◆";else->"●"}
private fun mealTypeUi(value:String)=mapOf("breakfast" to "早餐","lunch" to "午餐","dinner" to "晚餐","snack" to "加餐","other" to "其他")[value]?:"一餐"
private fun minutesLabel(value:Long)=if(value>=60)"${value/60} 小时 ${value%60} 分" else "$value 分钟"
private fun signed(value:Double)=(if(value>0)"+" else "")+number(value)
private fun number(value:Double):String=BigDecimal.valueOf(value).setScale(if(abs(value)>=100)0 else 1,RoundingMode.HALF_UP).stripTrailingZeros().toPlainString()
