import assert from "node:assert/strict";
import test from "node:test";
import { assertCompleteQueryTransport, buildCapabilityHttpRequest } from "../src/index.js";

test("every published query has one HTTP transport",()=>assert.doesNotThrow(assertCompleteQueryTransport));
test("today and timeline use their real typed HTTP routes",()=>{const today=buildCapabilityHttpRequest("https://life.example.com/","life.today",{date:"2026-09-12",time_zone:"Asia/Shanghai",domains:["health","money"]});assert.equal(today.method,"GET");assert.equal(today.url,"https://life.example.com/api/today?date=2026-09-12&time_zone=Asia%2FShanghai&domains=health%2Cmoney");const timeline=buildCapabilityHttpRequest("https://life.example.com","life.timeline",{domains:["meals"],limit:30});assert.equal(timeline.url,"https://life.example.com/api/timeline?domains=meals&limit=30");});
test("daily record check is one bounded typed request",()=>{const request=buildCapabilityHttpRequest("https://life.example.com/","life.daily_record_check",{date:"2026-09-19",time_zone:"Asia/Shanghai"});assert.equal(request.method,"POST");assert.equal(request.url,"https://life.example.com/api/life/daily-record-check");assert.deepEqual(JSON.parse(request.body!),{date:"2026-09-19",time_zone:"Asia/Shanghai",expectations:{minimum_meal_records:3,expected_meal_types:[],minimum_purchase_records:0,minimum_money_entries:0}});});
test("write transports validate and construct the canonical command envelope",()=>{const request=buildCapabilityHttpRequest("https://life.example.com","money.record_entry",{command_id:"cmd_transport_12345678",input:{entry_type:"expense",amount:"12.30",currency:"CNY",occurred_on:"2026-09-12",time_zone:"Asia/Shanghai"}});assert.equal(request.method,"POST");assert.equal(JSON.parse(request.body!).protocol,"shadow.command");});

test("meal paging preserves opaque cursors",()=>{const request=buildCapabilityHttpRequest("https://life.example.com","life.list_meals",{limit:10,cursor:"opaque+/=="});assert.equal(new URL(request.url).searchParams.get("cursor"),"opaque+/==");});
test("unknown outcomes can be recovered with the original validated command id",()=>{const request=buildCapabilityHttpRequest("https://life.example.com","operations.find",{command_id:"cmd_transport_12345678"});assert.equal(request.url,"https://life.example.com/api/operations/by-command/cmd_transport_12345678");assert.throws(()=>buildCapabilityHttpRequest("https://life.example.com","operations.find",{command_id:"bad-key"}));});
test("date-only history queries need both boundaries and preserve domain filters",()=>{const request=buildCapabilityHttpRequest("https://life.example.com","life.search",{types:["meals"],from_on:"2026-09-21",to_on_exclusive:"2026-09-22"});const url=new URL(request.url);assert.equal(url.searchParams.has("q"),false);assert.equal(url.searchParams.get("types"),"meals");assert.throws(()=>buildCapabilityHttpRequest("https://life.example.com","life.search",{}));assert.throws(()=>buildCapabilityHttpRequest("https://life.example.com","life.search",{from_on:"2026-09-21"}));});
