import { useEffect, useState } from "react";
import type { ConsumptionStatsResult } from "@shadow/contracts";
import { coveragePercent, loadConsumptionStats, type ConsumptionStatsFilters } from "./consumption-stats.js";
import { formatMoneyAmount } from "./money-display.js";

const initial:ConsumptionStatsFilters={months:3,scope:"",category:"",merchantRankBy:"orders",itemRankBy:"purchased_orders",currency:"CNY"};
const scopeLabels:Record<string,string>={restaurant_delivery:"餐饮外卖",grocery_delivery:"商超到家",dine_in:"到店餐饮",takeaway:"打包自取",physical_retail:"线下零售",drink_snack:"饮品零食",other:"其他",unknown:"待识别"};
const categoryLabels:Record<string,string>={dish:"菜品",staple:"主食",snack:"零食",beverage:"饮品",fresh_food:"生鲜",daily_goods:"日用品",other:"其他",unknown:"待识别"};
const timeLabels:Record<string,string>={morning:"早餐前后",lunch:"午餐",afternoon:"下午",dinner:"晚餐",late_night:"夜间",unknown:"时间未知"};

export function ConsumptionStatsPanel({headers}:{headers:HeadersInit}){
  const[filters,setFilters]=useState(initial),[data,setData]=useState<ConsumptionStatsResult>(),[pending,setPending]=useState(true),[error,setError]=useState<string>();
  const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  useEffect(()=>{let current=true;setPending(true);setError(undefined);void loadConsumptionStats(fetch,headers,filters,timeZone).then(value=>{if(current)setData(value)}).catch(caught=>{if(current)setError(caught instanceof Error?caught.message:"统计读取失败")}).finally(()=>{if(current)setPending(false)});return()=>{current=false}},[filters,headers,timeZone]);
  const maxOrders=Math.max(1,...(data?.monthly.map(month=>month.orders)??[]));
  return <section className="consumption-stats">
    <div className="panel-heading"><div><span className="eyebrow">CONSUMPTION INSIGHTS</span><h2>消费与购买统计</h2><p>订单、实际饮食与金额分开计数；退款归回原订单月份。</p></div><span className="status">规则 {data?.algorithm_version??"v1"}</span></div>
    <div className="stats-filters" aria-label="统计筛选"><fieldset><legend>时间范围</legend>{([1,3,6,12] as const).map(months=><button type="button" className={filters.months===months?"active secondary":"secondary"} key={months} onClick={()=>setFilters({...filters,months})}>{months} 个月</button>)}</fieldset><label>消费场景<select value={filters.scope} onChange={event=>setFilters({...filters,scope:event.target.value})}><option value="">全部场景</option>{options(scopeLabels)}</select></label><label>品类<select value={filters.category} onChange={event=>setFilters({...filters,category:event.target.value})}><option value="">全部品类</option>{options(categoryLabels)}</select></label><label>商家排序<select value={filters.merchantRankBy} onChange={event=>setFilters({...filters,merchantRankBy:event.target.value as ConsumptionStatsFilters["merchantRankBy"]})}><option value="orders">订单数</option><option value="gross_spend">消费总额</option><option value="net_spend">退款后净额</option></select></label><label>商品排序<select value={filters.itemRankBy} onChange={event=>setFilters({...filters,itemRankBy:event.target.value as ConsumptionStatsFilters["itemRankBy"]})}><option value="purchased_orders">购买订单数</option><option value="confirmed_consumptions">确认食用次数</option><option value="line_spend">商品金额</option></select></label></div>
    {pending&&<p className="empty-copy">正在按原始订单与饮食事实重新汇总…</p>}{error&&<p className="inline-error">{error}</p>}
    {data&&<><div className="stats-summary"><Metric label="订单" value={data.coverage.orders}/><Metric label="已关联饮食" value={data.coverage.meal_linked_orders}/><Metric label="场景覆盖" value={`${coveragePercent(data.coverage.orders-data.coverage.scope_unknown,data.coverage.orders)}%`}/><Metric label="支付覆盖" value={`${coveragePercent(data.coverage.payment_known,data.coverage.orders)}%`}/></div>
      <section className="stats-card"><h3>月度趋势</h3><div className="month-chart">{data.monthly.map(month=><article key={month.month}><div className="month-bar" style={{height:`${Math.max(4,month.orders/maxOrders*100)}%`}} title={`${month.orders} 单`}/><b>{month.orders}</b><span>{month.month.slice(5)} 月</span><small>{money(month.spend,filters.currency,"net")}</small></article>)}</div></section>
      <div className="stats-columns"><Ranking title="常去商家" rows={data.merchants.map(item=>({name:item.canonical_name,meta:`${scopeLabels[item.scope]} · ${item.orders} 单 · ${item.confirmed_meals} 次食用`,value:filters.merchantRankBy==="orders"?String(item.orders):money(item.spend,filters.currency,filters.merchantRankBy==="gross_spend"?"gross":"net"),raw:item.raw_names.join(" / ")}))}/><Ranking title="常买商品 / 菜品" rows={data.items.map(item=>({name:item.canonical_name,meta:`${categoryLabels[item.category]} · ${item.purchased_orders} 单购买 · ${item.confirmed_consumptions} 次食用`,value:filters.itemRankBy==="purchased_orders"?String(item.purchased_orders):filters.itemRankBy==="confirmed_consumptions"?String(item.confirmed_consumptions):moneyLine(item.line_spend,filters.currency),raw:item.raw_names.join(" / ")}))}/></div>
      <section className="stats-card"><h3>消费时段</h3><div className="time-grid">{data.time_distribution.map(item=><article key={item.bucket}><b>{item.orders}</b><span>{timeLabels[item.bucket]}</span><small>{item.confirmed_meals} 次确认饮食</small></article>)}</div></section>
      <Coverage data={data}/></>}
  </section>;
}

function Metric({label,value}:{label:string;value:string|number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function Ranking({title,rows}:{title:string;rows:{name:string;meta:string;value:string;raw:string}[]}){return <section className="stats-card ranking"><h3>{title}</h3>{rows.length?<ol>{rows.map((row,index)=><li key={`${row.name}:${index}`}><span className="rank">{index+1}</span><span><b>{row.name}</b><small>{row.meta}</small>{row.raw!==row.name&&<i title="归一化前名称">原始：{row.raw}</i>}</span><strong>{row.value}</strong></li>)}</ol>:<p className="empty-copy">当前筛选下没有数据。</p>}</section>}
function Coverage({data}:{data:ConsumptionStatsResult}){return <section className="stats-card coverage-card"><h3>数据口径与覆盖</h3><p>只纳入已确认且未作废的事实；服务费、包装费、餐具、偏好说明和“首件…等多件”折叠摘要不进入商品榜。金额按币种分开，数量按购买/食用及单位分开。</p><dl><div><dt>商品行</dt><dd>{data.coverage.included_item_lines} / {data.coverage.item_lines}</dd></div><div><dt>排除服务行</dt><dd>{data.coverage.excluded_service_lines}</dd></div><div><dt>排除折叠摘要</dt><dd>{data.coverage.excluded_folded_lines}</dd></div><div><dt>明细不完整订单</dt><dd>{data.coverage.folded_orders}</dd></div><div><dt>已补录订单</dt><dd>{data.coverage.supplemented_orders}</dd></div><div><dt>明确分类</dt><dd>{data.coverage.item_category_explicit}</dd></div><div><dt>规则推断</dt><dd>{data.coverage.item_category_derived}</dd></div><div><dt>待识别</dt><dd>{data.coverage.item_category_unknown}</dd></div></dl>{!data.coverage.money_authorized&&<p className="coverage-warning">没有账目读取权限，金额指标不会显示，也不会按零处理。</p>}{(data.unknowns.merchants.length>0||data.unknowns.items.length>0)&&<details><summary>查看待识别项</summary><p>商家：{data.unknowns.merchants.map(item=>`${item.name}（${item.orders}）`).join("、")||"无"}</p><p>商品：{data.unknowns.items.map(item=>`${item.name}（${item.occurrences}）`).join("、")||"无"}</p></details>}</section>}
function options(labels:Record<string,string>){return Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}
function money(rows:{currency:string;gross:string;refund:string;net:string}[],currency:string,key:"gross"|"net"):string{const row=rows.find(item=>item.currency===currency);return row?`${formatMoneyAmount(row[key],currency)} ${currency}`:"—"}
function moneyLine(rows:{currency:string;amount:string}[],currency:string):string{const row=rows.find(item=>item.currency===currency);return row?`${formatMoneyAmount(row.amount,currency)} ${currency}`:"—"}
