import { useEffect, useRef, useState, type FormEvent } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
import { buildRecipeMealCommand, buildSaveFoodCommand, buildSaveRecipeCommand, emptyFoodFields, emptyRecipeFields, foodFields, initialRecipeMealFields, loadFoodCatalog, recipeFields, type FoodCatalog, type FoodFields, type RecipeFields, type RecipeMealFields } from "./food-catalog.js";

type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
export function FoodCatalogPanel({headers,date,timeZone,canSaveFood,canSaveRecipe,canRecordRecipe,execute,onChanged}:{headers:HeadersInit;date:string;timeZone:string;canSaveFood:boolean;canSaveRecipe:boolean;canRecordRecipe:boolean;execute:Execute;onChanged:()=>Promise<void>}){
  const[catalog,setCatalog]=useState<FoodCatalog>(),[query,setQuery]=useState(""),[food,setFood]=useState<FoodFields>(emptyFoodFields),[recipe,setRecipe]=useState<RecipeFields>(emptyRecipeFields),[meal,setMeal]=useState<RecipeMealFields>(()=>initialRecipeMealFields(date,timeZone)),[pending,setPending]=useState<string>(),[error,setError]=useState<string>(),ids=useRef<Record<string,string>>({});
  async function load(search=query){try{setError(undefined);setCatalog(await loadFoodCatalog(fetch,headers,search));}catch(caught){setError(caught instanceof Error?caught.message:"食物目录读取失败");}}
  useEffect(()=>{void load("")},[]);
  async function run(kind:string,built:{capability:WriteCapabilityName;input:unknown},reset:()=>void,event:FormEvent){event.preventDefault();setPending(kind);setError(undefined);try{ids.current[kind]??=`cmd_web_${crypto.randomUUID()}`;await execute(built.capability,built.input,ids.current[kind]!);delete ids.current[kind];reset();await Promise.all([load(""),onChanged()]);}catch(caught){setError(caught instanceof Error?caught.message:"保存失败");}finally{setPending(undefined);}}
  const foods=catalog?.foods??[],recipes=catalog?.recipes??[];
  return <section className="food-panel"><div className="panel-heading"><div><span className="eyebrow">FOOD &amp; RECIPES</span><h2>食物与食谱</h2></div><form className="catalog-search" onSubmit={event=>{event.preventDefault();void load(query)}}><input aria-label="搜索食物或食谱" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称"/><button type="submit">搜索</button></form></div><p>营养未填写就保持未知；从食谱记餐会复制当时版本，不随之后的修改变化。</p>{error&&<p className="inline-error">{error}</p>}
    <div className="catalog-grid">
      {canSaveFood&&<form className="catalog-form" onSubmit={event=>void run("food",buildSaveFoodCommand(food),()=>setFood(emptyFoodFields()),event)}><h3>{food.foodId?"修改食物":"新增食物"}</h3><label>选择<select value={food.foodId} onChange={event=>{const selected=foods.find(item=>item.id===event.target.value);setFood(selected?foodFields(selected):emptyFoodFields());}}><option value="">新建</option>{foods.map(item=><option value={item.id} key={item.id}>{item.name} · v{item.revision}</option>)}</select></label><label>名称<input required value={food.name} onChange={event=>setFood({...food,name:event.target.value})}/></label><div className="field-pair"><label>每份数量<input inputMode="decimal" value={food.servingAmount} onChange={event=>setFood({...food,servingAmount:event.target.value})}/></label><label>每份单位<input required={Boolean(food.servingAmount)} value={food.servingUnit} onChange={event=>setFood({...food,servingUnit:event.target.value})}/></label></div><div className="nutrient-grid"><Nutrient label="千卡" value={food.energyKcal} set={value=>setFood({...food,energyKcal:value})}/><Nutrient label="蛋白质 g" value={food.proteinG} set={value=>setFood({...food,proteinG:value})}/><Nutrient label="脂肪 g" value={food.fatG} set={value=>setFood({...food,fatG:value})}/><Nutrient label="碳水 g" value={food.carbG} set={value=>setFood({...food,carbG:value})}/><Nutrient label="纤维 g" value={food.fiberG} set={value=>setFood({...food,fiberG:value})}/><Nutrient label="钠 mg" value={food.sodiumMg} set={value=>setFood({...food,sodiumMg:value})}/></div><label>数据来源<input value={food.provenance} onChange={event=>setFood({...food,provenance:event.target.value})} placeholder="如：包装标签；不确定请留空"/></label><label>状态<select value={food.state} onChange={event=>setFood({...food,state:event.target.value as FoodFields["state"]})}><option value="active">使用中</option><option value="archived">已归档</option></select></label>{food.foodId&&<label>修改原因<input required value={food.reason} onChange={event=>setFood({...food,reason:event.target.value})}/></label>}<button disabled={pending!==undefined}>{pending==="food"?"保存中…":"保存食物"}</button></form>}
      {canSaveRecipe&&<form className="catalog-form" onSubmit={event=>void run("recipe",buildSaveRecipeCommand(recipe,foods),()=>setRecipe(emptyRecipeFields()),event)}><h3>{recipe.recipeId?"修改食谱":"新增食谱"}</h3><label>选择<select value={recipe.recipeId} onChange={event=>{const selected=recipes.find(item=>item.id===event.target.value);setRecipe(selected?recipeFields(selected):emptyRecipeFields());}}><option value="">新建</option>{recipes.map(item=><option value={item.id} key={item.id}>{item.title} · v{item.revision}</option>)}</select></label><label>标题<input required value={recipe.title} onChange={event=>setRecipe({...recipe,title:event.target.value})}/></label><label>成品份数<input required inputMode="decimal" value={recipe.servings} onChange={event=>setRecipe({...recipe,servings:event.target.value})}/></label><label>原料<textarea required value={recipe.ingredients} onChange={event=>setRecipe({...recipe,ingredients:event.target.value})} placeholder={"燕麦|40|g\n牛奶|250|ml"}/><small>每行固定为“名称|数量|单位”；名称与个人食物完全一致时自动建立引用。</small></label><label>步骤<textarea value={recipe.instructions} onChange={event=>setRecipe({...recipe,instructions:event.target.value})}/></label><label>状态<select value={recipe.state} onChange={event=>setRecipe({...recipe,state:event.target.value as RecipeFields["state"]})}><option value="active">使用中</option><option value="archived">已归档</option></select></label>{recipe.recipeId&&<label>修改原因<input required value={recipe.reason} onChange={event=>setRecipe({...recipe,reason:event.target.value})}/></label>}<button disabled={pending!==undefined}>{pending==="recipe"?"保存中…":"保存食谱"}</button></form>}
      {canRecordRecipe&&<form className="catalog-form recipe-meal" onSubmit={event=>void run("meal",buildRecipeMealCommand(meal),()=>setMeal(initialRecipeMealFields(date,timeZone)),event)}><h3>按食谱记餐</h3><label>食谱<select required value={meal.recipeId} onChange={event=>{const selected=recipes.find(item=>item.id===event.target.value);setMeal({...meal,recipeId:selected?.id??"",recipeRevision:selected?.revision});}}><option value="">请选择</option>{recipes.filter(item=>item.state==="active").map(item=><option key={item.id} value={item.id}>{item.title} · v{item.revision}</option>)}</select></label><label>实际食用比例<input required inputMode="decimal" value={meal.consumedFraction} onChange={event=>setMeal({...meal,consumedFraction:event.target.value})}/><small>1 表示全部，0.5 表示一半；不会猜测人数。</small></label><div className="field-pair"><label>用餐日<input type="date" required value={meal.occurredOn} onChange={event=>setMeal({...meal,occurredOn:event.target.value})}/></label><label>餐次<select value={meal.mealType} onChange={event=>setMeal({...meal,mealType:event.target.value as RecipeMealFields["mealType"]})}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label></div><label>事实时区<input required value={meal.timeZone} onChange={event=>setMeal({...meal,timeZone:event.target.value})}/></label><label>备注<textarea value={meal.note} onChange={event=>setMeal({...meal,note:event.target.value})}/></label><button disabled={pending!==undefined}>{pending==="meal"?"保存中…":"记录实际用餐"}</button></form>}
    </div><h3>目录</h3>{!foods.length&&!recipes.length?<p>还没有食物或食谱。</p>:<ul className="catalog-list">{foods.map(item=><li key={item.id}><b>{item.name}</b><span>{item.serving_amount?`每份 ${item.serving_amount} ${item.serving_unit}`:"份量未填写"} · 热量 {nutrient(item.nutrients.energy_kcal,"kcal")} · v{item.revision}{item.state==="archived"?" · 已归档":""}</span></li>)}{recipes.map(item=><li key={item.id}><b>{item.title}</b><span>{item.servings} 份 · {item.items.length} 项原料 · v{item.revision}{item.state==="archived"?" · 已归档":""}</span></li>)}</ul>}</section>;
}
function Nutrient({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <label>{label}<input inputMode="decimal" value={value} onChange={event=>set(event.target.value)} placeholder="未填写"/></label>}
function nutrient(value:unknown,unit:string):string{return typeof value==="string"?`${value} ${unit}`:"未填写";}
