import { useEffect, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";

type LibraryRow={id:string;title:string;itemType?:string;item_type?:string;revision:number;readingState?:{progress:string|number;state:string}|null};
type LibraryDetail={item:{id:string;title:string;item_type:string;current_revision:number};sources:Array<{asset?:{id:string;media_type?:string;sha256?:string}}>;revisions:Array<{revision:number;text?:string|null;url?:string|null}>;snippets:Array<{id:string;text:string;item_revision:number;locator:unknown}>;processing_jobs:Array<{id:string;kind:string;requested_processor:string;state:string;attempts:number;last_error?:string|null}>;reading_state?:{item_revision:number;progress:string|number;state:string;locator:unknown}|null;legacy_links:Array<{id:string;legacy_uri:string;verification_state:string;verification_error?:string|null}>};
async function json<T>(response:Response):Promise<T>{const body=await response.json() as T&{message?:string};if(!response.ok)throw new Error(body.message??`HTTP ${response.status}`);return body;}

export function LibraryPanel({headers,capabilities,execute,onChanged}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute;onChanged:()=>Promise<void>}){
  const[items,setItems]=useState<LibraryRow[]>([]),[detail,setDetail]=useState<LibraryDetail>(),[query,setQuery]=useState(""),[file,setFile]=useState<File>(),[title,setTitle]=useState(""),[progress,setProgress]=useState(0),[legacyUri,setLegacyUri]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  async function load(q=query){try{const body=await json<{items:LibraryRow[]}>(await fetch(`/api/library?limit=50${q.trim()?`&q=${encodeURIComponent(q.trim())}`:""}`,{headers}));setItems(body.items);}catch(caught){setError(caught instanceof Error?caught.message:"资料读取失败");}}
  async function open(id:string){try{const value=await json<LibraryDetail>(await fetch(`/api/library/items/${encodeURIComponent(id)}`,{headers}));setDetail(value);setProgress(Number(value.reading_state?.progress??0));}catch(caught){setError(caught instanceof Error?caught.message:"资料详情读取失败");}}
  useEffect(()=>{void load("")},[]);
  async function upload(event:FormEvent){event.preventDefault();if(!file)return;setPending(true);setError(undefined);try{const asset=await json<{asset_version_id:string}>(await fetch("/api/assets",{method:"POST",headers:{...(headers as Record<string,string>),"content-type":file.type||"application/octet-stream"},body:file})),kind=file.type.startsWith("image/")?"image":"import",itemType=file.type.startsWith("image/")?"image":"document",captured=await execute("library.capture",{title:title.trim()||file.name,item_type:itemType,tags:[],source:{kind,captured_on:new Intl.DateTimeFormat("en-CA").format(new Date()),asset_version_id:asset.asset_version_id}},`library:capture:${asset.asset_version_id}`),itemId=String(captured.actual_values.library_item_id);if(["text/plain","text/markdown","application/json"].includes(file.type))await execute("library.queue_processing",{item_id:itemId,source_asset_version_id:asset.asset_version_id,kind:"text_extract",requested_processor:"builtin-text-v1"},`library:process:${asset.asset_version_id}`);setFile(undefined);setTitle("");await Promise.all([load(""),onChanged()]);await open(itemId);}catch(caught){setError(caught instanceof Error?caught.message:"原件保存失败");}finally{setPending(false);}}
  async function saveProgress(){if(!detail)return;setPending(true);try{await execute("library.set_reading_state",{item_id:detail.item.id,item_revision:detail.item.current_revision,locator:{kind:"progress",fraction:progress},progress,state:progress===1?"completed":"active"},`library:reading:${detail.item.id}`);await open(detail.item.id);await load();}catch(caught){setError(caught instanceof Error?caught.message:"阅读进度保存失败");}finally{setPending(false);}}
  async function retry(jobId:string){setPending(true);try{await execute("library.retry_processing",{job_id:jobId},`library:retry:${jobId}`);if(detail)await open(detail.item.id);}catch(caught){setError(caught instanceof Error?caught.message:"任务重试失败");}finally{setPending(false);}}
  async function registerLegacy(event:FormEvent){event.preventDefault();if(!detail)return;setPending(true);try{await execute("library.register_legacy_link",{item_id:detail.item.id,legacy_uri:legacyUri,algorithm:"legacy-unverified"},`library:legacy:${detail.item.id}`);setLegacyUri("");await open(detail.item.id);}catch(caught){setError(caught instanceof Error?caught.message:"旧链接登记失败");}finally{setPending(false);}}
  return <section className="library-panel"><div className="panel-heading"><div><span className="eyebrow">LIBRARY</span><h2>阅读与找回</h2></div><form className="library-search" onSubmit={event=>{event.preventDefault();void load();}}><input aria-label="全文搜索" value={query} onChange={event=>setQuery(event.target.value)} placeholder="标题、正文、识别片段"/><button>搜索</button></form></div>{error&&<p className="inline-error">{error}</p>}
    <div className="library-grid"><form className="library-upload" onSubmit={upload}><h3>固定原件</h3><label>标题（可选）<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>文件<input type="file" required onChange={event=>setFile(event.target.files?.[0])}/></label><button disabled={pending||!file||!capabilities.has("library.capture")}>保存原件</button><small>纯文本会排入本地提取；图片和音频需接入真实 OCR/转写处理器。</small></form><section className="library-list"><h3>资料</h3>{!items.length?<p>没有匹配资料。</p>:<ul>{items.map(item=><li key={item.id}><button type="button" onClick={()=>void open(item.id)}><b>{item.title}</b><span>修订 {item.revision}{item.readingState?` · ${Math.round(Number(item.readingState.progress)*100)}%`:""}</span></button></li>)}</ul>}</section></div>
    {detail&&<section className="library-reader"><header><div><small>{detail.item.item_type} · 修订 {detail.item.current_revision}</small><h3>{detail.item.title}</h3></div><button type="button" className="secondary" onClick={()=>setDetail(undefined)}>关闭</button></header>{detail.revisions[0]?.text&&<pre>{detail.revisions[0].text}</pre>}{detail.snippets.map(snippet=><blockquote key={snippet.id}>{snippet.text}<small>修订 {snippet.item_revision} · {JSON.stringify(snippet.locator)}</small></blockquote>)}<label>阅读进度 {Math.round(progress*100)}%<input type="range" min="0" max="1" step="0.01" value={progress} onChange={event=>setProgress(Number(event.target.value))}/></label><button type="button" disabled={pending} onClick={()=>void saveProgress()}>保存阅读位置</button><h4>处理任务</h4>{detail.processing_jobs.length?<ul>{detail.processing_jobs.map(job=><li key={job.id}><span className={`status ${job.state}`}>{job.state}</span> {job.kind} · {job.requested_processor} · 尝试 {job.attempts}{job.last_error&&<small>{job.last_error}</small>}{job.state==="failed"&&<button type="button" onClick={()=>void retry(job.id)}>重试</button>}</li>)}</ul>:<p>没有处理任务。</p>}<h4>旧 URI / 证明</h4>{detail.legacy_links.map(link=><p key={link.id}><code>{link.legacy_uri}</code> · <span className={`status ${link.verification_state}`}>{link.verification_state}</span>{link.verification_error&&` · ${link.verification_error}`}</p>)}<form className="legacy-form" onSubmit={registerLegacy}><label>登记无法校验的旧 URI<input required value={legacyUri} onChange={event=>setLegacyUri(event.target.value)} placeholder="shadow://legacy/..."/></label><button disabled={pending}>登记为未验证</button></form></section>}
  </section>;
}
