import { useEffect, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";

type LibraryRow={id:string;title:string;itemType?:string;item_type?:string;revision:number;readingState?:{progress:string|number;state:string}|null};
type LibraryDetail={item:{id:string;title:string;item_type:string;current_revision:number};sources:Array<{asset?:{id:string;media_type?:string;sha256?:string}}>;revisions:Array<{revision:number;text?:string|null;url?:string|null}>;snippets:Array<{id:string;text:string;item_revision:number;locator:unknown}>;processing_jobs:Array<{id:string;kind:string;requested_processor:string;state:string;attempts:number;last_error?:string|null}>;reading_state?:{item_revision:number;progress:string|number;state:string;locator:unknown}|null;legacy_links:Array<{id:string;legacy_uri:string;verification_state:string;verification_error?:string|null}>};
type UploadWorkflow={version:1;identityKey:string;assetVersionId:string;title:string;itemType:"image"|"document";sourceKind:"image"|"import";mediaType:string;capturedOn:string;itemId?:string;stage:"uploaded"|"captured"};
async function json<T>(response:Response):Promise<T>{const body=await response.json() as T&{message?:string};if(!response.ok)throw new Error(body.message??`HTTP ${response.status}`);return body;}

export function LibraryPanel({identityKey,headers,capabilities,execute,onChanged}:{identityKey:string;headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute;onChanged:()=>Promise<void>}){
  const[items,setItems]=useState<LibraryRow[]>([]),[detail,setDetail]=useState<LibraryDetail>(),[query,setQuery]=useState(""),[file,setFile]=useState<File>(),[title,setTitle]=useState(""),[workflow,setWorkflow]=useState<UploadWorkflow>(),[progress,setProgress]=useState(0),[legacyUri,setLegacyUri]=useState(""),[showUpload,setShowUpload]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  const workflowKey=`shadow-life:library-upload:${identityKey}`;
  async function load(q=query){try{const body=await json<{items:LibraryRow[]}>(await fetch(`/api/library?limit=50${q.trim()?`&q=${encodeURIComponent(q.trim())}`:""}`,{headers}));setItems(body.items);}catch(caught){setError(caught instanceof Error?caught.message:"资料读取失败");}}
  async function open(id:string){try{const value=await json<LibraryDetail>(await fetch(`/api/library/items/${encodeURIComponent(id)}`,{headers}));setDetail(value);setProgress(Number(value.reading_state?.progress??0));}catch(caught){setError(caught instanceof Error?caught.message:"资料详情读取失败");}}
  useEffect(()=>{void load("");if(!identityKey)return;try{const raw=sessionStorage.getItem(workflowKey),saved=raw?JSON.parse(raw) as UploadWorkflow:undefined;if(saved?.version===1&&saved.identityKey===identityKey)setWorkflow(saved);}catch{}},[identityKey]);
  function persistWorkflow(value:UploadWorkflow|undefined){setWorkflow(value);try{if(value)sessionStorage.setItem(workflowKey,JSON.stringify(value));else sessionStorage.removeItem(workflowKey);}catch{if(value)throw new Error("浏览器无法保存上传阶段；为避免重复捕获，已停止后续步骤。");}}
  async function continueWorkflow(value:UploadWorkflow){let current=value;try{if(current.stage==="uploaded"){const captured=await execute("library.capture",{title:current.title,item_type:current.itemType,tags:[],source:{kind:current.sourceKind,captured_on:current.capturedOn,asset_version_id:current.assetVersionId}},`library:capture:${current.assetVersionId}`),itemId=String(captured.actual_values.library_item_id);current={...current,itemId,stage:"captured"};persistWorkflow(current);}if(["text/plain","text/markdown","application/json"].includes(current.mediaType)){if(!current.itemId)throw new Error("捕获回执缺少资料 ID。");await execute("library.queue_processing",{item_id:current.itemId,source_asset_version_id:current.assetVersionId,kind:"text_extract",requested_processor:"builtin-text-v1"},`library:process:${current.assetVersionId}`);}persistWorkflow(undefined);setFile(undefined);setTitle("");await Promise.all([load(""),onChanged()]);if(current.itemId)await open(current.itemId);}catch(caught){persistWorkflow(current);throw caught;}}
  async function upload(event:FormEvent){event.preventDefault();if(!file||!identityKey)return;setPending(true);setError(undefined);try{const mediaType=file.type||"application/octet-stream",asset=await json<{asset_version_id:string}>(await fetch("/api/assets",{method:"POST",headers:{...(headers as Record<string,string>),"content-type":mediaType},body:file})),value:UploadWorkflow={version:1,identityKey,assetVersionId:asset.asset_version_id,title:title.trim()||file.name,itemType:mediaType.startsWith("image/")?"image":"document",sourceKind:mediaType.startsWith("image/")?"image":"import",mediaType,capturedOn:new Intl.DateTimeFormat("en-CA").format(new Date()),stage:"uploaded"};persistWorkflow(value);await continueWorkflow(value);}catch(caught){setError(caught instanceof Error?caught.message:"原件保存失败");}finally{setPending(false);}}
  async function resume(){if(!workflow)return;setPending(true);setError(undefined);try{await continueWorkflow(workflow);}catch(caught){setError(caught instanceof Error?caught.message:"继续资料处理失败");}finally{setPending(false);}}
  async function saveProgress(){if(!detail)return;setPending(true);try{await execute("library.set_reading_state",{item_id:detail.item.id,item_revision:detail.item.current_revision,locator:{kind:"progress",fraction:progress},progress,state:progress===1?"completed":"active"},`library:reading:${detail.item.id}`);await open(detail.item.id);await load();}catch(caught){setError(caught instanceof Error?caught.message:"阅读进度保存失败");}finally{setPending(false);}}
  async function retry(jobId:string){setPending(true);try{await execute("library.retry_processing",{job_id:jobId},`library:retry:${jobId}`);if(detail)await open(detail.item.id);}catch(caught){setError(caught instanceof Error?caught.message:"任务重试失败");}finally{setPending(false);}}
  async function registerLegacy(event:FormEvent){event.preventDefault();if(!detail)return;setPending(true);try{await execute("library.register_legacy_link",{item_id:detail.item.id,legacy_uri:legacyUri,algorithm:"legacy-unverified"},`library:legacy:${detail.item.id}`);setLegacyUri("");await open(detail.item.id);}catch(caught){setError(caught instanceof Error?caught.message:"旧链接登记失败");}finally{setPending(false);}}
  return <section className="library-panel"><div className="panel-heading"><div><span className="eyebrow">LIBRARY</span><h2>阅读与找回</h2></div><div className="panel-actions"><form className="library-search" onSubmit={event=>{event.preventDefault();void load();}}><input aria-label="全文搜索" value={query} onChange={event=>setQuery(event.target.value)} placeholder="标题、正文、识别片段"/><button>搜索</button></form><button type="button" onClick={()=>setShowUpload(value=>!value)}>{showUpload?"收起录入":"＋ 录入资料"}</button></div></div>{error&&<p className="inline-error">{error}</p>}
    {showUpload&&<form className="library-upload editor-card" onSubmit={upload}><div className="panel-heading"><h3>固定原件</h3><button type="button" className="icon-button" aria-label="关闭录入" onClick={()=>setShowUpload(false)}>×</button></div>{workflow&&<aside className="import-summary"><b>{workflow.title}</b><span>{workflow.stage==="uploaded"?"原件已上传，尚未生成资料记录":"原件和资料记录已保存，处理任务尚未排队"}</span><button type="button" disabled={pending} onClick={()=>void resume()}>从当前阶段继续</button><button type="button" className="secondary" disabled={pending} onClick={()=>persistWorkflow(undefined)}>放弃本地流程记录</button></aside>}<label>标题（可选）<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>文件<input type="file" required onChange={event=>setFile(event.target.files?.[0])}/></label><button disabled={pending||Boolean(workflow)||!file||!identityKey||!capabilities.has("library.capture")}>上传并保存原件</button><small>上传、捕获、排队分别记录阶段；网络中断后只继续未完成步骤，不会重新上传或重复捕获。</small></form>}<section className="library-list"><h3>资料</h3>{!items.length?<p>没有匹配资料。</p>:<ul>{items.map(item=><li key={item.id}><button type="button" onClick={()=>void open(item.id)}><b>{item.title}</b><span>修订 {item.revision}{item.readingState?` · ${Math.round(Number(item.readingState.progress)*100)}%`:""}</span></button></li>)}</ul>}</section>
    {detail&&<section className="library-reader"><header><div><small>{detail.item.item_type} · 修订 {detail.item.current_revision}</small><h3>{detail.item.title}</h3></div><button type="button" className="secondary" onClick={()=>setDetail(undefined)}>关闭</button></header>{detail.sources[0]?.asset&&<AssetPreview asset={detail.sources[0].asset} title={detail.item.title} headers={headers}/>} {detail.revisions[0]?.text&&<pre>{detail.revisions[0].text}</pre>}{detail.snippets.map(snippet=><blockquote key={snippet.id}>{snippet.text}<small>修订 {snippet.item_revision} · {locatorSummary(snippet.locator)}</small></blockquote>)}<label>阅读进度 {Math.round(progress*100)}%<input type="range" min="0" max="1" step="0.01" value={progress} onChange={event=>setProgress(Number(event.target.value))}/></label><button type="button" disabled={pending} onClick={()=>void saveProgress()}>保存阅读位置</button><h4>处理任务</h4>{detail.processing_jobs.length?<ul>{detail.processing_jobs.map(job=><li key={job.id}><span className={`status ${job.state}`}>{job.state}</span> {job.kind} · {job.requested_processor} · 尝试 {job.attempts}{job.last_error&&<small>{job.last_error}</small>}{job.state==="failed"&&<button type="button" onClick={()=>void retry(job.id)}>重试</button>}</li>)}</ul>:<p>没有处理任务。</p>}<h4>旧 URI / 证明</h4>{detail.legacy_links.map(link=><p key={link.id}><code>{link.legacy_uri}</code> · <span className={`status ${link.verification_state}`}>{link.verification_state}</span>{link.verification_error&&` · ${link.verification_error}`}</p>)}<form className="legacy-form" onSubmit={registerLegacy}><label>登记无法校验的旧 URI<input required value={legacyUri} onChange={event=>setLegacyUri(event.target.value)} placeholder="shadow://legacy/..."/></label><button disabled={pending}>登记为未验证</button></form></section>}
  </section>;
}

function AssetPreview({asset,title,headers}:{asset:{id:string;media_type?:string};title:string;headers:HeadersInit}){
  const[url,setUrl]=useState<string>(),[mediaType,setMediaType]=useState(asset.media_type??""),[error,setError]=useState<string>();
  useEffect(()=>{let objectUrl:string|undefined,active=true;void fetch(`/api/assets/${encodeURIComponent(asset.id)}/preview`,{headers}).then(async response=>{if(response.status===415){if(active)setError("此类型不能在页面内预览，请下载原件。");return;}if(!response.ok)throw new Error(`预览读取失败（HTTP ${response.status}）`);const blob=await response.blob();objectUrl=URL.createObjectURL(blob);if(active){setMediaType(blob.type);setUrl(objectUrl);}else URL.revokeObjectURL(objectUrl);}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:"预览读取失败");});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[asset.id]);
  async function download(){const response=await fetch(`/api/assets/${encodeURIComponent(asset.id)}`,{headers});if(!response.ok){setError(`原件下载失败（HTTP ${response.status}）`);return;}const blob=await response.blob(),downloadUrl=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=downloadUrl;anchor.download=title;anchor.click();setTimeout(()=>URL.revokeObjectURL(downloadUrl),0);}
  return <section className="asset-preview"><div className="asset-toolbar"><b>固定原件</b><button type="button" className="secondary" onClick={()=>void download()}>下载原件</button></div>{url&&mediaType.startsWith("image/")&&<img src={url} alt={title}/>} {url&&mediaType==="application/pdf"&&<iframe title={`${title} PDF 预览`} src={url}/>} {!url&&!error&&<p>正在载入原件预览…</p>}{error&&<p className="inline-error">{error}</p>}</section>;
}
function locatorSummary(value:unknown):string{if(!value||typeof value!=="object"||Array.isArray(value))return "位置未标注";const entries=Object.entries(value as Record<string,unknown>).filter(([,item])=>typeof item==="string"||typeof item==="number");return entries.length?entries.map(([key,item])=>`${key} ${String(item)}`).join(" · "):"位置未标注";}
