import { useEffect, useState, type FormEvent } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
type Project={id:string;title:string;goal:string;starts_on:string|null;ends_on:string|null;state:string;revision:number;milestones:Array<Record<string,unknown>>;links:Array<Record<string,unknown>>;actions:Array<Record<string,unknown>>};
export function LifeProjectPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){const [projects,setProjects]=useState<Project[]>([]),[title,setTitle]=useState(""),[goal,setGoal]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[milestone,setMilestone]=useState(""),[linkKind,setLinkKind]=useState(""),[linkId,setLinkId]=useState(""),[linkRevision,setLinkRevision]=useState("1"),[actionProject,setActionProject]=useState(""),[actionTitle,setActionTitle]=useState(""),[actionDue,setActionDue]=useState(""),[error,setError]=useState<string>(),[pending,setPending]=useState(false);
  async function load(){const response=await fetch("/api/life/projects?limit=20",{headers});if(!response.ok)throw new Error(`读取生活项目失败（HTTP ${response.status}）`);const items=((await response.json()) as {items:Project[]}).items;setProjects(items);setActionProject(current=>current||items[0]?.id||"");}
  useEffect(()=>{void load().catch(caught=>setError(caught instanceof Error?caught.message:"读取项目失败"));},[]);
  async function save(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{await execute("life.save_project",{title:title.trim(),goal:goal.trim(),...(start?{starts_on:start}:{}),...(end?{ends_on:end}:{}),state:"active",milestones:milestone.trim()?[{title:milestone.trim(),...(end?{due_on:end}:{}),state:"planned"}]:[],links:linkKind&&linkId.trim()?[{kind:linkKind,id:linkId.trim(),revision:Number(linkRevision),role:"supporting"}]:[]},`cmd_web_project_${crypto.randomUUID()}`);setTitle("");setGoal("");setMilestone("");setLinkId("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存项目失败");}finally{setPending(false);}}
  async function addAction(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{await execute("life.save_action_item",{project_id:actionProject,title:actionTitle.trim(),...(actionDue?{due_on:actionDue}:{}),state:"open"},`cmd_web_action_${crypto.randomUUID()}`);setActionTitle("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存行动失败");}finally{setPending(false);}}
  if(!capabilities.has("life.projects"))return null;return <section className="wide life-projects"><div className="panel-heading"><div><span className="eyebrow">LIFE PROJECT</span><h2>轻量生活项目</h2></div></div><p>项目只组织目标、里程碑、行动与稳定引用，不复制健康、账目、旅行或资料事实。</p>{error&&<p className="inline-error">{error}</p>}{capabilities.has("life.save_project")&&<form className="compact-form" onSubmit={save}><h3>新建项目</h3><label>名称<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>开始<input type="date" value={start} onChange={event=>setStart(event.target.value)}/></label><label>结束<input type="date" value={end} onChange={event=>setEnd(event.target.value)}/></label><label className="full">目标<textarea required value={goal} onChange={event=>setGoal(event.target.value)}/></label><label>首个里程碑<input value={milestone} onChange={event=>setMilestone(event.target.value)}/></label><label>关联类型<select value={linkKind} onChange={event=>setLinkKind(event.target.value)}><option value="">暂不关联</option><option value="trip">旅行</option><option value="health_plan">健康计划</option><option value="recurring_plan">周期事项</option><option value="owned_item">物品</option><option value="library_item">资料</option><option value="money_entry">账目</option><option value="meal">餐次</option><option value="recipe">食谱</option></select></label>{linkKind&&<><label>对象 ID<input required value={linkId} onChange={event=>setLinkId(event.target.value)}/></label><label>对象修订<input required inputMode="numeric" value={linkRevision} onChange={event=>setLinkRevision(event.target.value)}/></label></>}<button disabled={pending}>{pending?"保存中…":"保存项目"}</button></form>}{projects.length?<ul className="project-list">{projects.map(project=><li key={project.id}><b>{project.title}</b><p>{project.goal}</p><small>{project.starts_on??"未设开始"} 至 {project.ends_on??"未设结束"} · {project.milestones.length} 个里程碑 · {project.links.length} 个当前可见引用 · {project.actions.length} 个行动</small></li>)}</ul>:<p>还没有生活项目。</p>}{capabilities.has("life.save_action_item")&&projects.length>0&&<form className="review-range" onSubmit={addAction}><label>项目<select value={actionProject} onChange={event=>setActionProject(event.target.value)}>{projects.map(project=><option value={project.id} key={project.id}>{project.title}</option>)}</select></label><label>下一步<input required value={actionTitle} onChange={event=>setActionTitle(event.target.value)}/></label><label>到期日<input type="date" value={actionDue} onChange={event=>setActionDue(event.target.value)}/></label><button disabled={pending}>添加行动</button></form>}</section>;}
