import { useEffect, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import { ObjectPicker, type ObjectKind } from "./ObjectPicker.js";

type Milestone={id?:string;title:string;due_on?:string|null;state:"planned"|"completed"|"cancelled"};
type ProjectLink={ref_kind:string;ref_id:string;ref_revision:number;role:string};
type Action={id:string;title:string;due_on:string|null;state:"open"|"completed"|"cancelled";revision:number;recurring_occurrence_id?:string|null;health_habit_id?:string|null};
type Project={id:string;title:string;goal:string;starts_on:string|null;ends_on:string|null;state:"active"|"completed"|"paused"|"cancelled";revision:number;milestones:Milestone[];links:ProjectLink[];actions:Action[]};

export function LifeProjectPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}) {
  const [projects,setProjects]=useState<Project[]>([]),[editing,setEditing]=useState<Project>(),[title,setTitle]=useState(""),[goal,setGoal]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[milestone,setMilestone]=useState(""),[linkKind,setLinkKind]=useState<ObjectKind|"">(""),[linkId,setLinkId]=useState(""),[linkRevision,setLinkRevision]=useState(1),[actionProject,setActionProject]=useState(""),[actionTitle,setActionTitle]=useState(""),[actionDue,setActionDue]=useState(""),[error,setError]=useState<string>(),[pending,setPending]=useState(false);
  const canRewriteProject=["travel.workspace","health.records","money.planning","money.records","life.owned_items","library.records","life.list_meals","life.food_catalog"].every(capability=>capabilities.has(capability));
  async function load(){const response=await fetch("/api/life/projects?limit=20",{headers});if(!response.ok)throw new Error(`读取生活项目失败（HTTP ${response.status}）`);const items=((await response.json()) as {items:Project[]}).items;setProjects(items);setActionProject(current=>current||items[0]?.id||"");}
  useEffect(()=>{void load().catch(caught=>setError(caught instanceof Error?caught.message:"读取项目失败"));},[]);
  function reset(){setEditing(undefined);setTitle("");setGoal("");setStart("");setEnd("");setMilestone("");setLinkKind("");setLinkId("");setLinkRevision(1);}
  function edit(project:Project){setEditing(project);setTitle(project.title);setGoal(project.goal);setStart(project.starts_on??"");setEnd(project.ends_on??"");setMilestone("");setLinkKind("");setLinkId("");}
  async function save(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{const milestones=editing?editing.milestones:milestone.trim()?[{title:milestone.trim(),...(end?{due_on:end}:{}),state:"planned" as const}]:[],links=editing?editing.links.map(item=>({kind:item.ref_kind as ObjectKind,id:item.ref_id,revision:item.ref_revision,role:item.role})):linkKind&&linkId?[{kind:linkKind,id:linkId,revision:linkRevision,role:"supporting"}]:[];await execute("life.save_project",{...(editing?{project_id:editing.id,expected_revision:editing.revision,reason:"在计划工作台更新项目"}:{}),title:title.trim(),goal:goal.trim(),starts_on:start||null,ends_on:end||null,state:editing?.state??"active",milestones,links},`project:save:${editing?.id??"new"}`);reset();await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存项目失败");}finally{setPending(false);}}
  async function addAction(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{await execute("life.save_action_item",{project_id:actionProject,title:actionTitle.trim(),due_on:actionDue||null,state:"open"},`project:action:${actionProject}`);setActionTitle("");setActionDue("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存行动失败");}finally{setPending(false);}}
  async function updateAction(project:Project,action:Action,state:"open"|"completed"){setPending(true);setError(undefined);try{await execute("life.save_action_item",{action_item_id:action.id,expected_revision:action.revision,project_id:project.id,title:action.title,due_on:action.due_on,state,...(action.recurring_occurrence_id?{recurring_occurrence_id:action.recurring_occurrence_id}:{}),...(action.health_habit_id?{health_habit_id:action.health_habit_id}:{})},`project:action-state:${action.id}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"更新行动失败");}finally{setPending(false);}}
  async function updateProject(project:Project,state:Project["state"]){setPending(true);setError(undefined);try{await execute("life.save_project",{project_id:project.id,expected_revision:project.revision,reason:"在计划工作台更新项目状态",title:project.title,goal:project.goal,starts_on:project.starts_on,ends_on:project.ends_on,state,milestones:project.milestones,links:project.links.map(item=>({kind:item.ref_kind as ObjectKind,id:item.ref_id,revision:item.ref_revision,role:item.role}))},`project:state:${project.id}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"更新项目失败");}finally{setPending(false);}}
  if(!capabilities.has("life.projects"))return null;
  return <section className="wide life-projects"><div className="panel-heading"><div><span className="eyebrow">LIFE PROJECT</span><h2>生活项目</h2></div>{capabilities.has("life.save_project")&&<button type="button" className="secondary" onClick={reset}>新建项目</button>}</div><p>项目负责组织目标、里程碑与行动；健康、账目、旅行和资料仍保留各自唯一事实。</p>{error&&<p className="inline-error">{error}</p>}
    {capabilities.has("life.save_project")&&<form className="compact-form" onSubmit={save}><h3>{editing?`编辑 ${editing.title}`:"把目标变成项目"}</h3><label>名称<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>开始<input type="date" value={start} onChange={event=>setStart(event.target.value)}/></label><label>结束<input type="date" value={end} onChange={event=>setEnd(event.target.value)}/></label><label className="full">想达成什么<textarea required value={goal} onChange={event=>setGoal(event.target.value)}/></label>{!editing&&<><label>首个里程碑<input value={milestone} onChange={event=>setMilestone(event.target.value)}/></label><label>关联类型<select value={linkKind} onChange={event=>{setLinkKind(event.target.value as ObjectKind|"");setLinkId("");}}><option value="">暂不关联</option><option value="trip">旅行</option><option value="health_plan">健康计划</option><option value="recurring_plan">周期事项</option><option value="owned_item">物品</option><option value="library_item">资料</option><option value="money_entry">账目</option><option value="meal">餐次</option><option value="recipe">食谱</option></select></label>{linkKind&&<div className="full"><ObjectPicker kind={linkKind} headers={headers} value={linkId} optional={false} onChange={option=>{setLinkId(option?.id??"");setLinkRevision(option?.revision??1);}}/></div>}</>}<div className="actions"><button disabled={pending||Boolean(linkKind&&!linkId)}>{pending?"保存中…":"保存项目"}</button>{editing&&<button type="button" className="secondary" onClick={reset}>取消</button>}</div></form>}
    {projects.length?<ul className="project-list">{projects.map(project=><li key={project.id}><div className="project-title"><div><b>{project.title}</b><p>{project.goal}</p></div><span className={`status ${project.state}`}>{projectState(project.state)}</span></div><small>{project.starts_on??"未设开始"} 至 {project.ends_on??"未设结束"} · {project.milestones.length} 个里程碑 · {project.links.length} 个可见关联 · {project.actions.filter(action=>action.state==="open").length} 个待办</small>{project.actions.length>0&&<ul className="action-list">{project.actions.slice(0,6).map(action=><li key={action.id}><button type="button" className={`action-toggle ${action.state}`} disabled={pending} aria-label={action.state==="open"?"标记完成":"恢复待办"} onClick={()=>void updateAction(project,action,action.state==="open"?"completed":"open")}>{action.state==="open"?"○":"✓"}</button><b>{action.title}</b>{action.due_on&&<small>{action.due_on}</small>}</li>)}</ul>}{canRewriteProject?<div className="actions"><button type="button" className="secondary" onClick={()=>edit(project)}>编辑</button>{project.state==="active"?<><button type="button" className="secondary" onClick={()=>void updateProject(project,"paused")}>暂停</button><button type="button" onClick={()=>void updateProject(project,"completed")}>完成项目</button></>:<button type="button" className="secondary" onClick={()=>void updateProject(project,"active")}>恢复进行</button>}</div>:<small>当前权限只能查看部分关联，因此已禁用整项目覆盖式修改；行动项仍可独立更新。</small>}</li>)}</ul>:<p>还没有生活项目。</p>}
    {capabilities.has("life.save_action_item")&&projects.length>0&&<form className="review-range" onSubmit={addAction}><label>项目<select value={actionProject} onChange={event=>setActionProject(event.target.value)}>{projects.map(project=><option value={project.id} key={project.id}>{project.title}</option>)}</select></label><label>下一步<input required value={actionTitle} onChange={event=>setActionTitle(event.target.value)}/></label><label>到期日<input type="date" value={actionDue} onChange={event=>setActionDue(event.target.value)}/></label><button disabled={pending}>添加行动</button></form>}
  </section>;
}
function projectState(value:Project["state"]){return({active:"进行中",completed:"已完成",paused:"已暂停",cancelled:"已取消"})[value];}
