import { useEffect, useState } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
type Review={id:string;from_on:string;to_on:string;time_zone:string;domains:string[];algorithm_version:string;metrics:Record<string,unknown>;coverage:Record<string,unknown>;evidence:unknown[];revision:number;generated_at:string};
const iso=(date:Date)=>new Intl.DateTimeFormat("en-CA").format(date);
export function LifeReviewPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){const end=new Date(),start=new Date(end);start.setDate(start.getDate()-6);const [from,setFrom]=useState(()=>iso(start)),[to,setTo]=useState(()=>iso(end)),[reviews,setReviews]=useState<Review[]>([]),[error,setError]=useState<string>(),[pending,setPending]=useState(false);const domainCapabilities={money:"money.records",meals:"life.list_meals",health:"health.records",items:"life.owned_items",library:"library.records"} as const,domains=Object.entries(domainCapabilities).filter(([,capability])=>capabilities.has(capability)).map(([domain])=>domain);
  async function load(){const response=await fetch("/api/life/reviews?limit=20",{headers});if(!response.ok)throw new Error(`读取复盘失败（HTTP ${response.status}）`);setReviews(((await response.json()) as {items:Review[]}).items);}
  useEffect(()=>{void load().catch(caught=>setError(caught instanceof Error?caught.message:"读取复盘失败"));},[]);
  async function generate(review?:Review){setPending(true);setError(undefined);try{await execute("life.generate_review",{...(review?{review_id:review.id,expected_revision:review.revision,from_on:review.from_on,to_on:review.to_on,time_zone:review.time_zone,domains:review.domains}:{from_on:from,to_on:to,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone,domains})},`cmd_web_review_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"生成复盘失败");}finally{setPending(false);}}
  if(!capabilities.has("life.reviews"))return null;return <section className="wide life-reviews"><div className="panel-heading"><div><span className="eyebrow">REVIEW</span><h2>可重算复盘</h2></div></div><p>总额由程序按原币种计算；Agent 只能解释这些指标，不能补造记录、生活总分或健康因果。</p>{error&&<p className="inline-error">{error}</p>}{capabilities.has("life.generate_review")&&<form className="review-range" onSubmit={event=>{event.preventDefault();void generate();}}><label>开始<input type="date" required value={from} onChange={event=>setFrom(event.target.value)}/></label><label>结束<input type="date" required value={to} onChange={event=>setTo(event.target.value)}/></label><button disabled={pending||!domains.length}>{pending?"计算中…":"生成复盘"}</button></form>}{reviews.length?<ol className="review-list">{reviews.map(review=><li key={review.id}><div><b>{review.from_on} 至 {review.to_on}</b><small>{review.algorithm_version} · 修订 {review.revision} · {review.evidence.length} 条证据</small></div><pre>{JSON.stringify(review.metrics,null,2)}</pre><details><summary>覆盖率与限制</summary><pre>{JSON.stringify(review.coverage,null,2)}</pre></details>{capabilities.has("life.generate_review")&&<button type="button" className="secondary" disabled={pending} onClick={()=>void generate(review)}>按当前事实重算</button>}</li>)}</ol>:<p>还没有复盘快照。</p>}</section>;}
