import { StrictMode, useEffect, useRef, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
import "./styles.css";
import { applyAssistantEvent, createAssistantView, readAssistantSse, renderAssistantView, type AssistantRunState } from "./assistant-stream.js";
import { loadDashboard, loadHealthTrend, type DashboardDomain, type HealthTrend, type HealthWorkspace, type TimelineItem, type TodayOverview } from "./dashboard.js";
import { buildFormCommand, healthMetricUnits, initialRecordFields, type HealthMetric, type MealType, type PlanKind, type RecordFormFields, type RecordKind } from "./record-form.js";
import { MoneyImportPanel } from "./MoneyImportPanel.js";
import { RecordBrowser } from "./RecordBrowser.js";
import { selectionFromLocation, selectionHref } from "./record-detail.js";
import { WorkoutPanel } from "./WorkoutPanel.js";
import { FoodCatalogPanel } from "./FoodCatalogPanel.js";
import { TravelPanel } from "./TravelPanel.js";
type Tab="today"|"record"|"plan"|"library"|"assistant";
const healthMetricLabels:Record<HealthMetric,string>={weight:"体重",body_fat:"体脂率",heart_rate:"心率",blood_pressure_systolic:"收缩压",blood_pressure_diastolic:"舒张压",temperature:"体温",sleep_duration:"睡眠时长",steps:"步数",custom:"其他"};
const auth=import.meta.env.DEV?{authorization:"Bearer dev:subject_example"}:{}; const headers={"content-type":"application/json",...auth};let epochHeader="";const writeHeaders=()=>({...headers,...(epochHeader?{"x-shadow-write-epochs":epochHeader}:{})});
const today=()=>new Intl.DateTimeFormat("en-CA").format(new Date()); const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
async function command(capability:WriteCapabilityName,input:unknown,commandId:string):Promise<ExecutionResult>{const response=await fetch(`/api/commands/${capability}`,{method:"POST",headers:writeHeaders(),body:JSON.stringify({protocol:"shadow.command",capability,command_id:commandId,input})});const value=await response.json() as ExecutionResult&{message?:string};if(!response.ok)throw new Error(value.message??`HTTP ${response.status}`);return value;}
function App(){
  const initialTab=new URLSearchParams(window.location.search).get("tab");
  const [tab,setTab]=useState<Tab>(initialTab==="record"||initialTab==="plan"||initialTab==="library"||initialTab==="assistant"?initialTab:"today");
  const [data,setData]=useState<Partial<Record<DashboardDomain,unknown[]>>>({});
  const [todayData,setTodayData]=useState<TodayOverview>();
  const [timeline,setTimeline]=useState<TimelineItem[]>([]);
  const [timelineCursor,setTimelineCursor]=useState<string|null>(null);
  const [healthWorkspace,setHealthWorkspace]=useState<HealthWorkspace>();
  const [capabilities,setCapabilities]=useState<string[]>([]);
  const [healthMetric,setHealthMetric]=useState<HealthMetric>("weight");
  const [result,setResult]=useState<ExecutionResult>();
  const [error,setError]=useState<string>();
  const [readError,setReadError]=useState<string>();
  const [pending,setPending]=useState(false);
  const [stableCommand,setStableCommand]=useState(()=>`cmd_web_${crypto.randomUUID()}`);
  const [fields,setFields]=useState<RecordFormFields>(()=>initialRecordFields(today(),zone()));
  async function load(){try{const loaded=await loadDashboard(fetch,auth,{date:today(),timeZone:zone()});epochHeader=loaded.epochHeader;setData(loaded.data);setTodayData(loaded.today);setTimeline(loaded.timeline?.items??[]);setTimelineCursor(loaded.timeline?.next_cursor??null);setHealthWorkspace(loaded.health);setCapabilities(loaded.capabilities);setFields(current=>!loaded.capabilities.includes("money.set_budget")&&loaded.capabilities.includes("health.set_plan")&&current.planKind==="budget"?{...current,planKind:"goal"}:current);const labels:Record<DashboardDomain|"today"|"timeline",string>={meals:"饮食",money:"账目",health:"健康",travel:"旅行",library:"资料",today:"今日摘要",timeline:"时间线"},messages=(Object.entries(loaded.errors) as [DashboardDomain|"today"|"timeline",string][]).map(([domain,message])=>`${labels[domain]}：${message}`);setReadError(messages.length?messages.join("；"):undefined);}catch(caught){setReadError(caught instanceof Error?caught.message:"读取失败");}}
  useEffect(()=>{void load()},[]);
  async function save(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{if(tab==="today"||tab==="assistant")return;const built=buildFormCommand(tab,fields);setResult(await command(built.capability,built.input,stableCommand));setStableCommand(`cmd_web_${crypto.randomUUID()}`);setFields(initialRecordFields(today(),zone()));await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存失败");}finally{setPending(false);}}
  async function selectHealthMetric(metric:HealthMetric){setHealthMetric(metric);try{const trend=await loadHealthTrend(fetch,auth,metric);setHealthWorkspace(current=>{const errors={...(current?.errors??{})};delete errors.trend;return{...current,trend,errors};});}catch(caught){setHealthWorkspace(current=>({...current,errors:{...(current?.errors??{}),trend:caught instanceof Error?caught.message:"读取失败"}}));}}
  const visible=new Set(capabilities),hasHealthWorkspace=visible.has("health.daily")||visible.has("health.trend")||visible.has("health.sources"),selection=selectionFromLocation(window.location.search);
  return <main>
    <header><span className="eyebrow">SHADOW LIFE</span><h1>生活事实，一处记录</h1><p>普通记录直接保存；金额、日期、时区和来源以实际输入为准。</p>{readError?.includes("登录")&&<a href="/auth/login">重新登录</a>}</header>
    <nav>{(["today","record","plan","library","assistant"] as Tab[]).map(value=><button type="button" className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{({today:"今天",record:"记录",plan:"计划",library:"资料库",assistant:"助手"})[value]}</button>)}</nav>
    {readError&&<aside className="error">{readError}</aside>}
    {tab==="today"?<section className="grid"><Card title="今日饮食" value={metric(todayData,"meals","count")}/><Card title="今日账目" value={metric(todayData,"money","entries")}/><Card title="今日健康事实" value={metric(todayData,"health","facts")}/><Card title="今日到访" value={metric(todayData,"travel","visits")}/><Card title="今日新增资料" value={metric(todayData,"library","captured")}/><TodayAttention data={todayData}/><div className="wide"><h2>统一时间线</h2><FactList data={data} timeline={timeline}/></div></section>:tab==="assistant"?<Assistant/>:<section className="workspace"><EntryForm tab={tab} fields={fields} setFields={setFields} pending={pending} save={save} canBudget={visible.has("money.set_budget")} canHealthPlan={visible.has("health.set_plan")}/>{tab==="record"&&<RecordBrowser timeline={timeline} nextCursor={timelineCursor} selection={selection} capabilities={visible} headers={auth} execute={command} onChanged={load}/>} {tab==="record"&&visible.has("life.food_catalog")&&<FoodCatalogPanel headers={auth} date={today()} timeZone={zone()} canSaveFood={visible.has("life.save_food")} canSaveRecipe={visible.has("life.save_recipe")} canRecordRecipe={visible.has("life.record_meal_from_recipe")} execute={command} onChanged={load}/>} {tab==="record"&&hasHealthWorkspace&&<HealthPanel workspace={healthWorkspace} metric={healthMetric} onMetric={selectHealthMetric}/>} {tab==="record"&&visible.has("health.record_workout")&&<WorkoutPanel records={data.health??[]} date={today()} timeZone={zone()} execute={command} onChanged={load}/>} {tab==="plan"&&<MoneyImportPanel enabled={visible.has("money.stage_import")&&visible.has("money.import_review")} headers={auth} execute={command} timeZone={zone()}/>} {tab==="plan"&&visible.has("travel.workspace")&&<TravelPanel headers={auth} capabilities={visible} execute={command}/>}</section>}
    {error&&<aside className="error">{error}</aside>}{result&&<section className="receipt"><b>已保存</b><p>{result.capability} · {result.execution_id}</p></section>}
  </main>;
}
function EntryForm({tab,fields,setFields,pending,save,canBudget,canHealthPlan}:{tab:"record"|"plan"|"library";fields:RecordFormFields;setFields:(fields:RecordFormFields)=>void;pending:boolean;save:(event:FormEvent)=>Promise<void>;canBudget:boolean;canHealthPlan:boolean}){
  const isMeal=tab==="record"&&fields.kind==="meal",isHealth=tab==="record"&&fields.kind==="health",isMoney=tab==="record"&&(fields.kind==="expense"||fields.kind==="income");
  if(tab==="plan"){
    if(!canBudget&&!canHealthPlan)return <section className="empty-state"><h2>计划</h2><p>当前账号没有可写的预算或健康计划权限。</p></section>;
    const isBudget=fields.planKind==="budget",isGoal=fields.planKind==="goal";
    return <form onSubmit={save}>
      <label>计划类型<select value={fields.planKind} onChange={event=>setFields({...fields,planKind:event.target.value as PlanKind})}>{canBudget&&<option value="budget">月度预算</option>}{canHealthPlan&&<><option value="goal">健康目标</option><option value="habit">生活习惯</option><option value="workout">训练计划</option></>}</select></label>
      {isBudget?<><label>预算月份<input type="month" required value={fields.occurredOn.slice(0,7)} onChange={event=>setFields({...fields,occurredOn:`${event.target.value}-01`})}/></label><label>分类<input required value={fields.category} onChange={event=>setFields({...fields,category:event.target.value})}/></label><label>金额<input inputMode="decimal" required value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})} placeholder="2000.00"/></label></>:<><label>计划名称<input required value={fields.title} onChange={event=>setFields({...fields,title:event.target.value})}/></label>{isGoal?<><HealthMetricSelect fields={fields} setFields={setFields}/><label>目标值<input inputMode="decimal" required value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})}/></label><label>单位<input required value={fields.unit} onChange={event=>setFields({...fields,unit:event.target.value})}/></label><label>目标日期（可选）<input type="date" value={fields.occurredOn} onChange={event=>setFields({...fields,occurredOn:event.target.value})}/></label></>:<><label>每周执行日<input required value={fields.scheduleDays} onChange={event=>setFields({...fields,scheduleDays:event.target.value})} placeholder="1,3,5"/><small>1 表示周一，7 表示周日；可用逗号或空格分隔。</small></label>{fields.planKind==="workout"&&<label>训练说明（可选）<textarea value={fields.note} onChange={event=>setFields({...fields,note:event.target.value})}/></label>}</>}</>}
      <button disabled={pending}>{pending?"保存中…":"直接保存"}</button>
    </form>;
  }
  return <form onSubmit={save}>{tab==="record"&&<label>记录类型<select value={fields.kind} onChange={event=>setFields({...fields,kind:event.target.value as RecordKind})}><option value="expense">支出</option><option value="income">收入</option><option value="meal">饮食</option><option value="health">健康测量</option></select></label>}{tab==="record"&&<><label>实际发生日<input type="date" required value={fields.occurredOn} onChange={event=>setFields({...fields,occurredOn:event.target.value})}/></label><label>事实时区<input required value={fields.timeZone} onChange={event=>setFields({...fields,timeZone:event.target.value})}/></label></>}{isMeal&&<label>餐次<select value={fields.mealType} onChange={event=>setFields({...fields,mealType:event.target.value as MealType})}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label>}{isHealth&&<HealthMetricSelect fields={fields} setFields={setFields}/>}<label>{tab==="library"?"标题":isMeal?"吃了什么":isHealth?"测量标签（可选）":"商家或对象（可选）"}<input required={tab==="library"||isMeal} value={fields.title} onChange={event=>setFields({...fields,title:event.target.value})}/></label>{tab!=="library"&&<label>{isMeal?"付款金额（可选）":isHealth?"测量值":"金额"}<input inputMode="decimal" required={!isMeal} value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})} placeholder="35.00"/></label>}{isMeal&&fields.amount.trim()&&<label>支付日<input type="date" required value={fields.paymentOn} onChange={event=>setFields({...fields,paymentOn:event.target.value})}/></label>}{isHealth?<label>单位<input required value={fields.unit} onChange={event=>setFields({...fields,unit:event.target.value})}/></label>:!isMeal&&<label>{tab==="library"?"标签":"分类"}<input value={fields.category} onChange={event=>setFields({...fields,category:event.target.value})}/></label>}{(isMoney||(isMeal&&Boolean(fields.amount.trim())))&&<label>支付方式<select value={fields.paymentMethod} onChange={event=>setFields({...fields,paymentMethod:event.target.value})}><option value="">未说明</option><option value="alipay">支付宝</option><option value="wechat">微信</option><option value="cash">现金</option><option value="bank_card">银行卡</option><option value="other">其他</option></select></label>}<label>说明<textarea required={tab==="library"} value={fields.note} onChange={event=>setFields({...fields,note:event.target.value})}/></label><button disabled={pending}>{pending?"保存中…":"直接保存"}</button></form>;
}
function HealthMetricSelect({fields,setFields}:{fields:RecordFormFields;setFields:(fields:RecordFormFields)=>void}){return <label>健康指标<select value={fields.healthMetric} onChange={event=>{const healthMetric=event.target.value as HealthMetric;setFields({...fields,healthMetric,unit:healthMetricUnits[healthMetric]});}}>{Object.entries(healthMetricLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
function HealthPanel({workspace,metric,onMetric}:{workspace:HealthWorkspace|undefined;metric:HealthMetric;onMetric:(metric:HealthMetric)=>Promise<void>}){
  const daily=asObject(workspace?.daily),summary=asObject(daily.result),activity=asObject(summary.activity),facts=asArray(summary.facts),workouts=asArray(summary.workouts),habits=asArray(summary.habits),trend=workspace?.trend;
  return <section className="health-panel">
    <div className="panel-heading"><div><span className="eyebrow">HEALTH</span><h2>健康概览</h2></div><label>趋势指标<select value={metric} onChange={event=>void onMetric(event.target.value as HealthMetric)}>{Object.entries(healthMetricLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
    <div className="health-grid">
      <section className="health-card"><h3>今日汇总</h3>{workspace?.errors.daily?<p className="inline-error">{workspace.errors.daily}</p>:Object.keys(daily).length===0?<p>今天还没有生成健康汇总。</p>:<><dl><MetricTerm label="事实" value={facts.length}/><MetricTerm label="步数" value={scalar(activity.steps)}/><MetricTerm label="活动分钟" value={scalar(activity.active_minutes)}/><MetricTerm label="训练" value={workouts.length}/><MetricTerm label="习惯" value={habits.length}/></dl><small>算法 {scalar(daily.algorithm_version)} · 修订 {scalar(daily.revision)}</small></>}</section>
      <section className="health-card trend-card"><h3>{healthMetricLabels[metric]}趋势</h3>{workspace?.errors.trend?<p className="inline-error">{workspace.errors.trend}</p>:<TrendTable trend={trend}/>}</section>
      <section className="health-card sources-card"><h3>数据来源</h3>{workspace?.errors.sources?<p className="inline-error">{workspace.errors.sources}</p>:!workspace?.sources?.length?<p>还没有已连接的数据来源。</p>:<ul className="source-list">{workspace.sources.map(source=><li key={`${source.source_type}:${source.instance_key}`}><div><b>{sourceLabel(source.source_type)}</b><span className={`status ${source.permission_state}`}>{permissionLabel(source.permission_state)}</span></div><small>{source.instance_key} · 同步代次 {source.sync_epoch}</small>{source.cursors.length?<ul>{source.cursors.map(cursor=><li key={`${cursor.device_id}:${cursor.record_type}`}>{cursor.record_type} · {cursor.state} · {formatDateTime(cursor.updated_at)}</li>)}</ul>:<small>暂无同步进度</small>}</li>)}</ul>}</section>
    </div>
  </section>;
}
function TrendTable({trend}:{trend:HealthTrend|undefined}){if(!trend)return <p>暂无趋势数据。</p>;if(!trend.points.length)return <p>这个指标还没有有效测量。</p>;return <><div className="trend-summary"><b>{trend.coverage.points} 个点</b><span>{trend.coverage.from} 至 {trend.coverage.to}{trend.coverage.truncated?" · 仅显示前 90 个":""}</span></div><ol className="trend-list">{[...trend.points].reverse().slice(0,12).map(point=><li key={point.id}><time>{point.occurred_on}</time><strong>{point.value} {point.unit}</strong><small>{sourceLabel(point.source_kind)}</small></li>)}</ol></>}
function MetricTerm({label,value}:{label:string;value:string|number}){return <><dt>{label}</dt><dd>{value}</dd></>}
function asObject(value:unknown):Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function asArray(value:unknown):unknown[]{return Array.isArray(value)?value:[];}
function scalar(value:unknown):string|number{return typeof value==="string"||typeof value==="number"?value:"—";}
function sourceLabel(value:string):string{return({manual:"手动记录",health_connect:"Health Connect",samsung:"Samsung Health",scale:"体脂秤",normalized:"已归一化",file_import:"文件导入",legacy_health:"旧健康数据"} as Record<string,string>)[value]??value;}
function permissionLabel(value:string):string{return({granted:"已授权",revoked:"已撤销",expired:"已过期",rescan_required:"需要重扫"} as Record<string,string>)[value]??value;}
function formatDateTime(value:string):string{const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat("zh-CN",{dateStyle:"short",timeStyle:"short"}).format(date);}
function TodayAttention({data}:{data:TodayOverview|undefined}){const money=data?.domains.money,health=data?.domains.health,travel=data?.domains.travel,due=money?.due_items??[],issues=health?.sync_issues??[],trips=travel?.current_trips??[];if(money===undefined&&health===undefined&&travel===undefined)return null;return <section className="wide attention"><h2>现在需要留意</h2>{!due.length&&!issues.length&&!trips.length?<p>没有到期事项、同步异常或进行中的旅程。</p>:<div className="attention-grid">{due.length>0&&<section><h3>待处理</h3><ul>{due.map(item=><li key={item.id}><b>{item.title}</b><span>{item.due_on}{item.amount?` · ${item.amount} ${item.currency??""}`:""}</span></li>)}</ul></section>}{issues.length>0&&<section><h3>同步异常</h3><ul>{issues.map(item=><li key={item.id}><b>{sourceLabel(item.source_type)} · {permissionLabel(item.permission_state)}</b><span>{item.instance_key} · 代次 {item.sync_epoch}{item.last_sync_at?` · ${formatDateTime(item.last_sync_at)}`:""}</span></li>)}</ul></section>}{trips.length>0&&<section><h3>进行中的旅程</h3><ul>{trips.map(item=><li key={item.id}><b>{item.title}</b><span>{item.starts_on} 至 {item.ends_on}</span></li>)}</ul></section>}</div>}</section>}
function FactList({data,timeline}:{data:Partial<Record<DashboardDomain,unknown[]>>;timeline:TimelineItem[]}){const labels:Record<DashboardDomain,string>={meals:"饮食",money:"账目",health:"健康",travel:"旅程",library:"资料"};if(timeline.length)return <ul>{timeline.map(item=><li key={`${item.domain}:${item.kind}:${item.id}`}><a href={selectionHref(item)}><b>{labels[item.domain]}</b> · {item.title}{item.amount?` · ${item.amount} ${item.currency??""}`:""} · {item.happened_at.slice(0,10)}</a></li>)}</ul>;const rows=(Object.entries(data) as [DashboardDomain,unknown[]][]).flatMap(([domain,items])=>items.map((item,index)=>normalizeFact(domain,item,index))).sort((left,right)=>right.occurred.localeCompare(left.occurred)).slice(0,12);if(!rows.length)return <p>还没有可见记录。</p>;return <ul>{rows.map(row=><li key={`${row.domain}:${row.id}`}><b>{labels[row.domain]}</b> · {row.title}{row.amount?` · ${row.amount} ${row.currency??""}`:""}{row.occurred?` · ${row.occurred.slice(0,10)}`:""}</li>)}</ul>}
function normalizeFact(domain:DashboardDomain,item:unknown,index:number){const value=item!==null&&typeof item==="object"?item as Record<string,unknown>:{};return{domain,id:String(value.id??index),title:String(value.title??value.name??value.counterparty??value.metric??value.metric_key??value.entryType??value.entry_type??value.kind??"记录"),amount:typeof value.amount==="string"||typeof value.amount==="number"?String(value.amount):undefined,currency:typeof value.currency==="string"?value.currency:undefined,occurred:String(value.occurred_on??value.occurredOn??value.created_at??value.createdAt??"")};}
function Card({title,value}:{title:string;value:number|string}){return <article><span>{title}</span><strong>{value}</strong></article>}
function metric(data:TodayOverview|undefined,domain:DashboardDomain,key:"count"|"entries"|"facts"|"visits"|"captured"):number|string{const value=data?.domains[domain]?.[key];return typeof value==="number"?value:"—";}
function Assistant(){
  const[text,setText]=useState(""),[threadId,setThreadId]=useState<string|undefined>(()=>localStorage.getItem("shadow.thread")??undefined),[turns,setTurns]=useState<{role:"user"|"assistant";text:string}[]>([]),[pendingRun,setPendingRun]=useState(false),[runState,setRunState]=useState<AssistantRunState>(),[activeRunId,setActiveRunId]=useState<string>();
  const active=useRef<{runId?:string}|undefined>(undefined);
  useEffect(()=>{if(!threadId)return;void fetch(`/api/threads/${threadId}/messages`,{headers:auth}).then(async response=>{if(!response.ok)throw new Error();const body=await response.json() as {items:{role:"user"|"assistant";content:string}[]};setTurns(body.items.map(item=>({role:item.role,text:item.content})));}).catch(()=>{localStorage.removeItem("shadow.thread");setThreadId(undefined);});},[threadId]);
  async function run(e:FormEvent){
    e.preventDefault();const prompt=text.trim();if(!prompt||pendingRun)return;
    setPendingRun(true);setRunState("started");setActiveRunId(undefined);setText("");setTurns(current=>[...current,{role:"user",text:prompt}]);
    const view=createAssistantView();active.current={};
    try{
      let id=threadId;
      if(!id){const thread=await fetch("/api/threads",{method:"POST",headers:writeHeaders(),body:JSON.stringify({title:prompt.slice(0,40)})});if(!thread.ok)throw new Error(thread.status===401?"登录已失效，请重新登录。":"助手运行时暂不可用");id=((await thread.json()) as {id:string}).id;localStorage.setItem("shadow.thread",id);setThreadId(id);}
      const response=await fetch(`/api/threads/${id}/runs`,{method:"POST",headers:writeHeaders(),body:JSON.stringify({text:prompt})});
      if(!response.ok||!response.body)throw new Error(`助手请求失败（HTTP ${response.status}）`);
      await readAssistantSse(response.body,(event,sequence)=>{applyAssistantEvent(view,event,sequence);if(view.runId){active.current={runId:view.runId};setActiveRunId(view.runId);}if(view.state)setRunState(view.state);});
      if(view.runId&&view.state!=="completed"&&view.state!=="interrupted"&&view.state!=="awaiting_input"){
        const recovery=await fetch(`/api/runs/${view.runId}?after=${view.lastSequence}`,{headers:auth});
        if(recovery.ok){const body=await recovery.json() as {run:{status:string;error?:string|null};events:{sequence:number;payload:unknown}[]};for(const event of body.events)applyAssistantEvent(view,event.payload,event.sequence);if(!view.state||view.state==="started"||view.state==="streaming"||view.state==="committed_partial"){if(body.run.status==="completed")view.state="completed";else if(body.run.status==="awaiting_input")view.state="awaiting_input";else if(body.run.status==="interrupted"||body.run.status==="failed"){view.state="interrupted";view.reason=body.run.error??"运行已中断";}}}
      }
      setRunState(view.state);setTurns(current=>[...current,{role:"assistant",text:renderAssistantView(view)}]);
    }catch(error){setTurns(current=>[...current,{role:"assistant",text:error instanceof Error?error.message:"助手请求失败"}]);}
    finally{active.current=undefined;setActiveRunId(undefined);setPendingRun(false);}
  }
  async function stop(){const runId=active.current?.runId;if(!runId)return;setRunState("interrupted");await fetch(`/api/runs/${runId}/stop`,{method:"POST",headers:writeHeaders()});}
  return <section><div>{turns.map((turn,index)=><p key={index}><b>{turn.role==="user"?"你":"Shadow"}：</b>{turn.text}</p>)}</div>{pendingRun&&<p className="run-state">状态：{runStateLabel(runState)}{activeRunId?` · ${activeRunId}`:""}</p>}<form onSubmit={run}><label>告诉 Shadow 要记录、补充或查找什么<textarea required value={text} onChange={e=>setText(e.target.value)}/></label><div className="actions"><button disabled={pendingRun}>{pendingRun?"处理中…":"发送"}</button>{pendingRun&&<button className="secondary" type="button" disabled={!activeRunId} onClick={()=>void stop()}>停止</button>}</div></form></section>;
}
function runStateLabel(state:AssistantRunState|undefined):string{return({started:"正在启动",streaming:"正在回复",awaiting_input:"等待补充",committed_partial:"部分操作已保存",completed:"已完成",interrupted:"正在停止"} as const)[state??"started"];}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
