import { StrictMode, useEffect, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
import "./styles.css";
type Tab="today"|"record"|"plan"|"library"|"assistant";
const auth=import.meta.env.DEV?{authorization:"Bearer dev:subject_example"}:{}; const headers={"content-type":"application/json",...auth};let epochHeader="";const writeHeaders=()=>({...headers,...(epochHeader?{"x-shadow-write-epochs":epochHeader}:{})});
const today=()=>new Intl.DateTimeFormat("en-CA").format(new Date()); const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
async function command(capability:WriteCapabilityName,input:unknown,commandId:string):Promise<ExecutionResult>{const response=await fetch(`/api/commands/${capability}`,{method:"POST",headers:writeHeaders(),body:JSON.stringify({protocol:"shadow.command",capability,command_id:commandId,input})});const value=await response.json() as ExecutionResult&{message?:string};if(!response.ok)throw new Error(value.message??`HTTP ${response.status}`);return value;}
function App(){const[tab,setTab]=useState<Tab>("today"),[data,setData]=useState<Record<string,unknown[]>>({}),[result,setResult]=useState<ExecutionResult>(),[error,setError]=useState<string>(),[readError,setReadError]=useState<string>(),[pending,setPending]=useState(false),[stableCommand,setStableCommand]=useState(()=>`cmd_web_${crypto.randomUUID()}`),[fields,setFields]=useState({title:"",amount:"",note:"",category:"",paymentMethod:"",kind:"expense"});
async function load(){try{const epochResponse=await fetch("/api/write-epochs",{headers:auth});if(epochResponse.ok){const epochBody=await epochResponse.json() as {items:{domain:string;epoch:number}[]};epochHeader=epochBody.items.map(item=>`${item.domain}=${item.epoch}`).join(",");}const endpoints={meals:"/api/meals",money:"/api/money",health:"/api/health",travel:"/api/travel",library:"/api/library"};const pairs=await Promise.all(Object.entries(endpoints).map(async([key,url])=>{const response=await fetch(url,{headers:auth});if(!response.ok)throw new Error(response.status===401?"登录已失效，请重新登录。":`读取失败（HTTP ${response.status}）`);return[key,(await response.json() as {items:unknown[]}).items] as const;}));setData(Object.fromEntries(pairs));setReadError(undefined);}catch(caught){setReadError(caught instanceof Error?caught.message:"读取失败");}}useEffect(()=>{void load()},[]);
async function save(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{const date=today(),timeZone=zone();let capability:WriteCapabilityName="money.record_entry",input:unknown={entry_type:fields.kind,amount:fields.amount,currency:"CNY",occurred_on:date,time_zone:timeZone,...(fields.note?{note:fields.note}:{}),...(fields.category?{category:fields.category}:{}),...(fields.paymentMethod?{payment_method:fields.paymentMethod}:{})};if(tab==="record"&&fields.kind==="meal"){capability="life.record_meal";input={occurred_on:date,time_zone:timeZone,meal_type:"other",items:[{name:fields.title,estimate:false}],...(fields.amount?{payment:{amount:fields.amount,currency:"CNY",occurred_on:date,time_zone:timeZone,...(fields.paymentMethod?{payment_method:fields.paymentMethod}:{})}}:{})};}else if(tab==="record"&&fields.kind==="health"){capability="health.record_measurement";input={metric:"custom",label:fields.title,value:fields.amount,unit:fields.category||"unit",occurred_on:date,time_zone:timeZone};}else if(tab==="plan"){capability="money.set_budget";input={period:date.slice(0,7),category:fields.category,amount:fields.amount,currency:"CNY"};}else if(tab==="library"){capability="library.capture";input={title:fields.title,item_type:"note",text:fields.note,tags:fields.category?fields.category.split(/[,，]/u).map(x=>x.trim()).filter(Boolean):[]};}setResult(await command(capability,input,stableCommand));setStableCommand(`cmd_web_${crypto.randomUUID()}`);setFields({title:"",amount:"",note:"",category:"",paymentMethod:"",kind:"expense"});await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存失败")}finally{setPending(false)}}
return <main><header><span className="eyebrow">SHADOW LIFE</span><h1>生活事实，一处记录</h1><p>普通记录直接保存；金额、时间和来源以实际输入为准。</p>{readError?.includes("登录")&&<a href="/auth/login">重新登录</a>}</header><nav>{(["today","record","plan","library","assistant"] as Tab[]).map(value=><button type="button" className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{({today:"今天",record:"记录",plan:"计划",library:"资料库",assistant:"助手"})[value]}</button>)}</nav>{readError&&<aside className="error">{readError}</aside>}{tab==="today"?<section className="grid"><Card title="最近饮食" value={data.meals?.length??"—"}/><Card title="最近账目" value={data.money?.length??"—"}/><Card title="最近健康记录" value={data.health?.length??"—"}/><Card title="最近旅程" value={data.travel?.length??"—"}/><div className="wide"><h2>最近事实</h2><FactList data={data}/></div></section>:tab==="assistant"?<Assistant/>:<form onSubmit={save}>{tab==="record"&&<label>记录类型<select value={fields.kind} onChange={e=>setFields({...fields,kind:e.target.value})}><option value="expense">支出</option><option value="income">收入</option><option value="meal">饮食</option><option value="health">健康测量</option></select></label>}<label>{tab==="library"?"标题":"名称"}<input required={tab==="library"||fields.kind==="meal"||fields.kind==="health"} value={fields.title} onChange={e=>setFields({...fields,title:e.target.value})}/></label>{tab!=="library"&&<label>{fields.kind==="meal"?"付款金额（可选）":"金额或数值"}<input required={tab==="plan"||fields.kind==="expense"||fields.kind==="income"||fields.kind==="health"} value={fields.amount} onChange={e=>setFields({...fields,amount:e.target.value})} placeholder="35.00"/></label>}<label>{tab==="library"?"标签":"分类或单位"}<input required={tab==="plan"} value={fields.category} onChange={e=>setFields({...fields,category:e.target.value})}/></label>{tab==="record"&&fields.kind!=="health"&&<label>支付方式<select value={fields.paymentMethod} onChange={e=>setFields({...fields,paymentMethod:e.target.value})}><option value="">未说明</option><option value="alipay">支付宝</option><option value="wechat">微信</option><option value="cash">现金</option><option value="bank_card">银行卡</option><option value="other">其他</option></select></label>}<label>说明<textarea required={tab==="library"} value={fields.note} onChange={e=>setFields({...fields,note:e.target.value})}/></label><button disabled={pending}>{pending?"保存中…":"直接保存"}</button></form>}{error&&<aside className="error">{error}</aside>}{result&&<section className="receipt"><b>已保存</b><p>{result.capability} · {result.execution_id}</p></section>}</main>}
function FactList({data}:{data:Record<string,unknown[]>}){const labels:Record<string,string>={meals:"饮食",money:"账目",health:"健康",travel:"旅程",library:"资料"};const rows=Object.entries(data).flatMap(([domain,items])=>items.slice(0,3).map(value=>({domain,value:value as Record<string,unknown>})));if(!rows.length)return <p>还没有记录。</p>;return <ul>{rows.map(({domain,value},index)=><li key={`${domain}:${String(value.id??index)}`}><b>{labels[domain]??domain}</b> · {String(value.title??value.name??value.metric??value.entryType??value.kind??"记录")}{value.amount?` · ${String(value.amount)} ${String(value.currency??"")}`:""}{(value.occurredOn??value.createdAt)?` · ${String(value.occurredOn??value.createdAt).slice(0,10)}`:""}</li>)}</ul>}
function Card({title,value}:{title:string;value:number|string}){return <article><span>{title}</span><strong>{value}</strong></article>}
function Assistant(){
  const[text,setText]=useState(""),[threadId,setThreadId]=useState<string|undefined>(()=>localStorage.getItem("shadow.thread")??undefined),[turns,setTurns]=useState<{role:"user"|"assistant";text:string}[]>([]),[pendingRun,setPendingRun]=useState(false);
  useEffect(()=>{if(!threadId)return;void fetch(`/api/threads/${threadId}/messages`,{headers:auth}).then(async response=>{if(!response.ok)throw new Error();const body=await response.json() as {items:{role:"user"|"assistant";content:string}[]};setTurns(body.items.map(item=>({role:item.role,text:item.content})));}).catch(()=>{localStorage.removeItem("shadow.thread");setThreadId(undefined);});},[threadId]);
  async function run(e:FormEvent){e.preventDefault();const prompt=text.trim();if(!prompt||pendingRun)return;setPendingRun(true);setText("");setTurns(current=>[...current,{role:"user",text:prompt}]);try{let id=threadId;if(!id){const thread=await fetch("/api/threads",{method:"POST",headers:writeHeaders(),body:JSON.stringify({title:prompt.slice(0,40)})});if(!thread.ok)throw new Error(thread.status===401?"登录已失效，请重新登录。":"助手运行时暂不可用");id=((await thread.json()) as {id:string}).id;localStorage.setItem("shadow.thread",id);setThreadId(id);}const response=await fetch(`/api/threads/${id}/runs`,{method:"POST",headers:writeHeaders(),body:JSON.stringify({text:prompt})});if(!response.ok||!response.body)throw new Error(`助手请求失败（HTTP ${response.status}）`);const reader=response.body.getReader(),decoder=new TextDecoder();let pending="",answer="",interrupted="";const receipts:string[]=[];while(true){const{value,done}=await reader.read();pending+=decoder.decode(value,{stream:!done});const lines=pending.split("\n");pending=lines.pop()??"";for(const line of lines)if(line.startsWith("data:")){try{const event=JSON.parse(line.slice(5).trim()) as {type?:string;text?:string;reason?:string;result?:{status?:string;execution_id?:string}};if(event.type==="message.delta")answer+=event.text??"";if(event.type==="run.interrupted")interrupted=event.reason??"运行已中断";if(event.type==="tool.completed"&&event.result?.status==="committed")receipts.push(`已保存：${event.result.execution_id??"操作回执已提交"}`);}catch{/* transport keeps waiting for a valid terminal event */}}if(done)break;}const visible=interrupted?`未完成：${interrupted}`:answer||receipts.join("\n")||"运行结束，但没有返回可核验的结果。";setTurns(current=>[...current,{role:"assistant",text:visible}]);}catch(error){setTurns(current=>[...current,{role:"assistant",text:error instanceof Error?error.message:"助手请求失败"}]);}finally{setPendingRun(false)}}
  return <section><div>{turns.map((turn,index)=><p key={index}><b>{turn.role==="user"?"你":"Shadow"}：</b>{turn.text}</p>)}</div><form onSubmit={run}><label>告诉 Shadow 要记录、补充或查找什么<textarea required value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={pendingRun}>{pendingRun?"处理中…":"发送"}</button></form></section>;
}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
