import { useEffect, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import { ObjectPicker } from "./ObjectPicker.js";

type Recipe={id:string;title:string;revision:number};
type PlanEntry={id?:string;plan_date:string;meal_type:string;title:string;servings:string;recipe_id?:string|null;recipe_revision?:number|null};
type MealPlan={id:string;title:string;starts_on:string;ends_on:string;time_zone:string;state:"draft"|"active"|"completed"|"cancelled";revision:number;entries:PlanEntry[]};
type ShoppingItem={id:string;name:string;quantity:string|null;unit:string|null;state:"needed"|"bought"|"skipped";purchase_item_id?:string|null;revision:number};
type ShoppingList={id:string;meal_plan_id:string;title:string;state:string;items:ShoppingItem[]};
type ExtraDraft={name:string;quantity:string;unit:string};
const localDate=()=>new Intl.DateTimeFormat("en-CA").format(new Date());

export function MealPlanningPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}) {
  const [recipes,setRecipes]=useState<Recipe[]>([]),[plans,setPlans]=useState<MealPlan[]>([]),[lists,setLists]=useState<ShoppingList[]>([]),[editing,setEditing]=useState<MealPlan>(),[linkingItem,setLinkingItem]=useState<ShoppingItem>(),[purchaseItemId,setPurchaseItemId]=useState(""),[title,setTitle]=useState("一周餐单"),[start,setStart]=useState(localDate),[end,setEnd]=useState(localDate),[entryDate,setEntryDate]=useState(localDate),[mealType,setMealType]=useState("dinner"),[recipeId,setRecipeId]=useState(""),[entryTitle,setEntryTitle]=useState(""),[servings,setServings]=useState("1"),[entries,setEntries]=useState<PlanEntry[]>([]),[extras,setExtras]=useState<ExtraDraft[]>([{name:"",quantity:"",unit:""}]),[showEditor,setShowEditor]=useState(false),[error,setError]=useState<string>(),[pending,setPending]=useState(false);
  async function load(){const [workspace,catalog]=await Promise.all([fetch("/api/life/meal-planning?limit=20",{headers}),fetch("/api/life/foods?limit=100",{headers})]);if(!workspace.ok)throw new Error(`读取餐单失败（HTTP ${workspace.status}）`);const value=await workspace.json() as {meal_plans:MealPlan[];shopping_lists:ShoppingList[]};setPlans(value.meal_plans);setLists(value.shopping_lists);if(catalog.ok){const values=await catalog.json() as {recipes:Recipe[]};setRecipes(values.recipes);setRecipeId(current=>current||values.recipes.find(recipe=>recipe.revision>0)?.id||"");}}
  useEffect(()=>{void load().catch(caught=>setError(caught instanceof Error?caught.message:"读取餐单失败"));},[]);
  function addEntry(){const recipe=recipes.find(value=>value.id===recipeId),freeTitle=entryTitle.trim();if(!recipe&&!freeTitle){setError("请选择食谱，或直接写下想吃的内容。");return;}if(entryDate<start||entryDate>end){setError("计划日期需要在餐单期间内。");return;}setEntries(current=>[...current,{plan_date:entryDate,meal_type:mealType,title:recipe?.title??freeTitle,servings,...(recipe?{recipe_id:recipe.id,recipe_revision:recipe.revision}:{})}]);setEntryTitle("");setError(undefined);}
  function reset(){setEditing(undefined);setShowEditor(false);setTitle("一周餐单");setStart(localDate());setEnd(localDate());setEntryDate(localDate());setEntries([]);}
  function edit(plan:MealPlan,copy=false){const days=copy?7:0,nextStart=shiftDate(plan.starts_on,days),nextEnd=shiftDate(plan.ends_on,days);setShowEditor(true);setEditing(copy?undefined:plan);setTitle(copy?`${plan.title}（下周）`:plan.title);setStart(nextStart);setEnd(nextEnd);setEntryDate(nextStart);setEntries(plan.entries.map(({id:_,...entry})=>({...entry,plan_date:shiftDate(entry.plan_date,days)})));}
  async function save(event:FormEvent){event.preventDefault();if(!entries.length){setError("请先加入至少一餐。");return;}setPending(true);setError(undefined);try{await execute("life.save_meal_plan",{...(editing?{meal_plan_id:editing.id,expected_revision:editing.revision,reason:"在餐单工作台更新安排"}:{}),title:title.trim(),starts_on:start,ends_on:end,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone,state:editing?.state??"active",entries},`meal-plan:save:${editing?.id??"new"}`);reset();await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存餐单失败");}finally{setPending(false);}}
  async function build(plan:MealPlan){setPending(true);setError(undefined);try{const extraItems=extras.filter(item=>item.name.trim()||item.quantity.trim()||item.unit.trim()).map((item,index)=>{const name=item.name.trim(),quantity=item.quantity.trim(),unit=item.unit.trim();if(!name)throw new Error(`第 ${index+1} 个额外项目缺少名称。`);if(Boolean(quantity)!==Boolean(unit))throw new Error(`“${name}”需要同时填写数量和单位。`);return{name,...(quantity&&unit?{quantity,unit}:{})};});await execute("life.build_shopping_list",{meal_plan_id:plan.id,expected_meal_plan_revision:plan.revision,title:`${plan.title}购物清单`,extras:extraItems},`meal-plan:shopping:${plan.id}`);setExtras([{name:"",quantity:"",unit:""}]);await load();}catch(caught){setError(caught instanceof Error?caught.message:"生成购物清单失败");}finally{setPending(false);}}
  async function update(item:ShoppingItem,state:ShoppingItem["state"],purchaseId?:string){setPending(true);setError(undefined);try{await execute("life.update_shopping_item",{shopping_item_id:item.id,expected_revision:item.revision,state,...(state==="bought"&&purchaseId?{purchase_item_id:purchaseId}:{})},`shopping-item:${item.id}`);setLinkingItem(undefined);setPurchaseItemId("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"更新清单失败");}finally{setPending(false);}}
  if(!capabilities.has("life.meal_planning"))return null;
  return <section className={`wide meal-planning ${showEditor?"show-editor":""}`}><div className="panel-heading"><div><span className="eyebrow">MEAL PLAN</span><h2>餐单与购物清单</h2></div><button type="button" className={showEditor?"secondary":""} onClick={()=>showEditor?reset():setShowEditor(true)}>{showEditor?"收起编辑":"＋ 新建餐单"}</button></div><p>先看已有安排和购物状态；需要编排时再打开编辑器。计划、买到和实际摄入始终是三种不同状态。</p>{error&&<p className="inline-error">{error}</p>}
    {capabilities.has("life.save_meal_plan")&&<form className="compact-form" onSubmit={save}><h3>{editing?`编辑 ${editing.title}`:"编排餐单"}</h3><label>餐单名称<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>开始<input type="date" required value={start} onChange={event=>{setStart(event.target.value);if(entryDate<event.target.value)setEntryDate(event.target.value);if(end<event.target.value)setEnd(event.target.value);}}/></label><label>结束<input type="date" required value={end} onChange={event=>setEnd(event.target.value)}/></label><div className="meal-entry-builder full"><label>计划日期<input type="date" required value={entryDate} onChange={event=>setEntryDate(event.target.value)}/></label><label>餐次<select value={mealType} onChange={event=>setMealType(event.target.value)}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label><label>食谱（可选）<select value={recipeId} onChange={event=>setRecipeId(event.target.value)}><option value="">不关联食谱</option>{recipes.filter(recipe=>recipe.revision>0).map(recipe=><option key={recipe.id} value={recipe.id}>{recipe.title} · v{recipe.revision}</option>)}</select></label><label>想吃什么<input required={!recipeId} value={entryTitle} onChange={event=>setEntryTitle(event.target.value)} placeholder={recipeId?"已使用所选食谱名称":"例如：番茄鸡蛋面"}/></label><label>份数<input required inputMode="decimal" value={servings} onChange={event=>setServings(event.target.value)}/></label><button type="button" disabled={!recipeId&&!entryTitle.trim()} onClick={addEntry}>加入餐单</button></div>{entries.length>0&&<ol className="meal-entry-list full">{entries.map((entry,index)=><li key={`${entry.plan_date}:${entry.meal_type}:${index}`}><span><b>{entry.plan_date} · {mealLabel(entry.meal_type)}</b><small>{entry.title} · {entry.servings} 份{entry.recipe_revision?` · 食谱 v${entry.recipe_revision}`:" · 自由计划"}</small></span><button type="button" className="text-button" onClick={()=>setEntries(current=>current.filter((_,position)=>position!==index))}>移除</button></li>)}</ol>}<button disabled={pending||!entries.length}>{pending?"保存中…":editing?"保存餐单修改":"保存完整餐单"}</button></form>}
    <div className="plan-grid">{plans.map(plan=><article className="plan-card" key={plan.id}><div className="project-title"><b>{plan.title}</b><span className={`status ${plan.state}`}>{plan.state==="active"?"进行中":plan.state}</span></div><small>{plan.starts_on} 至 {plan.ends_on} · {plan.entries.length} 餐 · v{plan.revision}</small><div className="meal-preview">{plan.entries.slice(0,4).map((entry,index)=><span key={entry.id??index}>{entry.plan_date.slice(5)} {mealLabel(entry.meal_type)} · {entry.title}</span>)}</div><div className="actions"><button type="button" className="secondary" onClick={()=>edit(plan)}>编辑</button><button type="button" className="secondary" onClick={()=>edit(plan,true)}>复制到下周</button>{capabilities.has("life.build_shopping_list")&&<button type="button" disabled={pending} onClick={()=>void build(plan)}>生成购物清单</button>}</div></article>)}</div>
    {plans.length>0&&<fieldset className="extra-items"><legend>购物清单额外项目</legend>{extras.map((item,index)=><div className="ingredient-row" key={index}><label>名称<input value={item.name} onChange={event=>setExtras(current=>current.map((value,position)=>position===index?{...value,name:event.target.value}:value))}/></label><label>数量<input inputMode="decimal" value={item.quantity} onChange={event=>setExtras(current=>current.map((value,position)=>position===index?{...value,quantity:event.target.value}:value))}/></label><label>单位<input value={item.unit} onChange={event=>setExtras(current=>current.map((value,position)=>position===index?{...value,unit:event.target.value}:value))}/></label><button type="button" className="icon-button" aria-label={`移除第 ${index+1} 项`} disabled={extras.length===1} onClick={()=>setExtras(current=>current.filter((_,position)=>position!==index))}>×</button></div>)}<button type="button" className="secondary" onClick={()=>setExtras(current=>[...current,{name:"",quantity:"",unit:""}])}>＋ 添加项目</button></fieldset>}
    {lists.map(list=><article className="shopping-card" key={list.id}><div className="project-title"><h3>{list.title}</h3><small>{list.items.filter(item=>item.state==="needed").length} 项待买</small></div><ul>{list.items.map(item=><li key={item.id}><span>{item.name}{item.quantity?` · ${item.quantity} ${item.unit??""}`:""}{item.purchase_item_id?" · 已关联购买明细":""}</span><span className={`status ${item.state}`}>{shoppingLabel(item.state)}</span>{capabilities.has("life.update_shopping_item")&&<span>{item.state!=="bought"&&<><button type="button" className="secondary" onClick={()=>void update(item,"bought")}>直接标记买到</button><button type="button" className="secondary" onClick={()=>{setLinkingItem(item);setPurchaseItemId("");}}>关联购买明细</button></>}{item.state!=="skipped"&&<button type="button" className="secondary" onClick={()=>void update(item,"skipped")}>跳过</button>}{item.state!=="needed"&&<button type="button" className="secondary" onClick={()=>void update(item,"needed")}>恢复待买</button>}</span>}</li>)}</ul></article>)}
    {linkingItem&&<section className="shopping-card"><h3>为“{linkingItem.name}”选择真实购买明细</h3><ObjectPicker kind="purchase_item" headers={headers} value={purchaseItemId} optional={false} onChange={option=>setPurchaseItemId(option?.id??"")}/><div className="actions"><button type="button" disabled={pending||!purchaseItemId} onClick={()=>void update(linkingItem,"bought",purchaseItemId)}>关联并标记买到</button><button type="button" className="secondary" onClick={()=>setLinkingItem(undefined)}>取消</button></div></section>}
  </section>;
}
function mealLabel(value:string){return({breakfast:"早餐",lunch:"午餐",dinner:"晚餐",snack:"加餐",other:"其他"} as Record<string,string>)[value]??value;}
function shoppingLabel(value:ShoppingItem["state"]){return({needed:"待购买",bought:"已买到",skipped:"已跳过"})[value];}
function shiftDate(value:string,days:number):string{const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
