import { useEffect, useState, type FormEvent } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
type Recipe={id:string;title:string;revision:number};type MealPlan={id:string;title:string;starts_on:string;ends_on:string;time_zone:string;state:string;revision:number;entries:Array<Record<string,unknown>>};type ShoppingList={id:string;meal_plan_id:string;title:string;state:string;items:Array<{id:string;name:string;quantity:string|null;unit:string|null;state:string;revision:number}>};
const localDate=()=>new Intl.DateTimeFormat("en-CA").format(new Date());
export function MealPlanningPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){const [recipes,setRecipes]=useState<Recipe[]>([]),[plans,setPlans]=useState<MealPlan[]>([]),[lists,setLists]=useState<ShoppingList[]>([]),[title,setTitle]=useState("一周餐单"),[start,setStart]=useState(localDate),[end,setEnd]=useState(localDate),[entryDate,setEntryDate]=useState(localDate),[mealType,setMealType]=useState("dinner"),[recipeId,setRecipeId]=useState(""),[servings,setServings]=useState("1"),[error,setError]=useState<string>(),[pending,setPending]=useState(false);
  async function load(){const [workspace,catalog]=await Promise.all([fetch("/api/life/meal-planning?limit=20",{headers}),fetch("/api/life/foods?limit=100",{headers})]);if(!workspace.ok)throw new Error(`读取餐单失败（HTTP ${workspace.status}）`);const value=await workspace.json() as {meal_plans:MealPlan[];shopping_lists:ShoppingList[]};setPlans(value.meal_plans);setLists(value.shopping_lists);if(catalog.ok){const values=(await catalog.json()) as {recipes:Recipe[]};setRecipes(values.recipes);setRecipeId(current=>current||values.recipes.find(recipe=>recipe.revision>0)?.id||"");}}
  useEffect(()=>{void load().catch(caught=>setError(caught instanceof Error?caught.message:"读取餐单失败"));},[]);
  async function save(event:FormEvent){event.preventDefault();const recipe=recipes.find(value=>value.id===recipeId);if(!recipe){setError("请先创建并选择一个有效食谱。");return;}setPending(true);setError(undefined);try{await execute("life.save_meal_plan",{title:title.trim(),starts_on:start,ends_on:end,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone,state:"active",entries:[{plan_date:entryDate,meal_type:mealType,title:recipe.title,servings,recipe_id:recipe.id,recipe_revision:recipe.revision}]},`cmd_web_meal_plan_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"保存餐单失败");}finally{setPending(false);}}
  async function build(plan:MealPlan){setPending(true);setError(undefined);try{await execute("life.build_shopping_list",{meal_plan_id:plan.id,expected_meal_plan_revision:plan.revision,title:`${plan.title}购物清单`,extras:[]},`cmd_web_shopping_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"生成购物清单失败");}finally{setPending(false);}}
  async function update(item:ShoppingList["items"][number],state:"bought"|"skipped"){setPending(true);setError(undefined);try{await execute("life.update_shopping_item",{shopping_item_id:item.id,expected_revision:item.revision,state},`cmd_web_shopping_item_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"更新清单失败");}finally{setPending(false);}}
  if(!capabilities.has("life.meal_planning"))return null;return <section className="wide meal-planning"><div className="panel-heading"><div><span className="eyebrow">MEAL PLAN</span><h2>餐单与购物清单</h2></div></div><p>计划吃、已经买到和实际摄入是三种不同状态；勾选清单不会生成餐次。</p>{error&&<p className="inline-error">{error}</p>}{capabilities.has("life.save_meal_plan")&&<form className="compact-form" onSubmit={save}><h3>按食谱安排一餐</h3><label>餐单名称<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>开始<input type="date" required value={start} onChange={event=>{setStart(event.target.value);setEntryDate(event.target.value);if(end<event.target.value)setEnd(event.target.value)}}/></label><label>结束<input type="date" required value={end} onChange={event=>setEnd(event.target.value)}/></label><label>计划日期<input type="date" required value={entryDate} onChange={event=>setEntryDate(event.target.value)}/></label><label>餐次<select value={mealType} onChange={event=>setMealType(event.target.value)}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label><label>食谱<select required value={recipeId} onChange={event=>setRecipeId(event.target.value)}><option value="">请选择</option>{recipes.filter(recipe=>recipe.revision>0).map(recipe=><option key={recipe.id} value={recipe.id}>{recipe.title} · 修订 {recipe.revision}</option>)}</select></label><label>计划份数<input required inputMode="decimal" value={servings} onChange={event=>setServings(event.target.value)}/></label><button disabled={pending||!recipeId}>{pending?"保存中…":"保存餐单"}</button></form>}{plans.map(plan=><article className="plan-card" key={plan.id}><b>{plan.title}</b><small>{plan.starts_on} 至 {plan.ends_on} · 修订 {plan.revision} · {plan.entries.length} 餐</small>{capabilities.has("life.build_shopping_list")&&<button type="button" className="secondary" disabled={pending} onClick={()=>void build(plan)}>生成该修订的购物清单</button>}</article>)}{lists.map(list=><article className="shopping-card" key={list.id}><h3>{list.title}</h3><small>状态 {list.state}</small><ul>{list.items.map(item=><li key={item.id}><span>{item.name}{item.quantity?` · ${item.quantity} ${item.unit??""}`:""}</span><span className={`status ${item.state}`}>{item.state}</span>{item.state==="needed"&&capabilities.has("life.update_shopping_item")&&<span><button type="button" className="secondary" onClick={()=>void update(item,"bought")}>买到了</button><button type="button" className="secondary" onClick={()=>void update(item,"skipped")}>跳过</button></span>}</li>)}</ul></article>)}</section>;}
