import type { WriteCapabilityName } from "@shadow/contracts";

export interface MoneyImportCandidate{ id:string;position:number;external_id:string|null;raw:Record<string,unknown>;proposed:Partial<{entry_type:"expense"|"income"|"refund";amount:string;currency:"CNY";occurred_on:string;time_zone:string;counterparty:string;category:string;payment_method:string;note:string}>;issues:string[];warnings:string[];applied_rule_ids:string[];status:"pending"|"invalid"|"confirmed"|"ignored";duplicate_of_record_id:string|null;linked_record_id:string|null;revision:number; }
export interface MoneyImportRule{id:string;match_value:string;replacements:Partial<{entry_type:"expense"|"income";counterparty:string;category:string;payment_method:string}>;state:"active"|"disabled";revision:number;}
export interface MoneyImportReview{batch:{id:string;source_name:string;format:"csv"|"json"|"markdown";content_hash:string;status:"review"|"completed";total:number;pending:number;confirmed:number;ignored:number;invalid:number;created_at:string};candidates:MoneyImportCandidate[];rules:MoneyImportRule[];}
export interface CandidateFields{entryType:"expense"|"income"|"refund";amount:string;occurredOn:string;timeZone:string;counterparty:string;category:string;paymentMethod:string;note:string;originalEntryId:string;rememberRule:boolean;}
export interface ImportCommand{capability:WriteCapabilityName;input:unknown;}

export async function loadMoneyImportReview(fetcher:typeof fetch,headers:HeadersInit,batchId:string):Promise<MoneyImportReview>{const response=await fetcher(`/api/money/imports/${encodeURIComponent(batchId)}`,{headers});if(!response.ok)throw new Error(response.status===401?"登录已失效，请重新登录。":`读取导入复核失败（HTTP ${response.status}）`);return response.json() as Promise<MoneyImportReview>;}
export function initialCandidateFields(candidate:MoneyImportCandidate,defaultZone:string):CandidateFields{return{entryType:candidate.proposed.entry_type??"expense",amount:candidate.proposed.amount??"",occurredOn:candidate.proposed.occurred_on??"",timeZone:candidate.proposed.time_zone??defaultZone,counterparty:candidate.proposed.counterparty??"",category:candidate.proposed.category??"",paymentMethod:candidate.proposed.payment_method??"",note:candidate.proposed.note??"",originalEntryId:"",rememberRule:false};}
export function resolveCandidateCommand(candidate:MoneyImportCandidate,decision:"confirm"|"ignore",fields:CandidateFields):ImportCommand{if(decision==="ignore")return{capability:"money.resolve_import_candidate",input:{candidate_id:candidate.id,expected_revision:candidate.revision,decision,reason:"在 Web 账单复核中忽略"}};return{capability:"money.resolve_import_candidate",input:{candidate_id:candidate.id,expected_revision:candidate.revision,decision,corrections:{entry_type:fields.entryType,amount:fields.amount.trim(),currency:"CNY",occurred_on:fields.occurredOn,time_zone:fields.timeZone,...(fields.counterparty.trim()?{counterparty:fields.counterparty.trim()}:{}),...(fields.category.trim()?{category:fields.category.trim()}:{}),...(fields.paymentMethod?{payment_method:fields.paymentMethod}:{}),...(fields.note.trim()?{note:fields.note.trim()}: {})},...(fields.entryType==="refund"&&fields.originalEntryId.trim()?{original_entry_id:fields.originalEntryId.trim()}:{}),remember_rule:fields.entryType!=="refund"&&fields.rememberRule,reason:"在 Web 账单复核中确认"}};}
export function disableImportRuleCommand(rule:MoneyImportRule):ImportCommand{return{capability:"money.set_import_rule",input:{rule_id:rule.id,expected_revision:rule.revision,match_value:rule.match_value,replacements:rule.replacements,state:"disabled"}};}
