import { useEffect, useState } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";

type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
type Notice={id:string;title:string;body:string;state:string;delivery_state:string;scheduled_at:string;snoozed_until?:string|null};
type View={items:Notice[];preferences:{enabled:boolean;quiet_start:string|null;quiet_end:string|null;time_zone:string;revision:number}};
async function body<T>(response:Response):Promise<T>{const value=await response.json() as T&{message?:string};if(!response.ok)throw new Error(value.message??`HTTP ${response.status}`);return value;}

export function NotificationPanel({headers,execute}:{headers:HeadersInit;execute:Execute}){
  const[view,setView]=useState<View>(),[enabled,setEnabled]=useState(true),[quietStart,setQuietStart]=useState("22:00"),[quietEnd,setQuietEnd]=useState("07:00"),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  async function load(){try{const value=await body<View>(await fetch("/api/notifications?limit=50",{headers}));setView(value);setEnabled(value.preferences.enabled);setQuietStart(value.preferences.quiet_start?.slice(0,5)??"22:00");setQuietEnd(value.preferences.quiet_end?.slice(0,5)??"07:00");}catch(caught){setError(caught instanceof Error?caught.message:"通知读取失败");}}
  useEffect(()=>{void load()},[]);
  async function preferences(){setPending(true);try{await execute("notifications.set_preferences",{enabled,quiet_start:quietStart,quiet_end:quietEnd,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone},`cmd_web_notifications_pref_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"通知设置失败");}finally{setPending(false);}}
  async function update(notification_id:string,action:"dismiss"|"snooze"){setPending(true);try{await execute("notifications.update",{notification_id,action,...(action==="snooze"?{snoozed_until:new Date(Date.now()+24*60*60*1000).toISOString()}: {})},`cmd_web_notification_${crypto.randomUUID()}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"通知更新失败");}finally{setPending(false);}}
  return <section className="wide notification-panel"><div className="panel-heading"><div><span className="eyebrow">NOTICES</span><h2>提醒与静默</h2></div><label className="checkbox-row"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/>启用提醒</label></div>{error&&<p className="inline-error">{error}</p>}<div className="notice-preferences"><label>静默开始<input type="time" value={quietStart} onChange={event=>setQuietStart(event.target.value)}/></label><label>静默结束<input type="time" value={quietEnd} onChange={event=>setQuietEnd(event.target.value)}/></label><button type="button" disabled={pending} onClick={()=>void preferences()}>保存设置</button></div>{!view?.items.length?<p>没有待处理提醒。</p>:<ul>{view.items.map(notice=><li key={notice.id}><div><b>{notice.title}</b><span>{notice.body}</span><small>{notice.delivery_state} · {new Date(notice.snoozed_until??notice.scheduled_at).toLocaleString()}</small></div><div className="actions"><button type="button" disabled={pending} onClick={()=>void update(notice.id,"snooze")}>延后一天</button><button type="button" className="secondary" disabled={pending} onClick={()=>void update(notice.id,"dismiss")}>忽略</button></div></li>)}</ul>}<small>系统通知只显示脱敏提示；金额、票号、健康读数等需打开应用后按权限读取。</small></section>;
}
