import { RecordDetailContent } from "./RecordDetailContent.js";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { DashboardDomain, TimelineItem } from "./dashboard.js";
import { canCorrectDetail, correctionCommand, detailEditKind, initialEditableFields, loadRecordDetail, selectionHref, type EditableRecordFields, type RecordSelection } from "./record-detail.js";
import type { Execute } from "./command-controller.js";
import { formatMoneyAmount } from "./money-display.js";

const labels:Record<DashboardDomain,string>={meals:"饮食",money:"账目",health:"健康",travel:"旅行",library:"资料"};
export function RecordBrowser({timeline,nextCursor,selection,capabilities,headers,execute,onChanged}:{timeline:TimelineItem[];nextCursor:string|null;selection:RecordSelection|undefined;capabilities:ReadonlySet<string>;headers:HeadersInit;execute:Execute;onChanged:()=>Promise<void>}){
  const [filter,setFilter]=useState<DashboardDomain|"all">("all"),[items,setItems]=useState(timeline),[cursor,setCursor]=useState(nextCursor),[detail,setDetail]=useState<Record<string,unknown>>(),[error,setError]=useState<string>(),[pending,setPending]=useState(false),[fields,setFields]=useState<EditableRecordFields>();
  const rows=useMemo(()=>(filter==="all"?items:items.filter(item=>item.domain===filter)).map(item=>item.amount?{...item,amount:formatMoneyAmount(item.amount,item.currency)}:item),[items,filter]);
  useEffect(()=>{setItems(timeline);setCursor(nextCursor);},[timeline,nextCursor]);
  useEffect(()=>{let active=true;setDetail(undefined);setFields(undefined);setError(undefined);if(!selection)return()=>{active=false};void loadRecordDetail(fetch,headers,selection).then(value=>{if(active){setDetail(value);setFields(initialEditableFields(value));}}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:"读取详情失败");});return()=>{active=false};},[selection?.domain,selection?.kind,selection?.id,selection?.recordId]);
  async function correct(event:FormEvent){event.preventDefault();if(!detail||!fields||!selection)return;setPending(true);setError(undefined);try{const built=correctionCommand(detail,fields);await execute(built.capability,built.input,`record:correct:${selection.domain}:${selection.id}`);const refreshed=await loadRecordDetail(fetch,headers,selection);setDetail(refreshed);setFields(initialEditableFields(refreshed));await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"修正失败");}finally{setPending(false);}}
  async function loadMore(){if(!cursor)return;setPending(true);setError(undefined);try{const response=await fetch(`/api/timeline?limit=30&cursor=${encodeURIComponent(cursor)}`,{headers});if(!response.ok)throw new Error(`读取更多记录失败（HTTP ${response.status}）`);const page=await response.json() as {items:TimelineItem[];next_cursor:string|null};setItems(current=>[...current,...page.items]);setCursor(page.next_cursor);}catch(caught){setError(caught instanceof Error?caught.message:"读取更多记录失败");}finally{setPending(false);}}
  async function addOwnedItem(purchaseItem:Record<string,unknown>){setPending(true);setError(undefined);try{await execute("life.save_owned_item",{purchase_item_id:String(purchaseItem.id),name:String(purchaseItem.raw_name??"物品"),ownership_state:"owned",documents:[]},`owned-item:purchase:${String(purchaseItem.id)}`);await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"加入物品失败");}finally{setPending(false);}}
  return <section className="record-browser wide">{!selection&&<><div className="panel-heading"><div><span className="eyebrow">HISTORY</span><h2>统一记录</h2></div><label>筛选<select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">全部</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><p>按时间浏览饮食、消费、健康与旅行记录。</p></>}{error&&!selection&&<p className="inline-error">{error}</p>}{!selection&&<><ol className="record-list">{rows.map(item=><li key={`${item.domain}:${item.kind}:${item.id}`}><a href={selectionHref(item)}><span><b>{labels[item.domain]}</b> · {item.title}</span><small>{formatDate(item.happened_at)}{item.amount?` · ${item.amount} ${item.currency??""}`:""}</small></a></li>)}</ol>{!rows.length&&<p>当前筛选没有记录。</p>}{cursor&&<button type="button" className="secondary load-more" disabled={pending} onClick={()=>void loadMore()}>{pending?"读取中…":"加载更早记录"}</button>}</>}{selection&&<section className="record-detail"><a className="detail-close" href="?tab=record">← 返回记录</a>{error&&<p className="inline-error">{error}</p>}{!detail&&!error&&<p role="status">正在读取详情…</p>}{detail&&<RecordDetailContent key={selection.id} value={detail} selection={selection}/>} {detail&&capabilities.has("life.save_owned_item")&&Array.isArray(detail.purchase_items)&&detail.purchase_items.length>0&&<section className="purchase-to-items"><h3>加入我的物品</h3><p>仅选择确实由你持有的购买明细，不会自动导入整张订单。</p>{detail.purchase_items.map((value,index)=>{const item=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return <button key={String(item.id??index)} type="button" className="secondary" disabled={pending||typeof item.id!=="string"} onClick={()=>void addOwnedItem(item)}>{String(item.raw_name??"购买明细")}</button>})}</section>} {detail&&fields&&canCorrectDetail(detail,capabilities)&&<details className="detail-meta"><summary>更正这条记录</summary><EditForm kind={detailEditKind(detail)!} fields={fields} setFields={setFields} pending={pending} submit={correct}/></details>}</section>}</section>;
}
function EditForm({kind,fields,setFields,pending,submit}:{kind:"health"|"money"|"meal";fields:EditableRecordFields;setFields:(value:EditableRecordFields)=>void;pending:boolean;submit:(event:FormEvent)=>Promise<void>}){return <form className="detail-edit" onSubmit={submit}><h3>修正事实</h3><label>发生日<input type="date" required value={fields.occurredOn} onChange={event=>setFields({...fields,occurredOn:event.target.value})}/></label><label>时区<input required value={fields.timeZone} onChange={event=>setFields({...fields,timeZone:event.target.value})}/></label>{kind==="health"?<><label>指标<select value={fields.healthMetric} onChange={event=>setFields({...fields,healthMetric:event.target.value as EditableRecordFields["healthMetric"]})}><option value="weight">体重</option><option value="body_fat">体脂率</option><option value="heart_rate">心率</option><option value="blood_pressure_systolic">收缩压</option><option value="blood_pressure_diastolic">舒张压</option><option value="temperature">体温</option><option value="sleep_duration">睡眠时长</option><option value="steps">步数</option><option value="custom">其他</option></select></label><label>值<input required inputMode="decimal" value={fields.healthValue} onChange={event=>setFields({...fields,healthValue:event.target.value})}/></label><label>单位<input required value={fields.healthUnit} onChange={event=>setFields({...fields,healthUnit:event.target.value})}/></label><label>标签<input value={fields.healthLabel} onChange={event=>setFields({...fields,healthLabel:event.target.value})}/></label></>:kind==="money"?<><label>金额<input required inputMode="decimal" value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})}/></label><label>币种<input required value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value})}/></label><label>交易对方<input value={fields.counterparty} onChange={event=>setFields({...fields,counterparty:event.target.value})}/></label><label>分类<input value={fields.category} onChange={event=>setFields({...fields,category:event.target.value})}/></label><label>支付方式<input value={fields.paymentMethod} onChange={event=>setFields({...fields,paymentMethod:event.target.value})}/></label></>:<label>餐次<select value={fields.mealType} onChange={event=>setFields({...fields,mealType:event.target.value as EditableRecordFields["mealType"]})}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label>}<label className="full">备注<textarea value={fields.note} onChange={event=>setFields({...fields,note:event.target.value})}/></label><label className="full">修正原因<input required value={fields.reason} onChange={event=>setFields({...fields,reason:event.target.value})}/></label><button disabled={pending}>{pending?"保存修正中…":"保存修正"}</button></form>;}
function formatDate(value:string):string{const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(date);}
