import type { WriteCapabilityName } from "@shadow/contracts";
import type { DashboardDomain, TimelineItem } from "./dashboard.js";

export interface RecordSelection{domain:DashboardDomain;kind:string;id:string;recordId?:string;}
export interface DetailCommand{capability:WriteCapabilityName;input:unknown;}
export interface EditableRecordFields{occurredOn:string;timeZone:string;note:string;mealType:"breakfast"|"lunch"|"dinner"|"snack"|"other";amount:string;currency:string;counterparty:string;category:string;paymentMethod:string;healthMetric:"weight"|"body_fat"|"heart_rate"|"blood_pressure_systolic"|"blood_pressure_diastolic"|"temperature"|"sleep_duration"|"steps"|"custom";healthValue:string;healthUnit:string;healthLabel:string;reason:string;}

export function selectionFromLocation(search:string):RecordSelection|undefined{const query=new URLSearchParams(search),domain=query.get("domain"),id=query.get("id"),kind=query.get("kind");if(!isDomain(domain)||!id||!kind)return undefined;return{domain,kind,id,...(query.get("record_id")?{recordId:query.get("record_id")!}:{})};}
export function selectionHref(item:TimelineItem):string{const query=new URLSearchParams({tab:"record",domain:item.domain,kind:item.kind,id:item.id});if(item.record_id)query.set("record_id",item.record_id);return`?${query.toString()}`;}
export function detailEndpoint(selection:RecordSelection):string|undefined{if(selection.domain==="meals"||selection.domain==="money")return`/api/life/records/${encodeURIComponent(selection.recordId??selection.id)}`;if(selection.domain==="health")return`/api/health/records/${encodeURIComponent(selection.id)}`;if(selection.domain==="travel"&&(selection.kind==="trip"||selection.recordId))return`/api/travel/trips/${encodeURIComponent(selection.recordId??selection.id)}`;if(selection.domain==="library")return`/api/library/items/${encodeURIComponent(selection.id)}`;return undefined;}
export async function loadRecordDetail(fetcher:typeof fetch,headers:HeadersInit,selection:RecordSelection):Promise<Record<string,unknown>>{const endpoint=detailEndpoint(selection);if(!endpoint)throw new Error("该类型的完整详情尚未开放；列表仍保留其真实时间与标识。");const response=await fetcher(endpoint,{headers});if(!response.ok)throw new Error(response.status===404?"记录不存在或当前账号不可见。":response.status===401?"登录已失效，请重新登录。":`读取详情失败（HTTP ${response.status}）`);return response.json() as Promise<Record<string,unknown>>;}
export function initialEditableFields(detail:Record<string,unknown>):EditableRecordFields{const meal=mealValue(detail),entry=objectValue(detail.money_entry),fact=objectValue(detail.fact);return{occurredOn:stringValue(fact.occurred_on??detail.occurred_on??meal.occurred_on),timeZone:stringValue(fact.time_zone??detail.time_zone??meal.time_zone),note:stringValue(fact.note??detail.note??meal.note),mealType:mealTypeValue(meal.meal_type),amount:stringValue(entry.amount),currency:stringValue(entry.currency)||"CNY",counterparty:stringValue(entry.counterparty),category:stringValue(entry.category),paymentMethod:stringValue(entry.payment_method),healthMetric:healthMetricValue(fact.metric),healthValue:stringValue(fact.value),healthUnit:stringValue(fact.unit),healthLabel:stringValue(fact.label),reason:"在记录详情中核对并修正"};}
export function correctionCommand(detail:Record<string,unknown>,fields:EditableRecordFields):DetailCommand{const fact=objectValue(detail.fact);if(detail.kind==="measurement"&&detail.raw===null&&stringValue(fact.id))return{capability:"health.correct_measurement",input:{measurement_id:stringValue(fact.id),expected_revision:numberValue(fact.revision),metric:fields.healthMetric,value:fields.healthValue.trim(),unit:fields.healthUnit.trim(),...(fields.healthLabel.trim()?{label:fields.healthLabel.trim()}:{}),occurred_on:fields.occurredOn,time_zone:fields.timeZone,...(fields.note.trim()?{note:fields.note.trim()}:{}),reason:fields.reason.trim()}};const meal=mealValue(detail),mealId=stringValue(detail.meal_id??meal.meal_id??meal.id);if(mealId&&!detail.money_entry)return{capability:"life.correct_meal",input:{meal_id:mealId,expected_revision:numberValue(meal.revision??detail.revision),occurred_on:fields.occurredOn,time_zone:fields.timeZone,meal_type:fields.mealType,...(fields.note.trim()?{note:fields.note.trim()}:{}),reason:fields.reason.trim()}};const recordId=stringValue(detail.record_id),entry=objectValue(detail.money_entry);if(recordId&&Object.keys(entry).length)return{capability:"money.correct_entry",input:{record_id:recordId,expected_revision:numberValue(detail.revision),amount:fields.amount.trim(),currency:fields.currency.trim().toUpperCase(),occurred_on:fields.occurredOn,time_zone:fields.timeZone,...(fields.category.trim()?{category:fields.category.trim()}:{}),...(fields.counterparty.trim()?{counterparty:fields.counterparty.trim()}:{}),...(fields.paymentMethod?{payment_method:fields.paymentMethod}:{}),...(fields.note.trim()?{note:fields.note.trim()}:{}),reason:fields.reason.trim()}};throw new Error("该详情当前没有可修正的事实。");}
export function detailEditKind(detail:Record<string,unknown>):"health"|"money"|"meal"|undefined{if(detail.kind==="measurement"&&detail.raw===null&&stringValue(objectValue(detail.fact).id))return"health";const meal=mealValue(detail),mealId=stringValue(detail.meal_id??meal.meal_id??meal.id);if(mealId&&!detail.money_entry)return"meal";if(detail.record_id&&detail.money_entry)return"money";return undefined;}
export function canCorrectDetail(detail:Record<string,unknown>,capabilities:ReadonlySet<string>):boolean{const kind=detailEditKind(detail);return kind==="health"?capabilities.has("health.correct_measurement"):kind==="meal"?capabilities.has("life.correct_meal"):kind==="money"?capabilities.has("money.correct_entry"):false;}

function isDomain(value:string|null):value is DashboardDomain{return value==="meals"||value==="money"||value==="health"||value==="travel"||value==="library";}
function objectValue(value:unknown):Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function mealValue(detail:Record<string,unknown>):Record<string,unknown>{if(detail.meal_id)return detail;const meals=Array.isArray(detail.meals)?detail.meals:[];return objectValue(meals[0]);}
function stringValue(value:unknown):string{return typeof value==="string"?value:"";}
function numberValue(value:unknown):number{if(typeof value!=="number"||!Number.isInteger(value)||value<1)throw new Error("详情缺少可用修订版本，请重新加载。");return value;}
function mealTypeValue(value:unknown):EditableRecordFields["mealType"]{return value==="breakfast"||value==="lunch"||value==="dinner"||value==="snack"||value==="other"?value:"other";}
function healthMetricValue(value:unknown):EditableRecordFields["healthMetric"]{return value==="weight"||value==="body_fat"||value==="heart_rate"||value==="blood_pressure_systolic"||value==="blood_pressure_diastolic"||value==="temperature"||value==="sleep_duration"||value==="steps"||value==="custom"?value:"custom";}
