import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import type { ExecutionResult, WriteCapabilityName } from "@shadow/contracts";
import type { DashboardDomain, TimelineItem } from "./dashboard.js";
import { canCorrectDetail, correctionCommand, detailEditKind, initialEditableFields, loadRecordDetail, selectionHref, type EditableRecordFields, type RecordSelection } from "./record-detail.js";

type Execute=(capability:WriteCapabilityName,input:unknown,commandId:string)=>Promise<ExecutionResult>;
const labels:Record<DashboardDomain,string>={meals:"饮食",money:"账目",health:"健康",travel:"旅行",library:"资料"};
export function RecordBrowser({timeline,nextCursor,selection,capabilities,headers,execute,onChanged}:{timeline:TimelineItem[];nextCursor:string|null;selection:RecordSelection|undefined;capabilities:ReadonlySet<string>;headers:HeadersInit;execute:Execute;onChanged:()=>Promise<void>}){
  const [filter,setFilter]=useState<DashboardDomain|"all">("all"),[items,setItems]=useState(timeline),[cursor,setCursor]=useState(nextCursor),[detail,setDetail]=useState<Record<string,unknown>>(),[error,setError]=useState<string>(),[pending,setPending]=useState(false),[fields,setFields]=useState<EditableRecordFields>();const commandId=useRef<string|undefined>(undefined);
  const rows=useMemo(()=>filter==="all"?items:items.filter(item=>item.domain===filter),[items,filter]);
  useEffect(()=>{setItems(timeline);setCursor(nextCursor);},[timeline,nextCursor]);
  useEffect(()=>{let active=true;setDetail(undefined);setFields(undefined);setError(undefined);if(!selection)return()=>{active=false};void loadRecordDetail(fetch,headers,selection).then(value=>{if(active){setDetail(value);setFields(initialEditableFields(value));}}).catch(caught=>{if(active)setError(caught instanceof Error?caught.message:"读取详情失败");});return()=>{active=false};},[selection?.domain,selection?.kind,selection?.id,selection?.recordId]);
  async function correct(event:FormEvent){event.preventDefault();if(!detail||!fields)return;setPending(true);setError(undefined);try{const built=correctionCommand(detail,fields);commandId.current??=`cmd_web_${crypto.randomUUID()}`;await execute(built.capability,built.input,commandId.current);commandId.current=undefined;const refreshed=await loadRecordDetail(fetch,headers,selection!);setDetail(refreshed);setFields(initialEditableFields(refreshed));await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"修正失败");}finally{setPending(false);}}
  async function loadMore(){if(!cursor)return;setPending(true);setError(undefined);try{const response=await fetch(`/api/timeline?limit=30&cursor=${encodeURIComponent(cursor)}`,{headers});if(!response.ok)throw new Error(`读取更多记录失败（HTTP ${response.status}）`);const page=await response.json() as {items:TimelineItem[];next_cursor:string|null};setItems(current=>[...current,...page.items]);setCursor(page.next_cursor);}catch(caught){setError(caught instanceof Error?caught.message:"读取更多记录失败");}finally{setPending(false);}}
  return <section className="record-browser"><div className="panel-heading"><div><span className="eyebrow">HISTORY</span><h2>统一记录</h2></div><label>筛选<select value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">全部</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><p>按真实发生时间浏览；打开详情后的 URL 可复制分享，服务端仍按接收方权限裁剪。</p>{error&&!selection&&<p className="inline-error">{error}</p>}<ol className="record-list">{rows.map(item=><li key={`${item.domain}:${item.kind}:${item.id}`}><a href={selectionHref(item)}><span><b>{labels[item.domain]}</b> · {item.title}</span><small>{formatDate(item.happened_at)}{item.amount?` · ${item.amount} ${item.currency??""}`:""}</small></a></li>)}</ol>{!rows.length&&<p>当前筛选没有记录。</p>}{cursor&&<button type="button" className="secondary load-more" disabled={pending} onClick={()=>void loadMore()}>{pending?"读取中…":"加载更早记录"}</button>}{selection&&<section className="record-detail"><a className="detail-close" href="?tab=record">关闭详情</a><h3>{labels[selection.domain]} · {selection.kind}</h3><code>{selection.id}</code>{error&&<p className="inline-error">{error}</p>}{detail&&<DetailView value={detail}/>} {detail&&fields&&canCorrectDetail(detail,capabilities)&&<EditForm kind={detailEditKind(detail)!} fields={fields} setFields={setFields} pending={pending} submit={correct}/>}</section>}</section>;
}
function DetailView({value}:{value:Record<string,unknown>}){return <dl className="detail-grid">{Object.entries(value).filter(([,item])=>item!==null&&item!==undefined).map(([key,item])=><div key={key}><dt>{fieldLabel(key)}</dt><dd>{renderValue(item)}</dd></div>)}</dl>;}
function EditForm({kind,fields,setFields,pending,submit}:{kind:"health"|"money"|"meal";fields:EditableRecordFields;setFields:(value:EditableRecordFields)=>void;pending:boolean;submit:(event:FormEvent)=>Promise<void>}){return <form className="detail-edit" onSubmit={submit}><h3>修正事实</h3><label>发生日<input type="date" required value={fields.occurredOn} onChange={event=>setFields({...fields,occurredOn:event.target.value})}/></label><label>时区<input required value={fields.timeZone} onChange={event=>setFields({...fields,timeZone:event.target.value})}/></label>{kind==="health"?<><label>指标<select value={fields.healthMetric} onChange={event=>setFields({...fields,healthMetric:event.target.value as EditableRecordFields["healthMetric"]})}><option value="weight">体重</option><option value="body_fat">体脂率</option><option value="heart_rate">心率</option><option value="blood_pressure_systolic">收缩压</option><option value="blood_pressure_diastolic">舒张压</option><option value="temperature">体温</option><option value="sleep_duration">睡眠时长</option><option value="steps">步数</option><option value="custom">其他</option></select></label><label>值<input required inputMode="decimal" value={fields.healthValue} onChange={event=>setFields({...fields,healthValue:event.target.value})}/></label><label>单位<input required value={fields.healthUnit} onChange={event=>setFields({...fields,healthUnit:event.target.value})}/></label><label>标签<input value={fields.healthLabel} onChange={event=>setFields({...fields,healthLabel:event.target.value})}/></label></>:kind==="money"?<><label>金额<input required inputMode="decimal" value={fields.amount} onChange={event=>setFields({...fields,amount:event.target.value})}/></label><label>币种<input required value={fields.currency} onChange={event=>setFields({...fields,currency:event.target.value})}/></label><label>交易对方<input value={fields.counterparty} onChange={event=>setFields({...fields,counterparty:event.target.value})}/></label><label>分类<input value={fields.category} onChange={event=>setFields({...fields,category:event.target.value})}/></label><label>支付方式<input value={fields.paymentMethod} onChange={event=>setFields({...fields,paymentMethod:event.target.value})}/></label></>:<label>餐次<select value={fields.mealType} onChange={event=>setFields({...fields,mealType:event.target.value as EditableRecordFields["mealType"]})}><option value="breakfast">早餐</option><option value="lunch">午餐</option><option value="dinner">晚餐</option><option value="snack">加餐</option><option value="other">其他</option></select></label>}<label className="full">备注<textarea value={fields.note} onChange={event=>setFields({...fields,note:event.target.value})}/></label><label className="full">修正原因<input required value={fields.reason} onChange={event=>setFields({...fields,reason:event.target.value})}/></label><button disabled={pending}>{pending?"保存修正中…":"保存修正"}</button></form>;}
function renderValue(value:unknown):string{return typeof value==="string"||typeof value==="number"||typeof value==="boolean"?String(value):JSON.stringify(value,null,2);}
function fieldLabel(value:string):string{return({record_id:"记录 ID",meal_id:"餐次 ID",occurred_on:"发生日",occurred_at:"发生时间",time_zone:"时区",note:"备注",revision:"修订",state:"状态",money_entry:"账目",purchase:"消费",purchase_items:"购买明细",meals:"关联餐次",items:"摄入明细",payments:"付款",sources:"来源",trip:"旅程",reservations:"预订",segments:"行程段",visits:"到访",item:"资料",annotations:"批注",derivations:"派生"} as Record<string,string>)[value]??value;}
function formatDate(value:string):string{const date=new Date(value);return Number.isNaN(date.valueOf())?value:new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium",timeStyle:"short"}).format(date);}
