import { useEffect, useRef, useState, type FormEvent } from "react";
import type { ServiceCard } from "@shadow/contracts";
import type { Execute } from "./command-controller.js";

const localToday=()=>new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const statusLabel={active:"可使用",depleted:"已用完",expired:"已到期",closed:"已关闭"};
const blankCard=()=>({name:"",merchant_name:"",purchase_record_id:"",total_units:"",unit_label:"次",started_on:localToday(),expires_on:"",note:"",state:"active" as "active"|"closed"});
type PurchaseOption={id:string;record_id:string|null;title:string;supporting:string|null;amount:string|null;currency:string|null};

export function ServiceCardsPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){
  const [cards,setCards]=useState<ServiceCard[]>([]),[cursor,setCursor]=useState<string|null>(null),[query,setQuery]=useState("");
  const [selected,setSelected]=useState<ServiceCard>(),[editing,setEditing]=useState(false),[form,setForm]=useState(blankCard);
  const [useId,setUseId]=useState<string>(),[date,setDate]=useState(localToday()),[units,setUnits]=useState("1"),[note,setNote]=useState("");
  const [purchaseQuery,setPurchaseQuery]=useState(""),[purchases,setPurchases]=useState<PurchaseOption[]>([]);
  const [error,setError]=useState<string>(),[message,setMessage]=useState<string>(),[pending,setPending]=useState(false);
  const detailSequence=useRef(0),listSequence=useRef(0);
  async function get<T,>(path:string):Promise<T>{const response=await fetch(path,{headers});if(!response.ok)throw new Error(`读取失败（${response.status}）`);return response.json() as Promise<T>;}
  async function load(after?:string){const sequence=++listSequence.current;const result=await get<{items:ServiceCard[];next_after_id:string|null}>(`/api/money/service-cards?${new URLSearchParams({query,limit:"50",...(after?{after_id:after}:{})})}`);if(sequence!==listSequence.current)return;setCards(current=>after?[...current,...result.items]:result.items);setCursor(result.next_after_id);}
  useEffect(()=>{const timer=setTimeout(()=>{void load().catch(fail);},200);return()=>{clearTimeout(timer);listSequence.current++;};},[query]);
  useEffect(()=>{if(!editing)return;let active=true;const timer=setTimeout(()=>{void get<{items:PurchaseOption[]}>(`/api/money?${new URLSearchParams({q:purchaseQuery,limit:"30"})}`).then(result=>{if(active)setPurchases(result.items.filter(item=>item.record_id));}).catch(value=>{if(active)fail(value);});},250);return()=>{active=false;clearTimeout(timer);};},[purchaseQuery,editing]);
  function fail(value:unknown){setError(value instanceof Error?value.message:"操作失败");}
  async function open(id:string){const sequence=++detailSequence.current;const result=await get<{items:ServiceCard[]}>(`/api/money/service-cards?id=${encodeURIComponent(id)}`);if(sequence!==detailSequence.current)return;setSelected(result.items[0]);setEditing(false);resetUse();}
  function resetUse(){setUseId(undefined);setDate(localToday());setUnits("1");setNote("");}
  function edit(card?:ServiceCard){detailSequence.current++;setSelected(card);setForm(card?{name:card.name,merchant_name:card.merchant_name??"",purchase_record_id:card.purchase_record_id??"",total_units:String(card.total_units),unit_label:card.unit_label,started_on:card.started_on,expires_on:card.expires_on??"",note:card.note??"",state:card.state}:blankCard());setEditing(true);setMessage(undefined);setError(undefined);}
  async function write(capability:"money.save_service_card"|"money.record_service_card_use",input:unknown,key:string){setPending(true);setError(undefined);setMessage(undefined);try{const receipt=await execute(capability,input,key);const id=String(receipt.actual_values.card_id);await load();await open(id);setMessage(capability==="money.save_service_card"?"次卡已保存":"使用记录已保存，余量已更新");}catch(value){fail(value);}finally{setPending(false);}}
  function save(event:FormEvent){event.preventDefault();void write("money.save_service_card",{...(selected?{card_id:selected.id,expected_revision:selected.revision,reason:"更新次卡资料"}:{}),name:form.name,merchant_name:form.merchant_name||undefined,purchase_record_id:form.purchase_record_id||undefined,total_units:Number(form.total_units),unit_label:form.unit_label,started_on:form.started_on,expires_on:form.expires_on||undefined,time_zone:selected?.time_zone??Intl.DateTimeFormat().resolvedOptions().timeZone,state:form.state,note:form.note||undefined},`service-card:${selected?.id??"new"}`);}
  function recordUse(event:FormEvent){event.preventDefault();if(!selected)return;void write("money.record_service_card_use",{card_id:selected.id,expected_revision:selected.revision,use_id:useId,occurred_on:date,units:Number(units),note:note||undefined,...(useId?{reason:"更正实际用卡记录"}:{})},`service-card-use:${selected.id}:${useId??"new"}`);}
  async function older(){if(!selected?.next_uses_before_id)return;const card=selected;try{const result=await get<{items:ServiceCard[]}>(`/api/money/service-cards?${new URLSearchParams({id:card.id,uses_before_id:card.next_uses_before_id!})}`);const next=result.items[0];if(next)setSelected(current=>current?.id===next.id?(current.revision===next.revision?{...next,uses:[...current.uses,...next.uses]}:next):current);}catch(value){fail(value);}}
  return <section className="service-cards-panel"><div className="section-heading"><div><h2>次卡与服务权益</h2><p>管理理发卡、洗车卡、课时包，按实际使用扣次。</p></div>{capabilities.has("money.save_service_card")&&<button disabled={pending} onClick={()=>edit()}>新增次卡</button>}</div>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
    <label>查找次卡<input value={query} placeholder="卡名或商家" onChange={event=>setQuery(event.target.value)}/></label>
    <div className="record-grid">{cards.map(card=><article className="stats-card" key={card.id}><h3>{card.name}</h3><p>剩余 <strong>{card.remaining_units}</strong> / {card.total_units} {card.unit_label}</p><small>已记录使用 {card.used_units} {card.unit_label} · {statusLabel[card.balance_status]}</small>{card.expires_on&&<p>有效期至 {card.expires_on}</p>}<button className="secondary" disabled={pending} onClick={()=>void open(card.id).catch(fail)}>查看 / 记录使用</button></article>)}</div>
    {!cards.length&&<p>还没有匹配的次卡。</p>}{cursor&&<button className="secondary" disabled={pending} onClick={()=>void load(cursor).catch(fail)}>更多次卡</button>}
    {editing&&<form className="compact-form" onSubmit={save}><h3>{selected?"编辑次卡":"新增次卡"}</h3>
      <label>卡名<input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>商家<input value={form.merchant_name} onChange={event=>setForm({...form,merchant_name:event.target.value})}/></label>
      <label>总次数<input required type="number" min="1" max="1000000" step="1" value={form.total_units} onChange={event=>setForm({...form,total_units:event.target.value})}/></label><label>单位<input required maxLength={8} value={form.unit_label} onChange={event=>setForm({...form,unit_label:event.target.value})}/></label>
      <label>开始日期<input required type="date" value={form.started_on} onChange={event=>setForm({...form,started_on:event.target.value})}/></label><label>有效期至（未知可留空）<input type="date" min={form.started_on} value={form.expires_on} onChange={event=>setForm({...form,expires_on:event.target.value})}/></label>
      <label>搜索原购买 / 支出<input value={purchaseQuery} onChange={event=>setPurchaseQuery(event.target.value)} placeholder="例如：理发"/></label><label>关联原记录<select value={form.purchase_record_id} onChange={event=>setForm({...form,purchase_record_id:event.target.value})}><option value="">不关联</option>{form.purchase_record_id&&!purchases.some(item=>item.record_id===form.purchase_record_id)&&<option value={form.purchase_record_id}>保留当前关联</option>}{purchases.map(item=><option key={item.id} value={item.record_id!}>{item.title} · {item.supporting} · {item.amount} {item.currency}</option>)}</select></label>
      <label>状态<select value={form.state} onChange={event=>setForm({...form,state:event.target.value as "active"|"closed"})}><option value="active">启用</option><option value="closed">关闭</option></select></label><label>备注<textarea value={form.note} onChange={event=>setForm({...form,note:event.target.value})}/></label>
      <p className="full">总次数按购买的服务填写；已经使用的次数在保存后单独记录。</p><button disabled={pending}>{pending?"保存中…":"保存次卡"}</button><button type="button" className="secondary" disabled={pending} onClick={()=>setEditing(false)}>取消</button>
    </form>}
    {selected&&!editing&&<article className="editor-card service-card-detail"><h3>{selected.name}</h3><p>{selected.merchant_name} · {statusLabel[selected.balance_status]} · 剩余 {selected.remaining_units} {selected.unit_label}</p><p>开始：{selected.started_on} · 有效期：{selected.expires_on??"未记录"}</p>{selected.note&&<p>{selected.note}</p>}
      {selected.purchase_record_id&&<a href={`?${new URLSearchParams({tab:"record",section:"timeline",domain:"money",kind:"money_entry",id:selected.purchase_record_id})}`}>查看关联购买 / 支出</a>}
      {capabilities.has("money.save_service_card")&&<button className="secondary" disabled={pending} onClick={()=>edit(selected)}>编辑次卡</button>}
      {capabilities.has("money.record_service_card_use")&&(selected.state==="active"||useId)&&<form className="compact-form" onSubmit={recordUse}><h3>{useId?"更正使用记录":"记录实际使用"}</h3><label>使用日期<input required type="date" min={selected.started_on} max={localToday()} value={date} onChange={event=>setDate(event.target.value)}/></label><label>使用{selected.unit_label}数<input required type="number" min="1" step="1" value={units} onChange={event=>setUnits(event.target.value)}/></label><label>备注<input value={note} onChange={event=>setNote(event.target.value)}/></label><button disabled={pending}>{pending?"保存中…":useId?"保存更正":"记录使用"}</button>{useId&&<button type="button" className="secondary" disabled={pending} onClick={resetUse}>取消更正</button>}</form>}
      <h4>使用明细</h4>{!selected.uses.length&&<p>暂无使用记录。</p>}{selected.uses.map(use=><div className="stats-card" key={use.id}><p>{use.occurred_on} · {use.units} {selected.unit_label} · {use.state==="voided"?"已撤销":"已使用"}</p>{use.note&&<p>{use.note}</p>}{capabilities.has("money.record_service_card_use")&&<div className="actions"><button className="secondary" disabled={pending} onClick={()=>{setUseId(use.id);setDate(use.occurred_on);setUnits(String(use.units));setNote(use.note??"");}}>{use.state==="voided"?"恢复 / 更正":"更正"}</button>{use.state==="active"&&<button className="secondary" disabled={pending} onClick={()=>void write("money.record_service_card_use",{card_id:selected.id,expected_revision:selected.revision,use_id:use.id,occurred_on:use.occurred_on,units:use.units,state:"voided",note:use.note??undefined,reason:"撤销误记的用卡"},`service-card-void:${use.id}`)}>撤销误扣</button>}</div>}</div>)}{selected.next_uses_before_id&&<button className="secondary" disabled={pending} onClick={()=>void older()}>更早使用记录</button>}
    </article>}
  </section>;
}
