import { useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import type { TravelWorkspace } from "./travel-workspace.js";

const localDate=()=>new Intl.DateTimeFormat("en-CA").format(new Date());
const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;

export function TravelBasicsPanel({workspace,selectedTrip,capabilities,execute,onChanged}:{workspace:TravelWorkspace|undefined;selectedTrip:string;capabilities:ReadonlySet<string>;execute:Execute;onChanged:()=>Promise<void>}) {
  const [mode,setMode]=useState<"trip"|"place"|"visit"|"reservation">("trip"),[title,setTitle]=useState(""),[start,setStart]=useState(localDate),[end,setEnd]=useState(localDate),[note,setNote]=useState(""),[placeName,setPlaceName]=useState(""),[address,setAddress]=useState(""),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState(""),[favorite,setFavorite]=useState(false),[reservationType,setReservationType]=useState("hotel"),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[confirmation,setConfirmation]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  async function submit(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{
    if(mode==="trip")await execute("travel.create_trip",{title:title.trim(),starts_on:start,ends_on:end,time_zone:zone(),...(note.trim()?{note:note.trim()}:{})},"travel:create-trip");
    else if(mode==="place")await execute("travel.save_place",{name:placeName.trim(),...(address.trim()?{address:address.trim()}:{}),...(latitude&&longitude?{latitude:Number(latitude),longitude:Number(longitude)}:{}),tags:[],favorite},"travel:save-place");
    else if(mode==="visit"){const place=workspace?.places.find(item=>item.name===placeName);await execute("travel.record_visit",{place_name:placeName.trim(),occurred_on:start,time_zone:zone(),visibility:"private",...(selectedTrip?{trip_id:selectedTrip}:{}),...(place?.latitude&&place.longitude?{latitude:Number(place.latitude),longitude:Number(place.longitude)}:{}),...(note.trim()?{note:note.trim()}:{})},"travel:record-visit");}
    else await execute("travel.add_reservation",{trip_id:selectedTrip,reservation_type:reservationType,title:title.trim(),state:"confirmed",visibility:"private",...(startsAt?{starts_at:new Date(startsAt).toISOString()}:{}),...(endsAt?{ends_at:new Date(endsAt).toISOString()}:{}),...(confirmation.trim()?{confirmation_code:confirmation.trim()}:{})},`travel:reservation:${selectedTrip}`);
    setTitle("");setNote("");setPlaceName("");setAddress("");setLatitude("");setLongitude("");setStartsAt("");setEndsAt("");setConfirmation("");await onChanged();
  }catch(caught){setError(caught instanceof Error?caught.message:"保存旅行事实失败");}finally{setPending(false);}}
  const enabled=mode==="trip"?capabilities.has("travel.create_trip"):mode==="place"?capabilities.has("travel.save_place"):mode==="visit"?capabilities.has("travel.record_visit"):capabilities.has("travel.add_reservation");
  return <section className="travel-basics"><div className="subtabs">{(["trip","place","visit","reservation"] as const).map(value=><button type="button" key={value} className={mode===value?"active":""} onClick={()=>setMode(value)}>{({trip:"新旅程",place:"收藏地点",visit:"实际到访",reservation:"预订"})[value]}</button>)}</div>{error&&<p className="inline-error">{error}</p>}<form className="compact-form" onSubmit={submit}>
    <h3>{({trip:"创建旅程",place:"收藏一个地点",visit:"记录实际到访",reservation:"添加旅行预订"})[mode]}</h3>
    {(mode==="trip"||mode==="reservation")&&<label>{mode==="trip"?"旅程名称":"预订名称"}<input required value={title} onChange={event=>setTitle(event.target.value)}/></label>}
    {(mode==="trip"||mode==="visit")&&<label>{mode==="trip"?"开始":"到访日"}<input type="date" required value={start} onChange={event=>{setStart(event.target.value);if(mode==="trip"&&end<event.target.value)setEnd(event.target.value);}}/></label>}
    {mode==="trip"&&<><label>结束<input type="date" required value={end} onChange={event=>setEnd(event.target.value)}/></label><label className="full">说明<textarea value={note} onChange={event=>setNote(event.target.value)}/></label></>}
    {(mode==="place"||mode==="visit")&&<label>{mode==="place"?"地点名称":"到访地点"}{mode==="visit"&&workspace?.places.length?<select required value={placeName} onChange={event=>setPlaceName(event.target.value)}><option value="">请选择</option>{workspace.places.map(place=><option key={place.id} value={place.name}>{place.favorite?"★ ":""}{place.name}</option>)}</select>:<input required value={placeName} onChange={event=>setPlaceName(event.target.value)}/>}</label>}
    {mode==="place"&&<><label>地址<input value={address} onChange={event=>setAddress(event.target.value)}/></label><label>纬度（可选）<input inputMode="decimal" value={latitude} onChange={event=>setLatitude(event.target.value)}/></label><label>经度（可选）<input inputMode="decimal" value={longitude} onChange={event=>setLongitude(event.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={favorite} onChange={event=>setFavorite(event.target.checked)}/>收藏为常用地点</label></>}
    {mode==="visit"&&<label className="full">到访备注<textarea value={note} onChange={event=>setNote(event.target.value)}/></label>}
    {mode==="reservation"&&<><label>旅程<select required value={selectedTrip} disabled><option value="">请先在上方选择旅程</option>{workspace?.trips.map(trip=><option key={trip.id} value={trip.id}>{trip.title}</option>)}</select></label><label>类型<select value={reservationType} onChange={event=>setReservationType(event.target.value)}><option value="flight">航班</option><option value="rail">铁路</option><option value="hotel">住宿</option><option value="restaurant">餐厅</option><option value="activity">活动</option><option value="other">其他</option></select></label><label>开始时间<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>结束时间<input type="datetime-local" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label><label>确认号（私密）<input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label></>}
    <button disabled={pending||!enabled||(mode==="reservation"&&!selectedTrip)||(mode==="place"&&Boolean(latitude)!==Boolean(longitude))}>{pending?"保存中…":"直接保存"}</button>
  </form></section>;
}
