import { useEffect, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import type { TravelDayPlan, TravelWorkspace } from "./travel-workspace.js";
import { formatInTimeZone, parseInTimeZone } from "./travel-time.js";

type DraftStop={stop_id?:string;title:string;starts_at:string;place_id:string;note:string};
const localDate=()=>new Intl.DateTimeFormat("en-CA").format(new Date());
const emptyStop=():DraftStop=>({title:"",starts_at:"",place_id:"",note:""});

export function TravelPlanningPanel({workspace,selectedTrip,capabilities,execute,onChanged}:{workspace:TravelWorkspace|undefined;selectedTrip:string;capabilities:ReadonlySet<string>;execute:Execute;onChanged:()=>Promise<void>}){
  const[day,setDay]=useState(localDate),[editing,setEditing]=useState<TravelDayPlan>(),[stops,setStops]=useState<DraftStop[]>([emptyStop()]),[label,setLabel]=useState(""),[publishNote,setPublishNote]=useState(""),[mode,setMode]=useState("rail"),[origin,setOrigin]=useState(""),[destination,setDestination]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[distance,setDistance]=useState(""),[segmentNote,setSegmentNote]=useState(""),[editor,setEditor]=useState<"day"|"publish"|"segment">(),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  const trip=workspace?.trips.find(item=>item.id===selectedTrip);
  useEffect(()=>{if(trip)setDay(current=>current<trip.starts_on||current>trip.ends_on?trip.starts_on:current);},[selectedTrip,workspace?.as_of]);
  function editDay(plan?:TravelDayPlan){setEditor("day");setEditing(plan);setDay(plan?.plan_date??trip?.starts_on??localDate());setStops(plan?.items.map(item=>({...(item.stop_id?{stop_id:item.stop_id}:{}),title:item.title,starts_at:formatInTimeZone(item.starts_at,trip?.time_zone??Intl.DateTimeFormat().resolvedOptions().timeZone),place_id:item.place_id??"",note:item.note??""}))??[emptyStop()]);}
  async function saveDay(event:FormEvent){event.preventDefault();if(!selectedTrip||!trip)return;setPending(true);setError(undefined);try{await execute("travel.set_day_plan",{trip_id:selectedTrip,plan_date:day,...(editing?{expected_revision:editing.revision}:{}),items:stops.map(item=>({...((item.stop_id)?{stop_id:item.stop_id}:{}),title:item.title.trim(),...(item.starts_at?{starts_at:parseInTimeZone(item.starts_at,trip.time_zone)}:{}),...(item.place_id?{place_id:item.place_id}:{}),...(item.note.trim()?{note:item.note.trim()}: {})}))},`travel:day-plan:${selectedTrip}:${day}`);setEditor(undefined);await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"日程保存失败");}finally{setPending(false);}}
  async function publish(){if(!selectedTrip)return;setPending(true);setError(undefined);try{await execute("travel.publish_plan",{trip_id:selectedTrip,...(label.trim()?{label:label.trim()}:{}),...(publishNote.trim()?{note:publishNote.trim()}: {})},`travel:publish:${selectedTrip}`);setLabel("");setPublishNote("");setEditor(undefined);await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"日程发布失败");}finally{setPending(false);}}
  async function saveSegment(event:FormEvent){event.preventDefault();if(!selectedTrip||!trip)return;setPending(true);setError(undefined);try{await execute("travel.record_segment",{trip_id:selectedTrip,mode,origin:origin.trim(),destination:destination.trim(),...(startsAt?{starts_at:parseInTimeZone(startsAt,trip.time_zone)}:{}),...(endsAt?{ends_at:parseInTimeZone(endsAt,trip.time_zone)}:{}),...(distance.trim()?{distance_km:distance.trim()}:{}),...(segmentNote.trim()?{note:segmentNote.trim()}:{}),visibility:"private"},`travel:segment:${selectedTrip}`);setOrigin("");setDestination("");setStartsAt("");setEndsAt("");setDistance("");setSegmentNote("");setEditor(undefined);await onChanged();}catch(caught){setError(caught instanceof Error?caught.message:"行程段保存失败");}finally{setPending(false);}}
  if(!trip)return <section className="travel-planning"><h3>日程与交通</h3><p>先选择一个旅程，再编排每日停留点和实际交通段。</p></section>;
  return <section className={`travel-planning editor-${editor??"none"}`}><div className="panel-heading"><div><span className="eyebrow">ITINERARY</span><h2>每日计划与交通段</h2></div><div className="editor-launchers"><button type="button" className={editor==="day"?"active":"secondary"} onClick={()=>editor==="day"?setEditor(undefined):editDay()}>＋ 安排一天</button><button type="button" className={editor==="publish"?"active":"secondary"} onClick={()=>setEditor(value=>value==="publish"?undefined:"publish")}>发布版本</button><button type="button" className={editor==="segment"?"active":"secondary"} onClick={()=>setEditor(value=>value==="segment"?undefined:"segment")}>＋ 实际交通</button></div></div>{workspace?.day_plans.length?<label className="plan-picker">已有日程<select value={editing?.id??""} onChange={event=>editDay(workspace.day_plans.find(item=>item.id===event.target.value))}><option value="">选择日期查看或编辑</option>{workspace.day_plans.map(plan=><option key={plan.id} value={plan.id}>{plan.plan_date} · {plan.items.length} 站 · v{plan.revision}</option>)}</select></label>:<p>还没有安排每日停留点。</p>}{error&&<p className="inline-error">{error}</p>}
    <div className="travel-grid"><form className="travel-form" onSubmit={saveDay}><h3>{editing?"编辑当日安排":"编排一天"}</h3><p className="form-context">所有时间按旅程时区 {trip.time_zone} 保存。</p><label>日期<input type="date" min={trip.starts_on} max={trip.ends_on} required value={day} disabled={Boolean(editing)} onChange={event=>setDay(event.target.value)}/></label><ol className="meal-entry-list">{stops.map((stop,index)=><li key={stop.stop_id??index}><div><label>停留点标题<input required value={stop.title} onChange={event=>setStops(current=>current.map((item,position)=>position===index?{...item,title:event.target.value}:item))}/></label><label>开始时间（{trip.time_zone}，可选）<input type="datetime-local" value={stop.starts_at} onChange={event=>setStops(current=>current.map((item,position)=>position===index?{...item,starts_at:event.target.value}:item))}/></label><label>地点（可选）<select value={stop.place_id} onChange={event=>setStops(current=>current.map((item,position)=>position===index?{...item,place_id:event.target.value}:item))}><option value="">不关联地点</option>{workspace?.places.map(place=><option key={place.id} value={place.id}>{place.name}</option>)}</select></label><label>备注（可选）<input value={stop.note} onChange={event=>setStops(current=>current.map((item,position)=>position===index?{...item,note:event.target.value}:item))}/></label></div><button type="button" className="text-button" disabled={stops.length===1} onClick={()=>setStops(current=>current.filter((_,position)=>position!==index))}>移除</button></li>)}</ol><div className="actions"><button type="button" className="secondary" onClick={()=>setStops(current=>[...current,emptyStop()])}>添加停留点</button><button disabled={pending||!capabilities.has("travel.set_day_plan")}>{pending?"保存中…":"保存安排"}</button></div></form>
      <section><form className="travel-form" onSubmit={event=>{event.preventDefault();void publish();}}><h3>发布不可变版本</h3><label>版本名称（可选）<input value={label} onChange={event=>setLabel(event.target.value)}/></label><label>说明（可选）<textarea value={publishNote} onChange={event=>setPublishNote(event.target.value)}/></label><button disabled={pending||!workspace?.day_plans.length||!capabilities.has("travel.publish_plan")}>发布当前全部日程</button><small>在途模式只绑定这次发布的快照；之后修改草稿不会偷偷改变正在执行的行程。</small></form>
      <form className="travel-form" onSubmit={saveSegment}><h3>记录实际交通段</h3><label>方式<select value={mode} onChange={event=>setMode(event.target.value)}>{Object.entries({walk:"步行",bike:"骑行",taxi:"出租车",car:"驾车",bus:"公交",metro:"地铁",rail:"铁路",flight:"航班",ferry:"轮渡",other:"其他"}).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><label>出发地<input required value={origin} onChange={event=>setOrigin(event.target.value)}/></label><label>目的地<input required value={destination} onChange={event=>setDestination(event.target.value)}/></label><label>开始时间<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>结束时间<input type="datetime-local" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label><label>距离 km（可选）<input inputMode="decimal" value={distance} onChange={event=>setDistance(event.target.value)}/></label><label>备注（可选）<textarea value={segmentNote} onChange={event=>setSegmentNote(event.target.value)}/></label><button disabled={pending||!capabilities.has("travel.record_segment")}>保存交通事实</button></form></section></div>
    {workspace?.segments.length?<ul className="foreign-list">{workspace.segments.map(segment=><li key={segment.id}><b>{segment.origin} → {segment.destination}</b><span>{segment.mode}{segment.distance_km?` · ${segment.distance_km} km`:""}</span><small>{segment.starts_at?new Date(segment.starts_at).toLocaleString():"未填写时间"} · v{segment.revision}</small></li>)}</ul>:null}
  </section>;
}
