import { useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import type { TravelChecklist as Checklist } from "./travel-workspace.js";

export function TravelChecklist({tripId,checklist,canWrite,execute,onChanged}:{tripId:string;checklist:Checklist|null;canWrite:boolean;execute:Execute;onChanged:()=>Promise<void>}){
  const items=checklist?.items??[],[title,setTitle]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  async function save(next:typeof items){setPending(true);setError(undefined);try{await execute("travel.set_checklist",{trip_id:tripId,...(checklist?{expected_revision:checklist.revision}:{}),items:next.map(item=>({...item,id:item.id||undefined,note:item.note??undefined})),reason:"网页更新旅程清单"},`travel:checklist:${tripId}`);await onChanged();return true;}catch(caught){setError(caught instanceof Error?caught.message:"清单保存失败");return false;}finally{setPending(false);}}
  async function add(event:FormEvent){event.preventDefault();if(!title.trim())return;if(await save([...items,{id:"",title:title.trim(),state:"needed" as const,note:null}]))setTitle("");}
  return<section className="editor-card"><h3>旅程清单</h3><p>准备状态只属于计划，不会生成实际到访。</p>{error&&<p className="inline-error">{error}</p>}{items.length?<ul>{items.map((item,index)=><li key={item.id||index}><label><input type="checkbox" checked={item.state==="packed"} disabled={!canWrite||pending} onChange={event=>void save(items.map((current,position)=>position===index?{...current,state:event.target.checked?"packed" as const:"needed" as const}:current))}/>{item.title}</label><span> · {item.state==="packed"?"已备好":item.state==="skipped"?"无需准备":"待准备"}</span>{canWrite&&<button type="button" className="secondary" disabled={pending} onClick={()=>void save(items.filter((_,position)=>position!==index))}>移除</button>}</li>)}</ul>:<p>清单还没有项目。</p>}{canWrite&&<form onSubmit={add}><label>准备事项<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={200}/></label><button disabled={pending||!title.trim()}>加入清单</button></form>}</section>;
}
