import { itineraryDates, selectedItineraryDate, placesForDay } from "./travel-workspace.js";
import { formatInTimeZone } from "./travel-time.js";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import type { Execute } from "./command-controller.js";
import { nextTravelStop, type TravelMap, type TravelWorkspace } from "./travel-workspace.js";
import { TravelBasicsPanel } from "./TravelBasicsPanel.js";
import { TravelPlanningPanel } from "./TravelPlanningPanel.js";
import { TravelMapSurface } from "./TravelMapSurface.js";

const statusLabel={candidate:"候选",anchor:"锚点",planned:"已排入",visited:"标记去过"} as const;
async function readJson<T>(response:Response):Promise<T>{const value=await response.json() as T&{message?:string};if(!response.ok)throw new Error(value.message??`HTTP ${response.status}`);return value;}
function base64Utf8(value:string):string{const bytes=new TextEncoder().encode(value);let binary="";for(let offset=0;offset<bytes.length;offset+=16_384)binary+=String.fromCharCode(...bytes.subarray(offset,offset+16_384));return btoa(binary);}
function saveExport(value:{content:string;mime_type:string;filename:string}){const host=window.ShadowLifeHost;if(host?.saveExport){host.saveExport(value.filename,value.mime_type,base64Utf8(value.content));return;}const url=URL.createObjectURL(new Blob([value.content],{type:value.mime_type})),anchor=document.createElement("a");anchor.href=url;anchor.download=value.filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);}

export function TravelPanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){
  const[workspace,setWorkspace]=useState<TravelWorkspace>(),[selectedTrip,setSelectedTrip]=useState(()=>new URLSearchParams(location.search).get("trip")??""),[selectedMap,setSelectedMap]=useState<TravelMap>(),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[chosen,setChosen]=useState<Record<string,keyof typeof statusLabel>>({}),[gpx,setGpx]=useState(""),[trackName,setTrackName]=useState(""),[bundle,setBundle]=useState(""),[bundlePreview,setBundlePreview]=useState<{sha256:string;trip:{title:string;starts_on:string;ends_on:string};counts:Record<string,number>}>(),[showTools,setShowTools]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<string>();
  const [daySelection,setDaySelection]=useState<string>(),[mapScope,setMapScope]=useState<"day"|"all">("day");
  const requestSequence=useRef(0),initialized=useRef(false);
  async function load(tripId=selectedTrip,allowDefault=false){const sequence=++requestSequence.current;try{const query=tripId?`?trip_id=${encodeURIComponent(tripId)}`:"",value=await readJson<TravelWorkspace>(await fetch(`/api/travel/workspace${query}`,{headers}));if(sequence!==requestSequence.current)return;setError(undefined);setWorkspace(value);if(allowDefault)initialized.current=true;if(allowDefault&&!tripId&&value.trips[0])setSelectedTrip(value.trips[0].id);}catch(caught){if(sequence===requestSequence.current)setError(caught instanceof Error?caught.message:"旅行工作台读取失败");}}
  useEffect(()=>{const allowDefault=!initialized.current;void load(selectedTrip,allowDefault);},[selectedTrip]);
  useEffect(()=>{const query=new URLSearchParams(location.search);if(selectedTrip)query.set("trip",selectedTrip);else query.delete("trip");const suffix=query.toString();history.replaceState(null,"",`${location.pathname}${suffix?`?${suffix}`:""}${location.hash}`);},[selectedTrip]);
  function editMap(map?:TravelMap){setShowTools(Boolean(map));setSelectedMap(map);setTitle(map?.title??"");setDescription(map?.description??"");setChosen(Object.fromEntries((map?.items??[]).map(item=>[item.place_id,item.status])));}
  async function saveMap(event:FormEvent){event.preventDefault();setPending(true);setError(undefined);try{await execute("travel.save_map",{...(selectedMap?{map_id:selectedMap.id,expected_revision:selectedMap.revision,reason:"网页工作台更新"}:{}),title,description:description.trim()||undefined,state:selectedMap?.state??"active",items:Object.entries(chosen).map(([place_id,status])=>({place_id,status}))},`travel:map:${selectedMap?.id??"new"}`);editMap();await load();}catch(caught){setError(caught instanceof Error?caught.message:"地图保存失败");}finally{setPending(false);}}
  async function importTrack(event:FormEvent){event.preventDefault();if(!selectedTrip)return;setPending(true);setError(undefined);try{await execute("travel.import_track",{trip_id:selectedTrip,name:trackName.trim()||undefined,gpx},`travel:track:${selectedTrip}`);setGpx("");setTrackName("");await load();}catch(caught){setError(caught instanceof Error?caught.message:"轨迹导入失败");}finally{setPending(false);}}
  async function startRun(){const trip=workspace?.trips.find(item=>item.id===selectedTrip);if(!trip?.latest_plan_version_id)return;setPending(true);try{await execute("travel.start_run",{trip_id:trip.id,plan_version_id:trip.latest_plan_version_id},`travel:run:${trip.id}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"开始行程失败");}finally{setPending(false);}}
  async function finishStop(state:"arrived"|"skipped"){const run=workspace?.active_run,stop=nextTravelStop(run??null);if(!run||!stop)return;setPending(true);try{await execute("travel.set_stop_outcome",{run_id:run.id,stop_id:stop.stop_id,state},`travel:stop:${run.id}:${stop.stop_id}`);await load();}catch(caught){setError(caught instanceof Error?caught.message:"停留点更新失败");}finally{setPending(false);}}
  async function exportTrip(format:"bundle"|"gpx"|"ics"){if(!selectedTrip)return;try{saveExport(await readJson<{content:string;mime_type:string;filename:string}>(await fetch(`/api/travel/trips/${encodeURIComponent(selectedTrip)}/export?format=${format}`,{headers})));}catch(caught){setError(caught instanceof Error?caught.message:"导出失败");}}
  async function previewBundle(){setPending(true);setError(undefined);try{setBundlePreview(await readJson(await fetch("/api/travel/portable/preview",{method:"POST",headers:{"content-type":"application/json",...(headers as Record<string,string>)},body:JSON.stringify({format:"bundle",content:bundle})})));}catch(caught){setBundlePreview(undefined);setError(caught instanceof Error?caught.message:"Bundle 预检失败");}finally{setPending(false);}}
  async function restoreBundle(){if(!bundlePreview)return;setPending(true);setError(undefined);try{const result=await execute("travel.restore_bundle",{bundle},`travel:restore:${bundlePreview.sha256}`),tripId=String(result.actual_values.trip_id);setBundle("");setBundlePreview(undefined);setSelectedTrip(tripId);await load(tripId);}catch(caught){setError(caught instanceof Error?caught.message:"Bundle 恢复失败");}finally{setPending(false);}}
  const selectedPlaces=useMemo(()=>{const places=workspace?.places??[],chosenIds=Object.keys(chosen);return chosenIds.length?places.filter(place=>place.id in chosen):places;},[workspace,chosen]),next=nextTravelStop(workspace?.active_run??null),trip=workspace?.trips.find(item=>item.id===selectedTrip);
  const dates=trip?itineraryDates(trip,workspace?.day_plans??[]):[],selectedDate=selectedItineraryDate(dates,daySelection,formatInTimeZone(new Date(),trip?.time_zone??"UTC").slice(0,10));
  const mapPlaces=trip&&mapScope==="day"&&!showTools?placesForDay(workspace?.places??[],workspace?.day_plans.find(plan=>plan.plan_date===selectedDate)):selectedPlaces;
  return <section className={`travel-panel ${showTools?"show-tools":""}`}><div className="panel-heading"><div><span className="eyebrow">TRAVEL</span><h2>我的旅行</h2></div><div className="panel-actions"><label>当前旅程<select value={selectedTrip} onChange={event=>{setSelectedTrip(event.target.value);setDaySelection(undefined);}}><option value="">仅看地点收集</option>{workspace?.trips.map(item=><option key={item.id} value={item.id}>{item.title} · {item.starts_on}</option>)}</select></label><button type="button" className="text-button" onClick={()=>{if(showTools)editMap();else setShowTools(true);}}>{showTools?"收起工具":"地图与导入工具"}</button></div></div>{error&&<p className="inline-error">{error}</p>}
    <TravelBasicsPanel workspace={workspace} selectedTrip={selectedTrip} capabilities={capabilities} execute={execute} onChanged={()=>load(selectedTrip)}/>
    <div className="travel-itinerary-workspace"><TravelPlanningPanel key={selectedTrip} selectedDate={selectedDate} onSelectDate={setDaySelection} workspace={workspace} selectedTrip={selectedTrip} capabilities={capabilities} execute={execute} onChanged={()=>load(selectedTrip)}/>
    <div className="travel-grid"><section className="map-board"><div className="panel-heading"><h3>{selectedMap?.title??(mapScope==="day"&&trip?`${selectedDate} 地图`:"旅行地图")}</h3>{trip&&<select aria-label="地图范围" value={mapScope} onChange={event=>setMapScope(event.target.value as "day"|"all")}><option value="day">当天地点</option><option value="all">全部地点与轨迹</option></select>}</div><TravelMapSurface places={mapPlaces} tracks={mapScope==="day"&&trip&&!showTools?[]:workspace?.tracks??[]}/>{trip&&mapScope==="day"&&!mapPlaces.length&&<p>当天尚未关联收藏地点。编辑点位后可在地图上查看。</p>}<small>显示已保存地点与导入轨迹；地图展示不会自动生成到访记录。</small></section>
      <section className="transit-card"><h3>在途模式</h3>{!trip?<p>选择一个旅程查看已发布版本。</p>:workspace?.active_run?<>{next?<><b>{next.plan_date} · 下一站</b><h4>{next.title}</h4>{next.starts_at&&<p>{formatInTimeZone(next.starts_at,trip.time_zone).replace("T"," ")}</p>}<div className="actions"><button disabled={pending} onClick={()=>void finishStop("arrived")}>已到达</button><button className="secondary" disabled={pending} onClick={()=>void finishStop("skipped")}>跳过</button></div></>:<p>这个运行的停留点都已处理。</p>}</>:trip.latest_plan_version_id?<button disabled={pending||!capabilities.has("travel.start_run")} onClick={()=>void startRun()}>按最新发布版开始</button>:<p>尚无已发布计划，先发布日程再开始。</p>}<div className="export-actions"><button type="button" onClick={()=>void exportTrip("bundle")}>Bundle</button><button type="button" onClick={()=>void exportTrip("gpx")}>GPX</button><button type="button" onClick={()=>void exportTrip("ics")}>ICS</button></div></section>
    </div>
    </div><div className="travel-grid"><form className="travel-form" onSubmit={saveMap}><h3>{selectedMap?"编辑主题地图":"新建主题地图"}</h3><label>名称<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>说明<textarea value={description} onChange={event=>setDescription(event.target.value)}/></label><fieldset><legend>地点与收集状态</legend>{workspace?.places.map(place=><div className="place-choice" key={place.id}><label><input type="checkbox" checked={place.id in chosen} onChange={event=>setChosen(current=>{const next={...current};if(event.target.checked)next[place.id]="candidate";else delete next[place.id];return next;})}/><span>{place.favorite?"★ ":""}{place.name}</span></label>{place.id in chosen&&<select aria-label={`${place.name}状态`} value={chosen[place.id]} onChange={event=>setChosen(current=>({...current,[place.id]:event.target.value as keyof typeof statusLabel}))}>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>}</div>)}</fieldset><small>这里的“标记去过”只属于个人地图整理，不会写入 Visit；实际到访必须单独记录。</small><div className="actions"><button disabled={pending}>{pending?"保存中…":"保存地图"}</button>{selectedMap&&<button type="button" className="secondary" onClick={()=>editMap()}>取消编辑</button>}</div></form>
      <section className="map-list"><h3>主题地图</h3>{!workspace?.maps.length?<p>还没有主题地图。</p>:<ul>{workspace.maps.map(map=><li key={map.id}><button type="button" onClick={()=>editMap(map)}><b>{map.title}</b><span>{map.items.length} 个地点 · 修订 {map.revision}</span></button></li>)}</ul>}<form className="track-form" onSubmit={importTrack}><h3>导入 GPX 轨迹</h3><label>轨迹名称（可选）<input value={trackName} onChange={event=>setTrackName(event.target.value)}/></label><label>GPX 内容<textarea required value={gpx} onChange={event=>setGpx(event.target.value)} placeholder="粘贴不超过 900 KB 的 GPX"/></label><button disabled={pending||!selectedTrip||!capabilities.has("travel.import_track")}>导入但不生成到访</button>{workspace?.tracks.map(track=><small key={track.id}>{track.name} · {track.points.length} 点 · {track.original_sha256.slice(0,12)}</small>)}</form><section className="bundle-restore"><h3>恢复 Travel Bundle</h3><label>Bundle JSON<textarea value={bundle} onChange={event=>{setBundle(event.target.value);setBundlePreview(undefined);}} placeholder="先粘贴并预检，再恢复为新副本"/></label>{bundlePreview&&<div className="import-summary"><b>{bundlePreview.trip.title}</b><span>{bundlePreview.trip.starts_on} 至 {bundlePreview.trip.ends_on}</span><code>{bundlePreview.sha256.slice(0,16)}</code><small>{Object.entries(bundlePreview.counts).map(([key,value])=>`${key} ${value}`).join(" · ")}</small></div>}<div className="actions"><button type="button" disabled={pending||!bundle||!capabilities.has("travel.preview_portable")} onClick={()=>void previewBundle()}>只读预检</button><button type="button" disabled={pending||!bundlePreview||!capabilities.has("travel.restore_bundle")} onClick={()=>void restoreBundle()}>恢复新副本</button></div><small>恢复不覆盖原旅程；成员、运行、来源和票价关联不会被臆造。</small></section></section>
    </div>
  </section>;
}
