import {PurchaseItemRepair} from "./PurchaseItemRepair.js";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { UseCycleStatus } from "@shadow/contracts";
import type { Execute } from "./command-controller.js";

const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:zone(),year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const decimal=(v:string)=>v.replace(/(\.\d*?[1-9])0+$|\.0+$/u,"$1");
const optional=(v:string)=>v.trim()||undefined;
const unitLabel=(cycle:UseCycleStatus)=>cycle.quantity_label||({g:"克",ml:"毫升",count:"个"}[cycle.quantity_unit??"count"]);
const blank=()=>({item_name:"",started_on:today(),usage_state:"pending" as "pending"|"in_use",initial_quantity:"",quantity_unit:"count" as "g"|"ml"|"count",quantity_label:"",expected_daily_usage:"",match_mode:"none" as "none"|"exact_name"|"food_ref",match_value:"",replenish_threshold:"",replenish_lead_days:"",reminder_enabled:false,note:""});
function existingInput(c:UseCycleStatus){return{cycle_id:c.id,expected_revision:c.revision,purchase_record_id:c.purchase_record_id??undefined,purchase_item_id:c.purchase_item_id??undefined,item_name:c.item_name,started_on:c.started_on,ended_on:c.ended_on??undefined,state:c.state,usage_state:c.usage_state??"in_use",initial_quantity:c.initial_quantity??undefined,quantity_unit:c.quantity_unit??undefined,quantity_label:c.quantity_label??undefined,expected_daily_usage:c.expected_daily_usage??undefined,match_mode:c.match_mode,match_value:c.match_value??undefined,replenish_threshold:c.replenish_threshold??undefined,replenish_lead_days:c.replenish_lead_days??undefined,reminder_enabled:c.reminder_enabled,time_zone:c.time_zone,note:c.note??undefined};}
export function UseCyclePanel({headers,capabilities,execute}:{headers:HeadersInit;capabilities:ReadonlySet<string>;execute:Execute}){
  const [cycles,setCycles]=useState<UseCycleStatus[]>([]),[error,setError]=useState<string>(),[message,setMessage]=useState<string>(),[pending,setPending]=useState(false),[truncated,setTruncated]=useState(false);
  const [editing,setEditing]=useState<UseCycleStatus>(),[form,setForm]=useState(blank),[filter,setFilter]=useState("open");
  const [using,setUsing]=useState<UseCycleStatus>(),[quantity,setQuantity]=useState("1"),[date,setDate]=useState(today()),[note,setNote]=useState("");
  const editor=useRef<HTMLFormElement>(null),useForm=useRef<HTMLFormElement>(null);
  const canWrite=capabilities.has("money.set_use_cycle"),canUse=capabilities.has("money.record_consumable_use");
  async function load(){const response=await fetch(`/api/money/planning?period=${today().slice(0,7)}`,{headers});if(!response.ok)throw new Error(`读取失败（${response.status}）`);const value=await response.json() as {use_cycles:UseCycleStatus[];truncated:{use_cycles:boolean}};setCycles(value.use_cycles);setTruncated(value.truncated.use_cycles);}
  useEffect(()=>{void load().catch(e=>setError(String(e)));},[]);
  async function perform(action:()=>Promise<unknown>,success:string){setPending(true);setError(undefined);try{await action();setMessage(success);await load();}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setPending(false);}}
  function edit(c?:UseCycleStatus){setEditing(c);setForm(c?{item_name:c.item_name,started_on:c.started_on,usage_state:c.usage_state??"in_use",initial_quantity:c.initial_quantity??"",quantity_unit:c.quantity_unit??"count",quantity_label:c.quantity_label??"",expected_daily_usage:c.expected_daily_usage??"",match_mode:c.match_mode,match_value:c.match_value??"",replenish_threshold:c.replenish_threshold??"",replenish_lead_days:c.replenish_lead_days===null?"":String(c.replenish_lead_days),reminder_enabled:c.reminder_enabled,note:c.note??""}:blank());requestAnimationFrame(()=>editor.current?.scrollIntoView({block:"start"}));}
  const field=(key:keyof ReturnType<typeof blank>,value:string|boolean)=>setForm(f=>({...f,[key]:value}));
  async function save(e:FormEvent){e.preventDefault();await perform(async()=>{await execute("money.set_use_cycle",{...(editing?existingInput(editing):{state:"active",time_zone:zone()}),...form,initial_quantity:optional(form.initial_quantity),quantity_label:form.quantity_unit==="count"?optional(form.quantity_label):undefined,expected_daily_usage:optional(form.expected_daily_usage),match_value:optional(form.match_value),replenish_threshold:optional(form.replenish_threshold),replenish_lead_days:form.replenish_lead_days?Number(form.replenish_lead_days):undefined,note:optional(form.note)},`consumable:${editing?.id??form.item_name}`);setEditing(undefined);setForm(blank());},"消耗品已保存");}
  async function use(e:FormEvent){e.preventDefault();if(!using)return;await perform(async()=>{await execute("money.record_consumable_use",{cycle_id:using.id,expected_revision:using.revision,occurred_on:date,quantity,note:optional(note)},`consumable-use:${using.id}`);setUsing(undefined);},"已记录实际使用，原购买支出保持不变");}
  const shown=cycles.filter(c=>filter==="all"||filter==="open"&&c.state==="active"||filter==="pending"&&c.state==="active"&&c.usage_state==="pending");
  return <section className="consumables-panel"><div className="panel-heading"><div><h2>消耗品</h2><p>待启用 → 使用中 → 用完。估算和实际使用分别显示。</p></div><select aria-label="消耗品筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">待启用与使用中</option><option value="pending">待启用</option><option value="all">含本月结束的周期</option></select></div>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}{truncated&&<p>当前展示最近 100 个周期，可让助手按购买记录查找更早记录。</p>}
    <div className="record-grid">{shown.map(c=><article className="stats-card" key={c.id}><div className="panel-heading"><h3>{c.item_name}</h3><span>{c.state!=="active"?({completed:"已用完",discarded:"已丢弃",replenished:"已补货"}[c.state]):c.usage_state==="pending"?"待启用 / 未记开封":"使用中"}</span></div>
      {c.usage_state==="pending"?<p>尚未确认启用日期与当前余量{c.initial_quantity?` · 购买规格 ${decimal(c.initial_quantity)} ${unitLabel(c)}`:""}</p>:<><p>{c.remaining_quantity===null?"余量未知，请补充本批次数量":`按已记使用剩余 ${c.remaining_quantity} ${unitLabel(c)}`}</p><small>已确认使用 {c.consumed_quantity??"未知"} {unitLabel(c)}{c.match_mode!=="none"?` · 来自 ${c.matched_intakes} 条饮食记录`:""}</small>{c.estimated_remaining_quantity!==null&&c.estimated_remaining_quantity!==undefined&&<p>按日用量估算剩余 {c.estimated_remaining_quantity} {unitLabel(c)}（非实际盘点）</p>}{c.projected_depletion_on&&<p>预计耗尽：{c.projected_depletion_on}</p>}</>}
      {c.expected_daily_usage&&<small>预计每天 {decimal(c.expected_daily_usage)} {unitLabel(c)}</small>}{c.note&&<p>{c.note}</p>}{c.ignored_incompatible_intakes>0&&<p>{c.ignored_incompatible_intakes} 条饮食单位不兼容，未扣减。</p>}
      {c.purchase_record_id&&<a href={`?tab=record&section=timeline&domain=money&kind=money_entry&id=${encodeURIComponent(c.purchase_record_id)}&record_id=${encodeURIComponent(c.purchase_record_id)}`}>查看购买来源</a>}
      <div className="actions">{canWrite&&<button className="secondary" onClick={()=>edit(c)}>{c.usage_state==="pending"?"填写启用日期 / 规格":"编辑规格"}</button>}{canUse&&c.state==="active"&&c.usage_state!=="pending"&&c.match_mode==="none"&&c.quantity_unit&&<button disabled={pending} onClick={()=>{setUsing(c);setDate(today());setQuantity("1");setNote("");requestAnimationFrame(()=>useForm.current?.scrollIntoView({block:"start"}));}}>记一次使用</button>}{canWrite&&c.state==="active"&&<button className="secondary" disabled={pending} onClick={()=>void perform(()=>execute("money.set_use_cycle",{...existingInput(c),state:"completed",ended_on:today()},`consumable-close:${c.id}`),"本批次已结束")}>已用完</button>}</div>
      {!!c.uses?.length&&<details><summary>使用明细（最近 {c.uses.length} 条）</summary><ul>{c.uses.map(u=><li key={u.id}>{u.occurred_on} · {decimal(u.quantity)} {unitLabel(c)}{u.state==="voided"?" · 已撤销":""}{u.note?` · ${u.note}`:""}{canUse&&u.state==="active"&&<button className="secondary" disabled={pending} onClick={()=>void perform(()=>execute("money.record_consumable_use",{cycle_id:c.id,expected_revision:c.revision,use_id:u.id,occurred_on:u.occurred_on,quantity:u.quantity,state:"voided",reason:"用户撤销误记的消耗"},`consumable-void:${u.id}`),"已撤销这次消耗")}>撤销误记</button>}</li>)}</ul>{c.uses_truncated&&<small>还有更早记录；余量按全部有效记录计算。</small>}</details>}
    </article>)}</div>{!shown.length&&<p>还没有这一类消耗品。购买时可让助手同时建立待使用记录。</p>}
    {using&&<form ref={useForm} className="compact-form" onSubmit={use}><h3>记录使用：{using.item_name}</h3><label>实际使用日期<input required type="date" min={using.started_on} max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>使用数量（{unitLabel(using)}）<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>备注<input value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={pending}>记录使用</button><button className="secondary" type="button" onClick={()=>setUsing(undefined)}>取消</button></form>}
    {canWrite&&<form ref={editor} className="compact-form" onSubmit={save}><h3>{editing?`编辑：${editing.item_name}`:"新建消耗品"}</h3>{editing&&<button className="secondary" type="button" onClick={()=>edit()}>改为新建</button>}<label>名称<input required value={form.item_name} onChange={e=>field("item_name",e.target.value)}/></label><label>使用状态<select value={form.usage_state} onChange={e=>field("usage_state",e.target.value)}><option value="pending">待启用 / 未知开封情况</option><option value="in_use">已启用</option></select></label><label>{form.usage_state==="pending"?"购买 / 登记日期":"实际启用日期"}<input required type="date" max={today()} value={form.started_on} onChange={e=>field("started_on",e.target.value)}/></label><label>本批次初始数量<input inputMode="decimal" placeholder="未知可留空" value={form.initial_quantity} onChange={e=>field("initial_quantity",e.target.value)}/></label><label>计量方式<select value={form.quantity_unit} onChange={e=>field("quantity_unit",e.target.value)}><option value="count">数量（袋 / 卷 / 个）</option><option value="g">克</option><option value="ml">毫升</option></select></label>{form.quantity_unit==="count"&&<label>数量单位<input placeholder="袋、卷、个等" value={form.quantity_label} onChange={e=>field("quantity_label",e.target.value)}/></label>}<label>预计每日使用量<input inputMode="decimal" placeholder="只用于估算，未知留空" value={form.expected_daily_usage} onChange={e=>field("expected_daily_usage",e.target.value)}/></label><label>备注<input value={form.note} onChange={e=>field("note",e.target.value)}/></label>
      <details className="full"><summary>饮食自动扣减与补货提醒</summary><label>扣减方式<select value={form.match_mode} onChange={e=>{field("match_mode",e.target.value);if(e.target.value==="none"){field("match_value","");field("reminder_enabled",false);}}}><option value="none">手动记录</option><option value="exact_name">按饮食中的准确名称</option><option value="food_ref">按食物档案</option></select></label>{form.match_mode!=="none"&&<><label>匹配值<input value={form.match_value} onChange={e=>field("match_value",e.target.value)}/></label><label>补货阈值<input value={form.replenish_threshold} onChange={e=>field("replenish_threshold",e.target.value)}/></label><label>提前天数<input value={form.replenish_lead_days} onChange={e=>field("replenish_lead_days",e.target.value)}/></label><label><input type="checkbox" checked={form.reminder_enabled} onChange={e=>field("reminder_enabled",e.target.checked)}/>启用补货提醒</label></>}</details><button disabled={pending}>{pending?"保存中…":"保存消耗品"}</button></form>}
    {capabilities.has("life.update_purchase_items")&&<PurchaseItemRepair execute={execute}/>}
  </section>;
}
