import type { WriteCapabilityName } from "@shadow/contracts";

export interface WorkoutFields{planId:string;sessionType:string;occurredOn:string;timeZone:string;durationMinutes:string;distanceKm:string;caloriesKcal:string;rpe:string;heartRateAvg:string;note:string;}
export interface WorkoutCommand{capability:WriteCapabilityName;input:unknown;}
const workoutLabels:Readonly<Record<string,string>>={walk:"健走",walking:"健走",brisk_walking:"健走",run:"跑步",running:"跑步",track_running:"田径跑",circuit_training:"循环训练",hiking:"徒步",backpacking:"旅行徒步",cycling:"自行车",biking:"自行车",stationary_biking:"室内自行车",mountain_biking:"山地自行车",swimming:"游泳",pool_swimming:"游泳",open_water_swimming:"户外游泳",elliptical:"椭圆机",treadmill:"跑步机",rowing_machine:"划船机",strength_training:"力量训练",weight_training:"力量训练",yoga:"瑜伽",other:"其他运动"};
export function workoutTypeLabel(value:string):string{const trimmed=value.trim(),key=trimmed.toLowerCase().replace(/[ -]/gu,"_");return workoutLabels[key]??(/[^\u0000-\u007f]/u.test(trimmed)?trimmed:`其他运动 · ${trimmed.replaceAll("_"," ")}`);}
export function initialWorkoutFields(date:string,timeZone:string):WorkoutFields{return{planId:"",sessionType:"run",occurredOn:date,timeZone,durationMinutes:"",distanceKm:"",caloriesKcal:"",rpe:"",heartRateAvg:"",note:""};}
export function buildWorkoutCommand(fields:WorkoutFields):WorkoutCommand{return{capability:"health.record_workout",input:{...(fields.planId?{plan_id:fields.planId}:{}),session_type:fields.sessionType.trim(),occurred_on:fields.occurredOn,time_zone:fields.timeZone,...integerField("duration_minutes",fields.durationMinutes),...decimalField("distance_km",fields.distanceKm),...decimalField("calories_kcal",fields.caloriesKcal),...integerField("rpe",fields.rpe),...integerField("heart_rate_avg",fields.heartRateAvg),...(fields.note.trim()?{detail:{note:fields.note.trim()}}:{})}};}
function integerField(key:string,value:string):Record<string,number>{return value.trim()?{[key]:Number(value)}:{};}
function decimalField(key:string,value:string):Record<string,string>{return value.trim()?{[key]:value.trim()}:{};}
