// Generated by @shadow/contracts. Do not edit.
package com.shadow.life

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class DomainRecordsResultDtoItemsEntry(
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("supporting") val supporting: String?,
  @SerialName("happened_on") val happenedOn: String?,
  @SerialName("state") val state: String?,
  @SerialName("revision") val revision: Long?,
  @SerialName("record_id") val recordId: String?,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String?
)

@Serializable
data class DomainRecordsResultDto(
  @SerialName("items") val items: List<DomainRecordsResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class PlanningAgendaResultDtoItemsEntrySourceKind(val wireValue: String) {
  @SerialName("project_action") ProjectAction("project_action"),
  @SerialName("recurring_occurrence") RecurringOccurrence("recurring_occurrence"),
  @SerialName("health_habit") HealthHabit("health_habit")
}

@Serializable
enum class PlanningAgendaResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("open") Open("open"),
  @SerialName("pending") Pending("pending"),
  @SerialName("reminded") Reminded("reminded"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("handled") Handled("handled"),
  @SerialName("completed") Completed("completed"),
  @SerialName("dismissed") Dismissed("dismissed"),
  @SerialName("cancelled") Cancelled("cancelled"),
  @SerialName("not_applicable") NotApplicable("not_applicable")
}

@Serializable
enum class PlanningAgendaResultDtoItemsEntryTargetKind(val wireValue: String) {
  @SerialName("project") Project("project"),
  @SerialName("money_occurrence") MoneyOccurrence("money_occurrence"),
  @SerialName("health_habit") HealthHabit("health_habit")
}

@Serializable
data class PlanningAgendaResultDtoItemsEntryTarget(
  @SerialName("kind") val kind: PlanningAgendaResultDtoItemsEntryTargetKind,
  @SerialName("id") val id: String,
  @SerialName("project_id") val projectId: String?
)

@Serializable
enum class PlanningAgendaResultDtoItemsEntryPrimaryActionCapability(val wireValue: String) {
  @SerialName("life.save_action_item") LifeSaveActionItem("life.save_action_item"),
  @SerialName("money.set_occurrence_state") MoneySetOccurrenceState("money.set_occurrence_state")
}

@Serializable
data class PlanningAgendaResultDtoItemsEntryPrimaryAction(
  @SerialName("capability") val capability: PlanningAgendaResultDtoItemsEntryPrimaryActionCapability,
  @SerialName("target_id") val targetId: String,
  @SerialName("expected_revision") val expectedRevision: Long
)

@Serializable
data class PlanningAgendaResultDtoItemsEntry(
  @SerialName("source_kind") val sourceKind: PlanningAgendaResultDtoItemsEntrySourceKind,
  @SerialName("source_id") val sourceId: String,
  @SerialName("source_key") val sourceKey: String,
  @SerialName("title") val title: String,
  @SerialName("state") val state: PlanningAgendaResultDtoItemsEntryState,
  @SerialName("due_on") val dueOn: String,
  @SerialName("due_at") val dueAt: String?,
  @SerialName("target") val target: PlanningAgendaResultDtoItemsEntryTarget,
  @SerialName("primary_action") val primaryAction: PlanningAgendaResultDtoItemsEntryPrimaryAction?
)

@Serializable
data class PlanningAgendaResultDto(
  @SerialName("from_on") val fromOn: String,
  @SerialName("to_on_exclusive") val toOnExclusive: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("items") val items: List<PlanningAgendaResultDtoItemsEntry>,
  @SerialName("truncated") val truncated: Boolean,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class NotificationsResultDtoItemsEntryKind(val wireValue: String) {
  @SerialName("due") Due("due"),
  @SerialName("processing_failed") ProcessingFailed("processing_failed"),
  @SerialName("reminder") Reminder("reminder")
}

@Serializable
enum class NotificationsResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("dismissed") Dismissed("dismissed"),
  @SerialName("delivered") Delivered("delivered")
}

@Serializable
enum class NotificationsResultDtoItemsEntryReadState(val wireValue: String) {
  @SerialName("unread") Unread("unread"),
  @SerialName("read") Read("read")
}

@Serializable
enum class NotificationsResultDtoItemsEntryDeliveryState(val wireValue: String) {
  @SerialName("disabled") Disabled("disabled"),
  @SerialName("quiet") Quiet("quiet"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("scheduled") Scheduled("scheduled"),
  @SerialName("ready") Ready("ready")
}

@Serializable
enum class NotificationsResultDtoItemsEntryDeliveriesEntryState(val wireValue: String) {
  @SerialName("scheduled") Scheduled("scheduled"),
  @SerialName("delivered") Delivered("delivered"),
  @SerialName("failed") Failed("failed"),
  @SerialName("cancelled") Cancelled("cancelled"),
  @SerialName("unknown") Unknown("unknown")
}

@Serializable
data class NotificationsResultDtoItemsEntryDeliveriesEntry(
  @SerialName("installation_id") val installationId: String,
  @SerialName("state") val state: NotificationsResultDtoItemsEntryDeliveriesEntryState,
  @SerialName("attempt") val attempt: Long,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class NotificationsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("kind") val kind: NotificationsResultDtoItemsEntryKind,
  @SerialName("title") val title: String,
  @SerialName("body") val body: String,
  @SerialName("scheduled_at") val scheduledAt: String,
  @SerialName("state") val state: NotificationsResultDtoItemsEntryState,
  @SerialName("snoozed_until") val snoozedUntil: String?,
  @SerialName("read_state") val readState: NotificationsResultDtoItemsEntryReadState,
  @SerialName("delivery_state") val deliveryState: NotificationsResultDtoItemsEntryDeliveryState,
  @SerialName("deliveries") val deliveries: List<NotificationsResultDtoItemsEntryDeliveriesEntry>
)

@Serializable
data class NotificationsResultDtoPreferences(
  @SerialName("enabled") val enabled: Boolean,
  @SerialName("quiet_start") val quietStart: String?,
  @SerialName("quiet_end") val quietEnd: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String?
)

@Serializable
data class NotificationsResultDto(
  @SerialName("items") val items: List<NotificationsResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("preferences") val preferences: NotificationsResultDtoPreferences,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class LifeTodayResultDtoDomainsMeals(
  @SerialName("count") val count: Long,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsMoneyTotalsEntry(
  @SerialName("currency") val currency: String,
  @SerialName("gross_expense") val grossExpense: String,
  @SerialName("refund") val refund: String,
  @SerialName("income") val income: String,
  @SerialName("net_spending") val netSpending: String,
  @SerialName("net_cashflow") val netCashflow: String
)

@Serializable
enum class LifeTodayResultDtoDomainsMoneyDueItemsEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("reminded") Reminded("reminded"),
  @SerialName("snoozed") Snoozed("snoozed")
}

@Serializable
data class LifeTodayResultDtoDomainsMoneyDueItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("due_on") val dueOn: String,
  @SerialName("state") val state: LifeTodayResultDtoDomainsMoneyDueItemsEntryState,
  @SerialName("title") val title: String,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String?
)

@Serializable
data class LifeTodayResultDtoDomainsMoney(
  @SerialName("entries") val entries: Long,
  @SerialName("totals") val totals: List<LifeTodayResultDtoDomainsMoneyTotalsEntry>,
  @SerialName("due_items") val dueItems: List<LifeTodayResultDtoDomainsMoneyDueItemsEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsHealthSyncIssuesEntry(
  @SerialName("id") val id: String,
  @SerialName("source_type") val sourceType: String,
  @SerialName("instance_key") val instanceKey: String,
  @SerialName("permission_state") val permissionState: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("cursor_states") val cursorStates: List<String>,
  @SerialName("last_sync_at") val lastSyncAt: String?
)

@Serializable
data class LifeTodayResultDtoDomainsHealth(
  @SerialName("facts") val facts: Long,
  @SerialName("sync_issues") val syncIssues: List<LifeTodayResultDtoDomainsHealthSyncIssuesEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsTravelCurrentTripsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String
)

@Serializable
data class LifeTodayResultDtoDomainsTravel(
  @SerialName("visits") val visits: Long,
  @SerialName("current_trips") val currentTrips: List<LifeTodayResultDtoDomainsTravelCurrentTripsEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsLibrary(
  @SerialName("captured") val captured: Long,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomains(
  @SerialName("meals") val meals: LifeTodayResultDtoDomainsMeals? = null,
  @SerialName("money") val money: LifeTodayResultDtoDomainsMoney? = null,
  @SerialName("health") val health: LifeTodayResultDtoDomainsHealth? = null,
  @SerialName("travel") val travel: LifeTodayResultDtoDomainsTravel? = null,
  @SerialName("library") val library: LifeTodayResultDtoDomainsLibrary? = null
)

@Serializable
data class LifeTodayResultDto(
  @SerialName("date") val date: String,
  @SerialName("domains") val domains: LifeTodayResultDtoDomains,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeTimelineResultDtoItemsEntryDomain(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeTimelineResultDtoItemsEntry(
  @SerialName("domain") val domain: LifeTimelineResultDtoItemsEntryDomain,
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("happened_at") val happenedAt: String,
  @SerialName("title") val title: String,
  @SerialName("amount") val amount: String? = null,
  @SerialName("currency") val currency: String? = null,
  @SerialName("record_id") val recordId: String? = null
)

@Serializable
data class LifeTimelineResultDto(
  @SerialName("items") val items: List<LifeTimelineResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeSearchResultDtoItemsEntryDomain(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeSearchResultDtoItemsEntry(
  @SerialName("domain") val domain: LifeSearchResultDtoItemsEntryDomain,
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("supporting") val supporting: String?,
  @SerialName("happened_on") val happenedOn: String,
  @SerialName("amount") val amount: String? = null,
  @SerialName("currency") val currency: String? = null,
  @SerialName("record_id") val recordId: String? = null
)

@Serializable
enum class LifeSearchResultDtoAppliedFiltersTypesEntry(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeSearchResultDtoAppliedFilters(
  @SerialName("q") val q: String,
  @SerialName("types") val types: List<LifeSearchResultDtoAppliedFiltersTypesEntry>,
  @SerialName("from_on") val fromOn: String?,
  @SerialName("to_on_exclusive") val toOnExclusive: String?
)

@Serializable
data class LifeSearchResultDto(
  @SerialName("items") val items: List<LifeSearchResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String,
  @SerialName("applied_filters") val appliedFilters: LifeSearchResultDtoAppliedFilters
)

@Serializable
data class HealthSourcesResultDtoItemsEntryCursorsEntry(
  @SerialName("device_id") val deviceId: String,
  @SerialName("record_type") val recordType: String,
  @SerialName("cursor") val cursor: String?,
  @SerialName("state") val state: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class HealthSourcesResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("source_type") val sourceType: String,
  @SerialName("instance_key") val instanceKey: String,
  @SerialName("permission_state") val permissionState: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("fingerprint") val fingerprint: String?,
  @SerialName("cursors") val cursors: List<HealthSourcesResultDtoItemsEntryCursorsEntry>
)

@Serializable
data class HealthSourcesResultDto(
  @SerialName("items") val items: List<HealthSourcesResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)
