// Generated by @shadow/contracts. Do not edit.
@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)

package com.shadow.life

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

@Serializable
data class DomainRecordsResultDtoItemsEntry(
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("supporting") val supporting: String?,
  @SerialName("happened_on") val happenedOn: String?,
  @SerialName("state") val state: String?,
  @SerialName("revision") val revision: Long?,
  @SerialName("record_id") val recordId: String?,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String?
)

@Serializable
data class DomainRecordsResultDto(
  @SerialName("items") val items: List<DomainRecordsResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class PlanningAgendaResultDtoItemsEntrySourceKind(val wireValue: String) {
  @SerialName("project_action") ProjectAction("project_action"),
  @SerialName("recurring_occurrence") RecurringOccurrence("recurring_occurrence"),
  @SerialName("health_habit") HealthHabit("health_habit")
}

@Serializable
enum class PlanningAgendaResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("open") Open("open"),
  @SerialName("pending") Pending("pending"),
  @SerialName("reminded") Reminded("reminded"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("handled") Handled("handled"),
  @SerialName("completed") Completed("completed"),
  @SerialName("dismissed") Dismissed("dismissed"),
  @SerialName("cancelled") Cancelled("cancelled"),
  @SerialName("not_applicable") NotApplicable("not_applicable")
}

@Serializable
enum class PlanningAgendaResultDtoItemsEntryTargetKind(val wireValue: String) {
  @SerialName("project") Project("project"),
  @SerialName("money_occurrence") MoneyOccurrence("money_occurrence"),
  @SerialName("health_habit") HealthHabit("health_habit")
}

@Serializable
data class PlanningAgendaResultDtoItemsEntryTarget(
  @SerialName("kind") val kind: PlanningAgendaResultDtoItemsEntryTargetKind,
  @SerialName("id") val id: String,
  @SerialName("project_id") val projectId: String?
)

@Serializable
enum class PlanningAgendaResultDtoItemsEntryPrimaryActionCapability(val wireValue: String) {
  @SerialName("life.save_action_item") LifeSaveActionItem("life.save_action_item"),
  @SerialName("money.set_occurrence_state") MoneySetOccurrenceState("money.set_occurrence_state")
}

@Serializable
data class PlanningAgendaResultDtoItemsEntryPrimaryAction(
  @SerialName("capability") val capability: PlanningAgendaResultDtoItemsEntryPrimaryActionCapability,
  @SerialName("target_id") val targetId: String,
  @SerialName("expected_revision") val expectedRevision: Long
)

@Serializable
data class PlanningAgendaResultDtoItemsEntry(
  @SerialName("source_kind") val sourceKind: PlanningAgendaResultDtoItemsEntrySourceKind,
  @SerialName("source_id") val sourceId: String,
  @SerialName("source_key") val sourceKey: String,
  @SerialName("title") val title: String,
  @SerialName("state") val state: PlanningAgendaResultDtoItemsEntryState,
  @SerialName("due_on") val dueOn: String,
  @SerialName("due_at") val dueAt: String?,
  @SerialName("target") val target: PlanningAgendaResultDtoItemsEntryTarget,
  @SerialName("primary_action") val primaryAction: PlanningAgendaResultDtoItemsEntryPrimaryAction?
)

@Serializable
data class PlanningAgendaResultDto(
  @SerialName("from_on") val fromOn: String,
  @SerialName("to_on_exclusive") val toOnExclusive: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("items") val items: List<PlanningAgendaResultDtoItemsEntry>,
  @SerialName("truncated") val truncated: Boolean,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class NotificationsResultDtoItemsEntryKind(val wireValue: String) {
  @SerialName("due") Due("due"),
  @SerialName("processing_failed") ProcessingFailed("processing_failed"),
  @SerialName("reminder") Reminder("reminder")
}

@Serializable
enum class NotificationsResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("dismissed") Dismissed("dismissed"),
  @SerialName("delivered") Delivered("delivered")
}

@Serializable
enum class NotificationsResultDtoItemsEntryReadState(val wireValue: String) {
  @SerialName("unread") Unread("unread"),
  @SerialName("read") Read("read")
}

@Serializable
enum class NotificationsResultDtoItemsEntryDeliveryState(val wireValue: String) {
  @SerialName("disabled") Disabled("disabled"),
  @SerialName("quiet") Quiet("quiet"),
  @SerialName("snoozed") Snoozed("snoozed"),
  @SerialName("scheduled") Scheduled("scheduled"),
  @SerialName("ready") Ready("ready")
}

@Serializable
enum class NotificationsResultDtoItemsEntryDeliveriesEntryState(val wireValue: String) {
  @SerialName("scheduled") Scheduled("scheduled"),
  @SerialName("delivered") Delivered("delivered"),
  @SerialName("failed") Failed("failed"),
  @SerialName("cancelled") Cancelled("cancelled"),
  @SerialName("unknown") Unknown("unknown")
}

@Serializable
data class NotificationsResultDtoItemsEntryDeliveriesEntry(
  @SerialName("installation_id") val installationId: String,
  @SerialName("state") val state: NotificationsResultDtoItemsEntryDeliveriesEntryState,
  @SerialName("attempt") val attempt: Long,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class NotificationsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("kind") val kind: NotificationsResultDtoItemsEntryKind,
  @SerialName("title") val title: String,
  @SerialName("body") val body: String,
  @SerialName("scheduled_at") val scheduledAt: String,
  @SerialName("state") val state: NotificationsResultDtoItemsEntryState,
  @SerialName("snoozed_until") val snoozedUntil: String?,
  @SerialName("read_state") val readState: NotificationsResultDtoItemsEntryReadState,
  @SerialName("delivery_state") val deliveryState: NotificationsResultDtoItemsEntryDeliveryState,
  @SerialName("deliveries") val deliveries: List<NotificationsResultDtoItemsEntryDeliveriesEntry>
)

@Serializable
data class NotificationsResultDtoPreferences(
  @SerialName("enabled") val enabled: Boolean,
  @SerialName("quiet_start") val quietStart: String?,
  @SerialName("quiet_end") val quietEnd: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String?
)

@Serializable
data class NotificationsResultDto(
  @SerialName("items") val items: List<NotificationsResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("preferences") val preferences: NotificationsResultDtoPreferences,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class LifeTodayResultDtoDomainsMeals(
  @SerialName("count") val count: Long,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsMoneyTotalsEntry(
  @SerialName("currency") val currency: String,
  @SerialName("gross_expense") val grossExpense: String,
  @SerialName("refund") val refund: String,
  @SerialName("income") val income: String,
  @SerialName("net_spending") val netSpending: String,
  @SerialName("net_cashflow") val netCashflow: String
)

@Serializable
enum class LifeTodayResultDtoDomainsMoneyDueItemsEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("reminded") Reminded("reminded"),
  @SerialName("snoozed") Snoozed("snoozed")
}

@Serializable
data class LifeTodayResultDtoDomainsMoneyDueItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("due_on") val dueOn: String,
  @SerialName("state") val state: LifeTodayResultDtoDomainsMoneyDueItemsEntryState,
  @SerialName("title") val title: String,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String?
)

@Serializable
data class LifeTodayResultDtoDomainsMoney(
  @SerialName("entries") val entries: Long,
  @SerialName("totals") val totals: List<LifeTodayResultDtoDomainsMoneyTotalsEntry>,
  @SerialName("due_items") val dueItems: List<LifeTodayResultDtoDomainsMoneyDueItemsEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsHealthSyncIssuesEntry(
  @SerialName("id") val id: String,
  @SerialName("source_type") val sourceType: String,
  @SerialName("instance_key") val instanceKey: String,
  @SerialName("permission_state") val permissionState: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("cursor_states") val cursorStates: List<String>,
  @SerialName("last_sync_at") val lastSyncAt: String?
)

@Serializable
data class LifeTodayResultDtoDomainsHealth(
  @SerialName("facts") val facts: Long,
  @SerialName("sync_issues") val syncIssues: List<LifeTodayResultDtoDomainsHealthSyncIssuesEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsTravelCurrentTripsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String
)

@Serializable
data class LifeTodayResultDtoDomainsTravel(
  @SerialName("visits") val visits: Long,
  @SerialName("current_trips") val currentTrips: List<LifeTodayResultDtoDomainsTravelCurrentTripsEntry>,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomainsLibrary(
  @SerialName("captured") val captured: Long,
  @SerialName("freshness") val freshness: String?
)

@Serializable
data class LifeTodayResultDtoDomains(
  @SerialName("meals") val meals: LifeTodayResultDtoDomainsMeals? = null,
  @SerialName("money") val money: LifeTodayResultDtoDomainsMoney? = null,
  @SerialName("health") val health: LifeTodayResultDtoDomainsHealth? = null,
  @SerialName("travel") val travel: LifeTodayResultDtoDomainsTravel? = null,
  @SerialName("library") val library: LifeTodayResultDtoDomainsLibrary? = null
)

@Serializable
data class LifeTodayResultDto(
  @SerialName("date") val date: String,
  @SerialName("domains") val domains: LifeTodayResultDtoDomains,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeTimelineResultDtoItemsEntryDomain(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeTimelineResultDtoItemsEntry(
  @SerialName("domain") val domain: LifeTimelineResultDtoItemsEntryDomain,
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("happened_at") val happenedAt: String,
  @SerialName("title") val title: String,
  @SerialName("amount") val amount: String? = null,
  @SerialName("currency") val currency: String? = null,
  @SerialName("record_id") val recordId: String? = null
)

@Serializable
data class LifeTimelineResultDto(
  @SerialName("items") val items: List<LifeTimelineResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeSearchResultDtoItemsEntryDomain(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeSearchResultDtoItemsEntry(
  @SerialName("domain") val domain: LifeSearchResultDtoItemsEntryDomain,
  @SerialName("kind") val kind: String,
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("supporting") val supporting: String?,
  @SerialName("happened_on") val happenedOn: String,
  @SerialName("amount") val amount: String? = null,
  @SerialName("currency") val currency: String? = null,
  @SerialName("record_id") val recordId: String? = null
)

@Serializable
enum class LifeSearchResultDtoAppliedFiltersTypesEntry(val wireValue: String) {
  @SerialName("meals") Meals("meals"),
  @SerialName("money") Money("money"),
  @SerialName("health") Health("health"),
  @SerialName("travel") Travel("travel"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeSearchResultDtoAppliedFilters(
  @SerialName("q") val q: String,
  @SerialName("types") val types: List<LifeSearchResultDtoAppliedFiltersTypesEntry>,
  @SerialName("from_on") val fromOn: String?,
  @SerialName("to_on_exclusive") val toOnExclusive: String?
)

@Serializable
data class LifeSearchResultDto(
  @SerialName("items") val items: List<LifeSearchResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String,
  @SerialName("applied_filters") val appliedFilters: LifeSearchResultDtoAppliedFilters
)

@Serializable
enum class ListMealsResultDtoItemsEntryMealType(val wireValue: String) {
  @SerialName("breakfast") Breakfast("breakfast"),
  @SerialName("lunch") Lunch("lunch"),
  @SerialName("dinner") Dinner("dinner"),
  @SerialName("snack") Snack("snack"),
  @SerialName("other") Other("other")
}

@Serializable
data class ListMealsResultDtoItemsEntryItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("name") val name: String,
  @SerialName("food_ref_id") val foodRefId: String?,
  @SerialName("free_text") val freeText: String?,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("amount_g") val amountG: String?,
  @SerialName("energy_kcal") val energyKcal: String?,
  @SerialName("protein_g") val proteinG: String?,
  @SerialName("fat_g") val fatG: String?,
  @SerialName("carb_g") val carbG: String?,
  @SerialName("fiber_g") val fiberG: String?,
  @SerialName("sodium_mg") val sodiumMg: String?,
  @SerialName("consumed_fraction") val consumedFraction: String?,
  @SerialName("provenance") val provenance: String?,
  @SerialName("grouping_origin") val groupingOrigin: String?,
  @SerialName("estimate") val estimate: Boolean,
  @SerialName("revision") val revision: Long
)

@Serializable
enum class ListMealsResultDtoItemsEntryPaymentsEntryPaymentMethod(val wireValue: String) {
  @SerialName("alipay") Alipay("alipay"),
  @SerialName("wechat") Wechat("wechat"),
  @SerialName("jd_pay") JdPay("jd_pay"),
  @SerialName("jd_baitiao") JdBaitiao("jd_baitiao"),
  @SerialName("huabei") Huabei("huabei"),
  @SerialName("gift_card") GiftCard("gift_card"),
  @SerialName("cash") Cash("cash"),
  @SerialName("bank_card") BankCard("bank_card"),
  @SerialName("bank_transfer") BankTransfer("bank_transfer"),
  @SerialName("mixed") Mixed("mixed"),
  @SerialName("other") Other("other")
}

@Serializable
data class ListMealsResultDtoItemsEntryPaymentsEntry(
  @SerialName("id") val id: String,
  @SerialName("amount") val amount: String,
  @SerialName("currency") val currency: String,
  @SerialName("payment_method") val paymentMethod: ListMealsResultDtoItemsEntryPaymentsEntryPaymentMethod?
)

@Serializable
data class ListMealsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("meal_type") val mealType: ListMealsResultDtoItemsEntryMealType,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("items") val items: List<ListMealsResultDtoItemsEntryItemsEntry>,
  @SerialName("payments") val payments: List<ListMealsResultDtoItemsEntryPaymentsEntry>,
  @SerialName("source_ids") val sourceIds: List<String>
)

@Serializable
data class ListMealsResultDto(
  @SerialName("items") val items: List<ListMealsResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class HealthSourcesResultDtoItemsEntryCursorsEntry(
  @SerialName("device_id") val deviceId: String,
  @SerialName("record_type") val recordType: String,
  @SerialName("cursor") val cursor: String?,
  @SerialName("state") val state: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class HealthSourcesResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("source_type") val sourceType: String,
  @SerialName("instance_key") val instanceKey: String,
  @SerialName("permission_state") val permissionState: String,
  @SerialName("sync_epoch") val syncEpoch: Long,
  @SerialName("fingerprint") val fingerprint: String?,
  @SerialName("cursors") val cursors: List<HealthSourcesResultDtoItemsEntryCursorsEntry>
)

@Serializable
data class HealthSourcesResultDto(
  @SerialName("items") val items: List<HealthSourcesResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeProjectsResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("completed") Completed("completed"),
  @SerialName("paused") Paused("paused"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
enum class LifeProjectsResultDtoItemsEntryMilestonesEntryState(val wireValue: String) {
  @SerialName("planned") Planned("planned"),
  @SerialName("completed") Completed("completed"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
data class LifeProjectsResultDtoItemsEntryMilestonesEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("due_on") val dueOn: String?,
  @SerialName("state") val state: LifeProjectsResultDtoItemsEntryMilestonesEntryState,
  @SerialName("position") val position: Long
)

@Serializable
enum class LifeProjectsResultDtoItemsEntryLinksEntryRefKind(val wireValue: String) {
  @SerialName("trip") Trip("trip"),
  @SerialName("health_plan") HealthPlan("health_plan"),
  @SerialName("recurring_plan") RecurringPlan("recurring_plan"),
  @SerialName("owned_item") OwnedItem("owned_item"),
  @SerialName("library_item") LibraryItem("library_item"),
  @SerialName("money_entry") MoneyEntry("money_entry"),
  @SerialName("meal") Meal("meal"),
  @SerialName("recipe") Recipe("recipe")
}

@Serializable
data class LifeProjectsResultDtoItemsEntryLinksEntry(
  @SerialName("ref_kind") val refKind: LifeProjectsResultDtoItemsEntryLinksEntryRefKind,
  @SerialName("ref_id") val refId: String,
  @SerialName("ref_revision") val refRevision: Long,
  @SerialName("role") val role: String
)

@Serializable
enum class LifeProjectsResultDtoItemsEntryActionsEntryState(val wireValue: String) {
  @SerialName("open") Open("open"),
  @SerialName("completed") Completed("completed"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
data class LifeProjectsResultDtoItemsEntryActionsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("due_on") val dueOn: String?,
  @SerialName("state") val state: LifeProjectsResultDtoItemsEntryActionsEntryState,
  @SerialName("recurring_occurrence_id") val recurringOccurrenceId: String? = null,
  @SerialName("health_habit_id") val healthHabitId: String? = null,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("source_state") val sourceState: String? = null
)

@Serializable
data class LifeProjectsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("goal") val goal: String,
  @SerialName("starts_on") val startsOn: String?,
  @SerialName("ends_on") val endsOn: String?,
  @SerialName("state") val state: LifeProjectsResultDtoItemsEntryState,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("milestones") val milestones: List<LifeProjectsResultDtoItemsEntryMilestonesEntry>,
  @SerialName("links") val links: List<LifeProjectsResultDtoItemsEntryLinksEntry>,
  @SerialName("actions") val actions: List<LifeProjectsResultDtoItemsEntryActionsEntry>
)

@Serializable
data class LifeProjectsResultDto(
  @SerialName("items") val items: List<LifeProjectsResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class OwnedItemsResultDtoItemsEntryOwnershipState(val wireValue: String) {
  @SerialName("owned") Owned("owned"),
  @SerialName("gifted") Gifted("gifted"),
  @SerialName("returned") Returned("returned"),
  @SerialName("disposed") Disposed("disposed"),
  @SerialName("lost") Lost("lost")
}

@Serializable
data class OwnedItemsResultDtoItemsEntryPurchase(
  @SerialName("purchase_item_id") val purchaseItemId: String,
  @SerialName("purchase_id") val purchaseId: String,
  @SerialName("record_id") val recordId: String,
  @SerialName("raw_name") val rawName: String,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("line_amount") val lineAmount: String?
)

@Serializable
enum class OwnedItemsResultDtoItemsEntryDocumentsEntryRole(val wireValue: String) {
  @SerialName("receipt") Receipt("receipt"),
  @SerialName("manual") Manual("manual"),
  @SerialName("warranty") Warranty("warranty"),
  @SerialName("repair") Repair("repair")
}

@Serializable
data class OwnedItemsResultDtoItemsEntryDocumentsEntry(
  @SerialName("library_item_id") val libraryItemId: String,
  @SerialName("library_revision") val libraryRevision: Long,
  @SerialName("role") val role: OwnedItemsResultDtoItemsEntryDocumentsEntryRole,
  @SerialName("title") val title: String? = null
)

@Serializable
enum class OwnedItemsResultDtoItemsEntryEventsEntryEventKind(val wireValue: String) {
  @SerialName("maintenance") Maintenance("maintenance"),
  @SerialName("repair") Repair("repair"),
  @SerialName("return") Return("return"),
  @SerialName("dispose") Dispose("dispose"),
  @SerialName("gift") Gift("gift"),
  @SerialName("lost") Lost("lost"),
  @SerialName("restore") Restore("restore"),
  @SerialName("note") Note("note")
}

@Serializable
data class OwnedItemsResultDtoItemsEntryEventsEntry(
  @SerialName("id") val id: String,
  @SerialName("event_kind") val eventKind: OwnedItemsResultDtoItemsEntryEventsEntryEventKind,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("note") val note: String,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("document_library_item_id") val documentLibraryItemId: String?,
  @SerialName("document_library_revision") val documentLibraryRevision: Long?,
  @SerialName("cost_entry_id") val costEntryId: String? = null,
  @SerialName("cost_amount") val costAmount: String? = null,
  @SerialName("cost_currency") val costCurrency: String? = null,
  @SerialName("document_title") val documentTitle: String? = null
)

@Serializable
data class OwnedItemsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("name") val name: String,
  @SerialName("ownership_state") val ownershipState: OwnedItemsResultDtoItemsEntryOwnershipState,
  @SerialName("location") val location: String?,
  @SerialName("started_on") val startedOn: String?,
  @SerialName("warranty_ends_on") val warrantyEndsOn: String?,
  @SerialName("return_by") val returnBy: String?,
  @SerialName("purchase_item_id") val purchaseItemId: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("purchase") val purchase: OwnedItemsResultDtoItemsEntryPurchase?,
  @SerialName("documents") val documents: List<OwnedItemsResultDtoItemsEntryDocumentsEntry>,
  @SerialName("events") val events: List<OwnedItemsResultDtoItemsEntryEventsEntry>
)

@Serializable
data class OwnedItemsResultDto(
  @SerialName("items") val items: List<OwnedItemsResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class LifeReviewsResultDtoItemsEntryDomainsEntry(val wireValue: String) {
  @SerialName("money") Money("money"),
  @SerialName("meals") Meals("meals"),
  @SerialName("health") Health("health"),
  @SerialName("items") Items("items"),
  @SerialName("library") Library("library")
}

@Serializable
data class LifeReviewsResultDtoItemsEntryEvidenceEntry(
  @SerialName("type") val type: String,
  @SerialName("id") val id: String,
  @SerialName("revision") val revision: Long
)

@Serializable
data class LifeReviewsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("from_on") val fromOn: String,
  @SerialName("to_on") val toOn: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("domains") val domains: List<LifeReviewsResultDtoItemsEntryDomainsEntry>,
  @SerialName("algorithm_version") val algorithmVersion: String,
  @SerialName("metrics") val metrics: JsonObject,
  @SerialName("coverage") val coverage: JsonObject,
  @SerialName("evidence") val evidence: List<LifeReviewsResultDtoItemsEntryEvidenceEntry>,
  @SerialName("limitations") val limitations: List<String>,
  @SerialName("revision") val revision: Long,
  @SerialName("generated_at") val generatedAt: String
)

@Serializable
data class LifeReviewsResultDto(
  @SerialName("items") val items: List<LifeReviewsResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class AgentThreadsResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("last_message") val lastMessage: String?
)

@Serializable
data class AgentThreadsResultDto(
  @SerialName("items") val items: List<AgentThreadsResultDtoItemsEntry>
)

@Serializable
enum class AgentThreadMessagesResultDtoItemsEntryRole(val wireValue: String) {
  @SerialName("user") User("user"),
  @SerialName("assistant") Assistant("assistant")
}

@Serializable
data class AgentThreadMessagesResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("role") val role: AgentThreadMessagesResultDtoItemsEntryRole,
  @SerialName("content") val content: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class AgentThreadMessagesResultDto(
  @SerialName("items") val items: List<AgentThreadMessagesResultDtoItemsEntry>,
  @SerialName("next_cursor") val nextCursor: String?,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class MoneyPlanningResultDtoWindow(
  @SerialName("start_on") val startOn: String,
  @SerialName("end_on_exclusive") val endOnExclusive: String
)

@Serializable
data class MoneyPlanningResultDtoBudgetsEntry(
  @SerialName("id") val id: String,
  @SerialName("category") val category: String?,
  @SerialName("amount") val amount: String,
  @SerialName("currency") val currency: String,
  @SerialName("revision") val revision: Long,
  @SerialName("spent_basis") val spentBasis: String,
  @SerialName("spent") val spent: String
)

@Serializable
enum class MoneyPlanningResultDtoRecurringPlansEntryCadence(val wireValue: String) {
  @SerialName("daily") Daily("daily"),
  @SerialName("weekly") Weekly("weekly"),
  @SerialName("monthly") Monthly("monthly"),
  @SerialName("yearly") Yearly("yearly"),
  @SerialName("interval") Interval("interval")
}

@Serializable
enum class MoneyPlanningResultDtoRecurringPlansEntryState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("paused") Paused("paused"),
  @SerialName("ended") Ended("ended")
}

@Serializable
enum class MoneyPlanningResultDtoRecurringPlansEntryMissingDatePolicy(val wireValue: String) {
  @SerialName("skip") Skip("skip"),
  @SerialName("last_day") LastDay("last_day")
}

@Serializable
data class MoneyPlanningResultDtoRecurringPlansEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String,
  @SerialName("cadence") val cadence: MoneyPlanningResultDtoRecurringPlansEntryCadence,
  @SerialName("next_due_on") val nextDueOn: String,
  @SerialName("category") val category: String?,
  @SerialName("active") val active: Boolean,
  @SerialName("revision") val revision: Long,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("interval_days") val intervalDays: Long?,
  @SerialName("state") val state: MoneyPlanningResultDtoRecurringPlansEntryState,
  @SerialName("ended_on") val endedOn: String?,
  @SerialName("anchor_on") val anchorOn: String,
  @SerialName("local_time") val localTime: String?,
  @SerialName("missing_date_policy") val missingDatePolicy: MoneyPlanningResultDtoRecurringPlansEntryMissingDatePolicy,
  @SerialName("recurrence_rule") val recurrenceRule: String
)

@Serializable
enum class MoneyPlanningResultDtoOccurrencesEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("reminded") Reminded("reminded"),
  @SerialName("handled") Handled("handled"),
  @SerialName("dismissed") Dismissed("dismissed"),
  @SerialName("snoozed") Snoozed("snoozed")
}

@Serializable
data class MoneyPlanningResultDtoOccurrencesEntry(
  @SerialName("id") val id: String,
  @SerialName("plan_id") val planId: String,
  @SerialName("due_on") val dueOn: String,
  @SerialName("original_due_on") val originalDueOn: String,
  @SerialName("effective_due_on") val effectiveDueOn: String,
  @SerialName("state") val state: MoneyPlanningResultDtoOccurrencesEntryState,
  @SerialName("linked_record_id") val linkedRecordId: String?,
  @SerialName("feedback") val feedback: JsonObject,
  @SerialName("snoozed_until") val snoozedUntil: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
enum class MoneyPlanningResultDtoSpendingIntentsEntryState(val wireValue: String) {
  @SerialName("planned") Planned("planned"),
  @SerialName("purchased") Purchased("purchased"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
data class MoneyPlanningResultDtoSpendingIntentsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("expected_amount") val expectedAmount: String?,
  @SerialName("currency") val currency: String?,
  @SerialName("intended_on") val intendedOn: String?,
  @SerialName("state") val state: MoneyPlanningResultDtoSpendingIntentsEntryState,
  @SerialName("linked_record_id") val linkedRecordId: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
enum class MoneyPlanningResultDtoUseCyclesEntryState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("completed") Completed("completed"),
  @SerialName("discarded") Discarded("discarded")
}

@Serializable
data class MoneyPlanningResultDtoUseCyclesEntry(
  @SerialName("id") val id: String,
  @SerialName("purchase_record_id") val purchaseRecordId: String?,
  @SerialName("item_name") val itemName: String,
  @SerialName("started_on") val startedOn: String,
  @SerialName("ended_on") val endedOn: String?,
  @SerialName("state") val state: MoneyPlanningResultDtoUseCyclesEntryState,
  @SerialName("revision") val revision: Long
)

@Serializable
data class MoneyPlanningResultDtoLimits(
  @SerialName("budgets") val budgets: Long,
  @SerialName("recurring_plans") val recurringPlans: Long,
  @SerialName("occurrences") val occurrences: Long,
  @SerialName("spending_intents") val spendingIntents: Long,
  @SerialName("use_cycles") val useCycles: Long
)

@Serializable
data class MoneyPlanningResultDtoTruncated(
  @SerialName("budgets") val budgets: Boolean,
  @SerialName("recurring_plans") val recurringPlans: Boolean,
  @SerialName("occurrences") val occurrences: Boolean,
  @SerialName("spending_intents") val spendingIntents: Boolean,
  @SerialName("use_cycles") val useCycles: Boolean
)

@Serializable
data class MoneyPlanningResultDto(
  @SerialName("period") val period: String,
  @SerialName("window") val window: MoneyPlanningResultDtoWindow,
  @SerialName("budgets") val budgets: List<MoneyPlanningResultDtoBudgetsEntry>,
  @SerialName("recurring_plans") val recurringPlans: List<MoneyPlanningResultDtoRecurringPlansEntry>,
  @SerialName("occurrences") val occurrences: List<MoneyPlanningResultDtoOccurrencesEntry>,
  @SerialName("spending_intents") val spendingIntents: List<MoneyPlanningResultDtoSpendingIntentsEntry>,
  @SerialName("use_cycles") val useCycles: List<MoneyPlanningResultDtoUseCyclesEntry>,
  @SerialName("limits") val limits: MoneyPlanningResultDtoLimits,
  @SerialName("truncated") val truncated: MoneyPlanningResultDtoTruncated,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class MealPlanningResultDtoMealPlansEntryState(val wireValue: String) {
  @SerialName("draft") Draft("draft"),
  @SerialName("active") Active("active"),
  @SerialName("completed") Completed("completed"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
enum class MealPlanningResultDtoMealPlansEntryEntriesEntryMealType(val wireValue: String) {
  @SerialName("breakfast") Breakfast("breakfast"),
  @SerialName("lunch") Lunch("lunch"),
  @SerialName("dinner") Dinner("dinner"),
  @SerialName("snack") Snack("snack"),
  @SerialName("other") Other("other")
}

@Serializable
data class MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotRecipe(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("revision") val revision: Long,
  @SerialName("servings") val servings: String
)

@Serializable
enum class MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntryProvenance(val wireValue: String) {
  @SerialName("manual") Manual("manual"),
  @SerialName("estimated") Estimated("estimated"),
  @SerialName("reference_snapshot") ReferenceSnapshot("reference_snapshot"),
  @SerialName("legacy") Legacy("legacy")
}

@Serializable
enum class MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntryGroupingOrigin(val wireValue: String) {
  @SerialName("actual_meal") ActualMeal("actual_meal"),
  @SerialName("legacy_meal_bucket") LegacyMealBucket("legacy_meal_bucket")
}

@Serializable
data class MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntry(
  @SerialName("name") val name: String,
  @SerialName("food_ref_id") val foodRefId: String? = null,
  @SerialName("free_text") val freeText: String? = null,
  @SerialName("quantity") val quantity: String? = null,
  @SerialName("unit") val unit: String? = null,
  @SerialName("amount_g") val amountG: String? = null,
  @SerialName("energy_kcal") val energyKcal: String? = null,
  @SerialName("protein_g") val proteinG: String? = null,
  @SerialName("fat_g") val fatG: String? = null,
  @SerialName("carb_g") val carbG: String? = null,
  @SerialName("fiber_g") val fiberG: String? = null,
  @SerialName("sodium_mg") val sodiumMg: String? = null,
  @SerialName("consumed_fraction") val consumedFraction: String? = null,
  @SerialName("provenance") val provenance: MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntryProvenance? = null,
  @SerialName("grouping_origin") val groupingOrigin: MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntryGroupingOrigin? = null,
  @SerialName("estimate") val estimate: Boolean,
  @SerialName("evidence_note") val evidenceNote: String? = null,
  @SerialName("planned_quantity") val plannedQuantity: String? = null
)

@Serializable
data class MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshot(
  @SerialName("recipe") val recipe: MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotRecipe,
  @SerialName("items") val items: List<MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshotItemsEntry>
)

@Serializable
data class MealPlanningResultDtoMealPlansEntryEntriesEntry(
  @SerialName("id") val id: String,
  @SerialName("plan_date") val planDate: String,
  @SerialName("meal_type") val mealType: MealPlanningResultDtoMealPlansEntryEntriesEntryMealType,
  @SerialName("title") val title: String,
  @SerialName("servings") val servings: String,
  @SerialName("recipe_id") val recipeId: String?,
  @SerialName("recipe_revision") val recipeRevision: Long?,
  @SerialName("recipe_snapshot") val recipeSnapshot: MealPlanningResultDtoMealPlansEntryEntriesEntryRecipeSnapshot?,
  @SerialName("position") val position: Long
)

@Serializable
data class MealPlanningResultDtoMealPlansEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("state") val state: MealPlanningResultDtoMealPlansEntryState,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("entries") val entries: List<MealPlanningResultDtoMealPlansEntryEntriesEntry>
)

@Serializable
enum class MealPlanningResultDtoShoppingListsEntryState(val wireValue: String) {
  @SerialName("open") Open("open"),
  @SerialName("completed") Completed("completed"),
  @SerialName("cancelled") Cancelled("cancelled")
}

@Serializable
enum class MealPlanningResultDtoShoppingListsEntryItemsEntryState(val wireValue: String) {
  @SerialName("needed") Needed("needed"),
  @SerialName("bought") Bought("bought"),
  @SerialName("skipped") Skipped("skipped")
}

@Serializable
data class MealPlanningResultDtoShoppingListsEntryItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("name") val name: String,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("source_entry_ids") val sourceEntryIds: List<String>,
  @SerialName("state") val state: MealPlanningResultDtoShoppingListsEntryItemsEntryState,
  @SerialName("purchase_item_id") val purchaseItemId: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
data class MealPlanningResultDtoShoppingListsEntry(
  @SerialName("id") val id: String,
  @SerialName("meal_plan_id") val mealPlanId: String,
  @SerialName("meal_plan_revision") val mealPlanRevision: Long,
  @SerialName("title") val title: String,
  @SerialName("state") val state: MealPlanningResultDtoShoppingListsEntryState,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("items") val items: List<MealPlanningResultDtoShoppingListsEntryItemsEntry>
)

@Serializable
data class MealPlanningResultDto(
  @SerialName("meal_plans") val mealPlans: List<MealPlanningResultDtoMealPlansEntry>,
  @SerialName("shopping_lists") val shoppingLists: List<MealPlanningResultDtoShoppingListsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class ForeignEntriesResultDtoItemsEntryEntryType(val wireValue: String) {
  @SerialName("expense") Expense("expense"),
  @SerialName("income") Income("income")
}

@Serializable
enum class ForeignEntriesResultDtoItemsEntryPaymentMethod(val wireValue: String) {
  @SerialName("alipay") Alipay("alipay"),
  @SerialName("wechat") Wechat("wechat"),
  @SerialName("jd_pay") JdPay("jd_pay"),
  @SerialName("jd_baitiao") JdBaitiao("jd_baitiao"),
  @SerialName("huabei") Huabei("huabei"),
  @SerialName("gift_card") GiftCard("gift_card"),
  @SerialName("cash") Cash("cash"),
  @SerialName("bank_card") BankCard("bank_card"),
  @SerialName("bank_transfer") BankTransfer("bank_transfer"),
  @SerialName("mixed") Mixed("mixed"),
  @SerialName("other") Other("other")
}

@Serializable
enum class ForeignEntriesResultDtoItemsEntrySourceKind(val wireValue: String) {
  @SerialName("manual") Manual("manual"),
  @SerialName("provider") Provider("provider"),
  @SerialName("import") Import("import")
}

@Serializable
enum class ForeignEntriesResultDtoItemsEntryAllocationsEntryState(val wireValue: String) {
  @SerialName("unsettled") Unsettled("unsettled"),
  @SerialName("settled") Settled("settled"),
  @SerialName("waived") Waived("waived")
}

@Serializable
data class ForeignEntriesResultDtoItemsEntryAllocationsEntry(
  @SerialName("id") val id: String,
  @SerialName("participant_label") val participantLabel: String,
  @SerialName("original_amount") val originalAmount: String,
  @SerialName("state") val state: ForeignEntriesResultDtoItemsEntryAllocationsEntryState,
  @SerialName("settled_on") val settledOn: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class ForeignEntriesResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("record_id") val recordId: String,
  @SerialName("entry_type") val entryType: ForeignEntriesResultDtoItemsEntryEntryType,
  @SerialName("amount") val amount: String,
  @SerialName("currency") val currency: String,
  @SerialName("source_scale") val sourceScale: Long,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("counterparty") val counterparty: String?,
  @SerialName("category") val category: String?,
  @SerialName("payment_method") val paymentMethod: ForeignEntriesResultDtoItemsEntryPaymentMethod?,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("fx_snapshot_id") val fxSnapshotId: String,
  @SerialName("base_amount") val baseAmount: String,
  @SerialName("base_currency") val baseCurrency: String,
  @SerialName("rate") val rate: String,
  @SerialName("quote_convention") val quoteConvention: String,
  @SerialName("quoted_at") val quotedAt: String,
  @SerialName("source_kind") val sourceKind: ForeignEntriesResultDtoItemsEntrySourceKind,
  @SerialName("source_ref") val sourceRef: String?,
  @SerialName("trip_id") val tripId: String?,
  @SerialName("allocations") val allocations: List<ForeignEntriesResultDtoItemsEntryAllocationsEntry>
)

@Serializable
data class ForeignEntriesResultDto(
  @SerialName("items") val items: List<ForeignEntriesResultDtoItemsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class TravelWorkspaceResultDtoPlacesEntry(
  @SerialName("id") val id: String,
  @SerialName("name") val name: String,
  @SerialName("address") val address: String?,
  @SerialName("latitude") val latitude: String?,
  @SerialName("longitude") val longitude: String?,
  @SerialName("tags") val tags: List<String>,
  @SerialName("favorite") val favorite: Boolean,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class TravelWorkspaceResultDtoMapsEntryState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("archived") Archived("archived")
}

@Serializable
enum class TravelWorkspaceResultDtoMapsEntryItemsEntryStatus(val wireValue: String) {
  @SerialName("candidate") Candidate("candidate"),
  @SerialName("anchor") Anchor("anchor"),
  @SerialName("planned") Planned("planned"),
  @SerialName("visited") Visited("visited")
}

@Serializable
data class TravelWorkspaceResultDtoMapsEntryItemsEntry(
  @SerialName("place_id") val placeId: String,
  @SerialName("position") val position: Long,
  @SerialName("status") val status: TravelWorkspaceResultDtoMapsEntryItemsEntryStatus,
  @SerialName("note") val note: String?
)

@Serializable
data class TravelWorkspaceResultDtoMapsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("description") val description: String?,
  @SerialName("state") val state: TravelWorkspaceResultDtoMapsEntryState,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String,
  @SerialName("items") val items: List<TravelWorkspaceResultDtoMapsEntryItemsEntry>
)

@Serializable
enum class TravelWorkspaceResultDtoTripsEntryRole(val wireValue: String) {
  @SerialName("owner") Owner("owner"),
  @SerialName("editor") Editor("editor"),
  @SerialName("viewer") Viewer("viewer")
}

@Serializable
enum class TravelWorkspaceResultDtoTripsEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelWorkspaceResultDtoTripsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("revision") val revision: Long,
  @SerialName("is_owner") val isOwner: Boolean,
  @SerialName("role") val role: TravelWorkspaceResultDtoTripsEntryRole?,
  @SerialName("visibility") val visibility: TravelWorkspaceResultDtoTripsEntryVisibility?,
  @SerialName("latest_plan_version_id") val latestPlanVersionId: String?
)

@Serializable
data class TravelWorkspaceResultDtoActiveRunPlanSnapshotDaysEntryItemsEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("title") val title: String,
  @SerialName("starts_at") val startsAt: String? = null,
  @SerialName("place_id") val placeId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
data class TravelWorkspaceResultDtoActiveRunPlanSnapshotDaysEntry(
  @SerialName("plan_date") val planDate: String,
  @SerialName("items") val items: List<TravelWorkspaceResultDtoActiveRunPlanSnapshotDaysEntryItemsEntry>
)

@Serializable
data class TravelWorkspaceResultDtoActiveRunPlanSnapshot(
  @SerialName("days") val days: List<TravelWorkspaceResultDtoActiveRunPlanSnapshotDaysEntry>,
  @SerialName("stop_count") val stopCount: Long
)

@Serializable
enum class TravelWorkspaceResultDtoActiveRunOutcomesEntryState(val wireValue: String) {
  @SerialName("arrived") Arrived("arrived"),
  @SerialName("skipped") Skipped("skipped")
}

@Serializable
data class TravelWorkspaceResultDtoActiveRunOutcomesEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("state") val state: TravelWorkspaceResultDtoActiveRunOutcomesEntryState,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class TravelWorkspaceResultDtoActiveRun(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("plan_version_id") val planVersionId: String,
  @SerialName("state") val state: String,
  @SerialName("started_at") val startedAt: String,
  @SerialName("completed_at") val completedAt: String?,
  @SerialName("plan_snapshot") val planSnapshot: TravelWorkspaceResultDtoActiveRunPlanSnapshot,
  @SerialName("plan_version") val planVersion: Long,
  @SerialName("outcomes") val outcomes: List<TravelWorkspaceResultDtoActiveRunOutcomesEntry>
)

@Serializable
data class TravelWorkspaceResultDtoTracksEntryPointsEntry(
  @SerialName("latitude") val latitude: Double,
  @SerialName("longitude") val longitude: Double,
  @SerialName("elevation_m") val elevationM: Double? = null,
  @SerialName("recorded_at") val recordedAt: String? = null
)

@Serializable
data class TravelWorkspaceResultDtoTracksEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("name") val name: String,
  @SerialName("points") val points: List<TravelWorkspaceResultDtoTracksEntryPointsEntry>,
  @SerialName("original_sha256") val originalSha256: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class TravelWorkspaceResultDtoDayPlansEntryItemsEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("title") val title: String,
  @SerialName("starts_at") val startsAt: String? = null,
  @SerialName("place_id") val placeId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
data class TravelWorkspaceResultDtoDayPlansEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("plan_date") val planDate: String,
  @SerialName("items") val items: List<TravelWorkspaceResultDtoDayPlansEntryItemsEntry>,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class TravelWorkspaceResultDtoSegmentsEntryMode(val wireValue: String) {
  @SerialName("walk") Walk("walk"),
  @SerialName("bike") Bike("bike"),
  @SerialName("taxi") Taxi("taxi"),
  @SerialName("car") Car("car"),
  @SerialName("bus") Bus("bus"),
  @SerialName("metro") Metro("metro"),
  @SerialName("rail") Rail("rail"),
  @SerialName("flight") Flight("flight"),
  @SerialName("ferry") Ferry("ferry"),
  @SerialName("other") Other("other")
}

@Serializable
enum class TravelWorkspaceResultDtoSegmentsEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelWorkspaceResultDtoSegmentsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("mode") val mode: TravelWorkspaceResultDtoSegmentsEntryMode,
  @SerialName("origin") val origin: String,
  @SerialName("destination") val destination: String,
  @SerialName("starts_at") val startsAt: String?,
  @SerialName("ends_at") val endsAt: String?,
  @SerialName("distance_km") val distanceKm: String?,
  @SerialName("note") val note: String?,
  @SerialName("visibility") val visibility: TravelWorkspaceResultDtoSegmentsEntryVisibility,
  @SerialName("revision") val revision: Long
)

@Serializable
data class TravelWorkspaceResultDto(
  @SerialName("places") val places: List<TravelWorkspaceResultDtoPlacesEntry>,
  @SerialName("maps") val maps: List<TravelWorkspaceResultDtoMapsEntry>,
  @SerialName("trips") val trips: List<TravelWorkspaceResultDtoTripsEntry>,
  @SerialName("selected_trip_id") val selectedTripId: String?,
  @SerialName("active_run") val activeRun: TravelWorkspaceResultDtoActiveRun?,
  @SerialName("tracks") val tracks: List<TravelWorkspaceResultDtoTracksEntry>,
  @SerialName("day_plans") val dayPlans: List<TravelWorkspaceResultDtoDayPlansEntry>,
  @SerialName("segments") val segments: List<TravelWorkspaceResultDtoSegmentsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
enum class ProjectDirectoryResultDtoItemsEntryIcon(val wireValue: String) {
  @SerialName("chart-line") ChartLine("chart-line"),
  @SerialName("notebook-pen") NotebookPen("notebook-pen"),
  @SerialName("library") Library("library"),
  @SerialName("app-window") AppWindow("app-window")
}

@Serializable
enum class ProjectDirectoryResultDtoItemsEntryState(val wireValue: String) {
  @SerialName("configured") Configured("configured"),
  @SerialName("not_configured") NotConfigured("not_configured"),
  @SerialName("disabled") Disabled("disabled")
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ProjectDirectoryResultDtoItemsEntryTarget

@Serializable
@SerialName("browser")
data class ProjectDirectoryResultDtoItemsEntryTargetBrowser(
  @SerialName("url") val url: String
): ProjectDirectoryResultDtoItemsEntryTarget

@Serializable
@SerialName("app_link")
data class ProjectDirectoryResultDtoItemsEntryTargetAppLink(
  @SerialName("url") val url: String,
  @SerialName("package_name") val packageName: String,
  @SerialName("web_fallback_url") val webFallbackUrl: String
): ProjectDirectoryResultDtoItemsEntryTarget

@Serializable
enum class ProjectDirectoryResultDtoItemsEntryAuthHint(val wireValue: String) {
  @SerialName("shadow_identity") ShadowIdentity("shadow_identity"),
  @SerialName("project_managed") ProjectManaged("project_managed"),
  @SerialName("public") Public("public")
}

@Serializable
data class ProjectDirectoryResultDtoItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("subtitle") val subtitle: String,
  @SerialName("icon") val icon: ProjectDirectoryResultDtoItemsEntryIcon,
  @SerialName("state") val state: ProjectDirectoryResultDtoItemsEntryState,
  @SerialName("target") val target: ProjectDirectoryResultDtoItemsEntryTarget? = null,
  @SerialName("auth_hint") val authHint: ProjectDirectoryResultDtoItemsEntryAuthHint,
  @SerialName("order") val order: Long
)

@Serializable
data class ProjectDirectoryResultDto(
  @SerialName("schema_version") val schemaVersion: Double,
  @SerialName("catalog_revision") val catalogRevision: String,
  @SerialName("items") val items: List<ProjectDirectoryResultDtoItemsEntry>
)

@Serializable
enum class LibraryItemResultDtoItemState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("deleted") Deleted("deleted")
}

@Serializable
data class LibraryItemResultDtoItem(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("item_type") val itemType: String,
  @SerialName("current_revision") val currentRevision: Long,
  @SerialName("source_id") val sourceId: String?,
  @SerialName("state") val state: LibraryItemResultDtoItemState,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDtoRevisionsEntry(
  @SerialName("item_id") val itemId: String,
  @SerialName("revision") val revision: Long,
  @SerialName("text") val text: String?,
  @SerialName("url") val url: String?,
  @SerialName("tags") val tags: List<String>,
  @SerialName("reason") val reason: String?,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDtoSourcesEntrySource(
  @SerialName("id") val id: String,
  @SerialName("kind") val kind: String,
  @SerialName("external_id") val externalId: String?,
  @SerialName("captured_on") val capturedOn: String?,
  @SerialName("captured_at") val capturedAt: String?,
  @SerialName("time_zone") val timeZone: String?,
  @SerialName("original_text") val originalText: String?,
  @SerialName("asset_version_id") val assetVersionId: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
data class LibraryItemResultDtoSourcesEntryAsset(
  @SerialName("id") val id: String,
  @SerialName("asset_id") val assetId: String,
  @SerialName("media_type") val mediaType: String,
  @SerialName("sha256") val sha256: String,
  @SerialName("byte_size") val byteSize: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDtoSourcesEntry(
  @SerialName("source") val source: LibraryItemResultDtoSourcesEntrySource,
  @SerialName("asset") val asset: LibraryItemResultDtoSourcesEntryAsset?
)

@Serializable
data class LibraryItemResultDtoAnnotationsEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("anchor") val anchor: JsonElement,
  @SerialName("note") val note: String,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDtoDerivationsEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("source_asset_version_id") val sourceAssetVersionId: String,
  @SerialName("derived_asset_version_id") val derivedAssetVersionId: String,
  @SerialName("kind") val kind: String,
  @SerialName("processor_version") val processorVersion: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDtoProofsEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("revision") val revision: Long,
  @SerialName("content_hash") val contentHash: String,
  @SerialName("asset_hashes") val assetHashes: List<String>,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class LibraryItemResultDtoProcessingJobsEntryKind(val wireValue: String) {
  @SerialName("text_extract") TextExtract("text_extract"),
  @SerialName("ocr") Ocr("ocr"),
  @SerialName("transcript") Transcript("transcript")
}

@Serializable
enum class LibraryItemResultDtoProcessingJobsEntryState(val wireValue: String) {
  @SerialName("queued") Queued("queued"),
  @SerialName("running") Running("running"),
  @SerialName("completed") Completed("completed"),
  @SerialName("failed") Failed("failed")
}

@Serializable
data class LibraryItemResultDtoProcessingJobsEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("source_asset_version_id") val sourceAssetVersionId: String,
  @SerialName("kind") val kind: LibraryItemResultDtoProcessingJobsEntryKind,
  @SerialName("requested_processor") val requestedProcessor: String,
  @SerialName("state") val state: LibraryItemResultDtoProcessingJobsEntryState,
  @SerialName("attempts") val attempts: Long,
  @SerialName("derived_asset_version_id") val derivedAssetVersionId: String?,
  @SerialName("processor_version") val processorVersion: String?,
  @SerialName("last_error") val lastError: String?,
  @SerialName("started_at") val startedAt: String?,
  @SerialName("finished_at") val finishedAt: String?,
  @SerialName("lease_expires_at") val leaseExpiresAt: String?,
  @SerialName("created_at") val createdAt: String,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class LibraryItemResultDtoSnippetsEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("job_id") val jobId: String,
  @SerialName("item_revision") val itemRevision: Long,
  @SerialName("ordinal") val ordinal: Long,
  @SerialName("text") val text: String,
  @SerialName("locator") val locator: JsonElement,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class LibraryItemResultDtoReadingStateState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("completed") Completed("completed")
}

@Serializable
data class LibraryItemResultDtoReadingState(
  @SerialName("item_id") val itemId: String,
  @SerialName("item_revision") val itemRevision: Long,
  @SerialName("locator") val locator: JsonElement,
  @SerialName("progress") val progress: Double,
  @SerialName("state") val state: LibraryItemResultDtoReadingStateState,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
enum class LibraryItemResultDtoLegacyLinksEntryAlgorithm(val wireValue: String) {
  @SerialName("ed25519-sha256-ascii-v1") Ed25519Sha256AsciiV1("ed25519-sha256-ascii-v1"),
  @SerialName("legacy-unverified") LegacyUnverified("legacy-unverified")
}

@Serializable
enum class LibraryItemResultDtoLegacyLinksEntryVerificationState(val wireValue: String) {
  @SerialName("verified") Verified("verified"),
  @SerialName("invalid") Invalid("invalid"),
  @SerialName("unverified") Unverified("unverified")
}

@Serializable
data class LibraryItemResultDtoLegacyLinksEntry(
  @SerialName("id") val id: String,
  @SerialName("item_id") val itemId: String,
  @SerialName("legacy_uri") val legacyUri: String,
  @SerialName("algorithm") val algorithm: LibraryItemResultDtoLegacyLinksEntryAlgorithm,
  @SerialName("source_asset_version_id") val sourceAssetVersionId: String?,
  @SerialName("signed_content_sha256") val signedContentSha256: String?,
  @SerialName("verification_state") val verificationState: LibraryItemResultDtoLegacyLinksEntryVerificationState,
  @SerialName("verification_error") val verificationError: String?,
  @SerialName("checked_at") val checkedAt: String?,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class LibraryItemResultDto(
  @SerialName("item") val item: LibraryItemResultDtoItem,
  @SerialName("revisions") val revisions: List<LibraryItemResultDtoRevisionsEntry>,
  @SerialName("sources") val sources: List<LibraryItemResultDtoSourcesEntry>,
  @SerialName("annotations") val annotations: List<LibraryItemResultDtoAnnotationsEntry>,
  @SerialName("derivations") val derivations: List<LibraryItemResultDtoDerivationsEntry>,
  @SerialName("proofs") val proofs: List<LibraryItemResultDtoProofsEntry>,
  @SerialName("processing_jobs") val processingJobs: List<LibraryItemResultDtoProcessingJobsEntry>,
  @SerialName("snippets") val snippets: List<LibraryItemResultDtoSnippetsEntry>,
  @SerialName("reading_state") val readingState: LibraryItemResultDtoReadingState?,
  @SerialName("legacy_links") val legacyLinks: List<LibraryItemResultDtoLegacyLinksEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
data class TravelTripResultDtoTrip(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class TravelTripResultDtoReservationsEntryReservationType(val wireValue: String) {
  @SerialName("flight") Flight("flight"),
  @SerialName("rail") Rail("rail"),
  @SerialName("hotel") Hotel("hotel"),
  @SerialName("restaurant") Restaurant("restaurant"),
  @SerialName("activity") Activity("activity"),
  @SerialName("other") Other("other")
}

@Serializable
enum class TravelTripResultDtoReservationsEntryState(val wireValue: String) {
  @SerialName("pending") Pending("pending"),
  @SerialName("waitlisted") Waitlisted("waitlisted"),
  @SerialName("confirmed") Confirmed("confirmed"),
  @SerialName("changed") Changed("changed"),
  @SerialName("cancelled") Cancelled("cancelled"),
  @SerialName("refunded") Refunded("refunded")
}

@Serializable
enum class TravelTripResultDtoReservationsEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelTripResultDtoReservationsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("reservation_type") val reservationType: TravelTripResultDtoReservationsEntryReservationType,
  @SerialName("title") val title: String,
  @SerialName("starts_at") val startsAt: String?,
  @SerialName("ends_at") val endsAt: String?,
  @SerialName("state") val state: TravelTripResultDtoReservationsEntryState,
  @SerialName("visibility") val visibility: TravelTripResultDtoReservationsEntryVisibility,
  @SerialName("origin") val origin: String?,
  @SerialName("destination") val destination: String?,
  @SerialName("service_number") val serviceNumber: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("confirmation_code") val confirmationCode: String? = null,
  @SerialName("seat") val seat: String? = null,
  @SerialName("fare_entry_id") val fareEntryId: String? = null,
  @SerialName("source_id") val sourceId: String? = null
)

@Serializable
enum class TravelTripResultDtoSegmentsEntryMode(val wireValue: String) {
  @SerialName("walk") Walk("walk"),
  @SerialName("bike") Bike("bike"),
  @SerialName("taxi") Taxi("taxi"),
  @SerialName("car") Car("car"),
  @SerialName("bus") Bus("bus"),
  @SerialName("metro") Metro("metro"),
  @SerialName("rail") Rail("rail"),
  @SerialName("flight") Flight("flight"),
  @SerialName("ferry") Ferry("ferry"),
  @SerialName("other") Other("other")
}

@Serializable
enum class TravelTripResultDtoSegmentsEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelTripResultDtoSegmentsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("mode") val mode: TravelTripResultDtoSegmentsEntryMode,
  @SerialName("origin") val origin: String,
  @SerialName("destination") val destination: String,
  @SerialName("starts_at") val startsAt: String?,
  @SerialName("ends_at") val endsAt: String?,
  @SerialName("distance_km") val distanceKm: String?,
  @SerialName("visibility") val visibility: TravelTripResultDtoSegmentsEntryVisibility,
  @SerialName("revision") val revision: Long,
  @SerialName("voided_at") val voidedAt: String?,
  @SerialName("created_at") val createdAt: String,
  @SerialName("source_id") val sourceId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
enum class TravelTripResultDtoVisitsEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelTripResultDtoVisitsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("place_name") val placeName: String,
  @SerialName("latitude") val latitude: String?,
  @SerialName("longitude") val longitude: String?,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("visibility") val visibility: TravelTripResultDtoVisitsEntryVisibility,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String,
  @SerialName("source_id") val sourceId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
data class TravelTripResultDtoDayPlansEntryItemsEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("title") val title: String,
  @SerialName("starts_at") val startsAt: String? = null,
  @SerialName("place_id") val placeId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
data class TravelTripResultDtoDayPlansEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("plan_date") val planDate: String,
  @SerialName("items") val items: List<TravelTripResultDtoDayPlansEntryItemsEntry>,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class TravelTripResultDtoMembersEntryRole(val wireValue: String) {
  @SerialName("owner") Owner("owner"),
  @SerialName("editor") Editor("editor"),
  @SerialName("viewer") Viewer("viewer")
}

@Serializable
enum class TravelTripResultDtoMembersEntryVisibility(val wireValue: String) {
  @SerialName("shared") Shared("shared"),
  @SerialName("private") Private("private")
}

@Serializable
data class TravelTripResultDtoMembersEntry(
  @SerialName("member_id") val memberId: String,
  @SerialName("role") val role: TravelTripResultDtoMembersEntryRole,
  @SerialName("visibility") val visibility: TravelTripResultDtoMembersEntryVisibility,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class TravelTripResultDtoPlanVersionsEntrySnapshotDaysEntryItemsEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("title") val title: String,
  @SerialName("starts_at") val startsAt: String? = null,
  @SerialName("place_id") val placeId: String? = null,
  @SerialName("note") val note: String? = null
)

@Serializable
data class TravelTripResultDtoPlanVersionsEntrySnapshotDaysEntry(
  @SerialName("plan_date") val planDate: String,
  @SerialName("items") val items: List<TravelTripResultDtoPlanVersionsEntrySnapshotDaysEntryItemsEntry>
)

@Serializable
data class TravelTripResultDtoPlanVersionsEntrySnapshot(
  @SerialName("days") val days: List<TravelTripResultDtoPlanVersionsEntrySnapshotDaysEntry>,
  @SerialName("stop_count") val stopCount: Long
)

@Serializable
data class TravelTripResultDtoPlanVersionsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("version") val version: Long,
  @SerialName("label") val label: String?,
  @SerialName("note") val note: String?,
  @SerialName("snapshot") val snapshot: TravelTripResultDtoPlanVersionsEntrySnapshot,
  @SerialName("content_hash") val contentHash: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
enum class TravelTripResultDtoMyRunsEntryState(val wireValue: String) {
  @SerialName("active") Active("active"),
  @SerialName("completed") Completed("completed"),
  @SerialName("abandoned") Abandoned("abandoned")
}

@Serializable
enum class TravelTripResultDtoMyRunsEntryOutcomesEntryState(val wireValue: String) {
  @SerialName("arrived") Arrived("arrived"),
  @SerialName("skipped") Skipped("skipped")
}

@Serializable
data class TravelTripResultDtoMyRunsEntryOutcomesEntry(
  @SerialName("stop_id") val stopId: String,
  @SerialName("state") val state: TravelTripResultDtoMyRunsEntryOutcomesEntryState,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("updated_at") val updatedAt: String
)

@Serializable
data class TravelTripResultDtoMyRunsEntry(
  @SerialName("id") val id: String,
  @SerialName("trip_id") val tripId: String,
  @SerialName("plan_version_id") val planVersionId: String,
  @SerialName("state") val state: TravelTripResultDtoMyRunsEntryState,
  @SerialName("started_at") val startedAt: String,
  @SerialName("completed_at") val completedAt: String?,
  @SerialName("outcomes") val outcomes: List<TravelTripResultDtoMyRunsEntryOutcomesEntry>
)

@Serializable
data class TravelTripResultDtoRevisionsEntrySnapshot(
  @SerialName("id") val id: String,
  @SerialName("title") val title: String,
  @SerialName("starts_on") val startsOn: String,
  @SerialName("ends_on") val endsOn: String,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class TravelTripResultDtoRevisionsEntry(
  @SerialName("trip_id") val tripId: String,
  @SerialName("revision") val revision: Long,
  @SerialName("snapshot") val snapshot: TravelTripResultDtoRevisionsEntrySnapshot,
  @SerialName("reason") val reason: String,
  @SerialName("created_at") val createdAt: String
)

@Serializable
data class TravelTripResultDto(
  @SerialName("trip") val trip: TravelTripResultDtoTrip,
  @SerialName("reservations") val reservations: List<TravelTripResultDtoReservationsEntry>,
  @SerialName("segments") val segments: List<TravelTripResultDtoSegmentsEntry>,
  @SerialName("visits") val visits: List<TravelTripResultDtoVisitsEntry>,
  @SerialName("day_plans") val dayPlans: List<TravelTripResultDtoDayPlansEntry>,
  @SerialName("members") val members: List<TravelTripResultDtoMembersEntry>,
  @SerialName("plan_versions") val planVersions: List<TravelTripResultDtoPlanVersionsEntry>,
  @SerialName("my_runs") val myRuns: List<TravelTripResultDtoMyRunsEntry>,
  @SerialName("revisions") val revisions: List<TravelTripResultDtoRevisionsEntry>,
  @SerialName("as_of") val asOf: String
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface LifeRecordResultDto

@Serializable
enum class LifeRecordResultDtoRecordState(val wireValue: String) {
  @SerialName("draft") Draft("draft"),
  @SerialName("confirmed") Confirmed("confirmed"),
  @SerialName("voided") Voided("voided")
}

@Serializable
data class LifeRecordResultDtoRecordPurchase(
  @SerialName("id") val id: String,
  @SerialName("record_id") val recordId: String,
  @SerialName("merchant") val merchant: String?,
  @SerialName("amount") val amount: String?,
  @SerialName("currency") val currency: String,
  @SerialName("category") val category: String?,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("source_id") val sourceId: String? = null,
  @SerialName("scene") val scene: String?,
  @SerialName("channel_name_raw") val channelNameRaw: String?,
  @SerialName("place_ref") val placeRef: String?,
  @SerialName("rating") val rating: Long?,
  @SerialName("would_repeat") val wouldRepeat: Boolean?,
  @SerialName("revision") val revision: Long
)

@Serializable
data class LifeRecordResultDtoRecordPurchaseItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("purchase_id") val purchaseId: String,
  @SerialName("position") val position: Long,
  @SerialName("raw_name") val rawName: String,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit_price") val unitPrice: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("line_amount") val lineAmount: String?,
  @SerialName("category_key") val categoryKey: String?
)

@Serializable
enum class LifeRecordResultDtoRecordMoneyEntryEntryType(val wireValue: String) {
  @SerialName("expense") Expense("expense"),
  @SerialName("income") Income("income"),
  @SerialName("refund") Refund("refund")
}

@Serializable
enum class LifeRecordResultDtoRecordMoneyEntryPaymentMethod(val wireValue: String) {
  @SerialName("alipay") Alipay("alipay"),
  @SerialName("wechat") Wechat("wechat"),
  @SerialName("jd_pay") JdPay("jd_pay"),
  @SerialName("jd_baitiao") JdBaitiao("jd_baitiao"),
  @SerialName("huabei") Huabei("huabei"),
  @SerialName("gift_card") GiftCard("gift_card"),
  @SerialName("cash") Cash("cash"),
  @SerialName("bank_card") BankCard("bank_card"),
  @SerialName("bank_transfer") BankTransfer("bank_transfer"),
  @SerialName("mixed") Mixed("mixed"),
  @SerialName("other") Other("other")
}

@Serializable
data class LifeRecordResultDtoRecordMoneyEntry(
  @SerialName("id") val id: String,
  @SerialName("record_id") val recordId: String,
  @SerialName("entry_type") val entryType: LifeRecordResultDtoRecordMoneyEntryEntryType,
  @SerialName("amount") val amount: String,
  @SerialName("currency") val currency: String,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("category") val category: String?,
  @SerialName("counterparty") val counterparty: String?,
  @SerialName("source_id") val sourceId: String? = null,
  @SerialName("payment_method") val paymentMethod: LifeRecordResultDtoRecordMoneyEntryPaymentMethod?,
  @SerialName("source_scale") val sourceScale: Long,
  @SerialName("revision") val revision: Long
)

@Serializable
enum class LifeRecordResultDtoRecordMealsEntryMealType(val wireValue: String) {
  @SerialName("breakfast") Breakfast("breakfast"),
  @SerialName("lunch") Lunch("lunch"),
  @SerialName("dinner") Dinner("dinner"),
  @SerialName("snack") Snack("snack"),
  @SerialName("other") Other("other")
}

@Serializable
data class LifeRecordResultDtoRecordMealsEntryItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("meal_id") val mealId: String,
  @SerialName("position") val position: Long,
  @SerialName("name") val name: String,
  @SerialName("food_ref_id") val foodRefId: String?,
  @SerialName("free_text") val freeText: String?,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("amount_g") val amountG: String?,
  @SerialName("energy_kcal") val energyKcal: String?,
  @SerialName("protein_g") val proteinG: String?,
  @SerialName("fat_g") val fatG: String?,
  @SerialName("carb_g") val carbG: String?,
  @SerialName("fiber_g") val fiberG: String?,
  @SerialName("sodium_mg") val sodiumMg: String?,
  @SerialName("consumed_fraction") val consumedFraction: String?,
  @SerialName("provenance") val provenance: String?,
  @SerialName("grouping_origin") val groupingOrigin: String?,
  @SerialName("estimate") val estimate: Boolean,
  @SerialName("evidence_note") val evidenceNote: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
data class LifeRecordResultDtoRecordMealsEntry(
  @SerialName("id") val id: String,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("meal_type") val mealType: LifeRecordResultDtoRecordMealsEntryMealType,
  @SerialName("revision") val revision: Long,
  @SerialName("items") val items: List<LifeRecordResultDtoRecordMealsEntryItemsEntry>
)

@Serializable
data class LifeRecordResultDtoRecordSourcesEntry(
  @SerialName("id") val id: String,
  @SerialName("kind") val kind: String,
  @SerialName("external_id") val externalId: String?,
  @SerialName("captured_on") val capturedOn: String?,
  @SerialName("captured_at") val capturedAt: String?,
  @SerialName("time_zone") val timeZone: String?,
  @SerialName("original_text") val originalText: String?,
  @SerialName("asset_version_id") val assetVersionId: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
@SerialName("record")
data class LifeRecordResultDtoRecord(
  @SerialName("record_id") val recordId: String,
  @SerialName("state") val state: LifeRecordResultDtoRecordState,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("revision") val revision: Long,
  @SerialName("purchase") val purchase: LifeRecordResultDtoRecordPurchase? = null,
  @SerialName("purchase_items") val purchaseItems: List<LifeRecordResultDtoRecordPurchaseItemsEntry>? = null,
  @SerialName("money_entry") val moneyEntry: LifeRecordResultDtoRecordMoneyEntry? = null,
  @SerialName("meals") val meals: List<LifeRecordResultDtoRecordMealsEntry>? = null,
  @SerialName("sources") val sources: List<LifeRecordResultDtoRecordSourcesEntry>? = null
): LifeRecordResultDto

@Serializable
enum class LifeRecordResultDtoMealMealType(val wireValue: String) {
  @SerialName("breakfast") Breakfast("breakfast"),
  @SerialName("lunch") Lunch("lunch"),
  @SerialName("dinner") Dinner("dinner"),
  @SerialName("snack") Snack("snack"),
  @SerialName("other") Other("other")
}

@Serializable
data class LifeRecordResultDtoMealItemsEntry(
  @SerialName("id") val id: String,
  @SerialName("meal_id") val mealId: String,
  @SerialName("position") val position: Long,
  @SerialName("name") val name: String,
  @SerialName("food_ref_id") val foodRefId: String?,
  @SerialName("free_text") val freeText: String?,
  @SerialName("quantity") val quantity: String?,
  @SerialName("unit") val unit: String?,
  @SerialName("amount_g") val amountG: String?,
  @SerialName("energy_kcal") val energyKcal: String?,
  @SerialName("protein_g") val proteinG: String?,
  @SerialName("fat_g") val fatG: String?,
  @SerialName("carb_g") val carbG: String?,
  @SerialName("fiber_g") val fiberG: String?,
  @SerialName("sodium_mg") val sodiumMg: String?,
  @SerialName("consumed_fraction") val consumedFraction: String?,
  @SerialName("provenance") val provenance: String?,
  @SerialName("grouping_origin") val groupingOrigin: String?,
  @SerialName("estimate") val estimate: Boolean,
  @SerialName("evidence_note") val evidenceNote: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
enum class LifeRecordResultDtoMealPaymentsEntryEntryType(val wireValue: String) {
  @SerialName("expense") Expense("expense"),
  @SerialName("income") Income("income"),
  @SerialName("refund") Refund("refund")
}

@Serializable
enum class LifeRecordResultDtoMealPaymentsEntryPaymentMethod(val wireValue: String) {
  @SerialName("alipay") Alipay("alipay"),
  @SerialName("wechat") Wechat("wechat"),
  @SerialName("jd_pay") JdPay("jd_pay"),
  @SerialName("jd_baitiao") JdBaitiao("jd_baitiao"),
  @SerialName("huabei") Huabei("huabei"),
  @SerialName("gift_card") GiftCard("gift_card"),
  @SerialName("cash") Cash("cash"),
  @SerialName("bank_card") BankCard("bank_card"),
  @SerialName("bank_transfer") BankTransfer("bank_transfer"),
  @SerialName("mixed") Mixed("mixed"),
  @SerialName("other") Other("other")
}

@Serializable
data class LifeRecordResultDtoMealPaymentsEntry(
  @SerialName("id") val id: String,
  @SerialName("record_id") val recordId: String,
  @SerialName("entry_type") val entryType: LifeRecordResultDtoMealPaymentsEntryEntryType,
  @SerialName("amount") val amount: String,
  @SerialName("currency") val currency: String,
  @SerialName("occurred_on") val occurredOn: String,
  @SerialName("occurred_at") val occurredAt: String?,
  @SerialName("time_zone") val timeZone: String,
  @SerialName("note") val note: String?,
  @SerialName("category") val category: String?,
  @SerialName("counterparty") val counterparty: String?,
  @SerialName("source_id") val sourceId: String? = null,
  @SerialName("payment_method") val paymentMethod: LifeRecordResultDtoMealPaymentsEntryPaymentMethod?,
  @SerialName("source_scale") val sourceScale: Long,
  @SerialName("revision") val revision: Long
)

@Serializable
data class LifeRecordResultDtoMealSourcesEntry(
  @SerialName("id") val id: String,
  @SerialName("kind") val kind: String,
  @SerialName("external_id") val externalId: String?,
  @SerialName("captured_on") val capturedOn: String?,
  @SerialName("captured_at") val capturedAt: String?,
  @SerialName("time_zone") val timeZone: String?,
  @SerialName("original_text") val originalText: String?,
  @SerialName("asset_version_id") val assetVersionId: String?,
  @SerialName("revision") val revision: Long
)

@Serializable
@SerialName("meal")
data class LifeRecordResultDtoMeal(
  @SerialName("meal_id") val mealId: String,
  @SerialName("occurred_on") val occurredOn: String? = null,
  @SerialName("occurred_at") val occurredAt: String? = null,
  @SerialName("time_zone") val timeZone: String? = null,
  @SerialName("meal_type") val mealType: LifeRecordResultDtoMealMealType? = null,
  @SerialName("note") val note: String? = null,
  @SerialName("revision") val revision: Long? = null,
  @SerialName("items") val items: List<LifeRecordResultDtoMealItemsEntry>? = null,
  @SerialName("payments") val payments: List<LifeRecordResultDtoMealPaymentsEntry>? = null,
  @SerialName("sources") val sources: List<LifeRecordResultDtoMealSourcesEntry>? = null
): LifeRecordResultDto
