import { readFile, writeFile } from "node:fs/promises";
import { Pool, type PoolClient } from "pg";
import { canonical, sha256, stableMigrationId, validateBundle, type MigrationBundle } from "./bundle.js";

type Mode = "dry_run"|"apply"|"final_delta";
const [command, bundlePath, reportPath] = process.argv.slice(2);
if (!command || !bundlePath) throw new Error("usage: cli <validate|plan|apply|final-delta|reconcile|cutover-check> <bundle.json> [report.json]");
const raw = JSON.parse(await readFile(bundlePath,"utf8"));
const bundle = validateBundle(raw);
const bundleHash = sha256(bundle);
const ownerMapHash = sha256(bundle.owners);
const batchMode:Mode=command==="validate"||command==="plan"?"dry_run":command==="final-delta"?"final_delta":"apply";
const batchIdFor=(mode:Mode)=>stableMigrationId("migration",[bundleHash,bundle.mapper_version,ownerMapHash,mode]);

function plan(value: MigrationBundle,batchId:string) {
  return value.objects.flatMap(object => object.targets.map(target => ({
    item_id: stableMigrationId("migration_item", [batchId,object.source,target.component]),
    source: object.source,
    source_pk_hash: sha256(object.source.pk),
    payload_hash: sha256(object.payload),
    target
  })));
}
if(command==="validate"||command==="plan"){
  const batchId=batchIdFor("dry_run"),items=plan(bundle,batchId),baseReport={protocol:"shadow.migration-report",batch_id:batchId,bundle_hash:bundleHash,source_snapshot:bundle.source_snapshot,mapper_version:bundle.mapper_version,objects:bundle.objects.length,components:items.length};
  const report={...baseReport,writes:0,items:command==="plan"?items.map(({item_id,source,target})=>({item_id,source,target_type:target.type,target_id:target.id,component:target.component})):undefined};
  if(reportPath)await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");else console.log(JSON.stringify(report,null,2));
} else {
  const connectionString=process.env.DATABASE_URL;
  if(!connectionString)throw new Error("DATABASE_URL is required");
  const pool=new Pool({connectionString});
  try {
    const selected=command==="reconcile"||command==="cutover-check"?await pool.query<{id:string;mode:Mode}>("select id,mode from migration_batches where bundle_hash=$1 and mapper_version=$2 and owner_map_hash=$3 and mode in ('apply','final_delta') order by case mode when 'final_delta' then 0 else 1 end,started_at desc limit 1",[bundleHash,bundle.mapper_version,ownerMapHash]):undefined;
    const activeMode=selected?.rows[0]?.mode??batchMode,activeBatchId=selected?.rows[0]?.id??batchIdFor(activeMode),items=plan(bundle,activeBatchId),baseReport={protocol:"shadow.migration-report",batch_id:activeBatchId,bundle_hash:bundleHash,source_snapshot:bundle.source_snapshot,mapper_version:bundle.mapper_version,objects:bundle.objects.length,components:items.length};
    const report=command==="apply"||command==="final-delta"?await apply(pool,bundle,items,activeBatchId,bundleHash,ownerMapHash,activeMode):command==="reconcile"?await reconcile(pool,bundle,items,activeBatchId):command==="cutover-check"?await cutoverCheck(pool,bundle,items,activeBatchId,bundleHash,ownerMapHash):(()=>{throw new Error(`unknown command: ${command}`)})();
    if(reportPath)await writeFile(reportPath,JSON.stringify({...baseReport,...report},null,2)+"\n");else console.log(JSON.stringify({...baseReport,...report},null,2));
    const gate=report as {complete?:boolean;ready?:boolean};if((command==="reconcile"&&gate.complete!==true)||(command==="cutover-check"&&gate.ready!==true))process.exitCode=2;
  } finally { await pool.end(); }
}

async function apply(pool:Pool,bundle:MigrationBundle,items:ReturnType<typeof plan>,id:string,bundleHash:string,ownerMapHash:string,mode:Mode){
  const client=await pool.connect();let applied=0,replayed=0,conflicts=0;
  try {await client.query("begin");
    await client.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[`shadow-life:migration:${id}`]);
    await client.query("insert into migration_batches(id,bundle_hash,source_instance,source_snapshot,target_schema_version,mapper_version,owner_map_hash,mode,stage) values($1,$2,$3,$4,$5,$6,$7,$8,'applying') on conflict(id) do update set stage='applying'",[id,bundleHash,bundle.objects[0]?.source.instance??"empty",bundle.source_snapshot,bundle.target_schema_version,bundle.mapper_version,ownerMapHash,mode]);
    for(const item of items){
      const existing=await client.query<{payload_hash:string,status:string,target_id:string|null,last_applied_target_revision:number|null}>("select payload_hash,status,target_id,last_applied_target_revision from migration_items where id=$1 for update",[item.item_id]);
      if(existing.rowCount){if(existing.rows[0]!.payload_hash!==item.payload_hash)throw new Error(`source revision conflict: ${item.item_id}`);replayed++;continue;}
      const subjectId=bundle.owners[item.source.owner]!;
      await client.query("insert into principals(id) values($1) on conflict do nothing",[subjectId]);
      const prior=await client.query<{target_id:string;payload_hash:string}>("select map.target_id,item.payload_hash from legacy_object_maps map join migration_items item on item.source_instance=map.source_instance and item.source_table=map.source_table and item.source_pk_hash=map.source_pk_hash and item.target_type=map.target_type and item.target_id=map.target_id where map.source_instance=$1 and map.source_table=$2 and map.source_pk_hash=$3 and map.source_owner=$4 and map.target_type=$5 and map.role=$6 order by item.updated_at desc limit 1",[item.source.instance,item.source.table,item.source_pk_hash,item.source.owner,item.target.type,item.target.role]);
      if(prior.rowCount){const status=prior.rows[0]!.payload_hash===item.payload_hash&&prior.rows[0]!.target_id===item.target.id?"replayed":"conflict";await client.query("insert into migration_items(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_revision,payload_hash,target_component,status,target_type,target_id,detail) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",[item.item_id,id,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.revision??null,item.payload_hash,item.target.component,status,item.target.type,item.target.id,{prior_target_id:prior.rows[0]!.target_id}]);if(status==="conflict"){await client.query("insert into migration_conflicts(id,batch_id,migration_item_id,code,expected,actual) values($1,$2,$3,'source_changed_after_import',$4,$5)",[stableMigrationId("migration_conflict",item.item_id),id,item.item_id,{payload_hash:prior.rows[0]!.payload_hash,target_id:prior.rows[0]!.target_id},{payload_hash:item.payload_hash,target_id:item.target.id}]);conflicts++;}else replayed++;continue;}
      await insertTarget(client,item.target.type,item.target.id,subjectId,item.target.data);
      await client.query("insert into legacy_object_maps(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_owner,target_type,target_id,role) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(source_instance,source_table,source_pk_hash,source_owner,target_type,role) do nothing",[stableMigrationId("legacy_map",[item.source,item.target.type,item.target.role]),id,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.owner,item.target.type,item.target.id,item.target.role]);
      await client.query("insert into migration_items(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_revision,payload_hash,target_component,status,target_type,target_id,last_applied_target_revision,detail) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'applied',$10,$11,1,$12)",[item.item_id,id,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.revision??null,item.payload_hash,item.target.component,item.target.type,item.target.id,{decision:"preserved_without_inventing_missing_facts"}]);applied++;
    }
    await client.query("update migration_batches set stage=$2,summary=$3 where id=$1",[id,conflicts?"blocked":"reconciling",{applied,replayed,conflicts}]);await client.query("commit");
  }catch(error){await client.query("rollback");throw error;}finally{client.release();}
  return {applied,replayed,conflicts};
}

async function insertTarget(c:PoolClient,type:string,id:string,subject:string,data:Record<string,unknown>){
  const table=type==="money_entry"?"money_entries":type==="meal"?"meals":type==="health_raw"?"health_raw_records":"library_items";
  const collision=await c.query(`select subject_id from ${table} where id=$1`,[id]);if(collision.rowCount)throw new Error(`target id collision: ${type}/${id}`);
  if(type==="money_entry"){
    const recordId=String(data.record_id??stableMigrationId("record",id));
    if((await c.query("select 1 from consumption_records where id=$1",[recordId])).rowCount)throw new Error(`target id collision: consumption_record/${recordId}`);
    const state=String(data.state??"confirmed");
    await c.query("insert into consumption_records(id,subject_id,record_kind,state,occurred_on,occurred_at,time_zone,note,revision,confirmed_at,voided_at) values($1,$2,'money_only',$3,$4,$5,$6,$7,$8,$9,$10) on conflict(id) do nothing",[recordId,subject,state,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.revision??1,state==="confirmed"?(data.confirmed_at??new Date()):null,state==="voided"?(data.voided_at??new Date()):null]);
    await c.query("insert into money_entries(id,subject_id,entry_type,amount,currency,occurred_on,occurred_at,time_zone,note,category,counterparty,record_id,payment_method,source_scale,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) on conflict(id) do nothing",[id,subject,data.entry_type,data.amount,data.currency,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.category??null,data.counterparty??null,recordId,data.payment_method??null,data.source_scale??2,data.revision??1]);return;
  }
  if(type==="meal"){
    const entries=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];for(let p=0;p<entries.length;p++){const itemId=String(entries[p]!.id??stableMigrationId("intake",[id,p]));if((await c.query("select 1 from intake_items where id=$1",[itemId])).rowCount)throw new Error(`target id collision: intake_item/${itemId}`);}
    await c.query("insert into meals(id,subject_id,occurred_on,occurred_at,time_zone,meal_type,note,revision) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(id) do nothing",[id,subject,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.meal_type??"other",data.note??null,data.revision??1]);
    for(let p=0;p<entries.length;p++){const item=entries[p]!;await c.query("insert into intake_items(id,subject_id,meal_id,position,name,quantity,unit,energy_kcal,estimate,evidence_note,revision,free_text,amount_g,protein_g,fat_g,carb_g,provenance,grouping_origin) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1,$11,$12,$13,$14,$15,$16,$17)",[String(item.id??stableMigrationId("intake",[id,p])),subject,id,p,item.name??item.free_text,item.quantity??null,item.unit??null,item.energy_kcal??null,item.estimate??false,item.evidence_note??null,item.free_text??null,item.amount_g??null,item.protein_g??null,item.fat_g??null,item.carb_g??null,item.provenance??"legacy",data.grouping_origin??"legacy_meal_bucket"]);}return;
  }
  if(type==="health_raw"){
    const sourceId=String(data.source_instance_id??stableMigrationId("health_source",[subject,data.source_type,data.source_instance_key]));
    await c.query("insert into health_source_instances(id,subject_id,source_type,instance_key,fingerprint,permission_state,sync_epoch) values($1,$2,$3,$4,$5,$6,$7) on conflict(subject_id,source_type,instance_key) do nothing",[sourceId,subject,data.source_type??"legacy_health",data.source_instance_key??"legacy",data.source_fingerprint??null,data.permission_state??"historical",data.sync_epoch??1]);
    await c.query("insert into health_raw_records(id,subject_id,source_instance_id,record_type,client_record_id,current_version,current_sync_epoch,current_hash,state,pending_reason,parse_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) on conflict(id) do nothing",[id,subject,sourceId,data.record_type,data.client_record_id,data.record_version??1,data.sync_epoch??1,sha256(data.payload??{}),data.state??"pending",data.pending_reason??null,data.parse_version??"legacy"]);await c.query("insert into health_raw_revisions(raw_id,record_version,payload_hash,payload,change_kind) values($1,$2,$3,$4,$5) on conflict do nothing",[id,data.record_version??1,sha256(data.payload??{}),data.payload??{},data.change_kind??"upsert"]);await c.query("insert into health_normalization_queue(raw_id,raw_version,normalizer_version) values($1,$2,$3) on conflict do nothing",[id,data.record_version??1,data.parse_version??"legacy"]);return;
  }
  await c.query("insert into library_items(id,subject_id,title,item_type,current_revision) values($1,$2,$3,$4,1) on conflict(id) do nothing",[id,subject,data.title??"Legacy archive",data.item_type??"note"]);
  await c.query("insert into library_revisions(item_id,revision,text,url,tags) values($1,1,$2,$3,$4::jsonb) on conflict do nothing",[id,data.text??null,data.url??null,JSON.stringify(data.tags??[])]);
}

async function reconcile(database:Pool|PoolClient,bundle:MigrationBundle,items:ReturnType<typeof plan>,id:string){
  const result=await database.query<{status:string,count:string}>("select status,count(*)::text count from migration_items where batch_id=$1 group by status",[id]);const counts=Object.fromEntries(result.rows.map(row=>[row.status,Number(row.count)]));const disposed=Object.values(counts).reduce((a,b)=>a+b,0),differences:unknown[]=[];for(const item of items){const subject=bundle.owners[item.source.owner]!;differences.push(...await verifyTarget(database,item.target.type,item.target.id,subject,item.target.data));}const complete=disposed===items.length&&(counts.pending??0)===0&&(counts.blocked??0)===0&&(counts.conflict??0)===0&&differences.length===0;
  const targetFactHash=sha256(items.map(item=>({subject:bundle.owners[item.source.owner],type:item.target.type,id:item.target.id,data:item.target.data}))),reconciledAt=new Date().toISOString();await database.query("update migration_batches set stage=$2,completed_at=case when $2='completed' then now() else null end,summary=summary||$3::jsonb where id=$1",[id,complete?"completed":"blocked",JSON.stringify({reconciled:complete,reconciled_at:reconciledAt,target_fact_hash:targetFactHash,components:items.length,differences})]);return{complete,expected_components:items.length,disposed_components:disposed,statuses:counts,source_objects:bundle.objects.length,differences,target_fact_hash:targetFactHash,reconciled_at:reconciledAt};
}
async function cutoverCheck(pool:Pool,bundle:MigrationBundle,planned:ReturnType<typeof plan>,id:string,bundleHash:string,ownerMapHash:string){
  const client=await pool.connect(),lockKey=`shadow-life:migration:${id}`;try{await client.query("select pg_advisory_lock(hashtextextended($1,0))",[lockKey]);await client.query("begin isolation level repeatable read");try{const fresh=await reconcile(client,bundle,planned,id);const batch=await client.query<{stage:string;summary:Record<string,unknown>;bundle_hash:string;source_snapshot:string;mapper_version:string;owner_map_hash:string;mode:Mode}>("select stage,summary,bundle_hash,source_snapshot,mapper_version,owner_map_hash,mode from migration_batches where id=$1",[id]);const items=await client.query("select count(*) filter(where status in ('pending','blocked','conflict'))::int unresolved from migration_items where batch_id=$1",[id]);const projections=await client.query("select count(*) filter(where state<>'completed')::int incomplete from projection_checkpoints",[]);const healthWork=await client.query("select count(*) filter(where state<>'completed')::int incomplete from health_normalization_queue",[]);const healthDays=await client.query("select count(*) filter(where not valid)::int incomplete from health_projection_invalidations",[]);const epochs=await client.query<{domain:string;epoch:number;stage:string;target_schema:string}>("select domain,epoch,stage,target_schema from write_epochs order by domain",[]),row=batch.rows[0];const checks={final_delta_batch:row?.mode==="final_delta",source_snapshot_bound:row?.bundle_hash===bundleHash&&row.source_snapshot===bundle.source_snapshot&&row.mapper_version===bundle.mapper_version&&row.owner_map_hash===ownerMapHash,batch_completed:row?.stage==="completed",target_reconciled:fresh.complete&&row?.summary?.reconciled===true,migration_items_resolved:items.rows[0]?.unresolved===0,projections_completed:projections.rows[0]?.incomplete===0,health_normalization_completed:healthWork.rows[0]?.incomplete===0,health_daily_projections_completed:healthDays.rows[0]?.incomplete===0,write_epochs_frozen:epochs.rows.length===2&&epochs.rows.every(epoch=>epoch.stage==="read_only"),write_epochs:epochs.rows};const ready=checks.final_delta_batch&&checks.source_snapshot_bound&&checks.batch_completed&&checks.target_reconciled&&checks.migration_items_resolved&&checks.projections_completed&&checks.health_normalization_completed&&checks.health_daily_projections_completed&&checks.write_epochs_frozen;await client.query("commit");return{ready,checks,source_snapshot:bundle.source_snapshot,target_fact_hash:fresh.target_fact_hash,reconciled_at:fresh.reconciled_at};}catch(error){await client.query("rollback");throw error;}}finally{await client.query("select pg_advisory_unlock(hashtextextended($1,0))",[lockKey]).catch(()=>undefined);client.release();}
}

async function verifyTarget(pool:Pool|PoolClient,type:string,id:string,subject:string,expected:Record<string,unknown>):Promise<unknown[]>{
  let actual:Record<string,unknown>|undefined;
  if(type==="money_entry")actual=(await pool.query("select entry.entry_type,entry.amount::text amount,entry.currency,entry.occurred_on::text,entry.payment_method,entry.source_scale,record.state from money_entries entry join consumption_records record on record.id=entry.record_id where entry.id=$1 and entry.subject_id=$2",[id,subject])).rows[0];
  else if(type==="meal"){actual=(await pool.query("select meal.occurred_on::text,meal.time_zone,meal.meal_type,meal.note,(select grouping_origin from intake_items where meal_id=meal.id and effective order by position limit 1) grouping_origin from meals meal where meal.id=$1 and meal.subject_id=$2",[id,subject])).rows[0];if(actual&&Array.isArray(expected.items)){const rows=(await pool.query("select id,name,quantity::text,unit,energy_kcal::text,free_text,amount_g::text,protein_g::text,fat_g::text,carb_g::text,provenance,grouping_origin from intake_items where meal_id=$1 and effective order by position",[id])).rows;actual.items=rows;}}
  else if(type==="health_raw")actual=(await pool.query("select raw.record_type,raw.client_record_id,raw.current_version record_version,raw.state,revision.payload,revision.change_kind from health_raw_records raw join health_raw_revisions revision on revision.raw_id=raw.id and revision.record_version=raw.current_version where raw.id=$1 and raw.subject_id=$2",[id,subject])).rows[0];
  else actual=(await pool.query("select item.title,item.item_type,revision.text,revision.url,revision.tags from library_items item join library_revisions revision on revision.item_id=item.id and revision.revision=item.current_revision where item.id=$1 and item.subject_id=$2",[id,subject])).rows[0];
  if(!actual)return[{target_type:type,target_id:id,field:"$",expected:"present",actual:"missing"}];const differences:unknown[]=[];for(const [key,value] of Object.entries(expected)){if(key==="record_id"||key==="confirmed_at"||key==="voided_at"||key==="time_zone"&&actual[key]===undefined)continue;const left=normalize(value),right=normalize(project(actual[key],value));if(canonical(left)!==canonical(right))differences.push({target_type:type,target_id:id,field:key,expected:left,actual:right});}return differences;
}
function normalize(value:unknown):unknown{if(typeof value==="string"&&/^-?\d+(?:\.\d+)?$/u.test(value)){const normalized=value.replace(/(\.\d*?)0+$/u,"$1").replace(/\.$/u,"");return normalized==="-0"?"0":normalized;}if(Array.isArray(value))return value.map(normalize);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([,item])=>item!==null&&item!==undefined).map(([key,item])=>[key,normalize(item)]));return value;}
function project(actual:unknown,expected:unknown):unknown{if(Array.isArray(expected))return Array.isArray(actual)?expected.map((item,index)=>project(actual[index],item)):actual;if(expected&&typeof expected==="object"&&actual&&typeof actual==="object"){const source=actual as Record<string,unknown>;return Object.fromEntries(Object.keys(expected as Record<string,unknown>).map(key=>[key,project(source[key],(expected as Record<string,unknown>)[key])]));}return actual;}
