import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import { canonical, sha256, stableMigrationId, validateBundle, verifyBundleFiles, type MigrationBundle, type VerifiedManifestFile } from "./bundle.js";

type Mode = "dry_run"|"apply"|"final_delta";
const [command, bundlePath, reportPath] = process.argv.slice(2);
if (!command || !bundlePath) throw new Error("usage: cli <validate|plan|apply|restore-drill|final-delta|reconcile|cutover-check> <bundle.json> [report.json]");
const raw = JSON.parse(await readFile(bundlePath,"utf8"));
const bundle = validateBundle(raw);
const verifiedFiles=await verifyBundleFiles(bundle,bundlePath);
const bundleHash = sha256(bundle);
const ownerMapHash = sha256(bundle.owners);
const batchMode:Mode=command==="validate"||command==="plan"?"dry_run":command==="final-delta"?"final_delta":"apply";
const batchIdFor=(mode:Mode)=>stableMigrationId("migration",[bundleHash,bundle.mapper_version,ownerMapHash,mode]);

function plan(value: MigrationBundle,batchId:string) {
  return value.objects.flatMap(object => object.targets.map(target => ({
    item_id: stableMigrationId("migration_item", [batchId,object.source,target.component]),
    change_kind: object.change_kind,
    source: object.source,
    source_pk_hash: sha256(object.source.pk),
    payload_hash: sha256({source:object.payload,change_kind:object.change_kind,target}),
    target
  })));
}
if(command==="validate"||command==="plan"){
  const batchId=batchIdFor("dry_run"),items=plan(bundle,batchId),baseReport={protocol:"shadow.migration-report",batch_id:batchId,bundle_hash:bundleHash,source_snapshot:bundle.source_snapshot,mapper_version:bundle.mapper_version,objects:bundle.objects.length,components:items.length};
  const report={...baseReport,files_verified:verifiedFiles.length,writes:0,items:command==="plan"?items.map(({item_id,source,target})=>({item_id,source,target_type:target.type,target_id:target.id,component:target.component})):undefined};
  if(reportPath)await writeFile(reportPath,JSON.stringify(report,null,2)+"\n");else console.log(JSON.stringify(report,null,2));
} else {
  const connectionString=process.env.DATABASE_URL;
  if(!connectionString)throw new Error("DATABASE_URL is required");
  const pool=new Pool({connectionString});
  try {
    await assertTargetSchema(pool,bundle.target_schema_version);
    const selected=command==="reconcile"||command==="cutover-check"?await pool.query<{id:string;mode:Mode}>("select id,mode from migration_batches where bundle_hash=$1 and mapper_version=$2 and owner_map_hash=$3 and mode in ('apply','final_delta') order by case mode when 'final_delta' then 0 else 1 end,started_at desc limit 1",[bundleHash,bundle.mapper_version,ownerMapHash]):undefined;
    const activeMode=selected?.rows[0]?.mode??batchMode,activeBatchId=selected?.rows[0]?.id??batchIdFor(activeMode),items=plan(bundle,activeBatchId),baseReport={protocol:"shadow.migration-report",batch_id:activeBatchId,bundle_hash:bundleHash,source_snapshot:bundle.source_snapshot,mapper_version:bundle.mapper_version,objects:bundle.objects.length,components:items.length};
    const report=command==="apply"||command==="final-delta"?await apply(pool,bundle,items,activeBatchId,bundleHash,ownerMapHash,activeMode):command==="restore-drill"?await restoreDrill(pool,bundle,items,activeBatchId,bundleHash,ownerMapHash,verifiedFiles):command==="reconcile"?await reconcile(pool,bundle,items,activeBatchId,verifiedFiles):command==="cutover-check"?await cutoverCheck(pool,bundle,items,activeBatchId,bundleHash,ownerMapHash,verifiedFiles):(()=>{throw new Error(`unknown command: ${command}`)})();
    if(reportPath)await writeFile(reportPath,JSON.stringify({...baseReport,files_verified:verifiedFiles.length,...report},null,2)+"\n");else console.log(JSON.stringify({...baseReport,files_verified:verifiedFiles.length,...report},null,2));
    const gate=report as {complete?:boolean;ready?:boolean;conflicts?:number};if((command==="reconcile"&&gate.complete!==true)||(command==="restore-drill"&&gate.ready!==true)||(command==="cutover-check"&&gate.ready!==true)||((command==="apply"||command==="final-delta")&&(gate.conflicts??0)>0))process.exitCode=2;
  } finally { await pool.end(); }
}

async function assertTargetSchema(pool:Pool,expected:string){const result=await pool.query<{name:string}>("select name from schema_migrations order by name desc limit 1"),name=result.rows[0]?.name,current=name?.match(/^(\d{4})_/u)?.[1];if(current!==expected)throw new Error(`bundle targets schema ${expected}, but database is ${current??"unmigrated"}`);}

async function apply(pool:Pool,bundle:MigrationBundle,items:ReturnType<typeof plan>,id:string,bundleHash:string,ownerMapHash:string,mode:Mode){
  const client=await pool.connect();let applied=0,replayed=0,conflicts=0;
  try {await client.query("begin");
    await client.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[`shadow-life:migration:${id}`]);
    await client.query("insert into migration_batches(id,bundle_hash,source_instance,source_snapshot,target_schema_version,mapper_version,owner_map_hash,mode,stage) values($1,$2,$3,$4,$5,$6,$7,$8,'applying') on conflict(id) do update set stage='applying'",[id,bundleHash,bundle.objects[0]?.source.instance??"empty",bundle.source_snapshot,bundle.target_schema_version,bundle.mapper_version,ownerMapHash,mode]);
    for(const item of items){
      const subjectId=bundle.owners[item.source.owner]!;
      const existing=await client.query<{payload_hash:string;status:string;detail:Record<string,unknown>}>("select payload_hash,status,detail from migration_items where id=$1 for update",[item.item_id]);
      if(existing.rowCount){
        const row=existing.rows[0]!;if(row.payload_hash!==item.payload_hash)throw new Error(`source revision conflict: ${item.item_id}`);if(row.status==="conflict"){conflicts++;continue;}
        const verification=item.change_kind==="delete"?await verifyDeletedTarget(client,item.target.type,item.target.id,subjectId):await verifyTarget(client,item.target.type,item.target.id,subjectId,item.target.data),expectedHash=typeof row.detail.applied_fact_hash==="string"?row.detail.applied_fact_hash:undefined,actualHash=sha256(verification.actual);
        if(!expectedHash||expectedHash!==actualHash||verification.differences.length){await client.query("update migration_items set status='conflict',detail=detail||$2::jsonb,updated_at=now() where id=$1",[item.item_id,JSON.stringify({code:"target_changed_before_replay",expected_fact_hash:expectedHash??null,actual_fact_hash:actualHash})]);await client.query("insert into migration_conflicts(id,batch_id,migration_item_id,code,expected,actual) values($1,$2,$3,'target_changed_before_replay',$4,$5) on conflict(id) do update set expected=excluded.expected,actual=excluded.actual,resolved_at=null",[stableMigrationId("migration_conflict",item.item_id),id,item.item_id,{fact_hash:expectedHash??"missing_replay_evidence"},{fact_hash:actualHash,differences:verification.differences}]);conflicts++;continue;}
        replayed++;continue;
      }
      await client.query("insert into principals(id) values($1) on conflict do nothing",[subjectId]);
      const prior=await client.query<{target_id:string;payload_hash:string;source_revision:string|null;last_applied_target_revision:number|null;detail:Record<string,unknown>}>("select map.target_id,item.payload_hash,item.source_revision,item.last_applied_target_revision,item.detail from legacy_object_maps map join migration_items item on item.source_instance=map.source_instance and item.source_table=map.source_table and item.source_pk_hash=map.source_pk_hash and item.target_type=map.target_type and item.target_id=map.target_id where map.source_instance=$1 and map.source_table=$2 and map.source_pk_hash=$3 and map.source_owner=$4 and map.target_type=$5 and map.role=$6 and item.status in ('applied','replayed','archived') order by item.updated_at desc limit 1",[item.source.instance,item.source.table,item.source_pk_hash,item.source.owner,item.target.type,item.target.role]);
      if(prior.rowCount){
        const previous=prior.rows[0]!;
        if(previous.target_id!==item.target.id){await recordConflict(client,item,id,"target_identity_changed",{target_id:previous.target_id},{target_id:item.target.id});conflicts++;continue;}
        const current=item.change_kind==="delete"&&previous.detail.change_kind==="delete"?await verifyDeletedTarget(client,item.target.type,item.target.id,subjectId):await verifyTarget(client,item.target.type,item.target.id,subjectId,{});
        const currentHash=sha256(current.actual),previousHash=typeof previous.detail.applied_fact_hash==="string"?previous.detail.applied_fact_hash:undefined;
        if(previous.payload_hash===item.payload_hash){
          if(previousHash&&currentHash!==previousHash){await recordConflict(client,item,id,"target_changed_after_import",{fact_hash:previousHash},{fact_hash:currentHash,differences:current.differences});conflicts++;continue;}
          await saveMigrationItem(client,item,id,"replayed",previous.last_applied_target_revision,{change_kind:item.change_kind,prior_source_revision:previous.source_revision,applied_fact_hash:previousHash??currentHash});replayed++;continue;
        }
        if(mode!=="final_delta"){await recordConflict(client,item,id,"source_changed_after_import",{payload_hash:previous.payload_hash,source_revision:previous.source_revision},{payload_hash:item.payload_hash,source_revision:item.source.revision});conflicts++;continue;}
        if(!previousHash||currentHash!==previousHash){await recordConflict(client,item,id,"target_changed_after_import",{fact_hash:previousHash??"missing_prior_evidence"},{fact_hash:currentHash,differences:current.differences});conflicts++;continue;}
        const revision=await applyTargetDelta(client,item.target.type,item.target.id,subjectId,item.target.data,item.change_kind);
        const verified=item.change_kind==="delete"?await verifyDeletedTarget(client,item.target.type,item.target.id,subjectId):await verifyTarget(client,item.target.type,item.target.id,subjectId,item.target.data);
        if(verified.differences.length)throw new Error(`delta verification failed: ${item.target.type}/${item.target.id}`);
        await saveMigrationItem(client,item,id,item.change_kind==="delete"?"archived":"applied",revision,{change_kind:item.change_kind,prior_source_revision:previous.source_revision,prior_target_revision:previous.last_applied_target_revision,applied_fact_hash:sha256(verified.actual)});applied++;continue;
      }
      if(item.change_kind==="delete"){await recordConflict(client,item,id,"delete_without_prior_import",{mapped:true},{mapped:false});conflicts++;continue;}
      await insertTarget(client,item.target.type,item.target.id,subjectId,item.target.data);
      await client.query("insert into legacy_object_maps(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_owner,target_type,target_id,role) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(source_instance,source_table,source_pk_hash,source_owner,target_type,role) do nothing",[stableMigrationId("legacy_map",[item.source,item.target.type,item.target.role]),id,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.owner,item.target.type,item.target.id,item.target.role]);
      const verified=await verifyTarget(client,item.target.type,item.target.id,subjectId,item.target.data);if(verified.differences.length)throw new Error(`initial verification failed: ${item.target.type}/${item.target.id}: ${JSON.stringify(verified.differences.slice(0,5))}`);
      await saveMigrationItem(client,item,id,"applied",targetRevision(item.target.type,verified.actual),{change_kind:item.change_kind,decision:"preserved_without_inventing_missing_facts",applied_fact_hash:sha256(verified.actual)});applied++;
    }
    await client.query("update migration_batches set stage=$2,summary=$3 where id=$1",[id,conflicts?"blocked":"reconciling",{applied,replayed,conflicts}]);await client.query("commit");
  }catch(error){await client.query("rollback");throw error;}finally{client.release();}
  return {applied,replayed,conflicts};
}

async function restoreDrill(pool:Pool,bundle:MigrationBundle,items:ReturnType<typeof plan>,id:string,bundleHash:string,ownerMapHash:string,verifiedFiles:VerifiedManifestFile[]){
  if(process.env.SHADOW_MIGRATION_DRILL!=="isolated-empty-database")throw new Error("restore-drill requires SHADOW_MIGRATION_DRILL=isolated-empty-database");
  const counts=await pool.query<{facts:number;batches:number;operations:number}>("select ((select count(*) from consumption_records)+(select count(*) from meals)+(select count(*) from food_references)+(select count(*) from recipes)+(select count(*) from meal_templates)+(select count(*) from health_habit_definitions)+(select count(*) from workout_plans)+(select count(*) from health_goals)+(select count(*) from health_raw_records)+(select count(*) from legacy_archives)+(select count(*) from library_items))::int facts,(select count(*) from migration_batches)::int batches,(select count(*) from operations)::int operations"),before=counts.rows[0]!;if(before.facts!==0||before.batches!==0||before.operations!==0)throw new Error(`restore-drill refuses a non-empty database: ${JSON.stringify(before)}`);
  const first=await apply(pool,bundle,items,id,bundleHash,ownerMapHash,"apply"),second=await apply(pool,bundle,items,id,bundleHash,ownerMapHash,"apply"),reconciliation=await reconcile(pool,bundle,items,id,verifiedFiles),ready=first.applied===items.length&&first.conflicts===0&&second.applied===0&&second.replayed===items.length&&second.conflicts===0&&reconciliation.complete;return{ready,empty_database_verified:true,first_apply:first,replay_apply:second,reconciliation};
}

async function saveMigrationItem(c:PoolClient,item:ReturnType<typeof plan>[number],batchId:string,status:"applied"|"replayed"|"archived",revision:number|null,detail:Record<string,unknown>){await c.query("insert into migration_items(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_revision,payload_hash,target_component,status,target_type,target_id,last_applied_target_revision,detail) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)",[item.item_id,batchId,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.revision??null,item.payload_hash,item.target.component,status,item.target.type,item.target.id,revision,detail]);}
async function recordConflict(c:PoolClient,item:ReturnType<typeof plan>[number],batchId:string,code:string,expected:unknown,actual:unknown){await c.query("insert into migration_items(id,batch_id,source_instance,source_table,source_pk,source_pk_hash,source_revision,payload_hash,target_component,status,target_type,target_id,detail) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'conflict',$10,$11,$12)",[item.item_id,batchId,item.source.instance,item.source.table,item.source.pk,item.source_pk_hash,item.source.revision??null,item.payload_hash,item.target.component,item.target.type,item.target.id,{change_kind:item.change_kind,code}]);await c.query("insert into migration_conflicts(id,batch_id,migration_item_id,code,expected,actual) values($1,$2,$3,$4,$5,$6)",[stableMigrationId("migration_conflict",item.item_id),batchId,item.item_id,code,expected,actual]);}
function targetRevision(type:string,actual:unknown):number|null{if(!actual||typeof actual!=="object")return null;const record=actual as Record<string,unknown>,value=type==="health_raw"?record.record_version:record.revision;return typeof value==="number"?value:Number(value??0)||null;}

async function insertTarget(c:PoolClient,type:string,id:string,subject:string,data:Record<string,unknown>){
  const table=targetTable(type,data);
  const collision=await c.query(`select subject_id from ${table} where id=$1`,[id]);if(collision.rowCount)throw new Error(`target id collision: ${type}/${id}`);
  if(type==="money_entry"){
    const recordId=String(data.record_id??stableMigrationId("record",id));
    if((await c.query("select 1 from consumption_records where id=$1",[recordId])).rowCount)throw new Error(`target id collision: consumption_record/${recordId}`);
    const state=String(data.state??"confirmed");
    await c.query("insert into consumption_records(id,subject_id,record_kind,state,occurred_on,occurred_at,time_zone,note,revision,confirmed_at,voided_at) values($1,$2,'money_only',$3,$4,$5,$6,$7,$8,$9,$10) on conflict(id) do nothing",[recordId,subject,state,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.revision??1,state==="draft"?null:(data.confirmed_at??data.voided_at??data.occurred_at??new Date()),state==="voided"?(data.voided_at??new Date()):null]);
    await c.query("insert into money_entries(id,subject_id,entry_type,amount,currency,occurred_on,occurred_at,time_zone,note,category,counterparty,record_id,payment_method,source_scale,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) on conflict(id) do nothing",[id,subject,data.entry_type,data.amount,data.currency,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.category??null,data.counterparty??null,recordId,data.payment_method??null,data.source_scale??2,data.revision??1]);return;
  }
  if(type==="purchase"){
    const recordId=String(data.record_id??stableMigrationId("record",id)),money=data.money_entry&&typeof data.money_entry==="object"?data.money_entry as Record<string,unknown>:null,items=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];
    if((await c.query("select 1 from consumption_records where id=$1",[recordId])).rowCount)throw new Error(`target id collision: consumption_record/${recordId}`);
    const state=String(data.state??"confirmed");
    await c.query("insert into consumption_records(id,subject_id,record_kind,state,occurred_on,occurred_at,time_zone,note,revision,confirmed_at,voided_at) values($1,$2,'consumption',$3,$4,$5,$6,$7,$8,$9,$10)",[recordId,subject,state,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.revision??1,state==="draft"?null:(data.confirmed_at??new Date()),state==="voided"?(data.voided_at??new Date()):null]);
    await c.query("insert into purchases(id,subject_id,record_id,merchant,amount,currency,category,occurred_on,occurred_at,time_zone,note,scene,channel_name_raw,place_ref,rating,would_repeat,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)",[id,subject,recordId,data.merchant??null,data.amount??null,data.currency??"CNY",data.category??null,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.scene??null,data.channel_name_raw??null,data.place_ref??null,data.rating??null,data.would_repeat??null,data.revision??1]);
    if(money){const moneyId=String(money.id??stableMigrationId("money",id));if((await c.query("select 1 from money_entries where id=$1",[moneyId])).rowCount)throw new Error(`target id collision: money_entry/${moneyId}`);await c.query("insert into money_entries(id,subject_id,entry_type,amount,currency,occurred_on,occurred_at,time_zone,note,category,counterparty,record_id,payment_method,source_scale,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)",[moneyId,subject,money.entry_type,money.amount,money.currency??data.currency??"CNY",data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",money.note??data.note??null,money.category??data.category??null,money.counterparty??data.merchant??null,recordId,money.payment_method??null,money.source_scale??2,money.revision??1]);}
    for(let position=0;position<items.length;position++){const item=items[position]!,itemId=String(item.id??stableMigrationId("purchase_item",[id,position]));if((await c.query("select 1 from purchase_items where id=$1",[itemId])).rowCount)throw new Error(`target id collision: purchase_item/${itemId}`);await c.query("insert into purchase_items(id,purchase_id,position,raw_name,quantity,unit_price,unit,line_amount,category_key) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[itemId,id,position,item.raw_name,item.quantity??null,item.unit_price??null,item.unit??null,item.line_amount??null,item.category_key??null]);}return;
  }
  if(type==="meal"){
    const entries=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];for(let p=0;p<entries.length;p++){const itemId=String(entries[p]!.id??stableMigrationId("intake",[id,p]));if((await c.query("select 1 from intake_items where id=$1",[itemId])).rowCount)throw new Error(`target id collision: intake_item/${itemId}`);}
    await c.query("insert into meals(id,subject_id,occurred_on,occurred_at,time_zone,meal_type,note,state,revision) values($1,$2,$3,$4,$5,$6,$7,'active',$8) on conflict(id) do nothing",[id,subject,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.meal_type??"other",data.note??null,data.revision??1]);
    await insertMealItems(c,id,subject,data);return;
  }
  if(type==="food"){
    await c.query("insert into food_references(id,subject_id,name,serving_amount,serving_unit,nutrients,provenance,state,revision) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9)",[id,subject,data.name,data.serving_amount??null,data.serving_unit??null,JSON.stringify(data.nutrients??{}),data.provenance??"legacy_health",data.state??"active",data.revision??1]);return;
  }
  if(type==="recipe"){
    const items=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];await c.query("insert into recipes(id,subject_id,title,servings,instructions,state,revision) values($1,$2,$3,$4,$5,$6,$7)",[id,subject,data.title,data.servings??1,data.instructions??null,data.state??"active",data.revision??1]);for(let position=0;position<items.length;position++)await c.query("insert into recipe_items(recipe_id,position,snapshot) values($1,$2,$3::jsonb)",[id,position,JSON.stringify(items[position])]);return;
  }
  if(type==="meal_template"){
    const items=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];await c.query("insert into meal_templates(id,subject_id,name,revision) values($1,$2,$3,$4)",[id,subject,data.name,data.revision??1]);for(let position=0;position<items.length;position++)await c.query("insert into meal_template_items(id,template_id,position,snapshot) values($1,$2,$3,$4::jsonb)",[stableMigrationId("template_item",[id,position]),id,position,JSON.stringify(items[position])]);return;
  }
  if(type==="health_plan"){
    const kind=String(data.kind),state=String(data.state??"active"),revision=data.revision??1;if(kind==="habit")await c.query("insert into health_habit_definitions(id,subject_id,name,schedule,state,revision) values($1,$2,$3,$4::jsonb,$5,$6)",[id,subject,data.name,JSON.stringify(data.schedule??{}),state,revision]);else if(kind==="workout")await c.query("insert into workout_plans(id,subject_id,title,schedule,detail,state,revision) values($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7)",[id,subject,data.name,JSON.stringify(data.schedule??{}),JSON.stringify(data.detail??{}),state,revision]);else await c.query("insert into health_goals(id,subject_id,name,metric_key,target_value,unit,due_on,state,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,subject,data.name,data.metric_key,data.target_value,data.unit,data.due_on??null,state,revision]);return;
  }
  if(type==="asset"){
    const bytes=Buffer.from(String(data.bytes_base64),"base64"),contentHash=createHash("sha256").update(bytes).digest("hex");if(bytes.byteLength!==Number(data.byte_size)||contentHash!==data.sha256)throw new Error(`asset content verification failed: ${id}`);const versionId=stableMigrationId("asset_version",[id,data.sha256]),sourceId=stableMigrationId("source",[id,"legacy_health_photo"]),mealId=String(data.meal_id);
    if(!(await c.query("select 1 from meals where id=$1 and subject_id=$2",[mealId,subject])).rowCount)throw new Error(`asset meal target missing: ${mealId}`);
    await c.query("insert into assets(id,subject_id,media_type) values($1,$2,$3)",[id,subject,data.media_type]);await c.query("insert into asset_versions(id,asset_id,sha256,byte_size,storage_key) values($1,$2,$3,$4,$5)",[versionId,id,data.sha256,data.byte_size,`legacy/${id}`]);await c.query("insert into asset_blobs(asset_version_id,bytes) values($1,$2)",[versionId,bytes]);await c.query("insert into sources(id,subject_id,kind,external_id,captured_on,time_zone,original_text,asset_version_id) select $1,$2,'legacy_health_photo',$3,meal.occurred_on,meal.time_zone,$4,$5 from meals meal where meal.id=$6 and meal.subject_id=$2",[sourceId,subject,String(data.filename),`旧 Health 餐次照片：${String(data.filename)}`,versionId,mealId]);await c.query("insert into meal_source_links(meal_id,source_id,role) values($1,$2,'evidence')",[mealId,sourceId]);await c.query("insert into asset_references(asset_id,subject_id,target_type,target_id,role) values($1,$2,'meal',$3,'evidence')",[id,subject,mealId]);return;
  }
  if(type==="health_raw"){
    const sourceId=String(data.source_instance_id??stableMigrationId("health_source",[subject,data.source_type,data.source_instance_key]));
    await c.query("insert into health_source_instances(id,subject_id,source_type,instance_key,fingerprint,permission_state,sync_epoch) values($1,$2,$3,$4,$5,$6,$7) on conflict(subject_id,source_type,instance_key) do nothing",[sourceId,subject,data.source_type??"legacy_health",data.source_instance_key??"legacy",data.source_fingerprint??null,data.permission_state??"historical",data.sync_epoch??1]);
    await c.query("insert into health_raw_records(id,subject_id,source_instance_id,record_type,client_record_id,current_version,current_sync_epoch,current_hash,state,pending_reason,parse_version) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) on conflict(id) do nothing",[id,subject,sourceId,data.record_type,data.client_record_id,data.record_version??1,data.sync_epoch??1,sha256(data.payload??{}),data.state??"pending",data.pending_reason??null,data.parse_version??"legacy"]);await c.query("insert into health_raw_revisions(raw_id,record_version,payload_hash,payload,change_kind) values($1,$2,$3,$4,$5) on conflict do nothing",[id,data.record_version??1,sha256(data.payload??{}),data.payload??{},data.change_kind??"upsert"]);await c.query("insert into health_normalization_queue(raw_id,raw_version,normalizer_version) values($1,$2,$3) on conflict do nothing",[id,data.record_version??1,data.parse_version??"legacy"]);return;
  }
  await c.query("insert into legacy_archives(id,subject_id,source_instance,source_table,source_snapshot,chunk_no,chunk_count,row_count,content,content_hash,state,revision) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,'active',1)",[id,subject,data.source_instance,data.source_table,data.source_snapshot,data.chunk_no,data.chunk_count,data.row_count,JSON.stringify(data.content),data.content_hash]);
  await c.query("insert into library_items(id,subject_id,title,item_type,state,current_revision) values($1,$2,$3,'note','active',1)",[id,subject,data.title??"Legacy archive"]);
  await c.query("insert into library_revisions(item_id,revision,text,tags) values($1,1,$2,$3::jsonb)",[id,JSON.stringify({source_instance:data.source_instance,source_table:data.source_table,source_snapshot:data.source_snapshot,chunk_no:data.chunk_no,chunk_count:data.chunk_count,row_count:data.row_count,content_hash:data.content_hash}),JSON.stringify(data.tags??[])]);
}

function targetTable(type:string,data:Record<string,unknown>):string{if(type==="money_entry")return"money_entries";if(type==="purchase")return"purchases";if(type==="meal")return"meals";if(type==="food")return"food_references";if(type==="recipe")return"recipes";if(type==="meal_template")return"meal_templates";if(type==="health_raw")return"health_raw_records";if(type==="asset")return"assets";if(type==="health_plan")return String(data.kind)==="habit"?"health_habit_definitions":String(data.kind)==="workout"?"workout_plans":"health_goals";return"legacy_archives";}

async function insertMealItems(c:PoolClient,mealId:string,subject:string,data:Record<string,unknown>){const entries=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[];for(let p=0;p<entries.length;p++){const item=entries[p]!;await c.query("insert into intake_items(id,subject_id,meal_id,position,name,food_ref_id,quantity,unit,energy_kcal,estimate,evidence_note,revision,free_text,amount_g,protein_g,fat_g,carb_g,fiber_g,sodium_mg,consumed_fraction,provenance,grouping_origin,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,1,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,true)",[String(item.id??stableMigrationId("intake",[mealId,p])),subject,mealId,p,item.name??item.free_text,item.food_ref_id??null,item.quantity??null,item.unit??null,item.energy_kcal??null,item.estimate??false,item.evidence_note??null,item.free_text??null,item.amount_g??null,item.protein_g??null,item.fat_g??null,item.carb_g??null,item.fiber_g??null,item.sodium_mg??null,item.consumed_fraction??null,item.provenance??"legacy",data.grouping_origin??"legacy_meal_bucket"]);}}

async function applyTargetDelta(c:PoolClient,type:string,id:string,subject:string,data:Record<string,unknown>,changeKind:"upsert"|"delete"):Promise<number>{
  if(type==="money_entry"){
    const selected=await c.query<{record_id:string;revision:number;record_revision:number;record:Record<string,unknown>;entry:Record<string,unknown>}>("select entry.record_id,entry.revision,record.revision record_revision,to_jsonb(record) record,(to_jsonb(entry)||jsonb_build_object('amount',entry.amount::text)) entry from money_entries entry join consumption_records record on record.id=entry.record_id where entry.id=$1 and entry.subject_id=$2 for update of entry,record",[id,subject]);const current=selected.rows[0];if(!current)throw new Error(`delta target missing: ${type}/${id}`);
    await c.query("insert into consumption_record_revisions(record_id,revision,snapshot,reason) values($1,$2,$3::jsonb,'legacy_final_delta')",[current.record_id,current.record_revision,JSON.stringify({record:current.record,money_entry:current.entry})]);
    if(changeKind==="delete"){await c.query("update consumption_records set state='voided',confirmed_at=coalesce(confirmed_at,now()),voided_at=now(),revision=revision+1,updated_at=now() where id=$1",[current.record_id]);const updated=await c.query<{revision:number}>("update money_entries set revision=revision+1 where id=$1 returning revision",[id]);return updated.rows[0]!.revision;}
    const state=String(data.state??"confirmed"),confirmedAt=state==="draft"?null:data.confirmed_at??current.record.confirmed_at??new Date(),voidedAt=state==="voided"?(data.voided_at??current.record.voided_at??new Date()):null;
    await c.query("update consumption_records set state=$2,occurred_on=$3,occurred_at=$4,time_zone=$5,note=$6,confirmed_at=$7,voided_at=$8,revision=revision+1,updated_at=now() where id=$1",[current.record_id,state,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,confirmedAt,voidedAt]);
    const updated=await c.query<{revision:number}>("update money_entries set entry_type=$2,amount=$3,currency=$4,occurred_on=$5,occurred_at=$6,time_zone=$7,note=$8,category=$9,counterparty=$10,payment_method=$11,source_scale=$12,revision=revision+1 where id=$1 returning revision",[id,data.entry_type,data.amount,data.currency,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.note??null,data.category??null,data.counterparty??null,data.payment_method??null,data.source_scale??2]);return updated.rows[0]!.revision;
  }
  if(type==="meal"){
    const selected=await c.query<{revision:number;meal:Record<string,unknown>;items:unknown[]}>("select meal.revision,to_jsonb(meal) meal,coalesce((select jsonb_agg((to_jsonb(item)||jsonb_build_object('quantity',item.quantity::text,'amount_g',item.amount_g::text,'energy_kcal',item.energy_kcal::text,'protein_g',item.protein_g::text,'fat_g',item.fat_g::text,'carb_g',item.carb_g::text,'fiber_g',item.fiber_g::text,'sodium_mg',item.sodium_mg::text,'consumed_fraction',item.consumed_fraction::text)) order by item.position) from intake_items item where item.meal_id=meal.id),'[]'::jsonb) items from meals meal where meal.id=$1 and meal.subject_id=$2 for update",[id,subject]);const current=selected.rows[0];if(!current)throw new Error(`delta target missing: ${type}/${id}`);await c.query("insert into meal_revisions(meal_id,revision,snapshot,reason) values($1,$2,$3::jsonb,'legacy_final_delta')",[id,current.revision,JSON.stringify({meal:current.meal,items:current.items})]);
    if(changeKind==="delete"){const updated=await c.query<{revision:number}>("update meals set state='deleted',revision=revision+1 where id=$1 returning revision",[id]);await c.query("update intake_items set effective=false,revision=revision+1 where meal_id=$1 and effective",[id]);return updated.rows[0]!.revision;}
    const entries=Array.isArray(data.items)?data.items as Record<string,unknown>[]:[],ids=entries.map((item,p)=>String(item.id??stableMigrationId("intake",[id,p])));if(ids.length){const collision=await c.query("select id from intake_items where id=any($1::text[]) and meal_id<>$2",[ids,id]);if(collision.rowCount)throw new Error(`delta intake id collision: ${String(collision.rows[0]!.id)}`);}await c.query("delete from intake_items where meal_id=$1",[id]);await c.query("update meals set occurred_on=$2,occurred_at=$3,time_zone=$4,meal_type=$5,note=$6,state='active',revision=revision+1 where id=$1",[id,data.occurred_on,data.occurred_at??null,data.time_zone??"Asia/Shanghai",data.meal_type??"other",data.note??null]);await insertMealItems(c,id,subject,data);return current.revision+1;
  }
  if(type==="health_raw"){
    const selected=await c.query<{current_version:string;parse_version:string|null}>("select current_version::text,parse_version from health_raw_records where id=$1 and subject_id=$2 for update",[id,subject]);const current=selected.rows[0];if(!current)throw new Error(`delta target missing: ${type}/${id}`);const previousVersion=Number(current.current_version),version=Number(data.record_version??previousVersion+1);if(!Number.isSafeInteger(version)||version<=previousVersion)throw new Error(`health delta version must advance: ${type}/${id}`);const payload=changeKind==="delete"?null:data.payload??{},payloadHash=sha256(payload),revisionKind=changeKind==="delete"?"delete":String(data.change_kind??"upsert"),state=changeKind==="delete"?"deleted":String(data.state??"pending"),normalizer=String(data.parse_version??current.parse_version??"legacy");await c.query("insert into health_raw_revisions(raw_id,record_version,payload_hash,payload,change_kind) values($1,$2,$3,$4,$5)",[id,version,payloadHash,payload,revisionKind]);await c.query("update health_raw_records set record_type=$2,client_record_id=$3,current_version=$4,current_sync_epoch=$5,current_hash=$6,state=$7,pending_reason=$8,parse_version=$9 where id=$1",[id,data.record_type,data.client_record_id,version,data.sync_epoch??1,payloadHash,state,data.pending_reason??null,normalizer]);await c.query("insert into health_normalization_queue(raw_id,raw_version,normalizer_version) values($1,$2,$3) on conflict do nothing",[id,version,normalizer]);return version;
  }
  if(type!=="archive")throw new Error(`final delta is not implemented for target type ${type}`);
  const selected=await c.query<{revision:number}>("select revision from legacy_archives where id=$1 and subject_id=$2 for update",[id,subject]);const current=selected.rows[0];if(!current)throw new Error(`delta target missing: ${type}/${id}`);const revision=current.revision+1;if(changeKind==="delete"){await c.query("update legacy_archives set state='deleted',revision=$2,updated_at=now() where id=$1",[id,revision]);await c.query("update library_items set state='deleted',current_revision=current_revision+1 where id=$1",[id]);return revision;}await c.query("update legacy_archives set source_instance=$2,source_table=$3,source_snapshot=$4,chunk_no=$5,chunk_count=$6,row_count=$7,content=$8::jsonb,content_hash=$9,state='active',revision=$10,updated_at=now() where id=$1",[id,data.source_instance,data.source_table,data.source_snapshot,data.chunk_no,data.chunk_count,data.row_count,JSON.stringify(data.content),data.content_hash,revision]);await c.query("update library_items set title=$2,state='active',current_revision=current_revision+1 where id=$1",[id,data.title??"Legacy archive"]);await c.query("insert into library_revisions(item_id,revision,text,tags,reason) select $1,current_revision,$2,$3::jsonb,'legacy_final_delta' from library_items where id=$1",[id,JSON.stringify({source_instance:data.source_instance,source_table:data.source_table,source_snapshot:data.source_snapshot,chunk_no:data.chunk_no,chunk_count:data.chunk_count,row_count:data.row_count,content_hash:data.content_hash}),JSON.stringify(data.tags??[])]);return revision;
}

async function reconcile(database:Pool|PoolClient,bundle:MigrationBundle,items:ReturnType<typeof plan>,id:string,verifiedFiles:VerifiedManifestFile[]){
  const result=await database.query<{status:string,count:string}>("select status,count(*)::text count from migration_items where batch_id=$1 group by status",[id]);const counts=Object.fromEntries(result.rows.map(row=>[row.status,Number(row.count)]));const disposed=Object.values(counts).reduce((a,b)=>a+b,0),differences:unknown[]=[],actualFacts:unknown[]=[];
  for(const item of items){const subject=bundle.owners[item.source.owner]!,verification=item.change_kind==="delete"?await verifyDeletedTarget(database,item.target.type,item.target.id,subject):await verifyTarget(database,item.target.type,item.target.id,subject,item.target.data);differences.push(...verification.differences);actualFacts.push({subject,type:item.target.type,id:item.target.id,change_kind:item.change_kind,data:verification.actual});const mapping=await database.query<{target_id:string}>("select target_id from legacy_object_maps where source_instance=$1 and source_table=$2 and source_pk_hash=$3 and source_owner=$4 and target_type=$5 and role=$6",[item.source.instance,item.source.table,item.source_pk_hash,item.source.owner,item.target.type,item.target.role]);if(mapping.rowCount!==1||mapping.rows[0]!.target_id!==item.target.id)differences.push({target_type:item.target.type,target_id:item.target.id,field:"$mapping",expected:{source:item.source,target_id:item.target.id,role:item.target.role},actual:mapping.rows});const reverse=await database.query("select source_instance,source_table,source_pk_hash,source_owner,role from legacy_object_maps where target_type=$1 and target_id=$2",[item.target.type,item.target.id]);if(reverse.rowCount!==1||reverse.rows[0]?.source_instance!==item.source.instance||reverse.rows[0]?.source_table!==item.source.table||reverse.rows[0]?.source_pk_hash!==item.source_pk_hash||reverse.rows[0]?.source_owner!==item.source.owner||reverse.rows[0]?.role!==item.target.role)differences.push({target_type:item.target.type,target_id:item.target.id,field:"$reverse_mapping",expected:{source_instance:item.source.instance,source_table:item.source.table,source_pk_hash:item.source_pk_hash,source_owner:item.source.owner,role:item.target.role},actual:reverse.rows});}
  const complete=disposed===items.length&&(counts.pending??0)===0&&(counts.blocked??0)===0&&(counts.conflict??0)===0&&differences.length===0;
  const targetFactHash=sha256({targets:actualFacts,files:verifiedFiles}),reconciledAt=new Date().toISOString();await database.query("update migration_batches set stage=$2,completed_at=case when $2='completed' then now() else null end,summary=summary||$3::jsonb where id=$1",[id,complete?"completed":"blocked",JSON.stringify({reconciled:complete,reconciled_at:reconciledAt,target_fact_hash:targetFactHash,components:items.length,differences})]);return{complete,expected_components:items.length,disposed_components:disposed,statuses:counts,source_objects:bundle.objects.length,differences,target_fact_hash:targetFactHash,reconciled_at:reconciledAt};
}
async function cutoverCheck(pool:Pool,bundle:MigrationBundle,planned:ReturnType<typeof plan>,id:string,bundleHash:string,ownerMapHash:string,verifiedFiles:VerifiedManifestFile[]){
  const client=await pool.connect(),lockKey=`shadow-life:migration:${id}`;try{await client.query("select pg_advisory_lock(hashtextextended($1,0))",[lockKey]);await client.query("begin isolation level repeatable read");try{const fresh=await reconcile(client,bundle,planned,id,verifiedFiles);const batch=await client.query<{stage:string;summary:Record<string,unknown>;bundle_hash:string;source_snapshot:string;mapper_version:string;owner_map_hash:string;mode:Mode}>("select stage,summary,bundle_hash,source_snapshot,mapper_version,owner_map_hash,mode from migration_batches where id=$1",[id]);const items=await client.query("select count(*) filter(where status in ('pending','blocked','conflict'))::int unresolved from migration_items where batch_id=$1",[id]);const projections=await client.query("select count(*) filter(where state<>'completed')::int incomplete from projection_checkpoints",[]);const healthWork=await client.query("select count(*) filter(where state<>'completed')::int incomplete from health_normalization_queue",[]);const healthDays=await client.query("select count(*) filter(where not valid)::int incomplete from health_projection_invalidations",[]);const epochs=await client.query<{domain:string;epoch:number;stage:string;target_schema:string}>("select domain,epoch,stage,target_schema from write_epochs order by domain",[]),row=batch.rows[0];const checks={final_delta_batch:row?.mode==="final_delta",source_snapshot_bound:row?.bundle_hash===bundleHash&&row.source_snapshot===bundle.source_snapshot&&row.mapper_version===bundle.mapper_version&&row.owner_map_hash===ownerMapHash,batch_completed:row?.stage==="completed",target_reconciled:fresh.complete&&row?.summary?.reconciled===true,migration_items_resolved:items.rows[0]?.unresolved===0,projections_completed:projections.rows[0]?.incomplete===0,health_normalization_completed:healthWork.rows[0]?.incomplete===0,health_daily_projections_completed:healthDays.rows[0]?.incomplete===0,write_epochs_frozen:epochs.rows.length===2&&epochs.rows.every(epoch=>epoch.stage==="read_only"),write_epochs:epochs.rows};const ready=checks.final_delta_batch&&checks.source_snapshot_bound&&checks.batch_completed&&checks.target_reconciled&&checks.migration_items_resolved&&checks.projections_completed&&checks.health_normalization_completed&&checks.health_daily_projections_completed&&checks.write_epochs_frozen;await client.query("commit");return{ready,checks,source_snapshot:bundle.source_snapshot,target_fact_hash:fresh.target_fact_hash,reconciled_at:fresh.reconciled_at};}catch(error){await client.query("rollback");throw error;}}finally{await client.query("select pg_advisory_unlock(hashtextextended($1,0))",[lockKey]).catch(()=>undefined);client.release();}
}

async function verifyTarget(pool:Pool|PoolClient,type:string,id:string,subject:string,expected:Record<string,unknown>):Promise<{differences:unknown[];actual:unknown}>{
  let actual:Record<string,unknown>|undefined;
  if(type==="money_entry")actual=(await pool.query("select record.id record_id,entry.entry_type,entry.amount::text amount,entry.currency,entry.occurred_on::text,entry.occurred_at::text,entry.time_zone,entry.note,entry.category,entry.counterparty,entry.payment_method,entry.source_scale,entry.revision,record.state,record.revision record_revision,record.confirmed_at::text,record.voided_at::text from money_entries entry join consumption_records record on record.id=entry.record_id where entry.id=$1 and entry.subject_id=$2",[id,subject])).rows[0];
  else if(type==="purchase"){actual=(await pool.query("select purchase.record_id,purchase.merchant,purchase.amount::text amount,purchase.currency,purchase.category,purchase.occurred_on::text,purchase.occurred_at::text,purchase.time_zone,purchase.note,purchase.scene,purchase.channel_name_raw,purchase.place_ref,purchase.rating,purchase.would_repeat,purchase.revision,record.state,record.confirmed_at::text,record.voided_at::text from purchases purchase join consumption_records record on record.id=purchase.record_id where purchase.id=$1 and purchase.subject_id=$2",[id,subject])).rows[0];if(actual){actual.items=(await pool.query("select id,position,raw_name,quantity::text,unit_price::text,unit,line_amount::text,category_key from purchase_items where purchase_id=$1 order by position",[id])).rows;const money=(await pool.query("select id,entry_type,amount::text amount,currency,note,category,counterparty,payment_method,source_scale,revision from money_entries where record_id=$1",[actual.record_id])).rows[0];actual.money_entry=money??null;}}
  else if(type==="meal"){actual=(await pool.query("select meal.occurred_on::text,meal.occurred_at::text,meal.time_zone,meal.meal_type,meal.note,meal.state,meal.revision,(select grouping_origin from intake_items where meal_id=meal.id and effective order by position limit 1) grouping_origin from meals meal where meal.id=$1 and meal.subject_id=$2",[id,subject])).rows[0];if(actual){const rows=(await pool.query("select id,name,food_ref_id,quantity::text,unit,energy_kcal::text,estimate,evidence_note,free_text,amount_g::text,protein_g::text,fat_g::text,carb_g::text,fiber_g::text,sodium_mg::text,consumed_fraction::text,provenance,grouping_origin,revision from intake_items where meal_id=$1 and effective order by position",[id])).rows;actual.items=rows;}}
  else if(type==="food")actual=(await pool.query("select name,serving_amount::text,serving_unit,nutrients,provenance,state,revision from food_references where id=$1 and subject_id=$2",[id,subject])).rows[0];
  else if(type==="recipe"){actual=(await pool.query("select title,servings::text,instructions,state,revision from recipes where id=$1 and subject_id=$2",[id,subject])).rows[0];if(actual)actual.items=(await pool.query("select snapshot from recipe_items where recipe_id=$1 order by position",[id])).rows.map(row=>row.snapshot);}
  else if(type==="meal_template"){actual=(await pool.query("select name,revision from meal_templates where id=$1 and subject_id=$2",[id,subject])).rows[0];if(actual)actual.items=(await pool.query("select snapshot from meal_template_items where template_id=$1 order by position",[id])).rows.map(row=>row.snapshot);}
  else if(type==="health_plan"){const kind=String(expected.kind),table=targetTable(type,expected),name=kind==="workout"?"title":"name";actual=(await pool.query(`select ${name} name,${kind==="goal"?"metric_key,target_value::text target_value,unit,due_on::text due_on,":""}${kind==="workout"?"schedule,detail,":""}${kind==="habit"?"schedule,":""}state,revision from ${table} where id=$1 and subject_id=$2`,[id,subject])).rows[0];if(actual)actual.kind=kind;}
  else if(type==="health_raw")actual=(await pool.query("select source.source_type,source.instance_key source_instance_key,source.fingerprint source_fingerprint,raw.record_type,raw.client_record_id,raw.current_version::text record_version,raw.current_sync_epoch sync_epoch,raw.parse_version,revision.payload,revision.change_kind from health_raw_records raw join health_source_instances source on source.id=raw.source_instance_id join health_raw_revisions revision on revision.raw_id=raw.id and revision.record_version=raw.current_version where raw.id=$1 and raw.subject_id=$2",[id,subject])).rows[0];
  else if(type==="asset")actual=(await pool.query("select asset.media_type,replace(encode(blob.bytes,'base64'),E'\\n','') bytes_base64,octet_length(blob.bytes)::int byte_size,version.sha256,reference.target_id meal_id,source.external_id filename from assets asset join asset_versions version on version.asset_id=asset.id join asset_blobs blob on blob.asset_version_id=version.id join asset_references reference on reference.asset_id=asset.id and reference.subject_id=asset.subject_id and reference.target_type='meal' join sources source on source.asset_version_id=version.id and source.subject_id=asset.subject_id where asset.id=$1 and asset.subject_id=$2",[id,subject])).rows[0];
  else actual=(await pool.query("select archive.source_instance,archive.source_table,archive.source_snapshot,archive.chunk_no,archive.chunk_count,archive.row_count,archive.content,archive.content_hash,archive.state,archive.revision,item.title,revision.tags from legacy_archives archive join library_items item on item.id=archive.id and item.subject_id=archive.subject_id join library_revisions revision on revision.item_id=item.id and revision.revision=item.current_revision where archive.id=$1 and archive.subject_id=$2",[id,subject])).rows[0];
  if(!actual)return{differences:[{target_type:type,target_id:id,field:"$",expected:"present",actual:"missing"}],actual:null};const differences:unknown[]=[];for(const [key,value] of Object.entries(expected)){if(key==="confirmed_at"||key==="voided_at"||key==="time_zone"&&actual[key]===undefined)continue;const left=normalize(value),right=normalize(project(actual[key],value));if(canonical(left)!==canonical(right))differences.push({target_type:type,target_id:id,field:key,expected:left,actual:right});}return{differences,actual:normalize(actual)};
}
async function verifyDeletedTarget(pool:Pool|PoolClient,type:string,id:string,subject:string):Promise<{differences:unknown[];actual:unknown}>{const result=await verifyTarget(pool,type,id,subject,{}),expectedState=type==="money_entry"||type==="purchase"?"voided":"deleted";let actual=result.actual&&typeof result.actual==="object"?(result.actual as Record<string,unknown>).state:undefined;if(type==="health_raw")actual=(await pool.query("select state from health_raw_records where id=$1 and subject_id=$2",[id,subject])).rows[0]?.state;if(actual!==expectedState)result.differences.push({target_type:type,target_id:id,field:"state",expected:expectedState,actual});return result;}
function normalize(value:unknown):unknown{if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}[T ].*(?:Z|[+-]\d{2}(?::?\d{2})?)$/u.test(value)){const parsed=Date.parse(value);if(Number.isFinite(parsed))return new Date(parsed).toISOString();}if(typeof value==="string"&&/^-?\d+(?:\.\d+)?$/u.test(value)){const normalized=value.replace(/(\.\d*?)0+$/u,"$1").replace(/\.$/u,"");return normalized==="-0"?"0":normalized;}if(Array.isArray(value))return value.map(normalize);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([,item])=>item!==null&&item!==undefined).map(([key,item])=>[key,normalize(item)]));return value;}
function project(actual:unknown,expected:unknown):unknown{if(typeof expected==="number"&&typeof actual==="string"&&/^-?\d+(?:\.\d+)?$/u.test(actual))return Number(actual);if(Array.isArray(expected)){if(!Array.isArray(actual))return actual;if(expected.length===0)return actual.length===0?[]:actual.map(()=>"unexpected");return actual.map((item,index)=>project(item,expected[index]??expected[0]));}if(expected&&typeof expected==="object"&&actual&&typeof actual==="object"){const source=actual as Record<string,unknown>;return Object.fromEntries(Object.keys(expected as Record<string,unknown>).map(key=>[key,project(source[key],(expected as Record<string,unknown>)[key])]));}return actual;}
