import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { Pool } from "pg";
import { findSecretFields, sha256 } from "./bundle.js";
import { catalogFingerprint, deterministicRows, snapshotId, type LegacySnapshot } from "./snapshot.js";

const [sourceInstance,outputPath,schemaArgument="public"]=process.argv.slice(2);const connectionString=process.env.LEGACY_DATABASE_URL;
if(!sourceInstance||!outputPath||!connectionString)throw new Error("usage: LEGACY_DATABASE_URL=... export-postgres <source-instance> <output.json> [schema,...]");
const selectedSchemas=[...new Set(schemaArgument.split(",").map(value=>value.trim()).filter(Boolean))];
if(!selectedSchemas.length||selectedSchemas.some(value=>!/^[a-z_][a-z0-9_$]*$/iu.test(value)))throw new Error("schema list contains an invalid PostgreSQL identifier");
const excluded=new Set(["local_identities","browser_sessions","oidc_transactions"]);
const forbidden=/(^|_)(password|passwd|access_token|refresh_token|cookie|client_secret|private_key|dsn|authorization)($|_)/iu;
const pool=new Pool({connectionString,max:1});const client=await pool.connect();
try{
  await client.query("begin isolation level repeatable read read only");
  const catalog=await client.query<{table_schema:string;table_name:string;column_name:string;data_type:string;udt_name:string;is_nullable:"YES"|"NO";ordinal_position:number}>("select table_schema,table_name,column_name,data_type,udt_name,is_nullable,ordinal_position from information_schema.columns where table_schema=any($1::text[]) and table_name<>'alembic_version' order by table_schema,table_name,ordinal_position",[selectedSchemas]);
  const primaryKeys=await client.query<{table_schema:string;table_name:string;column_name:string;position:number}>("select usage.table_schema,usage.table_name,usage.column_name,usage.ordinal_position position from information_schema.table_constraints constraint_row join information_schema.key_column_usage usage on usage.constraint_name=constraint_row.constraint_name and usage.constraint_schema=constraint_row.constraint_schema and usage.table_schema=constraint_row.table_schema and usage.table_name=constraint_row.table_name where constraint_row.table_schema=any($1::text[]) and constraint_row.constraint_type='PRIMARY KEY' order by usage.table_schema,usage.table_name,usage.ordinal_position",[selectedSchemas]);const keyPositions=new Map(primaryKeys.rows.map(row=>[`${row.table_schema}\u0000${row.table_name}\u0000${row.column_name}`,row.position]));
  const tables=new Map<string,{schema:string;table:string;columns:Array<{name:string;data_type:string;udt_name:string;nullable:boolean;primary_key_position:number|null}>}>();for(const row of catalog.rows){const key=`${row.table_schema}\u0000${row.table_name}`,entry=tables.get(key)??{schema:row.table_schema,table:row.table_name,columns:[]};entry.columns.push({name:row.column_name,data_type:row.data_type,udt_name:row.udt_name,nullable:row.is_nullable==="YES",primary_key_position:keyPositions.get(`${row.table_schema}\u0000${row.table_name}\u0000${row.column_name}`)??null});tables.set(key,entry);}
  const secretColumns=[...tables.values()].flatMap(({schema,table,columns})=>excluded.has(table)?[]:columns.filter(column=>forbidden.test(column.name)).map(column=>`${schema}.${table}.${column.name}`));if(secretColumns.length)throw new Error(`refusing export with secret-bearing columns: ${secretColumns.join(", ")}`);
  const snapshots:LegacySnapshot["tables"]=[];for(const {schema,table,columns} of tables.values()){if(excluded.has(table)){snapshots.push({schema,table,disposition:"excluded_session_or_identity_secret",columns,row_count:0,rows:[],sha256:null});continue;}const quotedSchema=`"${schema.replaceAll('"','""')}"`,quotedTable=`"${table.replaceAll('"','""')}"`,result=await client.query(`select * from ${quotedSchema}.${quotedTable}`),rows=deterministicRows(result.rows),secretFields=findSecretFields(rows,`$.${schema}.${table}`);if(secretFields.length)throw new Error(`refusing export with secret-bearing JSON fields: ${secretFields.slice(0,20).join(", ")}`);snapshots.push({schema,table,disposition:"staged_for_mapping",columns,row_count:rows.length,rows,sha256:sha256(rows)});}
  if(!snapshots.length)throw new Error(`no tables found in requested schemas: ${selectedSchemas.join(", ")}`);
  const fingerprint=catalogFingerprint(snapshots),snapshot_id=snapshotId({source_instance:sourceInstance,catalog_fingerprint:fingerprint,tables:snapshots}),payload:LegacySnapshot={protocol:"shadow.legacy-snapshot",snapshot_id,source_instance:sourceInstance,exported_at:new Date().toISOString(),database:"postgresql",isolation:"repeatable read read only",catalog_fingerprint:fingerprint,excluded_tables:snapshots.filter(table=>table.disposition==="excluded_session_or_identity_secret").map(table=>`${table.schema}.${table.table}`).sort(),tables:snapshots};const encoded=JSON.stringify(payload,null,2)+"\n";await writeFile(outputPath,encoded,{mode:0o600});await client.query("commit");console.log(JSON.stringify({protocol:payload.protocol,snapshot_id,source_instance:sourceInstance,schemas:selectedSchemas,tables:snapshots.length,rows:snapshots.reduce((sum,item)=>sum+item.row_count,0),sha256:createHash("sha256").update(encoded).digest("hex"),output:outputPath}));
}catch(error){await client.query("rollback");throw error;}finally{client.release();await pool.end();}
