import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { Pool } from "pg";
import { sha256 } from "./bundle.js";
import { catalogFingerprint, deterministicRows, snapshotId, type LegacySnapshot } from "./snapshot.js";

const [sourceInstance,outputPath]=process.argv.slice(2);const connectionString=process.env.LEGACY_DATABASE_URL;
if(!sourceInstance||!outputPath||!connectionString)throw new Error("usage: LEGACY_DATABASE_URL=... export-postgres <source-instance> <output.json>");
const excluded=new Set(["local_identities","browser_sessions","oidc_transactions"]);
const forbidden=/(^|_)(password|passwd|access_token|refresh_token|cookie|client_secret|private_key|dsn|authorization)($|_)/iu;
const pool=new Pool({connectionString,max:1});const client=await pool.connect();
try{
  await client.query("begin isolation level repeatable read read only");
  const catalog=await client.query<{table_name:string;column_name:string;data_type:string;udt_name:string;is_nullable:"YES"|"NO";ordinal_position:number}>("select table_name,column_name,data_type,udt_name,is_nullable,ordinal_position from information_schema.columns where table_schema='public' and table_name not in ('alembic_version') order by table_name,ordinal_position");
  const primaryKeys=await client.query<{table_name:string;column_name:string;position:number}>("select usage.table_name,usage.column_name,usage.ordinal_position position from information_schema.table_constraints constraint_row join information_schema.key_column_usage usage on usage.constraint_name=constraint_row.constraint_name and usage.constraint_schema=constraint_row.constraint_schema where constraint_row.table_schema='public' and constraint_row.constraint_type='PRIMARY KEY' order by usage.table_name,usage.ordinal_position");const keyPositions=new Map(primaryKeys.rows.map(row=>[`${row.table_name}\u0000${row.column_name}`,row.position]));
  const tables=new Map<string,Array<{name:string;data_type:string;udt_name:string;nullable:boolean;primary_key_position:number|null}>>();for(const row of catalog.rows){const columns=tables.get(row.table_name)??[];columns.push({name:row.column_name,data_type:row.data_type,udt_name:row.udt_name,nullable:row.is_nullable==="YES",primary_key_position:keyPositions.get(`${row.table_name}\u0000${row.column_name}`)??null});tables.set(row.table_name,columns);}
  const secretColumns=[...tables].flatMap(([table,columns])=>excluded.has(table)?[]:columns.filter(column=>forbidden.test(column.name)).map(column=>`${table}.${column.name}`));if(secretColumns.length)throw new Error(`refusing export with secret-bearing columns: ${secretColumns.join(", ")}`);
  const snapshots:LegacySnapshot["tables"]=[];for(const [table,columns] of tables){if(excluded.has(table)){snapshots.push({table,disposition:"excluded_session_or_identity_secret",columns,row_count:0,rows:[],sha256:null});continue;}const quoted=`"${table.replaceAll('"','""')}"`,result=await client.query(`select * from ${quoted}`),rows=deterministicRows(result.rows);snapshots.push({table,disposition:"staged_for_mapping",columns,row_count:rows.length,rows,sha256:sha256(rows)});}
  const fingerprint=catalogFingerprint(snapshots),snapshot_id=snapshotId({source_instance:sourceInstance,catalog_fingerprint:fingerprint,tables:snapshots}),payload:LegacySnapshot={protocol:"shadow.legacy-snapshot",snapshot_id,source_instance:sourceInstance,exported_at:new Date().toISOString(),database:"postgresql",isolation:"repeatable read read only",catalog_fingerprint:fingerprint,excluded_tables:[...excluded].sort(),tables:snapshots};const encoded=JSON.stringify(payload,null,2)+"\n";await writeFile(outputPath,encoded,{mode:0o600});await client.query("commit");console.log(JSON.stringify({protocol:payload.protocol,snapshot_id,source_instance:sourceInstance,tables:snapshots.length,rows:snapshots.reduce((sum,item)=>sum+item.row_count,0),sha256:createHash("sha256").update(encoded).digest("hex"),output:outputPath}));
}catch(error){await client.query("rollback");throw error;}finally{client.release();await pool.end();}
