import { readFile, realpath, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { basename, relative, resolve } from "node:path";
import { z } from "zod";
import { auditMapping, mappingReviewSchema, tableIdentity, validateSnapshot, type LegacySnapshot, type MappingReview } from "./snapshot.js";
import { canonical, sha256, stableMigrationId, validateBundle, type MigrationBundle } from "./bundle.js";

const configSchema=z.object({
  source_kind:z.enum(["health","ledger"]),
  owner_key:z.string().min(1).max(200),
  target_subject_id:z.string().regex(/^[a-z][a-z0-9_]{7,127}$/u),
  ownership_confirmed:z.literal(true),
  ownership_confirmation:z.string().min(1).max(500),
  mapper_version:z.string().min(1).max(100).default("shadow-life-production-v1"),
  target_schema_version:z.string().regex(/^\d{4}$/u).default("0035"),
  asset_root:z.string().min(1).optional()
}).strict();

async function main(){
  const [snapshotPath,configPath,bundlePath,reviewPath,auditPath]=process.argv.slice(2);
  if(!snapshotPath||!configPath||!bundlePath||!reviewPath||!auditPath)throw new Error("usage: production-mapper <snapshot.json> <owner-map.json> <bundle.json> <review.json> <audit.json>");
  const snapshot=validateSnapshot(JSON.parse(await readFile(snapshotPath,"utf8"))),config=configSchema.parse(JSON.parse(await readFile(configPath,"utf8")));
  const review=buildReview(snapshot,config.source_kind,config.mapper_version),audit=auditMapping(snapshot,review);
  if(!audit.ready)throw new Error(`mapping review is not ready: ${audit.gaps.join("; ")}`);
  const objects=config.source_kind==="health"?await mapHealth(snapshot,config.owner_key,config.asset_root):mapLedger(snapshot,config.owner_key);
  const bundle=validateBundle({protocol:"shadow.legacy-bundle",source_snapshot:snapshot.snapshot_id,mapper_version:config.mapper_version,target_schema_version:config.target_schema_version,owners:{[config.owner_key]:config.target_subject_id},manifest:{files:[]},objects});
  await Promise.all([
    writeFile(bundlePath,JSON.stringify(bundle,null,2)+"\n",{mode:0o600}),
    writeFile(reviewPath,JSON.stringify(review,null,2)+"\n",{mode:0o600}),
    writeFile(auditPath,JSON.stringify({...audit,ownership:{confirmed:true,confirmation:config.ownership_confirmation,owner_key_hash:sha256(config.owner_key),target_subject_hash:sha256(config.target_subject_id)},source_rows:snapshot.tables.reduce((count,table)=>count+table.row_count,0),migration_objects:bundle.objects.length,migration_components:bundle.objects.reduce((count,object)=>count+object.targets.length,0)},null,2)+"\n",{mode:0o600})
  ]);
  console.log(JSON.stringify({protocol:"shadow.production-mapper-result",snapshot_id:snapshot.snapshot_id,source_kind:config.source_kind,ready:true,tables:audit.tables,source_rows:snapshot.tables.reduce((count,table)=>count+table.row_count,0),objects:bundle.objects.length,components:bundle.objects.reduce((count,object)=>count+object.targets.length,0),bundle_sha256:sha256(bundle)}));
}

const healthNative=new Set(["health.body_metrics","health.daily_activity","health.sleep_sessions","health.workout_logs","health.release_logs","health.habit_logs","health.foods","health.recipes","health.meal_templates","health.diet_logs","health.diet_photos","health.fitness_tests","health.lab_results","health.workout_plans","health.habits"]);
const ledgerNative=new Set(["ledger_records","money_entries","consumption_events","consumption_lines","money_categories"]);

function buildReview(snapshot:LegacySnapshot,kind:"health"|"ledger",mapperVersion:string):MappingReview{
  const native=kind==="health"?healthNative:ledgerNative;
  return mappingReviewSchema.parse({protocol:"shadow.legacy-mapping-review",snapshot_id:snapshot.snapshot_id,source_instance:snapshot.source_instance,mapper_version:mapperVersion,tables:snapshot.tables.map(table=>{
    const name=tableIdentity(table),session=table.disposition==="excluded_session_or_identity_secret",runtime=table.disposition==="excluded_runtime_state",isNative=native.has(name),disposition=session?"excluded_session_or_identity":runtime?"excluded_runtime_state":isNative?"native":"historical_archive";
    const mapping_key=session||runtime?null:`${kind}.${isNative?"native":"archive"}.v1`;
    return{name,disposition,mapping_key,reason:session?"Authentication/session state is intentionally not migrated; the user signs in again.":runtime?"Source-bound cursor/runtime state is intentionally re-established by the native client.":isNative?"Mapped into an operable Shadow Life model and retained in the immutable table archive.":"Retained as a searchable, immutable historical table archive.",columns:table.columns.map(column=>{const pk=column.primary_key_position!==null;return{name:column.name,disposition:session?"excluded_session_or_identity":runtime?"excluded_runtime_state":isNative?(pk?"source_identity":"native_field"):(pk?"source_identity":"archive_payload"),target:session||runtime?null:isNative?pk?"legacy_object_maps.source_pk":`production_mapper.${name}.${column.name}`:pk?"legacy_archive.source_pk":`library_revisions.text.${column.name}`,reason:session?"Excluded with its session/identity table.":runtime?"Excluded with source-bound runtime state.":pk?"Preserved as deterministic source identity.":isNative?"Preserved in the native projection and/or the immutable table archive.":"Preserved verbatim except explicit credential-field redaction."};})};
  })});
}

type Row=Record<string,unknown>;
function included(snapshot:LegacySnapshot){return snapshot.tables.filter(table=>table.disposition==="staged_for_mapping");}
function byName(snapshot:LegacySnapshot,name:string):LegacySnapshot["tables"][number]|undefined{return snapshot.tables.find(table=>tableIdentity(table)===name);}
function rows(snapshot:LegacySnapshot,name:string):Row[]{return byName(snapshot,name)?.rows??[];}
function pk(table:LegacySnapshot["tables"][number],row:Row):Record<string,string|number|boolean|null>{const fields=table.columns.filter(column=>column.primary_key_position!==null).sort((a,b)=>a.primary_key_position!-b.primary_key_position!);if(!fields.length)return{row_hash:sha256(row)};return Object.fromEntries(fields.map(column=>[column.name,scalar(row[column.name])]));}
function scalar(value:unknown):string|number|boolean|null{return value===null||typeof value==="string"||typeof value==="number"||typeof value==="boolean"?value:canonical(value);}
function value(row:Row,key:string):unknown{return row[key]??null;}
function stringValue(row:Row,key:string):string|undefined{const found=value(row,key);return found===null?undefined:String(found);}
function numberValue(row:Row,key:string):number|undefined{const found=value(row,key);if(found===null)return undefined;const parsed=Number(found);return Number.isFinite(parsed)?parsed:undefined;}
function integerValue(row:Row,key:string):number|undefined{const found=numberValue(row,key);return found===undefined?undefined:Math.max(0,Math.round(found));}
function booleanValue(row:Row,key:string):boolean|undefined{const found=value(row,key);return typeof found==="boolean"?found:found===null?undefined:String(found)==="true";}
function revision(row:Row):string|undefined{return stringValue(row,"record_version")??stringValue(row,"revision")??stringValue(row,"updated_at")??stringValue(row,"created_at");}
function source(snapshot:LegacySnapshot,table:string,sourcePk:Record<string,string|number|boolean|null>,owner:string,sourceRevision?:string){return{instance:snapshot.source_instance,table,pk:sourcePk,owner,...(sourceRevision?{revision:sourceRevision}:{})};}
function target(component:string,type:MigrationBundle["objects"][number]["targets"][number]["type"],id:string,data:Record<string,unknown>,role="primary"){return{component,type,id,role,data};}
function archive(snapshot:LegacySnapshot,table:LegacySnapshot["tables"][number],owner:string):MigrationBundle["objects"]{
  const chunks:Row[][]=[];let current:Row[]=[],bytes=0;for(const row of table.rows){const size=Buffer.byteLength(JSON.stringify(row));if(current.length&&bytes+size>300_000){chunks.push(current);current=[];bytes=0;}current.push(row);bytes+=size;}if(current.length||table.rows.length===0)chunks.push(current);
  return chunks.map((chunk,index)=>{const safe=sanitize(chunk),content={protocol:"shadow.legacy-table-archive",snapshot_id:snapshot.snapshot_id,source_instance:snapshot.source_instance,table:tableIdentity(table),table_row_count:table.row_count,chunk:index+1,chunks:chunks.length,rows:safe.value};return{change_kind:"upsert" as const,source:source(snapshot,tableIdentity(table),{table_sha256:table.sha256!,archive_chunk:index+1},owner),payload:{row_count:chunk.length,table_row_count:table.row_count,table_sha256:table.sha256!,archive_chunk:index+1,archive_chunks:chunks.length,redacted_fields:safe.redactions},targets:[target("historical_archive","archive",stableMigrationId("archive",[snapshot.snapshot_id,tableIdentity(table),index+1]),{title:`旧系统历史 · ${tableIdentity(table)} · ${index+1}/${chunks.length}`,source_instance:snapshot.source_instance,source_table:tableIdentity(table),source_snapshot:snapshot.snapshot_id,chunk_no:index+1,chunk_count:chunks.length,row_count:chunk.length,content,content_hash:sha256(content),tags:["legacy-migration",snapshot.source_instance,tableIdentity(table),`snapshot:${snapshot.snapshot_id}`]})]};});
}
function sanitize(input:unknown):{value:unknown;redactions:number}{let redactions=0;const walk=(current:unknown):unknown=>{if(Array.isArray(current))return current.map(walk);if(!current||typeof current!=="object")return current;return Object.fromEntries(Object.entries(current as Row).filter(([,item])=>item!==undefined).map(([key,item])=>{if(/(^|_)(password|passwd|token|cookie|secret|private_key|dsn|authorization)($|_)/iu.test(key)){redactions++;return[`redacted_${Buffer.from(key).toString("base64url")}`,{digest:sha256(item),reason:"credential_or_runtime_secret"}];}return[key,walk(item)];}));};return{value:walk(input),redactions};}
function nativeObject(snapshot:LegacySnapshot,table:string,row:Row,owner:string,targets:MigrationBundle["objects"][number]["targets"]){const tableDef=byName(snapshot,table);if(!tableDef)throw new Error(`missing table ${table}`);const safe=sanitize(row);return{change_kind:"upsert" as const,source:source(snapshot,table,pk(tableDef,row),owner,revision(row)),payload:{legacy_row:safe.value,redacted_fields:safe.redactions},targets};}

function rawTarget(snapshot:LegacySnapshot,table:string,row:Row,recordType:string,payload:Record<string,unknown>,suffix="primary"){
  const identity=[snapshot.source_instance,table,pk(byName(snapshot,table)!,row),recordType,suffix],id=stableMigrationId("health_raw",identity),sourceKind=stringValue(row,"source")??"legacy";
  return target(`health_${recordType}_${suffix}`,"health_raw",id,{source_type:"legacy_health",source_instance_key:`${snapshot.source_instance}:${table}:${sourceKind}`,source_fingerprint:sha256([snapshot.snapshot_id,table,sourceKind]),record_type:recordType,client_record_id:`${table}:${canonical(pk(byName(snapshot,table)!,row))}:${suffix}`,record_version:Math.max(1,integerValue(row,"record_version")??1),sync_epoch:1,parse_version:"health-normalizer",payload,change_kind:"upsert"},suffix);
}
function clean<T extends Row>(record:T):T{return Object.fromEntries(Object.entries(record).filter(([,item])=>item!==undefined&&item!==null)) as T;}
function metric(row:Row,key:string,metricKey:string,unit:string){const found=stringValue(row,key);return found===undefined?undefined:{metric_key:metricKey,value:found,unit,original_field:key,autofilled:Boolean((row.autofilled as Row|undefined)?.[key])};}
function date(value:unknown):string{return String(value).slice(0,10);}
function instant(value:unknown):string|undefined{return value===null||value===undefined?undefined:new Date(String(value)).toISOString();}
function minutesBetween(start:unknown,end:unknown):number{const left=Date.parse(String(start)),right=Date.parse(String(end));return Number.isFinite(left)&&Number.isFinite(right)?Math.max(0,Math.round((right-left)/60000)):0;}
function mealType(value:unknown):string{return value==="早餐"?"breakfast":value==="午餐"?"lunch":value==="晚餐"?"dinner":value==="加餐"?"snack":"other";}
function intake(item:Row,id:string,foodNames:Map<string,string>,foodIds:Map<string,string>){const foodKey=stringValue(item,"food_id"),free=stringValue(item,"free_text"),name=foodKey?foodNames.get(foodKey):undefined;return clean({id,name:name??free??"旧饮食记录",food_ref_id:foodKey?foodIds.get(foodKey):undefined,free_text:free,amount_g:stringValue(item,"amount_g"),energy_kcal:stringValue(item,"kcal"),protein_g:stringValue(item,"protein_g"),fat_g:stringValue(item,"fat_g"),carb_g:stringValue(item,"carb_g"),estimate:false,evidence_note:stringValue(item,"notes"),provenance:"legacy_health"});}

async function mapHealth(snapshot:LegacySnapshot,owner:string,assetRoot?:string):Promise<MigrationBundle["objects"]>{
  const objects:MigrationBundle["objects"]=included(snapshot).flatMap(table=>archive(snapshot,table,owner));
  const bodyTable="health.body_metrics";for(const row of rows(snapshot,bodyTable)){const observations=[metric(row,"weight_kg","weight","kg"),metric(row,"body_fat_pct","body_fat","%"),metric(row,"muscle_mass_kg","muscle_mass","kg"),metric(row,"skeletal_muscle_kg","skeletal_muscle","kg"),metric(row,"bmr_kcal","bmr","kcal/day"),metric(row,"body_water_kg","body_water","kg"),metric(row,"visceral_fat_level","visceral_fat","level"),metric(row,"waist_cm","waist","cm"),metric(row,"chest_cm","chest","cm"),metric(row,"hip_cm","hip","cm"),metric(row,"bp_systolic","blood_pressure_systolic","mmHg"),metric(row,"bp_diastolic","blood_pressure_diastolic","mmHg"),metric(row,"resting_hr","heart_rate","bpm"),metric(row,"spo2_pct","spo2","%")].filter(Boolean) as Row[];const targets:MigrationBundle["objects"][number]["targets"]=[];if(observations.length)targets.push(rawTarget(snapshot,bodyTable,row,"body",{occurred_on:date(row.log_date),time_zone:"Asia/Shanghai",group_kind:"legacy_daily_form",observations},"measurements"));if(row.mood_score!==null||row.energy_level!==null||row.sleep_quality!==null||row.morning_erection!==null||row.notes!==null)targets.push(rawTarget(snapshot,bodyTable,row,"wellbeing",clean({occurred_on:date(row.log_date),time_zone:"Asia/Shanghai",mood_score:integerValue(row,"mood_score"),energy_level:integerValue(row,"energy_level"),sleep_quality:integerValue(row,"sleep_quality"),morning_erection:booleanValue(row,"morning_erection"),notes:stringValue(row,"notes")}),"wellbeing"));if(targets.length)objects.push(nativeObject(snapshot,bodyTable,row,owner,targets));}
  const activityTable="health.daily_activity";for(const row of rows(snapshot,activityTable))objects.push(nativeObject(snapshot,activityTable,row,owner,[rawTarget(snapshot,activityTable,row,"daily_activity",clean({occurred_on:date(row.log_date),time_zone:"Asia/Shanghai",steps:integerValue(row,"steps"),device_calories_kcal:stringValue(row,"active_kcal"),field_sources:row.field_sources&&typeof row.field_sources==="object"?row.field_sources:{steps:stringValue(row,"source")??"legacy_health",device_calories_kcal:stringValue(row,"source")??"legacy_health"}}))]));
  const sleepTable="health.sleep_sessions";for(const row of rows(snapshot,sleepTable))objects.push(nativeObject(snapshot,sleepTable,row,owner,[rawTarget(snapshot,sleepTable,row,"sleep",clean({wake_date:date(row.wake_date),time_zone:"Asia/Shanghai",started_at:instant(row.start_at),ended_at:instant(row.end_at),total_minutes:integerValue(row,"total_sleep_min")??minutesBetween(row.start_at,row.end_at),deep_minutes:integerValue(row,"deep_min"),light_minutes:integerValue(row,"light_min"),rem_minutes:integerValue(row,"rem_min"),awake_minutes:integerValue(row,"awake_min")}))]));
  for(const table of ["health.workout_logs","health.release_logs"]){for(const row of rows(snapshot,table)){const started=instant(row.started_at),occurredOn=date(row.log_date),asiaMatches=!started||localDate(started,"Asia/Shanghai")===occurredOn,utcMatches=!started||localDate(started,"UTC")===occurredOn,timeZone=asiaMatches?"Asia/Shanghai":"UTC",structuredStarted=asiaMatches||utcMatches?started:undefined;objects.push(nativeObject(snapshot,table,row,owner,[rawTarget(snapshot,table,row,"workout",clean({occurred_on:occurredOn,time_zone:timeZone,session_type:stringValue(row,"session_type")??(table.endsWith("release_logs")?"release":"workout"),started_at:structuredStarted,duration_minutes:integerValue(row,"duration_min"),distance_km:stringValue(row,"distance_km"),calories_kcal:stringValue(row,"calories"),rpe:integerValue(row,"rpe"),heart_rate_avg:integerValue(row,"avg_hr"),detail:clean({legacy_detail:row.detail??undefined,legacy_started_at:structuredStarted?undefined:started,max_hr:integerValue(row,"max_hr"),notes:stringValue(row,"notes"),plan_id:stringValue(row,"plan_id"),enrollment_id:stringValue(row,"enrollment_id"),source:stringValue(row,"source"),external_id:stringValue(row,"external_id")})}))]));}}
  const habits=new Map(rows(snapshot,"health.habits").map(row=>[String(row.id),row]));for(const row of rows(snapshot,"health.habit_logs")){const habit=habits.get(String(row.habit_id));objects.push(nativeObject(snapshot,"health.habit_logs",row,owner,[rawTarget(snapshot,"health.habit_logs",row,"habit",{occurred_on:date(row.log_date),time_zone:"Asia/Shanghai",habit_key:String(habit?.name??row.habit_id),done_count:integerValue(row,"done_count")??0,explicit_denial:(integerValue(row,"done_count")??0)===0})]));}
  for(const row of rows(snapshot,"health.fitness_tests"))objects.push(nativeObject(snapshot,"health.fitness_tests",row,owner,[rawTarget(snapshot,"health.fitness_tests",row,"fitness_test",{occurred_on:date(row.test_date),time_zone:"Asia/Shanghai",group_kind:"fitness_test",observations:[{metric_key:"fitness_value",value:String(row.value),unit:"score",original_field:String(row.item)}]})]));
  for(const row of rows(snapshot,"health.lab_results"))objects.push(nativeObject(snapshot,"health.lab_results",row,owner,[rawTarget(snapshot,"health.lab_results",row,"lab",{occurred_on:date(row.report_date),time_zone:"Asia/Shanghai",group_kind:"lab_report",observations:[{metric_key:"lab_value",value:String(row.value),unit:stringValue(row,"unit")??"value",original_field:String(row.item_label??row.item_key)}]})]));
  const foodNames=new Map<string,string>(),foodIds=new Map<string,string>();for(const row of rows(snapshot,"health.foods")){const id=stableMigrationId("food",[snapshot.source_instance,pk(byName(snapshot,"health.foods")!,row)]);foodNames.set(String(row.id),String(row.name));foodIds.set(String(row.id),id);objects.push(nativeObject(snapshot,"health.foods",row,owner,[target("food_reference","food",id,{name:String(row.name),nutrients:clean({energy_kcal:stringValue(row,"kcal_per_100g"),protein_g:stringValue(row,"protein_g"),fat_g:stringValue(row,"fat_g"),carb_g:stringValue(row,"carb_g"),category:stringValue(row,"category"),tcm_tags:row.tcm_tags??undefined,notes:stringValue(row,"notes"),barcode:stringValue(row,"barcode")}),provenance:"legacy_health",state:"active",revision:1})]));}
  for(const row of rows(snapshot,"health.recipes")){const id=stableMigrationId("recipe",[snapshot.source_instance,pk(byName(snapshot,"health.recipes")!,row)]),instructions=[stringValue(row,"method"),stringValue(row,"effects"),stringValue(row,"contraindications"),stringValue(row,"source")].filter(Boolean).join("\n\n");objects.push(nativeObject(snapshot,"health.recipes",row,owner,[target("recipe","recipe",id,{title:String(row.name),servings:1,instructions,items:[{name:String(row.name),free_text:String(row.ingredients),estimate:true}],state:"active",revision:1})]));}
  for(const row of rows(snapshot,"health.meal_templates")){const id=stableMigrationId("meal_template",[snapshot.source_instance,pk(byName(snapshot,"health.meal_templates")!,row)]),items=Array.isArray(row.items)?row.items.map((item,index)=>intake(item as Row,stableMigrationId("intake",[id,index]),foodNames,foodIds)):[];objects.push(nativeObject(snapshot,"health.meal_templates",row,owner,[target("meal_template","meal_template",id,{name:String(row.name),items,revision:1})]));}
  const buckets=new Map<string,Row[]>();for(const row of rows(snapshot,"health.diet_logs")){const key=`${date(row.log_date)}:${String(row.meal)}`,bucket=buckets.get(key)??[];bucket.push(row);buckets.set(key,bucket);}for(const [key,bucket] of buckets){const [occurredOn,legacyMeal]=key.split(":"),id=stableMigrationId("meal",[snapshot.source_instance,"health.diet_logs",key]),items=bucket.sort((a,b)=>Number(a.id)-Number(b.id)).map(row=>intake(row,stableMigrationId("intake",[snapshot.source_instance,"health.diet_logs",row.id]),foodNames,foodIds)),safe=sanitize(bucket);objects.push({change_kind:"upsert",source:source(snapshot,"health.diet_logs",{bucket:key},owner,bucket.map(revision).filter(Boolean).sort().at(-1)),payload:{legacy_rows:safe.value,redacted_fields:safe.redactions},targets:[target("meal","meal",id,{occurred_on:occurredOn!,time_zone:"Asia/Shanghai",meal_type:mealType(legacyMeal),grouping_origin:"legacy_health_date_meal",items,revision:1})]});}
  for(const row of rows(snapshot,"health.workout_plans")){const id=stableMigrationId("health_plan",[snapshot.source_instance,"workout",row.id]);objects.push(nativeObject(snapshot,"health.workout_plans",row,owner,[target("workout_plan","health_plan",id,{kind:"workout",name:String(row.name),schedule:row.weekly_template??{kind:"legacy_unspecified"},detail:clean({goal:stringValue(row,"goal"),duration_weeks:integerValue(row,"duration_weeks"),source_doc:stringValue(row,"source_doc"),content_md:stringValue(row,"content_md"),phases:row.phases??undefined}),state:"active",revision:1})]));}
  for(const row of rows(snapshot,"health.habits")){const id=stableMigrationId("health_plan",[snapshot.source_instance,"habit",row.id]);objects.push(nativeObject(snapshot,"health.habits",row,owner,[target("habit_plan","health_plan",id,{kind:"habit",name:String(row.name),schedule:clean({period:stringValue(row,"period")??"daily",target_per_period:integerValue(row,"target_per_period")??1,time_hint:stringValue(row,"time_hint"),auto_rule:stringValue(row,"auto_rule"),sort:integerValue(row,"sort")??0}),state:booleanValue(row,"active")===false?"ended":"active",revision:1})]));}
  const photos=rows(snapshot,"health.diet_photos");if(photos.length&&!assetRoot)throw new Error("health photo rows require asset_root");if(assetRoot){const root=await realpath(assetRoot);for(const row of photos){const filename=String(row.filename);if(filename!==basename(filename))throw new Error(`unsafe legacy photo filename: ${filename}`);const file=await realpath(resolve(root,filename)),within=relative(root,file);if(within.startsWith(".."))throw new Error(`legacy photo escapes asset root: ${filename}`);const bytes=await readFile(file),id=stableMigrationId("asset",[snapshot.source_instance,"health.diet_photos",row.id]),key=`${date(row.log_date)}:${String(row.meal)}`,mealId=stableMigrationId("meal",[snapshot.source_instance,"health.diet_logs",key]),contentHash=createHash("sha256").update(bytes).digest("hex"),targets:MigrationBundle["objects"][number]["targets"]=[];if(!buckets.has(key))targets.push(target("photo_meal","meal",mealId,{occurred_on:date(row.log_date),time_zone:"Asia/Shanghai",meal_type:mealType(row.meal),items:[],revision:1}));targets.push(target("meal_photo","asset",id,{media_type:stringValue(row,"content_type")??"application/octet-stream",bytes_base64:bytes.toString("base64"),byte_size:bytes.byteLength,sha256:contentHash,meal_id:mealId,filename}));objects.push(nativeObject(snapshot,"health.diet_photos",row,owner,targets));}}
  return objects;
}

function localDate(at:unknown,timeZone:string):string{const instantValue=new Date(String(at));if(Number.isNaN(instantValue.getTime()))return date(at);const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(instantValue),part=(name:string)=>parts.find(item=>item.type===name)?.value;return`${part("year")}-${part("month")}-${part("day")}`;}
function mapLedger(snapshot:LegacySnapshot,owner:string):MigrationBundle["objects"]{
  const objects:MigrationBundle["objects"]=included(snapshot).flatMap(table=>archive(snapshot,table,owner));
  const records=new Map(rows(snapshot,"ledger_records").map(row=>[String(row.id),row])),moneyByRecord=new Map(rows(snapshot,"money_entries").map(row=>[String(row.record_id),row])),eventsByRecord=new Map(rows(snapshot,"consumption_events").map(row=>[String(row.record_id),row])),categories=new Map(rows(snapshot,"money_categories").map(row=>[String(row.id),String(row.name??row.key)])),linesByEvent=new Map<string,Row[]>();for(const row of rows(snapshot,"consumption_lines")){const key=String(row.event_id),bucket=linesByEvent.get(key)??[];bucket.push(row);linesByEvent.set(key,bucket);}
  const recordTable=byName(snapshot,"ledger_records");if(!recordTable)throw new Error("ledger snapshot does not contain ledger_records");
  for(const record of records.values()){
    const money=moneyByRecord.get(String(record.id)),event=eventsByRecord.get(String(record.id));if(!money&&!event)continue;const timeZone=stringValue(record,"timezone")??"Asia/Shanghai",occurredAt=instant(record.occurred_at),occurredOn=localDate(record.occurred_at,timeZone),category=money?.category_id?categories.get(String(money.category_id)):undefined,state=String(record.state??"confirmed"),base=clean({record_id:stableMigrationId("record",[snapshot.source_instance,record.id]),state,occurred_on:occurredOn,occurred_at:occurredAt,time_zone:timeZone,note:stringValue(record,"note"),revision:integerValue(record,"revision")??1,confirmed_at:instant(record.confirmed_at),voided_at:instant(record.voided_at)}),safe=sanitize({record,money,event,lines:event?linesByEvent.get(String(event.id))??[]:[]});
    if(event){const id=stableMigrationId("purchase",[snapshot.source_instance,event.id]),lines=(linesByEvent.get(String(event.id))??[]).sort((a,b)=>(integerValue(a,"sort_order")??0)-(integerValue(b,"sort_order")??0)).map((line,index)=>clean({id:stableMigrationId("purchase_item",[snapshot.source_instance,line.id]),raw_name:String(line.raw_name),quantity:stringValue(line,"quantity"),unit:stringValue(line,"unit"),line_amount:stringValue(line,"amount"),category_key:stringValue(line,"content_category"),position:index})),entry=money?clean({id:stableMigrationId("money",[snapshot.source_instance,money.id]),entry_type:String(money.type),amount:String(money.amount),currency:String(money.currency),category,counterparty:stringValue(event,"merchant_name_raw"),payment_method:stringValue(money,"payment_method"),source_scale:String(money.amount).split(".")[1]?.length??0,revision:1}):undefined;objects.push({change_kind:"upsert",source:source(snapshot,"ledger_records",pk(recordTable,record),owner,revision(record)),payload:{legacy_join:safe.value,redacted_fields:safe.redactions},targets:[target("purchase","purchase",id,clean({...base,merchant:stringValue(event,"merchant_name_raw"),amount:money?String(money.amount):undefined,currency:money?String(money.currency):"CNY",category,scene:stringValue(event,"scene"),channel_name_raw:stringValue(event,"channel_name_raw"),place_ref:stringValue(event,"place_ref"),rating:integerValue(event,"rating"),would_repeat:booleanValue(event,"would_repeat"),items:lines,money_entry:entry}))]});
    }else if(money){const id=stableMigrationId("money",[snapshot.source_instance,money.id]);objects.push({change_kind:"upsert",source:source(snapshot,"ledger_records",pk(recordTable,record),owner,revision(record)),payload:{legacy_join:safe.value,redacted_fields:safe.redactions},targets:[target("money_entry","money_entry",id,clean({...base,entry_type:String(money.type),amount:String(money.amount),currency:String(money.currency),category,counterparty:stringValue(money,"title"),payment_method:stringValue(money,"payment_method"),source_scale:String(money.amount).split(".")[1]?.length??0}))]});}
  }
  return objects;
}

await main();
