import assert from "node:assert/strict";
import test from "node:test";
import { materializeNotifications } from "../src/notification-worker.js";
import { pgOnly, reviewFixture } from "./review-fixture.js";

test("repairs folded purchase detail without duplicating the order or money",pgOnly,async t=>{
  const {pool,executor,context,command}=await reviewFixture(t);
  const purchase=await executor.execute(context,command("life.record_purchase",{occurred_on:"2026-06-13",time_zone:"Asia/Shanghai",scene:"online_purchase",merchant_name_raw:"京东",items:[{raw_name:"小熊电火锅等多件"}],payment:{amount:"225.96",currency:"CNY",occurred_on:"2026-06-13",time_zone:"Asia/Shanghai"}}));
  const folded=(await pool.query("select id from purchase_items where purchase_id=$1",[purchase.actual_values.purchase_id])).rows[0].id as string;
  const updateCommand=command("life.update_purchase_items",{record_id:purchase.actual_values.record_id,expected_revision:1,detail_state:"supplemented",folded_item_ids:[folded],changes:[{action:"append",item:{raw_name:"西麦即食燕麦片",quantity:"1854",unit:"g"}}],reason:"订单来源把多件商品折叠为首件摘要，按用户确认补录燕麦"});
  const first=await executor.execute(context,updateCommand),replayed=await executor.execute(context,updateCommand);assert.equal(replayed.execution_id,first.execution_id);
  await executor.execute(context,command("life.update_purchase_items",{record_id:purchase.actual_values.record_id,expected_revision:2,detail_state:"supplemented",folded_item_ids:[folded],changes:[{action:"replace",item_id:first.actual_values.changed_item_id,item:{raw_name:"西麦即食燕麦片，共1854g，3袋",quantity:"1854",unit:"g"}}],reason:"补全商品标题中的包装规格"}));
  const rows=await pool.query("select raw_name,detail_role,quantity::text,unit from purchase_items where purchase_id=$1 order by position",[purchase.actual_values.purchase_id]);assert.deepEqual(rows.rows,[{raw_name:"小熊电火锅等多件",detail_role:"folded_summary",quantity:null,unit:null},{raw_name:"西麦即食燕麦片，共1854g，3袋",detail_role:"supplemented_item",quantity:"1854.000000",unit:"g"}]);
  assert.equal((await pool.query("select count(*)::int count from purchases where id=$1",[purchase.actual_values.purchase_id])).rows[0].count,1);assert.equal((await pool.query("select count(*)::int count from money_entries where record_id=$1",[purchase.actual_values.record_id])).rows[0].count,1);assert.equal((await pool.query("select amount::text from money_entries where record_id=$1",[purchase.actual_values.record_id])).rows[0].amount,"225.960000");assert.equal((await pool.query("select count(*)::int count from consumption_record_revisions where record_id=$1",[purchase.actual_values.record_id])).rows[0].count,2);
  await assert.rejects(()=>executor.execute(context,command("life.update_purchase_items",{record_id:purchase.actual_values.record_id,expected_revision:1,detail_state:"supplemented",folded_item_ids:[folded],changes:[{action:"append",item:{raw_name:"重复燕麦",quantity:"1854",unit:"g"}}],reason:"陈旧版本"})),/revision changed/u);
});

test("recomputes use-cycle remaining from effective intake and materializes one reminder",pgOnly,async t=>{
  const {pool,run,queries,context}=await reviewFixture(t);
  const purchase=await run("life.record_purchase",{occurred_on:"2026-06-13",time_zone:"Asia/Shanghai",scene:"online_purchase",merchant_name_raw:"京东",items:[{raw_name:"西麦即食燕麦片",quantity:"1854",unit:"g"}]});const purchaseItem=(await pool.query("select id from purchase_items where purchase_id=$1",[purchase.actual_values.purchase_id])).rows[0].id as string;
  const created=await run("money.set_use_cycle",{purchase_record_id:purchase.actual_values.record_id,purchase_item_id:purchaseItem,item_name:"西麦燕麦（最后一袋，已开封）",started_on:"2026-09-15",state:"active",initial_quantity:"618",quantity_unit:"g",expected_daily_usage:"45",replenish_threshold:"90",time_zone:"Asia/Shanghai",match_mode:"exact_name",match_value:"西麦OATS",reminder_enabled:true});
  const meal=await run("life.record_meal",{occurred_on:"2026-09-15",time_zone:"Asia/Shanghai",meal_type:"breakfast",items:[{name:"西麦ＯＡＴＳ",quantity:"45",unit:"g",estimate:false},{name:"牛奶",quantity:"250",unit:"ml",estimate:false}]});let planning=await queries.moneyPlanning(context,"2026-09");let cycle=planning.use_cycles.find(item=>item.id===created.actual_values.use_cycle_id)!;assert.equal(cycle.remaining_quantity,"573");assert.equal(cycle.purchase_item_id,purchaseItem);
  const intake=(await pool.query("select id,revision from intake_items where meal_id=$1 and unit='g'",[meal.actual_values.meal_id])).rows[0];await run("life.correct_intake",{item_id:intake.id,expected_revision:intake.revision,item:{name:"西麦OATS",quantity:"573",unit:"g",estimate:false},reason:"修正实际用量"});planning=await queries.moneyPlanning(context,"2026-09");cycle=planning.use_cycles.find(item=>item.id===created.actual_values.use_cycle_id)!;assert.equal(cycle.remaining_quantity,"45");assert.equal(cycle.balance_status,"replenish_now");assert.equal(await materializeNotifications(pool),1);assert.equal(await materializeNotifications(pool),0);assert.equal((await pool.query("select count(*)::int count from notifications where source_type='use_cycle' and source_id=$1",[created.actual_values.use_cycle_id])).rows[0].count,1);
  await run("life.remove_intake",{item_id:intake.id,expected_revision:2,reason:"实际没有食用燕麦"});planning=await queries.moneyPlanning(context,"2026-09");cycle=planning.use_cycles.find(item=>item.id===created.actual_values.use_cycle_id)!;assert.equal(cycle.remaining_quantity,"618");assert.equal(cycle.matched_intakes,0);
});

test("unknown package specification stays explicit and never schedules a reminder",pgOnly,async t=>{
  const {pool,run,queries,context}=await reviewFixture(t);const created=await run("money.set_use_cycle",{item_name:"规格未知的燕麦",started_on:"2026-09-15",state:"active",quantity_unit:"g",expected_daily_usage:"45",replenish_lead_days:2,time_zone:"Asia/Shanghai",match_mode:"exact_name",match_value:"规格未知的燕麦",reminder_enabled:true});const planning=await queries.moneyPlanning(context,"2026-09"),cycle=planning.use_cycles.find(item=>item.id===created.actual_values.use_cycle_id)!;assert.equal(cycle.balance_status,"needs_specification");assert.equal(cycle.projected_depletion_on,null);await materializeNotifications(pool);assert.equal((await pool.query("select count(*)::int count from notifications where source_type='use_cycle' and source_id=$1",[created.actual_values.use_cycle_id])).rows[0].count,0);
});
