import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { Hono } from "hono";
import { deleteCookie, getCookie, setCookie } from "hono/cookie";

export type WebSessionOptions={authorizationUrl:string;tokenUrl:string;clientId:string;redirectUri:string;webOrigin:string;sessionSecret:string;clientSecret?:string};
const encode=(value:Buffer)=>value.toString("base64url");
const sign=(nonce:string,secret:string)=>`${nonce}.${createHmac("sha256",secret).update(nonce).digest("base64url")}`;
function validState(value:string|undefined,cookie:string|undefined,secret:string):boolean{if(!value||!cookie||value!==cookie)return false;const split=value.lastIndexOf(".");if(split<1)return false;const expected=sign(value.slice(0,split),secret);return expected.length===value.length&&timingSafeEqual(Buffer.from(expected),Buffer.from(value));}

export function installWebSessionRoutes(app:Hono,options:WebSessionOptions):void{
  app.get("/auth/login",context=>{const verifier=encode(randomBytes(48)),challenge=encode(createHash("sha256").update(verifier).digest()),state=sign(encode(randomBytes(24)),options.sessionSecret);setCookie(context,"shadow_oidc_state",state,{httpOnly:true,secure:true,sameSite:"Lax",path:"/auth",maxAge:600});setCookie(context,"shadow_oidc_verifier",verifier,{httpOnly:true,secure:true,sameSite:"Lax",path:"/auth",maxAge:600});const target=new URL(options.authorizationUrl);target.searchParams.set("response_type","code");target.searchParams.set("client_id",options.clientId);target.searchParams.set("redirect_uri",options.redirectUri);target.searchParams.set("scope","openid profile offline_access");target.searchParams.set("state",state);target.searchParams.set("code_challenge",challenge);target.searchParams.set("code_challenge_method","S256");return context.redirect(target.toString());});
  app.get("/auth/callback",async context=>{const code=context.req.query("code"),state=context.req.query("state"),savedState=getCookie(context,"shadow_oidc_state"),verifier=getCookie(context,"shadow_oidc_verifier");deleteCookie(context,"shadow_oidc_state",{path:"/auth"});deleteCookie(context,"shadow_oidc_verifier",{path:"/auth"});if(!code||!verifier||!validState(state,savedState,options.sessionSecret))return context.json({protocol:"shadow.error",code:"permission_denied",message:"The login response could not be verified."},401);const form=new URLSearchParams({grant_type:"authorization_code",code,client_id:options.clientId,redirect_uri:options.redirectUri,code_verifier:verifier});if(options.clientSecret)form.set("client_secret",options.clientSecret);const response=await fetch(options.tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:form});if(!response.ok)return context.json({protocol:"shadow.error",code:"permission_denied",message:"The product session could not be established."},401);const token=await response.json() as {access_token?:string;expires_in?:number};if(!token.access_token)return context.json({protocol:"shadow.error",code:"permission_denied",message:"The identity provider returned no access token."},401);setCookie(context,"shadow_access_token",token.access_token,{httpOnly:true,secure:true,sameSite:"Lax",path:"/",maxAge:Math.max(60,Math.min(token.expires_in??3600,86400))});return context.redirect(options.webOrigin);});
  app.post("/auth/logout",context=>{if(context.req.header("origin")!==options.webOrigin)return context.json({protocol:"shadow.error",code:"permission_denied",message:"The logout origin is invalid."},403);deleteCookie(context,"shadow_access_token",{path:"/"});return context.json({status:"logged_out"});});
}
