import assert from "node:assert/strict";
import test from "node:test";
import { capabilityRegistry } from "@shadow/contracts";
import { disableImportRuleCommand, initialCandidateFields, loadMoneyImportReview, resolveCandidateCommand, type MoneyImportCandidate } from "../src/money-import.js";

const candidate:MoneyImportCandidate={id:"import_candidate_12345678",position:0,external_id:"trade-1",raw:{金额:"18.00"},proposed:{entry_type:"expense",amount:"18.00",currency:"CNY",occurred_on:"2026-09-10",time_zone:"Asia/Shanghai",counterparty:"社区超市"},issues:[],warnings:[],applied_rule_ids:[],status:"pending",duplicate_of_record_id:null,linked_record_id:null,revision:1};

test("money import review uses an encoded batch route and explicit auth failure",async()=>{let requested="";const fetcher=async(input:RequestInfo|URL)=>{requested=String(input);return new Response(JSON.stringify({batch:{id:"import_batch_12345678",source_name:"账单",format:"csv",content_hash:"hash",status:"review",total:1,pending:1,confirmed:0,ignored:0,invalid:0,created_at:"2026-09-10T00:00:00Z"},candidates:[candidate],rules:[]}),{headers:{"content-type":"application/json"}});};const result=await loadMoneyImportReview(fetcher as typeof fetch,{},"import_batch_12345678");assert.equal(requested,"/api/money/imports/import_batch_12345678");assert.equal(result.candidates[0]?.raw.金额,"18.00");await assert.rejects(()=>loadMoneyImportReview((async()=>new Response("{}",{status:401})) as typeof fetch,{},"import_batch_12345678"),/登录已失效/u);});

test("candidate confirmation preserves reviewed fields and explicit refund links",()=>{const fields={...initialCandidateFields(candidate,"UTC"),entryType:"refund" as const,amount:"10.00",originalEntryId:"money_original_12345678",note:"部分退款",rememberRule:true},built=resolveCandidateCommand(candidate,"confirm",fields);assert.equal(built.capability,"money.resolve_import_candidate");assert.deepEqual(capabilityRegistry[built.capability].inputSchema.parse(built.input),{candidate_id:candidate.id,expected_revision:1,decision:"confirm",corrections:{entry_type:"refund",amount:"10.00",currency:"CNY",occurred_on:"2026-09-10",time_zone:"Asia/Shanghai",counterparty:"社区超市",note:"部分退款"},original_entry_id:"money_original_12345678",remember_rule:false,reason:"在 Web 账单复核中确认"});});

test("ignoring a candidate cannot accidentally carry accounting corrections",()=>{const built=resolveCandidateCommand(candidate,"ignore",initialCandidateFields(candidate,"UTC"));assert.deepEqual(capabilityRegistry[built.capability].inputSchema.parse(built.input),{candidate_id:candidate.id,expected_revision:1,decision:"ignore",remember_rule:false,reason:"在 Web 账单复核中忽略"});});

test("import rules remain explicit and reversibly disabled",()=>{const rule={id:"import_rule_12345678",match_value:"社区超市",replacements:{entry_type:"expense" as const,category:"日用",payment_method:"wechat"},state:"active" as const,revision:2},built=disableImportRuleCommand(rule);assert.equal(built.capability,"money.set_import_rule");assert.deepEqual(capabilityRegistry[built.capability].inputSchema.parse(built.input),{rule_id:rule.id,expected_revision:2,match_value:"社区超市",replacements:rule.replacements,state:"disabled"});});
