import type { Pool } from "pg";

export interface StoredRunEvent { sequence: number; event_type: string; payload: unknown; created_at: string; }
export interface StoredMessage { id:string; role:"user"|"assistant"; content:string; createdAt:string; }
export interface StoredRun { id:string; thread_id:string; status:"running"|"awaiting_input"|"completed"|"interrupted"|"failed"; error:string|null; started_at:string; finished_at:string|null; last_sequence:number; }

export class AgentRepository {
  constructor(private readonly pool: Pool) {}
  async createThread(subjectId: string, id: string, title: string): Promise<void> { await this.pool.query("insert into threads(id,subject_id,title) values($1,$2,$3)",[id,subjectId,title]); }
  async assertThread(subjectId: string, threadId: string): Promise<void> { const found=await this.pool.query("select 1 from threads where id=$1 and subject_id=$2",[threadId,subjectId]); if(!found.rowCount) throw new Error("thread_not_found"); }
  async addMessage(threadId: string,id:string,role:"user"|"assistant",content:string):Promise<void>{await this.pool.query("insert into messages(id,thread_id,role,content) values($1,$2,$3,$4)",[id,threadId,role,content]);await this.pool.query("update threads set updated_at=now() where id=$1",[threadId]);}
  async conversation(subjectId:string,threadId:string,limit=50):Promise<StoredMessage[]>{const result=await this.pool.query<{id:string;role:"user"|"assistant";content:string;created_at:string}>("select message.id,message.role,message.content,message.created_at::text from messages message join threads thread on thread.id=message.thread_id where message.thread_id=$1 and thread.subject_id=$2 order by message.created_at desc,message.id desc limit $3",[threadId,subjectId,limit]);return result.rows.reverse().map(row=>({id:row.id,role:row.role,content:row.content,createdAt:row.created_at}));}
  async createRun(threadId:string,id:string):Promise<void>{const client=await this.pool.connect();try{await client.query("begin");await client.query("select id from threads where id=$1 for update",[threadId]);const active=await client.query("select 1 from runs where thread_id=$1 and status='running'",[threadId]);if(active.rowCount)throw new Error("thread_has_active_run");await client.query("insert into runs(id,thread_id,status) values($1,$2,'running')",[id,threadId]);await client.query("commit");}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
  async appendEvent(runId:string,eventType:string,payload:unknown):Promise<number>{const client=await this.pool.connect();try{await client.query("begin");await client.query("select id from runs where id=$1 for update",[runId]);const next=await client.query<{sequence:number}>("select coalesce(max(sequence),0)+1 as sequence from run_events where run_id=$1",[runId]);const sequence=next.rows[0]!.sequence;await client.query("insert into run_events(run_id,sequence,event_type,payload) values($1,$2,$3,$4)",[runId,sequence,eventType,payload]);await client.query("commit");return sequence;}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
  async finishRun(runId:string,status:"awaiting_input"|"completed"|"interrupted"|"failed",error?:string):Promise<void>{await this.pool.query("update runs set status=$2,error=$3,finished_at=now() where id=$1",[runId,status,error]);}
  async run(subjectId:string,runId:string):Promise<StoredRun|undefined>{const result=await this.pool.query<StoredRun>("select r.id,r.thread_id,r.status,r.error,r.started_at::text,r.finished_at::text,coalesce((select max(sequence) from run_events where run_id=r.id),0)::int last_sequence from runs r join threads t on t.id=r.thread_id where r.id=$1 and t.subject_id=$2",[runId,subjectId]);return result.rows[0];}
  async events(subjectId:string,runId:string,after=0):Promise<StoredRunEvent[]>{const result=await this.pool.query<StoredRunEvent>("select e.sequence,e.event_type,e.payload,e.created_at::text from run_events e join runs r on r.id=e.run_id join threads t on t.id=r.thread_id where e.run_id=$1 and t.subject_id=$2 and e.sequence>$3 order by e.sequence",[runId,subjectId,after]);return result.rows;}
  async listThreads(subjectId:string):Promise<unknown[]>{const result=await this.pool.query("select t.id,t.title,t.created_at,t.updated_at,(select content from messages where thread_id=t.id order by created_at desc limit 1) last_message from threads t where subject_id=$1 order by updated_at desc limit 100",[subjectId]);return result.rows;}
}
