import { createHash } from "node:crypto";
import { healthDailyActivityPayloadSchema, healthHabitPayloadSchema, healthObservationPayloadSchema, healthSleepPayloadSchema, healthWellbeingPayloadSchema, healthWorkoutPayloadSchema } from "@shadow/contracts";
import { Pool, type PoolClient, type PoolConfig } from "pg";

const projectionTables=["health_observations","health_daily_wellbeing","health_sleep_sessions","health_workout_sessions","health_daily_activity","health_habit_logs"] as const;
const metricUnits:Record<string,readonly string[]>={weight:["kg"],body_fat:["%"],muscle_mass:["kg"],skeletal_muscle:["kg"],body_water:["kg"],visceral_fat:["level"],bmr:["kcal/day"],impedance_low:["ohm"],impedance_high:["ohm"],waist:["cm"],chest:["cm"],hip:["cm"],heart_rate:["bpm"],blood_pressure_systolic:["mmHg"],blood_pressure_diastolic:["mmHg"],temperature:["C","°C"],spo2:["%"],blood_glucose:["mmol/L","mg/dL"]};
const stableId=(prefix:string,value:string)=>`${prefix}_${createHash("sha256").update(value).digest("hex").slice(0,24)}`;

export interface HealthNormalizationResult{raw_id:string;raw_version:number;state:"completed"|"failed"|"stale"|"deleted";affected_dates:string[];error?:string;}

export async function normalizeHealthRaw(config:PoolConfig|Pool,rawId:string,rawVersion:number,normalizerVersion="health-normalizer"):Promise<HealthNormalizationResult>{
  const pool=config instanceof Pool?config:new Pool(config),ownsPool=!(config instanceof Pool),client=await pool.connect();
  try{return await normalize(client,rawId,rawVersion,normalizerVersion);}finally{client.release();if(ownsPool)await pool.end();}
}

async function normalize(client:PoolClient,rawId:string,rawVersion:number,normalizerVersion:string):Promise<HealthNormalizationResult>{
  await client.query("begin");
  try{
    const selected=await client.query<{subject_id:string;record_type:string;current_version:string;state:string;payload:unknown;change_kind:string}>("select raw.subject_id,raw.record_type,raw.current_version::text,raw.state,revision.payload,revision.change_kind from health_raw_records raw join health_raw_revisions revision on revision.raw_id=raw.id and revision.record_version=$2 where raw.id=$1 for update of raw",[rawId,rawVersion]);
    const raw=selected.rows[0];if(!raw)throw new Error("Health raw revision does not exist");
    if(Number(raw.current_version)!==rawVersion){await saveStep(client,rawId,rawVersion,normalizerVersion,"stale",[],null);await client.query("commit");return{raw_id:rawId,raw_version:rawVersion,state:"stale",affected_dates:[]};}
    const previousDates=await projectionDates(client,rawId);for(const table of projectionTables)await client.query(`update ${table} set effective=false where raw_id=$1 and effective`,[rawId]);
    if(raw.change_kind==="delete"||raw.state==="deleted"){await invalidate(client,raw.subject_id,previousDates,normalizerVersion);await saveStep(client,rawId,rawVersion,normalizerVersion,"deleted",previousDates,null);await client.query("commit");return{raw_id:rawId,raw_version:rawVersion,state:"deleted",affected_dates:previousDates};}
    const currentDates=await project(client,{...raw,raw_id:rawId,raw_version:rawVersion});const affectedDates=[...new Set([...previousDates,...currentDates])].sort();await invalidate(client,raw.subject_id,affectedDates,normalizerVersion);await client.query("update health_raw_records set state='normalized',pending_reason=null,normalization_attempts=normalization_attempts+1 where id=$1 and current_version=$2",[rawId,rawVersion]);await saveStep(client,rawId,rawVersion,normalizerVersion,"completed",affectedDates,null);await client.query("commit");return{raw_id:rawId,raw_version:rawVersion,state:"completed",affected_dates:affectedDates};
  }catch(error){await client.query("rollback");const message=error instanceof Error?error.message:"Health normalization failed";await client.query("begin");try{await client.query("update health_raw_records set state='failed',pending_reason='normalization_failed',normalization_attempts=normalization_attempts+1 where id=$1 and current_version=$2",[rawId,rawVersion]);await saveStep(client,rawId,rawVersion,normalizerVersion,"failed",[],message);await client.query("commit");}catch{await client.query("rollback");}return{raw_id:rawId,raw_version:rawVersion,state:"failed",affected_dates:[],error:message};}
}

async function project(client:PoolClient,raw:{raw_id:string;raw_version:number;subject_id:string;record_type:string;payload:unknown}):Promise<string[]>{
  const id=stableId("healthfact",raw.raw_id);
  if(["body","lab","fitness_test"].includes(raw.record_type)){const value=healthObservationPayloadSchema.parse(normalizeDeviceDecimals(raw.payload,raw.record_type));for(const [position,item] of value.observations.entries()){const allowed=metricUnits[item.metric_key];if(allowed&&!allowed.includes(item.unit))throw new Error(`Unsupported unit ${item.unit} for ${item.metric_key}`);await client.query("insert into health_observations(id,subject_id,raw_id,raw_version,metric_key,position,value,unit,occurred_on,occurred_at,time_zone,group_id,group_kind,original_field,autofilled,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,true) on conflict(raw_id,metric_key,position) do update set raw_version=excluded.raw_version,value=excluded.value,unit=excluded.unit,occurred_on=excluded.occurred_on,occurred_at=excluded.occurred_at,time_zone=excluded.time_zone,group_kind=excluded.group_kind,original_field=excluded.original_field,autofilled=excluded.autofilled,effective=true,revision=health_observations.revision+1",[stableId("healthobs",`${raw.raw_id}:${item.metric_key}:${position}`),raw.subject_id,raw.raw_id,raw.raw_version,item.metric_key,position,item.value,item.unit,value.occurred_on,value.occurred_at??null,value.time_zone,id,value.group_kind,item.original_field??null,item.autofilled]);}return[value.occurred_on];}
  if(raw.record_type==="wellbeing"){const value=healthWellbeingPayloadSchema.parse(raw.payload);await client.query("insert into health_daily_wellbeing(id,subject_id,raw_id,raw_version,occurred_on,time_zone,mood_score,energy_level,sleep_quality,morning_erection,notes,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true) on conflict(raw_id) do update set raw_version=excluded.raw_version,occurred_on=excluded.occurred_on,time_zone=excluded.time_zone,mood_score=excluded.mood_score,energy_level=excluded.energy_level,sleep_quality=excluded.sleep_quality,morning_erection=excluded.morning_erection,notes=excluded.notes,effective=true,revision=health_daily_wellbeing.revision+1",[id,raw.subject_id,raw.raw_id,raw.raw_version,value.occurred_on,value.time_zone,value.mood_score??null,value.energy_level??null,value.sleep_quality??null,value.morning_erection??null,value.notes??null]);return[value.occurred_on];}
  if(raw.record_type==="sleep"){const value=healthSleepPayloadSchema.parse(raw.payload);await client.query("insert into health_sleep_sessions(id,subject_id,raw_id,raw_version,wake_date,time_zone,started_at,ended_at,total_minutes,deep_minutes,light_minutes,rem_minutes,awake_minutes,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,true) on conflict(raw_id) do update set raw_version=excluded.raw_version,wake_date=excluded.wake_date,time_zone=excluded.time_zone,started_at=excluded.started_at,ended_at=excluded.ended_at,total_minutes=excluded.total_minutes,deep_minutes=excluded.deep_minutes,light_minutes=excluded.light_minutes,rem_minutes=excluded.rem_minutes,awake_minutes=excluded.awake_minutes,effective=true,revision=health_sleep_sessions.revision+1",[id,raw.subject_id,raw.raw_id,raw.raw_version,value.wake_date,value.time_zone,value.started_at??null,value.ended_at??null,value.total_minutes,value.deep_minutes??null,value.light_minutes??null,value.rem_minutes??null,value.awake_minutes??null]);return[value.wake_date];}
  if(raw.record_type==="workout"){const value=healthWorkoutPayloadSchema.parse(normalizeDeviceDecimals(raw.payload,raw.record_type));await client.query("insert into health_workout_sessions(id,subject_id,raw_id,raw_version,occurred_on,time_zone,session_type,started_at,duration_minutes,distance_km,calories_kcal,rpe,heart_rate_avg,detail,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,true) on conflict(raw_id) do update set raw_version=excluded.raw_version,occurred_on=excluded.occurred_on,time_zone=excluded.time_zone,session_type=excluded.session_type,started_at=excluded.started_at,duration_minutes=excluded.duration_minutes,distance_km=excluded.distance_km,calories_kcal=excluded.calories_kcal,rpe=excluded.rpe,heart_rate_avg=excluded.heart_rate_avg,detail=excluded.detail,effective=true,revision=health_workout_sessions.revision+1",[id,raw.subject_id,raw.raw_id,raw.raw_version,value.occurred_on,value.time_zone,value.session_type,value.started_at??null,value.duration_minutes??null,value.distance_km??null,value.calories_kcal??null,value.rpe??null,value.heart_rate_avg??null,value.detail??null]);return[value.occurred_on];}
  if(raw.record_type==="daily_activity"||raw.record_type==="steps_interval"){const value=healthDailyActivityPayloadSchema.parse(normalizeDeviceDecimals(raw.payload,raw.record_type)),effectiveCalories=maxDecimal(value.device_calories_kcal??null,value.workout_calories_kcal??null);if(raw.record_type==="steps_interval"&&!value.step_interval)throw new Error("steps_interval requires exact source bounds");await client.query("insert into health_daily_activity(id,subject_id,raw_id,raw_version,occurred_on,time_zone,steps,active_minutes,device_calories_kcal,workout_calories_kcal,effective_calories_kcal,field_sources,steps_started_at,steps_ended_at,steps_origin,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,true) on conflict(raw_id) do update set raw_version=excluded.raw_version,occurred_on=excluded.occurred_on,time_zone=excluded.time_zone,steps=excluded.steps,active_minutes=excluded.active_minutes,device_calories_kcal=excluded.device_calories_kcal,workout_calories_kcal=excluded.workout_calories_kcal,effective_calories_kcal=excluded.effective_calories_kcal,field_sources=excluded.field_sources,steps_started_at=excluded.steps_started_at,steps_ended_at=excluded.steps_ended_at,steps_origin=excluded.steps_origin,effective=true,revision=health_daily_activity.revision+1",[id,raw.subject_id,raw.raw_id,raw.raw_version,value.occurred_on,value.time_zone,value.steps??null,value.active_minutes??null,value.device_calories_kcal??null,value.workout_calories_kcal??null,effectiveCalories,JSON.stringify(value.field_sources),value.step_interval?.started_at??null,value.step_interval?.ended_at??null,value.step_interval?.data_origin??null]);return[value.occurred_on];}
  if(raw.record_type==="habit"){const value=healthHabitPayloadSchema.parse(raw.payload);await client.query("insert into health_habit_logs(id,subject_id,raw_id,raw_version,occurred_on,time_zone,habit_key,done_count,explicit_denial,note,effective) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true) on conflict(raw_id) do update set raw_version=excluded.raw_version,occurred_on=excluded.occurred_on,time_zone=excluded.time_zone,habit_key=excluded.habit_key,done_count=excluded.done_count,explicit_denial=excluded.explicit_denial,note=excluded.note,effective=true,revision=health_habit_logs.revision+1",[id,raw.subject_id,raw.raw_id,raw.raw_version,value.occurred_on,value.time_zone,value.habit_key,value.done_count,value.explicit_denial,value.note??null]);return[value.occurred_on];}
  throw new Error(`Unsupported health record type ${raw.record_type}`);
}

async function projectionDates(client:PoolClient,rawId:string):Promise<string[]>{const result=await client.query<{occurred_on:string}>("select occurred_on::text from health_observations where raw_id=$1 union select occurred_on::text from health_daily_wellbeing where raw_id=$1 union select wake_date::text from health_sleep_sessions where raw_id=$1 union select occurred_on::text from health_workout_sessions where raw_id=$1 union select occurred_on::text from health_daily_activity where raw_id=$1 union select occurred_on::text from health_habit_logs where raw_id=$1",[rawId]);return result.rows.map(row=>row.occurred_on);}
async function invalidate(client:PoolClient,subjectId:string,dates:string[],algorithmVersion:string):Promise<void>{for(const date of dates)await client.query("insert into health_projection_invalidations(subject_id,occurred_on,projection_key,algorithm_version,valid) values($1,$2,'daily_health',$3,false) on conflict(subject_id,occurred_on,projection_key,algorithm_version) do update set valid=false,updated_at=now()",[subjectId,date,algorithmVersion]);}
async function saveStep(client:PoolClient,rawId:string,rawVersion:number,normalizerVersion:string,state:string,dates:string[],error:string|null):Promise<void>{await client.query("insert into health_normalization_steps(raw_id,raw_version,normalizer_version,state,affected_dates,error) values($1,$2,$3,$4,$5,$6) on conflict(raw_id,raw_version,normalizer_version) do update set state=excluded.state,affected_dates=excluded.affected_dates,error=excluded.error,finished_at=now()",[rawId,rawVersion,normalizerVersion,state,JSON.stringify(dates),error]);}
function maxDecimal(left:string|null,right:string|null):string|null{if(left===null)return right;if(right===null)return left;const scale=Math.max(left.split(".")[1]?.length??0,right.split(".")[1]?.length??0);const integer=(value:string)=>BigInt(value.replace(".",""))*10n**BigInt(scale-(value.split(".")[1]?.length??0));return integer(left)>=integer(right)?left:right;}
function normalizeDeviceDecimals(payload:unknown,recordType:string):unknown{if(!payload||typeof payload!=="object"||Array.isArray(payload))return payload;const value={...(payload as Record<string,unknown>)};if(["body","lab","fitness_test"].includes(recordType)&&Array.isArray(value.observations))value.observations=value.observations.map(item=>item&&typeof item==="object"&&!Array.isArray(item)?{...(item as Record<string,unknown>),value:roundDeviceDecimal((item as Record<string,unknown>).value)}:item);if(recordType==="workout"){value.distance_km=roundDeviceDecimal(value.distance_km);value.calories_kcal=roundDeviceDecimal(value.calories_kcal);}if(recordType==="daily_activity"||recordType==="steps_interval"){value.device_calories_kcal=roundDeviceDecimal(value.device_calories_kcal);value.workout_calories_kcal=roundDeviceDecimal(value.workout_calories_kcal);}return value;}
function roundDeviceDecimal(value:unknown):unknown{if(typeof value!=="string")return value;const match=/^(0|[1-9]\d*)(?:\.(\d+))?$/u.exec(value),fraction=match?.[2];if(!match||!fraction||fraction.length<=6)return value;let scaled=BigInt(match[1]!+fraction.slice(0,6));if(fraction[6]!>="5")scaled+=1n;const integer=scaled/1_000_000n,decimal=(scaled%1_000_000n).toString().padStart(6,"0").replace(/0+$/u,"");return decimal?`${integer}.${decimal}`:integer.toString();}
