import { createHash } from "node:crypto";
import type { Pool } from "pg";
import { buildUseCycleStatus, type UseCycleIntakeRaw, type UseCycleRaw } from "@shadow/kernel";

function notificationId(subjectId:string,sourceType:string,sourceId:string,kind:string):string{return`notification_${createHash("sha256").update(`${subjectId}:${sourceType}:${sourceId}:${kind}`).digest("hex").slice(0,24)}`;}

export async function materializeNotifications(pool:Pool):Promise<number>{
  const due=await pool.query<{subject_id:string;id:string;scheduled_at:Date}>("select plan.subject_id,occurrence.id,(occurrence.due_on::timestamp+coalesce(plan.local_time,time '09:00')) at time zone plan.time_zone scheduled_at from recurring_occurrences occurrence join recurring_plans plan on plan.id=occurrence.plan_id where occurrence.state in ('pending','reminded','snoozed') and occurrence.due_on between current_date-1 and current_date+7");
  const failed=await pool.query<{subject_id:string;id:string;scheduled_at:Date}>("select subject_id,id,updated_at scheduled_at from library_processing_jobs where state='failed' and updated_at>=now()-interval '7 days'");
  const cycleResult=await pool.query<UseCycleRaw&{subject_id:string;as_of:string}>("select cycle.id,cycle.subject_id,cycle.purchase_record_id,cycle.purchase_item_id,cycle.item_name,cycle.started_on::text,cycle.ended_on::text,cycle.state,cycle.revision,cycle.initial_quantity::text,cycle.quantity_unit,cycle.expected_daily_usage::text,cycle.replenish_threshold::text,cycle.replenish_lead_days,cycle.time_zone,cycle.match_mode,cycle.match_value,cycle.reminder_enabled,to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as_of from use_cycles cycle where cycle.state='active' and cycle.reminder_enabled and cycle.match_mode<>'none'");
  const intakeResult=cycleResult.rows.length?await pool.query<UseCycleIntakeRaw&{cycle_id:string}>("select cycle.id cycle_id,item.id,item.name,item.food_ref_id,item.quantity::text,item.unit,item.amount_g::text,item.consumed_fraction::text from use_cycles cycle join meals meal on meal.subject_id=cycle.subject_id and meal.state='active' join intake_items item on item.meal_id=meal.id and item.subject_id=cycle.subject_id and item.effective where cycle.state='active' and cycle.reminder_enabled and ((cycle.match_mode='exact_name' and lower(btrim(regexp_replace(normalize(item.name,NFKC),'[[:space:]]+',' ','g')))=lower(btrim(regexp_replace(normalize(cycle.match_value,NFKC),'[[:space:]]+',' ','g')))) or (cycle.match_mode='food_ref' and item.food_ref_id=cycle.match_value)) and (case when meal.occurred_at is null then meal.occurred_on else (meal.occurred_at at time zone cycle.time_zone)::date end)>=cycle.started_on and (case when meal.occurred_at is null then meal.occurred_on else (meal.occurred_at at time zone cycle.time_zone)::date end)<=(clock_timestamp() at time zone cycle.time_zone)::date order by cycle.id,item.id"):({rows:[]} as {rows:Array<UseCycleIntakeRaw&{cycle_id:string}>});let inserted=0;
  for(const row of due.rows){const result=await pool.query("insert into notifications(id,subject_id,source_type,source_id,kind,redacted_title,redacted_body,scheduled_at) values($1,$2,'recurring_occurrence',$3,'due','有一项计划即将到期','打开 Shadow Life 查看详情。',$4) on conflict(subject_id,source_type,source_id,kind) do nothing",[notificationId(row.subject_id,"recurring_occurrence",row.id,"due"),row.subject_id,row.id,row.scheduled_at]);inserted+=result.rowCount??0;}
  for(const row of failed.rows){const result=await pool.query("insert into notifications(id,subject_id,source_type,source_id,kind,redacted_title,redacted_body,scheduled_at) values($1,$2,'library_processing_job',$3,'processing_failed','资料处理需要留意','打开 Shadow Life 查看失败状态并决定是否重试。',$4) on conflict(subject_id,source_type,source_id,kind) do nothing",[notificationId(row.subject_id,"library_processing_job",row.id,"processing_failed"),row.subject_id,row.id,row.scheduled_at]);inserted+=result.rowCount??0;}
  for(const cycle of cycleResult.rows){const status=buildUseCycleStatus(cycle,intakeResult.rows.filter(item=>item.cycle_id===cycle.id),cycle.as_of);if(status.balance_status!=="replenish_now"&&status.balance_status!=="depleted")continue;const result=await pool.query("insert into notifications(id,subject_id,source_type,source_id,kind,redacted_title,redacted_body,scheduled_at) values($1,$2,'use_cycle',$3,'replenishment','消耗品需要补货','打开 Shadow Life 查看确认后的剩余量。',now()) on conflict(subject_id,source_type,source_id,kind) do nothing",[notificationId(cycle.subject_id,"use_cycle",cycle.id,"replenishment"),cycle.subject_id,cycle.id]);inserted+=result.rowCount??0;}
  return inserted;
}
