import assert from "node:assert/strict";
import test from "node:test";
import { assignTripStopIds, parseGpx, portableDocument, publishTripPlan, serializeGpx, serializeTravelBundle, serializeTripIcs, tripPlanStopIds, tripRunIsComplete } from "../src/index.js";

test("published trip plans preserve explicit stops and deterministically identify historical ones",()=>{const first=publishTripPlan([{id:"trip_day_alpha",plan_date:"2026-10-02",items:[{title:"西湖"}]},{id:"trip_day_beta",plan_date:"2026-10-01",items:[{stop_id:"trip_stop_explicit",title:"杭州东站"}]}]);const second=publishTripPlan([{id:"trip_day_alpha",plan_date:"2026-10-02",items:[{title:"西湖"}]},{id:"trip_day_beta",plan_date:"2026-10-01",items:[{stop_id:"trip_stop_explicit",title:"杭州东站"}]}]);assert.deepEqual(first,second);assert.equal(first.days[0]!.plan_date,"2026-10-01");assert.equal(first.stop_count,2);assert.equal(tripPlanStopIds(first).size,2);});
test("published trip plans reject empty and duplicate stop identities",()=>{assert.throws(()=>publishTripPlan([]),/at least one day/u);assert.throws(()=>publishTripPlan([{id:"trip_day_alpha",plan_date:"2026-10-01",items:[]}]),/at least one stop/u);assert.throws(()=>publishTripPlan([{id:"trip_day_alpha",plan_date:"2026-10-01",items:[{stop_id:"trip_stop_same",title:"A"},{stop_id:"trip_stop_same",title:"B"}]}]),/Duplicate trip stop/u);});
test("day plan edits preserve only unambiguous stop identities",()=>{let sequence=0;const next=()=>`trip_stop_new_${++sequence}`;const result=assignTripStopIds([{stop_id:"trip_stop_old_a",title:"西湖"},{stop_id:"trip_stop_old_b",title:"西湖"},{stop_id:"trip_stop_old_c",title:"灵隐寺"}],[{title:"西湖"},{title:"西湖"},{title:"灵隐寺"}],next);assert.deepEqual(result.map(item=>item.stop_id),["trip_stop_new_1","trip_stop_new_2","trip_stop_old_c"]);assert.equal(tripRunIsComplete(new Set(result.map(item=>item.stop_id)),result.map(item=>item.stop_id)),true);assert.equal(tripRunIsComplete(new Set(result.map(item=>item.stop_id)),result.slice(1).map(item=>item.stop_id)),false);});
test("GPX import is bounded, rejects entity declarations, and round-trips track facts",()=>{const parsed=parseGpx('<?xml version="1.0"?><gpx><trk><name>西湖 &amp; 湖滨</name><trkseg><trkpt lat="30.25" lon="120.15"><ele>8.5</ele><time>2026-10-02T01:00:00Z</time></trkpt></trkseg></trk></gpx>');assert.equal(parsed.name,"西湖 & 湖滨");assert.deepEqual(parsed.points,[{latitude:30.25,longitude:120.15,elevation_m:8.5,recorded_at:"2026-10-02T01:00:00.000Z"}]);assert.deepEqual(parseGpx(serializeGpx("杭州",[{name:"轨迹",points:parsed.points}])).points,parsed.points);assert.throws(()=>parseGpx('<!DOCTYPE gpx [<!ENTITY x SYSTEM "file:///etc/passwd">]><gpx><trkpt lat="1" lon="1"></trkpt></gpx>'),/not allowed/u);assert.throws(()=>parseGpx('<gpx><trkpt lat="91" lon="1"></trkpt></gpx>'),/invalid coordinates/u);});
test("portable exports are deterministic and use exclusive all-day event end",()=>{const bundle=serializeTravelBundle({z:1,a:{d:2,c:3}});assert.equal(bundle,'{\n  "a": {\n    "c": 3,\n    "d": 2\n  },\n  "z": 1\n}\n');const ics=serializeTripIcs({id:"trip_hangzhou",title:"杭州,秋游",starts_on:"2026-10-01",ends_on:"2026-10-03",note:"第一天;出发"});assert.match(ics,/DTEND;VALUE=DATE:20261004/u);assert.match(ics,/SUMMARY:杭州\\,秋游/u);assert.deepEqual(portableDocument("ics","trip.ics","text/calendar",ics),portableDocument("ics","trip.ics","text/calendar",ics));});
