import { consumptionStatsInputSchema, domainRecordsResultSchema, foodCatalogInputSchema, foodCatalogResultSchema, healthDailyResultSchema, healthRecordResultSchema, healthSourcesResultSchema, healthTrendResultSchema, lifeRecordResultSchema, lifeSearchInputSchema, lifeSearchResultSchema, lifeTimelineInputSchema, lifeTimelineResultSchema, lifeTodayInputSchema, lifeTodayResultSchema, listMealsInputSchema, listMealsResultSchema, moneyImportReviewResultSchema, moneySummarySchema, travelExportInputSchema, travelExportResultSchema, travelTripResultSchema, travelWorkspaceInputSchema, travelWorkspaceResultSchema, type DomainRecordSummary, type LifeOverviewDomain, type MoneySummary } from "@shadow/contracts";
import { previewTravelPortableInputSchema, previewTravelPortableResultSchema, travelBundleSchema } from "@shadow/contracts";
import { libraryItemResultSchema, libraryProcessingQueueInputSchema, libraryProcessingQueueResultSchema } from "@shadow/contracts";
import { agentContextPackInputSchema, agentContextPackResultSchema, agentMemoriesInputSchema, agentMemoriesResultSchema, notificationsInputSchema, notificationsResultSchema } from "@shadow/contracts";
import { lifeReviewsInputSchema, lifeReviewsResultSchema, ownedItemsInputSchema, ownedItemsResultSchema } from "@shadow/contracts";
import { foreignEntriesInputSchema, foreignEntriesResultSchema, lifeProjectsInputSchema, lifeProjectsResultSchema, mealPlanningInputSchema, mealPlanningResultSchema, moneyPlanningResultSchema } from "@shadow/contracts";
import { planningAgendaInputSchema, planningAgendaResultSchema } from "@shadow/contracts";
import { invalidInput, notFound, permissionDenied } from "./errors.js";
import type { RequestContext, UnitOfWork } from "./ports.js";
import { parseGpx, portableDocument, serializeGpx, serializeTravelBundle, serializeTripIcs, validateTravelBundleSemantics, type TravelTrackPoint } from "./travel-portable.js";
import { buildConsumptionStats } from "./consumption-stats.js";

type Domain="money"|"health"|"travel"|"library";
type Cursor={domain:Domain;query:string;at:string;kind:string;id:string;as_of:string};
type LifeRecordSection="meal"|"purchase"|"money"|"sources";
type TimelineCursor={domains:string;at:string;domain:LifeOverviewDomain;kind:string;id:string;as_of:string};
type SearchCursor={signature:string;on:string;domain:LifeOverviewDomain;kind:string;id:string;as_of:string};
type NotificationCursor={at:string;id:string;as_of:string};
type MealCursor={on:string;at:string;id:string;as_of:string};
const overviewEffects:Record<LifeOverviewDomain,string>={meals:"life.meal.read",money:"money.entry.read",health:"health.measurement.read",travel:"travel.trip.read",library:"library.item.read"};
function objectEffect(kind:string):string{return kind==="meal"||kind==="purchase"?"life.meal.read":kind==="money_entry"?"money.entry.read":kind==="health_measurement"||kind==="health_workout"?"health.measurement.read":kind==="trip"?"travel.trip.read":"library.item.read";}
function lifeRecordWire(raw:unknown):unknown{
  const value=JSON.parse(JSON.stringify(raw)) as Record<string,unknown>;
  const object=(item:unknown):Record<string,unknown>=>item!==null&&typeof item==="object"&&!Array.isArray(item)?item as Record<string,unknown>:{};
  const rows=(item:unknown):Record<string,unknown>[]=>Array.isArray(item)?item.map(object):[];
  const pick=(item:Record<string,unknown>,keys:readonly string[])=>Object.fromEntries(keys.filter(key=>key in item).map(key=>[key,item[key]]));
  const times=(item:Record<string,unknown>,keys:readonly string[])=>{const result={...item};for(const key of keys)if(result[key]!==null&&result[key]!==undefined)result[key]=new Date(String(result[key])).toISOString();return result;};
  const intakeKeys=["id","meal_id","position","name","food_ref_id","free_text","quantity","unit","amount_g","energy_kcal","protein_g","fat_g","carb_g","fiber_g","sodium_mg","consumed_fraction","provenance","grouping_origin","estimate","evidence_note","revision"] as const;
  const moneyKeys=["id","record_id","entry_type","amount","currency","occurred_on","occurred_at","time_zone","note","category","counterparty","source_id","payment_method","source_scale","revision"] as const;
  const sourceKeys=["id","kind","external_id","captured_on","captured_at","time_zone","original_text","asset_version_id","revision"] as const;
  const money=(item:Record<string,unknown>)=>times(pick(item,moneyKeys),["occurred_at"]);
  const sources=(item:unknown)=>rows(item).map(row=>times(pick(row,sourceKeys),["captured_at"]));
  const intakes=(item:unknown)=>rows(item).map(row=>pick(row,intakeKeys));
  if("meal_id" in value){
    const result:Record<string,unknown>={kind:"meal",...times(pick(value,["meal_id","occurred_on","occurred_at","time_zone","meal_type","note","revision"]),["occurred_at"])};
    if("items" in value)result.items=intakes(value.items);
    if("payments" in value)result.payments=rows(value.payments).map(money);
    if("sources" in value)result.sources=sources(value.sources);
    return result;
  }
  const result:Record<string,unknown>={kind:"record",...times(pick(value,["record_id","state","occurred_on","occurred_at","time_zone","note","revision"]),["occurred_at"])};
  if("purchase" in value)result.purchase=value.purchase===null?null:times(pick(object(value.purchase),["id","record_id","merchant","amount","currency","category","occurred_on","occurred_at","time_zone","note","source_id","scene","channel_name_raw","place_ref","rating","would_repeat","revision"]),["occurred_at"]);
  if("purchase_items" in value)result.purchase_items=rows(value.purchase_items).map(row=>pick(row,["id","purchase_id","position","raw_name","quantity","unit_price","unit","line_amount","category_key"]));
  if("money_entry" in value)result.money_entry=value.money_entry===null?null:money(object(value.money_entry));
  if("meals" in value)result.meals=rows(value.meals).map(row=>({...pick(row,["id","occurred_on","meal_type","revision"]),items:intakes(row.items)}));
  if("sources" in value)result.sources=sources(value.sources);
  return result;
}
function healthRecordWire(raw:unknown):unknown{
  const value=JSON.parse(JSON.stringify(raw)) as Record<string,unknown>;
  const object=(item:unknown):Record<string,unknown>=>item!==null&&typeof item==="object"&&!Array.isArray(item)?item as Record<string,unknown>:{};
  const rows=(item:unknown):Record<string,unknown>[]=>Array.isArray(item)?item.map(object):[];
  const pick=(item:Record<string,unknown>,keys:readonly string[])=>Object.fromEntries(keys.filter(key=>key in item).map(key=>[key,item[key]]));
  const times=(item:Record<string,unknown>,keys:readonly string[])=>{const result={...item};for(const key of keys)if(result[key]!==null&&result[key]!==undefined)result[key]=new Date(String(result[key])).toISOString();return result;};
  const decimal=(item:unknown)=>item===null||item===undefined?null:String(item);
  const fact=object(value.fact),kind=String(value.kind);
  const keys:Record<string,readonly string[]>={
    measurement:["id","metric","value","unit","label","occurred_on","occurred_at","time_zone","note","source_id","raw_id","group_id","autofilled","effective","revision","created_at"],
    observation:["id","raw_id","raw_version","metric_key","position","value","unit","occurred_on","occurred_at","time_zone","group_id","group_kind","original_field","autofilled","effective","revision","created_at","related_observations"],
    daily_wellbeing:["id","raw_id","raw_version","occurred_on","time_zone","mood_score","energy_level","sleep_quality","morning_erection","notes","effective","revision","created_at"],
    sleep_session:["id","raw_id","raw_version","wake_date","time_zone","started_at","ended_at","total_minutes","deep_minutes","light_minutes","rem_minutes","awake_minutes","effective","revision","created_at"],
    workout_session:["id","raw_id","raw_version","plan_id","occurred_on","time_zone","session_type","started_at","duration_minutes","distance_km","calories_kcal","rpe","heart_rate_avg","detail","effective","revision","created_at"],
    daily_activity:["id","raw_id","raw_version","occurred_on","time_zone","steps","active_minutes","device_calories_kcal","workout_calories_kcal","effective_calories_kcal","field_sources","effective","revision","created_at","steps_started_at","steps_ended_at","steps_origin"],
    habit_log:["id","raw_id","raw_version","occurred_on","time_zone","habit_key","done_count","explicit_denial","note","effective","revision","created_at"]
  };
  const mapped=times(pick(fact,keys[kind]??[]),["occurred_at","started_at","ended_at","created_at","steps_started_at","steps_ended_at"]);
  if(kind==="observation")mapped.related_observations=rows(fact.related_observations).map(item=>pick(item,["id","metric_key","value","unit","original_field","autofilled"]));
  if(kind==="workout_session"){mapped.distance_km=decimal(fact.distance_km);mapped.calories_kcal=decimal(fact.calories_kcal);}
  const source=value.source===null?null:times(pick(object(value.source),["id","kind","external_id","captured_on","captured_at","time_zone","original_text","asset_version_id","revision"]),["captured_at"]);
  const rawView=value.raw===null?null:pick(object(value.raw),["id","record_type","client_record_id","current_version","state","parse_version","source_instance_id","source_type","source_instance_key"]);
  return{kind,fact:mapped,source,raw:rawView};
}
function travelTripWire(raw:unknown):unknown{
  const value=JSON.parse(JSON.stringify(raw)) as Record<string,unknown>;
  const object=(item:unknown):Record<string,unknown>=>item!==null&&typeof item==="object"&&!Array.isArray(item)?item as Record<string,unknown>:{};
  const rows=(item:unknown):Record<string,unknown>[]=>Array.isArray(item)?item.map(object):[];
  const pick=(item:Record<string,unknown>,keys:readonly string[])=>Object.fromEntries(keys.filter(key=>key in item).map(key=>[key,item[key]]));
  const decimal=(item:unknown)=>item===null||item===undefined?null:String(item);
  const tripKeys=["id","title","starts_on","ends_on","time_zone","note","revision","created_at"] as const;
  const reservationKeys=["id","trip_id","reservation_type","title","starts_at","ends_at","state","visibility","origin","destination","service_number","revision","created_at","confirmation_code","seat","fare_entry_id","source_id"] as const;
  const segmentKeys=["id","trip_id","mode","origin","destination","starts_at","ends_at","distance_km","visibility","revision","voided_at","created_at","source_id","note"] as const;
  const visitKeys=["id","trip_id","place_name","latitude","longitude","occurred_on","occurred_at","time_zone","visibility","revision","created_at","source_id","note"] as const;
  const planKeys=["id","trip_id","plan_date","items","revision","created_at"] as const;
  const versionKeys=["id","trip_id","version","label","note","snapshot","content_hash","created_at"] as const;
  const outcomeKeys=["stop_id","state","occurred_at","note","revision","updated_at"] as const;
  return{
    trip:pick(object(value.trip),tripKeys),
    reservations:rows(value.reservations).map(item=>pick(item,reservationKeys)),
    segments:rows(value.segments).map(item=>({...pick(item,segmentKeys),distance_km:decimal(item.distance_km)})),
    visits:rows(value.visits).map(item=>({...pick(item,visitKeys),latitude:decimal(item.latitude),longitude:decimal(item.longitude)})),
    day_plans:rows(value.day_plans).map(item=>pick(item,planKeys)),
    members:rows(value.members).map(item=>({member_id:item.subject_id,role:item.role,visibility:item.visibility,created_at:item.created_at})),
    plan_versions:rows(value.plan_versions).map(item=>pick(item,versionKeys)),
    my_runs:rows(value.my_runs).map(item=>({...pick(item,["id","trip_id","plan_version_id","state","started_at","completed_at"]),outcomes:rows(item.outcomes).map(outcome=>pick(outcome,outcomeKeys))})),
    revisions:rows(value.revisions).map(item=>({trip_id:item.trip_id,revision:item.revision,snapshot:pick(object(item.snapshot),tripKeys),reason:item.reason,created_at:item.created_at})),
    as_of:value.as_of
  };
}

export class QueryService {
  constructor(private readonly unitOfWork:UnitOfWork) {}
  async listMeals(context:RequestContext,input:unknown={}){
    if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");const parsed=listMealsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("meal list query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));let before:MealCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as MealCursor;}catch{throw invalidInput("meal cursor is invalid",["cursor"]);}if(!before.on||!before.at||!before.id||!before.as_of)throw invalidInput("meal cursor is invalid",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.listMeals(context.subjectId,{limit:parsed.data.limit,includeMoney:context.effects.has("money.entry.read"),...(before?{asOf:before.as_of,before:{on:before.on,at:before.at,id:before.id}}:{})})),last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({on:last.occurred_on,at:last._page_at,id:last.id,as_of:page.asOf} satisfies MealCursor)).toString("base64url"):null,items=page.items.map(({_page_at,...item})=>item);
    return listMealsResultSchema.parse({items,next_cursor:next,as_of:page.asOf});
  }
  async foodCatalog(context:RequestContext,input:unknown){if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");const parsed=foodCatalogInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("food catalog query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return foodCatalogResultSchema.parse(await this.unitOfWork.read(store=>store.foodCatalog(context.subjectId,parsed.data.query,parsed.data.limit)));}
  async summarizeMoney(context:RequestContext):Promise<MoneySummary>{if(!context.effects.has("money.summary.read"))throw permissionDenied("money.summary.read");return moneySummarySchema.parse(await this.unitOfWork.read(store=>store.summarizeMoney(context.subjectId)));}
  async listDomain(context:RequestContext,domain:Domain,options:{query?:string|undefined;limit?:number|undefined;cursor?:string|undefined}={}):Promise<{items:readonly DomainRecordSummary[];next_cursor:string|null;as_of:string}>{
    const effect=`${domain}.${domain==="library"?"item":domain==="health"?"measurement":domain==="travel"?"trip":"entry"}.read`;if(!context.effects.has(effect))throw permissionDenied(effect);
    const limit=options.limit??50;if(!Number.isInteger(limit)||limit<1||limit>100)throw invalidInput("limit must be between 1 and 100",["limit"]);const query=options.query?.trim().toLocaleLowerCase()??"";let asOf:string|undefined,before:Cursor|undefined;
    if(options.cursor){try{before=JSON.parse(Buffer.from(options.cursor,"base64url").toString("utf8")) as Cursor;}catch{throw invalidInput("cursor is invalid",["cursor"]);}if(before.domain!==domain||before.query!==query||!before.at||!before.kind||!before.id||!before.as_of)throw invalidInput("cursor does not match this query",["cursor"]);asOf=before.as_of;}
    const page=await this.unitOfWork.read(store=>store.listDomain(context.subjectId,domain,{...(query?{query}:{}),limit,...(asOf?{asOf}:{}),...(before?{before:{at:before.at,kind:before.kind,id:before.id}}:{})}));asOf=page.asOf;const items=page.items.map(({_page_at,...item})=>item);const last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({domain,query,at:last._page_at,kind:last.kind,id:last.id,as_of:asOf} satisfies Cursor)).toString("base64url"):null;return domainRecordsResultSchema.parse({items,next_cursor:next,as_of:asOf});
  }
  async healthTrend(context:RequestContext,input:{metric_key:string;from?:string|undefined;to?:string|undefined;limit:number}){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");return healthTrendResultSchema.parse(await this.unitOfWork.read(store=>store.healthTrend(context.subjectId,input)));}
  async healthSources(context:RequestContext){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");return healthSourcesResultSchema.parse(await this.unitOfWork.read(store=>store.healthSources(context.subjectId)));}
  async lifeToday(context:RequestContext,input:unknown){const parsed=lifeTodayInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("today query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const domains=this.overviewDomains(context,parsed.data.domains);return lifeTodayResultSchema.parse(await this.unitOfWork.read(store=>store.lifeToday(context.subjectId,parsed.data.date,parsed.data.time_zone,domains)));}
  async lifeTimeline(context:RequestContext,input:unknown){
    const parsed=lifeTimelineInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("timeline query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const domains=this.overviewDomains(context,parsed.data.domains),signature=domains.join(",");let before:TimelineCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as TimelineCursor;}catch{throw invalidInput("timeline cursor is invalid",["cursor"]);}if(before.domains!==signature||!before.at||!before.domain||!before.kind||!before.id||!before.as_of)throw invalidInput("timeline cursor does not match this query",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.lifeTimeline(context.subjectId,domains,{limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{at:before.at,domain:before.domain,kind:before.kind,id:before.id}}:{})})),last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({domains:signature,at:last.happened_at,domain:last.domain,kind:last.kind,id:last.id,as_of:page.asOf} satisfies TimelineCursor)).toString("base64url"):null;
    return lifeTimelineResultSchema.parse({items:page.items,next_cursor:next,as_of:page.asOf});
  }
  async lifeSearch(context:RequestContext,input:unknown){
    const parsed=lifeSearchInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("search query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));
    const domains=this.overviewDomains(context,parsed.data.types),signature=JSON.stringify({q:parsed.data.q.toLocaleLowerCase(),types:domains,from_on:parsed.data.from_on??null,to_on_exclusive:parsed.data.to_on_exclusive??null});let before:SearchCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as SearchCursor;}catch{throw invalidInput("search cursor is invalid",["cursor"]);}if(before.signature!==signature||!before.on||!before.domain||!before.kind||!before.id||!before.as_of)throw invalidInput("search cursor does not match this query",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.lifeSearch(context.subjectId,domains,{query:parsed.data.q.toLocaleLowerCase(),...(parsed.data.from_on?{fromOn:parsed.data.from_on}:{}),...(parsed.data.to_on_exclusive?{toOnExclusive:parsed.data.to_on_exclusive}:{}),limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{on:before.on,domain:before.domain,kind:before.kind,id:before.id}}:{})})),last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({signature,on:last.happened_on,domain:last.domain,kind:last.kind,id:last.id,as_of:page.asOf} satisfies SearchCursor)).toString("base64url"):null;
    return lifeSearchResultSchema.parse({items:page.items,next_cursor:next,as_of:page.asOf,applied_filters:{q:parsed.data.q,types:domains,from_on:parsed.data.from_on??null,to_on_exclusive:parsed.data.to_on_exclusive??null}});
  }
  async consumptionStats(context:RequestContext,input:unknown){
    if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");const parsed=consumptionStatsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("consumption stats query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));
    const monetary=parsed.data.merchant_rank_by!=="orders"||parsed.data.item_rank_by==="line_spend";if(monetary&&!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");const includeMoney=context.effects.has("money.entry.read");
    const data=await this.unitOfWork.read(store=>store.consumptionStatsData(context.subjectId,{fromOn:parsed.data.from_on,toOnExclusive:parsed.data.to_on_exclusive,timeZone:parsed.data.time_zone,includeMoney}));return buildConsumptionStats(data,parsed.data,includeMoney);
  }
  async lifeRecord(context:RequestContext,id:string,requested?:readonly LifeRecordSection[]){
    const sections=[...new Set(requested??[...(context.effects.has("life.meal.read")?["meal","purchase","sources"] as const:[]),...(context.effects.has("money.entry.read")?["money"] as const:[])])];
    if(!sections.length)throw permissionDenied("life.meal.read");
    if(sections.some(section=>section!=="money")&&!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");
    if(sections.includes("money")&&!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");
    const value=await this.unitOfWork.read(store=>store.lifeRecord(context.subjectId,id,sections));if(value===undefined)throw notFound("life record was not found");return lifeRecordResultSchema.parse(lifeRecordWire(value));
  }
  async moneyPlanning(context:RequestContext,period:string){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");if(!/^(?:0{3}[1-9]|0{2}[1-9]\d|0[1-9]\d{2}|[1-9]\d{3})-(0[1-9]|1[0-2])$/u.test(period))throw invalidInput("period must be a valid YYYY-MM",["period"]);return moneyPlanningResultSchema.parse(await this.unitOfWork.read(store=>store.moneyPlanning(context.subjectId,period)));}
  async moneyImportReview(context:RequestContext,batchId:string){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");const value=await this.unitOfWork.read(store=>store.moneyImportReview(context.subjectId,batchId));if(value===undefined)throw notFound("money import batch was not found");return moneyImportReviewResultSchema.parse(value);}
  async healthDaily(context:RequestContext,date:string){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");const value=await this.unitOfWork.read(store=>store.healthDaily(context.subjectId,date));if(value===undefined)throw notFound("health day was not found");const wire=JSON.parse(JSON.stringify(value)) as Record<string,unknown>;return healthDailyResultSchema.parse({occurred_on:wire.occurred_on,algorithm_version:wire.algorithm_version,result:wire.result,source_set_hash:wire.source_set_hash,revision:wire.revision,updated_at:new Date(String(wire.updated_at)).toISOString()});}
  async healthRecord(context:RequestContext,id:string){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");const value=await this.unitOfWork.read(store=>store.healthRecord(context.subjectId,id));if(value===undefined)throw notFound("health record was not found");return healthRecordResultSchema.parse(healthRecordWire(value));}
  async travelTrip(context:RequestContext,id:string){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const value=await this.unitOfWork.read(store=>store.travelTrip(context.subjectId,id));if(value===undefined)throw notFound("trip was not found");return travelTripResultSchema.parse(travelTripWire(value));}
  async travelWorkspace(context:RequestContext,input:unknown={}){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=travelWorkspaceInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("travel workspace query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const value=await this.unitOfWork.read(store=>store.travelWorkspace(context.subjectId,parsed.data.trip_id));if(value===undefined)throw notFound("trip was not found");return travelWorkspaceResultSchema.parse(value);}
  async travelExport(context:RequestContext,input:unknown){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=travelExportInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("travel export query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const raw=await this.unitOfWork.read(store=>store.travelExportData(context.subjectId,parsed.data.trip_id)) as {trip:{id:string;title:string;starts_on:string;ends_on:string;note?:string|null};tracks:Array<{name:string;points:TravelTrackPoint[]}>}|undefined;if(!raw)throw notFound("trip was not found");let content:string,mimeType:string,extension:string;if(parsed.data.format==="bundle"){content=serializeTravelBundle({format:"shadow-life.travel-bundle.v1",exported_trip:raw});mimeType="application/json";extension="json";}else if(parsed.data.format==="gpx"){content=serializeGpx(raw.trip.title,raw.tracks);mimeType="application/gpx+xml";extension="gpx";}else{content=serializeTripIcs(raw.trip);mimeType="text/calendar";extension="ics";}return travelExportResultSchema.parse(portableDocument(parsed.data.format,`${raw.trip.id}.${extension}`,mimeType,content));}
  async previewTravelPortable(context:RequestContext,input:unknown){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=previewTravelPortableInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("portable travel input is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));if(Buffer.byteLength(parsed.data.content,"utf8")>900_000)throw invalidInput("portable travel input exceeds 900000 bytes",["content"]);if(parsed.data.format==="gpx"){let track;try{track=parseGpx(parsed.data.content);}catch(error){throw invalidInput(error instanceof Error?error.message:"GPX is invalid",["content"]);}const latitudes=track.points.map(point=>point.latitude),longitudes=track.points.map(point=>point.longitude);return previewTravelPortableResultSchema.parse({format:"gpx",sha256:portableDocument("gpx","preview.gpx","application/gpx+xml",parsed.data.content).sha256,name:track.name,points:track.points.length,bounds:{south:Math.min(...latitudes),west:Math.min(...longitudes),north:Math.max(...latitudes),east:Math.max(...longitudes)}});}let decoded:unknown;try{decoded=JSON.parse(parsed.data.content);}catch{throw invalidInput("Travel Bundle is not valid JSON",["content"]);}const bundle=travelBundleSchema.safeParse(decoded);if(!bundle.success)throw invalidInput("Travel Bundle structure is invalid",bundle.error.issues.map(issue=>`content.${issue.path.join(".")}`));try{validateTravelBundleSemantics(bundle.data);}catch(error){throw invalidInput(error instanceof Error?error.message:"Travel Bundle semantics are invalid",["content"]);}const value=bundle.data.exported_trip;return previewTravelPortableResultSchema.parse({format:"bundle",sha256:portableDocument("bundle","preview.json","application/json",parsed.data.content).sha256,trip:{id:value.trip.id,title:value.trip.title,starts_on:value.trip.starts_on,ends_on:value.trip.ends_on,time_zone:value.trip.time_zone},counts:{places:value.places.length,maps:value.maps.length,reservations:value.reservations.length,segments:value.segments.length,visits:value.visits.length,day_plans:value.day_plans.length,plan_versions:value.plan_versions.length,tracks:value.tracks.length}});}
  async libraryItem(context:RequestContext,id:string){if(!context.effects.has("library.item.read"))throw permissionDenied("library.item.read");const value=await this.unitOfWork.read(store=>store.libraryItem(context.subjectId,id));if(value===undefined)throw notFound("library item was not found");return libraryItemResultSchema.parse(value);}
  async libraryProcessingQueue(context:RequestContext,input:unknown={}){if(!context.effects.has("library.processor.write"))throw permissionDenied("library.processor.write");if(!context.effects.has("library.asset.read"))throw permissionDenied("library.asset.read");const parsed=libraryProcessingQueueInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("library processing queue query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return libraryProcessingQueueResultSchema.parse(await this.unitOfWork.read(store=>store.libraryProcessingQueue(context.subjectId,parsed.data.kind,parsed.data.limit)));}
  async agentContextPack(context:RequestContext,input:unknown,threadId?:string){if(!context.effects.has("agent.run"))throw permissionDenied("agent.run");const parsed=agentContextPackInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("context pack query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const value=await this.unitOfWork.read(store=>store.agentContextPack(context.subjectId,parsed.data.context_pack_id,threadId)) as {object_refs?:Array<{kind:string}>}|undefined;if(!value)throw notFound("active context pack was not found");for(const ref of value.object_refs??[]){const effect=objectEffect(ref.kind);if(!context.effects.has(effect))throw permissionDenied(effect);}return agentContextPackResultSchema.parse(value);}
  async agentMemories(context:RequestContext,input:unknown={}){if(!context.effects.has("agent.run"))throw permissionDenied("agent.run");const parsed=agentMemoriesInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("memory query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const page=await this.unitOfWork.read(store=>store.agentMemories(context.subjectId,parsed.data.category,parsed.data.limit));return agentMemoriesResultSchema.parse({items:page.items.filter(value=>Array.isArray(value.evidence_refs)&&value.evidence_refs.every(ref=>ref&&typeof ref==="object"&&context.effects.has(objectEffect(String((ref as {kind?:unknown}).kind))))),as_of:page.asOf});}
  async notifications(context:RequestContext,input:unknown={}){
    if(!context.effects.has("notifications.read"))throw permissionDenied("notifications.read");
    const parsed=notificationsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("notification query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));
    let before:NotificationCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as NotificationCursor;}catch{throw invalidInput("notification cursor is invalid",["cursor"]);}if(!before.at||!before.id||!before.as_of)throw invalidInput("notification cursor is invalid",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.notifications(context.subjectId,{limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{at:before.at,id:before.id}}:{})})) as {items:Array<Record<string,unknown>&{id:string;_page_at:string}>;hasMore:boolean;preferences:unknown;asOf:string};
    const last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({at:last._page_at,id:last.id,as_of:page.asOf} satisfies NotificationCursor)).toString("base64url"):null,items=page.items.map(({_page_at,...item})=>item);
    return notificationsResultSchema.parse({items,next_cursor:next,preferences:page.preferences,as_of:page.asOf});
  }
  async ownedItems(context:RequestContext,input:unknown={}){if(!context.effects.has("life.item.read"))throw permissionDenied("life.item.read");const parsed=ownedItemsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("owned item query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return ownedItemsResultSchema.parse(await this.unitOfWork.read(store=>store.ownedItems(context.subjectId,parsed.data.state,parsed.data.limit,{purchase:context.effects.has("life.meal.read"),library:context.effects.has("library.item.read"),money:context.effects.has("money.entry.read")},parsed.data.id)));}
  async lifeReviews(context:RequestContext,input:unknown={}){if(!context.effects.has("life.review.read"))throw permissionDenied("life.review.read");const parsed=lifeReviewsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("life review query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const effects={money:"money.entry.read",meals:"life.meal.read",health:"health.measurement.read",items:"life.item.read",library:"library.item.read"} as const,authorized=Object.entries(effects).filter(([,effect])=>context.effects.has(effect)).map(([domain])=>domain);return lifeReviewsResultSchema.parse(await this.unitOfWork.read(store=>store.lifeReviews(context.subjectId,parsed.data.limit,authorized,parsed.data.id)));}
  async lifeProjects(context:RequestContext,input:unknown={}){if(!context.effects.has("life.project.read"))throw permissionDenied("life.project.read");const parsed=lifeProjectsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("life project query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const effects={trip:"travel.trip.read",health_plan:"health.measurement.read",recurring_plan:"money.entry.read",owned_item:"life.item.read",library_item:"library.item.read",money_entry:"money.entry.read",meal:"life.meal.read",recipe:"life.meal.read"} as const,kinds=Object.entries(effects).filter(([,effect])=>context.effects.has(effect)).map(([kind])=>kind);return lifeProjectsResultSchema.parse(await this.unitOfWork.read(store=>store.lifeProjects(context.subjectId,parsed.data.state,parsed.data.limit,kinds,parsed.data.id)));}
  async planningAgenda(context:RequestContext,input:unknown){const parsed=planningAgendaInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("planning agenda query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const visibility={includeProjects:context.effects.has("life.project.read"),includeMoney:context.effects.has("money.entry.read"),includeHealth:context.effects.has("health.measurement.read")};if(!Object.values(visibility).some(Boolean))throw permissionDenied("life.project.read");const value=await this.unitOfWork.read(store=>store.planningAgenda(context.subjectId,{fromOn:parsed.data.from_on,toOnExclusive:parsed.data.to_on_exclusive,timeZone:parsed.data.time_zone,limit:parsed.data.limit,...visibility}));return planningAgendaResultSchema.parse({from_on:parsed.data.from_on,to_on_exclusive:parsed.data.to_on_exclusive,time_zone:parsed.data.time_zone,items:value.items,truncated:value.truncated,as_of:value.asOf});}
  async mealPlanning(context:RequestContext,input:unknown={}){if(!context.effects.has("life.meal_plan.read"))throw permissionDenied("life.meal_plan.read");const parsed=mealPlanningInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("meal planning query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return mealPlanningResultSchema.parse(await this.unitOfWork.read(store=>store.mealPlanning(context.subjectId,parsed.data.limit)));}
  async purchaseItems(context:RequestContext,query:string|undefined,limit=50){if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");if(!Number.isInteger(limit)||limit<1||limit>100)throw invalidInput("limit must be between 1 and 100",["limit"]);if(query!==undefined&&query.length>200)throw invalidInput("query is too long",["q"]);return this.unitOfWork.read(store=>store.purchaseItems(context.subjectId,query?.trim().toLocaleLowerCase()||undefined,limit));}
  async foreignEntries(context:RequestContext,input:unknown={}){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");const parsed=foreignEntriesInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("foreign entry query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const includeTrip=context.effects.has("travel.trip.read");if(parsed.data.trip_id&&!includeTrip)throw permissionDenied("travel.trip.read");return foreignEntriesResultSchema.parse(await this.unitOfWork.read(store=>store.foreignEntries(context.subjectId,parsed.data.trip_id,parsed.data.limit,includeTrip)));}
  async agentPersonalContext(context:RequestContext){const aliasKinds=[...(context.effects.has("life.meal.read")?["food","meal_template"]:[]),...(context.effects.has("money.entry.read")?["merchant","payment_method"]:[])],includeMealTemplates=context.effects.has("life.meal.read");if(!aliasKinds.length&&!includeMealTemplates)return{aliases:[],mealTemplates:[]};return this.unitOfWork.read(store=>store.agentPersonalContext(context.subjectId,aliasKinds,includeMealTemplates));}
  private overviewDomains(context:RequestContext,requested?:readonly LifeOverviewDomain[]):LifeOverviewDomain[]{const available=(Object.keys(overviewEffects) as LifeOverviewDomain[]).filter(domain=>context.effects.has(overviewEffects[domain])).sort();if(!requested)return available;for(const domain of requested)if(!available.includes(domain))throw permissionDenied(overviewEffects[domain]);return[...new Set(requested)].sort();}
}
