import { domainRecordsResultSchema, foodCatalogInputSchema, foodCatalogResultSchema, healthSourcesResultSchema, healthTrendResultSchema, lifeSearchInputSchema, lifeSearchResultSchema, lifeTimelineInputSchema, lifeTimelineResultSchema, lifeTodayInputSchema, lifeTodayResultSchema, mealViewSchema, moneyImportReviewResultSchema, moneySummarySchema, travelExportInputSchema, travelExportResultSchema, travelWorkspaceInputSchema, type DomainRecordSummary, type LifeOverviewDomain, type MealView, type MoneySummary } from "@shadow/contracts";
import { previewTravelPortableInputSchema, travelBundleSchema } from "@shadow/contracts";
import { libraryProcessingQueueInputSchema } from "@shadow/contracts";
import { agentContextPackInputSchema, agentMemoriesInputSchema, notificationsInputSchema, notificationsResultSchema } from "@shadow/contracts";
import { lifeReviewsInputSchema, lifeReviewsResultSchema, ownedItemsInputSchema, ownedItemsResultSchema } from "@shadow/contracts";
import { foreignEntriesInputSchema, lifeProjectsInputSchema, lifeProjectsResultSchema, mealPlanningInputSchema, mealPlanningResultSchema, moneyPlanningResultSchema } from "@shadow/contracts";
import { planningAgendaInputSchema, planningAgendaResultSchema } from "@shadow/contracts";
import { invalidInput, notFound, permissionDenied } from "./errors.js";
import type { RequestContext, UnitOfWork } from "./ports.js";
import { parseGpx, portableDocument, serializeGpx, serializeTravelBundle, serializeTripIcs, validateTravelBundleSemantics, type TravelTrackPoint } from "./travel-portable.js";

type Domain="money"|"health"|"travel"|"library";
type Cursor={domain:Domain;query:string;at:string;kind:string;id:string;as_of:string};
type LifeRecordSection="meal"|"purchase"|"money"|"sources";
type TimelineCursor={domains:string;at:string;domain:LifeOverviewDomain;kind:string;id:string;as_of:string};
type SearchCursor={signature:string;on:string;domain:LifeOverviewDomain;kind:string;id:string;as_of:string};
type NotificationCursor={at:string;id:string;as_of:string};
const overviewEffects:Record<LifeOverviewDomain,string>={meals:"life.meal.read",money:"money.entry.read",health:"health.measurement.read",travel:"travel.trip.read",library:"library.item.read"};
function objectEffect(kind:string):string{return kind==="meal"||kind==="purchase"?"life.meal.read":kind==="money_entry"?"money.entry.read":kind==="health_measurement"||kind==="health_workout"?"health.measurement.read":kind==="trip"?"travel.trip.read":"library.item.read";}

export class QueryService {
  constructor(private readonly unitOfWork:UnitOfWork) {}
  async listMeals(context:RequestContext,limit=20):Promise<readonly MealView[]>{if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");if(!Number.isInteger(limit)||limit<1||limit>100)throw invalidInput("limit must be between 1 and 100",["limit"]);return mealViewSchema.array().parse(await this.unitOfWork.read(store=>store.listMeals(context.subjectId,limit,context.effects.has("money.entry.read"))));}
  async foodCatalog(context:RequestContext,input:unknown){if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");const parsed=foodCatalogInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("food catalog query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return foodCatalogResultSchema.parse(await this.unitOfWork.read(store=>store.foodCatalog(context.subjectId,parsed.data.query,parsed.data.limit)));}
  async summarizeMoney(context:RequestContext):Promise<MoneySummary>{if(!context.effects.has("money.summary.read"))throw permissionDenied("money.summary.read");return moneySummarySchema.parse(await this.unitOfWork.read(store=>store.summarizeMoney(context.subjectId)));}
  async listDomain(context:RequestContext,domain:Domain,options:{query?:string|undefined;limit?:number|undefined;cursor?:string|undefined}={}):Promise<{items:readonly DomainRecordSummary[];next_cursor:string|null;as_of:string}>{
    const effect=`${domain}.${domain==="library"?"item":domain==="health"?"measurement":domain==="travel"?"trip":"entry"}.read`;if(!context.effects.has(effect))throw permissionDenied(effect);
    const limit=options.limit??50;if(!Number.isInteger(limit)||limit<1||limit>100)throw invalidInput("limit must be between 1 and 100",["limit"]);const query=options.query?.trim().toLocaleLowerCase()??"";let asOf:string|undefined,before:Cursor|undefined;
    if(options.cursor){try{before=JSON.parse(Buffer.from(options.cursor,"base64url").toString("utf8")) as Cursor;}catch{throw invalidInput("cursor is invalid",["cursor"]);}if(before.domain!==domain||before.query!==query||!before.at||!before.kind||!before.id||!before.as_of)throw invalidInput("cursor does not match this query",["cursor"]);asOf=before.as_of;}
    const page=await this.unitOfWork.read(store=>store.listDomain(context.subjectId,domain,{...(query?{query}:{}),limit,...(asOf?{asOf}:{}),...(before?{before:{at:before.at,kind:before.kind,id:before.id}}:{})}));asOf=page.asOf;const items=page.items.map(({_page_at,...item})=>item);const last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({domain,query,at:last._page_at,kind:last.kind,id:last.id,as_of:asOf} satisfies Cursor)).toString("base64url"):null;return domainRecordsResultSchema.parse({items,next_cursor:next,as_of:asOf});
  }
  async healthTrend(context:RequestContext,input:{metric_key:string;from?:string|undefined;to?:string|undefined;limit:number}){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");return healthTrendResultSchema.parse(await this.unitOfWork.read(store=>store.healthTrend(context.subjectId,input)));}
  async healthSources(context:RequestContext){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");return healthSourcesResultSchema.parse(await this.unitOfWork.read(store=>store.healthSources(context.subjectId)));}
  async lifeToday(context:RequestContext,input:unknown){const parsed=lifeTodayInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("today query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const domains=this.overviewDomains(context,parsed.data.domains);return lifeTodayResultSchema.parse(await this.unitOfWork.read(store=>store.lifeToday(context.subjectId,parsed.data.date,parsed.data.time_zone,domains)));}
  async lifeTimeline(context:RequestContext,input:unknown){
    const parsed=lifeTimelineInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("timeline query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const domains=this.overviewDomains(context,parsed.data.domains),signature=domains.join(",");let before:TimelineCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as TimelineCursor;}catch{throw invalidInput("timeline cursor is invalid",["cursor"]);}if(before.domains!==signature||!before.at||!before.domain||!before.kind||!before.id||!before.as_of)throw invalidInput("timeline cursor does not match this query",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.lifeTimeline(context.subjectId,domains,{limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{at:before.at,domain:before.domain,kind:before.kind,id:before.id}}:{})})),last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({domains:signature,at:last.happened_at,domain:last.domain,kind:last.kind,id:last.id,as_of:page.asOf} satisfies TimelineCursor)).toString("base64url"):null;
    return lifeTimelineResultSchema.parse({items:page.items,next_cursor:next,as_of:page.asOf});
  }
  async lifeSearch(context:RequestContext,input:unknown){
    const parsed=lifeSearchInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("search query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));
    const domains=this.overviewDomains(context,parsed.data.types),signature=JSON.stringify({q:parsed.data.q.toLocaleLowerCase(),types:domains,from_on:parsed.data.from_on??null,to_on_exclusive:parsed.data.to_on_exclusive??null});let before:SearchCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as SearchCursor;}catch{throw invalidInput("search cursor is invalid",["cursor"]);}if(before.signature!==signature||!before.on||!before.domain||!before.kind||!before.id||!before.as_of)throw invalidInput("search cursor does not match this query",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.lifeSearch(context.subjectId,domains,{query:parsed.data.q.toLocaleLowerCase(),...(parsed.data.from_on?{fromOn:parsed.data.from_on}:{}),...(parsed.data.to_on_exclusive?{toOnExclusive:parsed.data.to_on_exclusive}:{}),limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{on:before.on,domain:before.domain,kind:before.kind,id:before.id}}:{})})),last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({signature,on:last.happened_on,domain:last.domain,kind:last.kind,id:last.id,as_of:page.asOf} satisfies SearchCursor)).toString("base64url"):null;
    return lifeSearchResultSchema.parse({items:page.items,next_cursor:next,as_of:page.asOf,applied_filters:{q:parsed.data.q,types:domains,from_on:parsed.data.from_on??null,to_on_exclusive:parsed.data.to_on_exclusive??null}});
  }
  async lifeRecord(context:RequestContext,id:string,requested?:readonly LifeRecordSection[]){
    const sections=[...new Set(requested??[...(context.effects.has("life.meal.read")?["meal","purchase","sources"] as const:[]),...(context.effects.has("money.entry.read")?["money"] as const:[])])];
    if(!sections.length)throw permissionDenied("life.meal.read");
    if(sections.some(section=>section!=="money")&&!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");
    if(sections.includes("money")&&!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");
    const value=await this.unitOfWork.read(store=>store.lifeRecord(context.subjectId,id,sections));if(value===undefined)throw notFound("life record was not found");return value;
  }
  async moneyPlanning(context:RequestContext,period:string){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");if(!/^(?:0{3}[1-9]|0{2}[1-9]\d|0[1-9]\d{2}|[1-9]\d{3})-(0[1-9]|1[0-2])$/u.test(period))throw invalidInput("period must be a valid YYYY-MM",["period"]);return moneyPlanningResultSchema.parse(await this.unitOfWork.read(store=>store.moneyPlanning(context.subjectId,period)));}
  async moneyImportReview(context:RequestContext,batchId:string){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");const value=await this.unitOfWork.read(store=>store.moneyImportReview(context.subjectId,batchId));if(value===undefined)throw notFound("money import batch was not found");return moneyImportReviewResultSchema.parse(value);}
  async healthDaily(context:RequestContext,date:string){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");const value=await this.unitOfWork.read(store=>store.healthDaily(context.subjectId,date));if(value===undefined)throw notFound("health day was not found");return value;}
  async healthRecord(context:RequestContext,id:string){if(!context.effects.has("health.measurement.read"))throw permissionDenied("health.measurement.read");const value=await this.unitOfWork.read(store=>store.healthRecord(context.subjectId,id));if(value===undefined)throw notFound("health record was not found");return value;}
  async travelTrip(context:RequestContext,id:string){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const value=await this.unitOfWork.read(store=>store.travelTrip(context.subjectId,id));if(value===undefined)throw notFound("trip was not found");return value;}
  async travelWorkspace(context:RequestContext,input:unknown={}){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=travelWorkspaceInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("travel workspace query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const value=await this.unitOfWork.read(store=>store.travelWorkspace(context.subjectId,parsed.data.trip_id));if(value===undefined)throw notFound("trip was not found");return value;}
  async travelExport(context:RequestContext,input:unknown){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=travelExportInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("travel export query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const raw=await this.unitOfWork.read(store=>store.travelExportData(context.subjectId,parsed.data.trip_id)) as {trip:{id:string;title:string;starts_on:string;ends_on:string;note?:string|null};tracks:Array<{name:string;points:TravelTrackPoint[]}>}|undefined;if(!raw)throw notFound("trip was not found");let content:string,mimeType:string,extension:string;if(parsed.data.format==="bundle"){content=serializeTravelBundle({format:"shadow-life.travel-bundle.v1",exported_trip:raw});mimeType="application/json";extension="json";}else if(parsed.data.format==="gpx"){content=serializeGpx(raw.trip.title,raw.tracks);mimeType="application/gpx+xml";extension="gpx";}else{content=serializeTripIcs(raw.trip);mimeType="text/calendar";extension="ics";}return travelExportResultSchema.parse(portableDocument(parsed.data.format,`${raw.trip.id}.${extension}`,mimeType,content));}
  async previewTravelPortable(context:RequestContext,input:unknown){if(!context.effects.has("travel.trip.read"))throw permissionDenied("travel.trip.read");const parsed=previewTravelPortableInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("portable travel input is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));if(Buffer.byteLength(parsed.data.content,"utf8")>900_000)throw invalidInput("portable travel input exceeds 900000 bytes",["content"]);if(parsed.data.format==="gpx"){let track;try{track=parseGpx(parsed.data.content);}catch(error){throw invalidInput(error instanceof Error?error.message:"GPX is invalid",["content"]);}const latitudes=track.points.map(point=>point.latitude),longitudes=track.points.map(point=>point.longitude);return{format:"gpx",sha256:portableDocument("gpx","preview.gpx","application/gpx+xml",parsed.data.content).sha256,name:track.name,points:track.points.length,bounds:{south:Math.min(...latitudes),west:Math.min(...longitudes),north:Math.max(...latitudes),east:Math.max(...longitudes)}};}let decoded:unknown;try{decoded=JSON.parse(parsed.data.content);}catch{throw invalidInput("Travel Bundle is not valid JSON",["content"]);}const bundle=travelBundleSchema.safeParse(decoded);if(!bundle.success)throw invalidInput("Travel Bundle structure is invalid",bundle.error.issues.map(issue=>`content.${issue.path.join(".")}`));try{validateTravelBundleSemantics(bundle.data);}catch(error){throw invalidInput(error instanceof Error?error.message:"Travel Bundle semantics are invalid",["content"]);}const value=bundle.data.exported_trip;return{format:"bundle",sha256:portableDocument("bundle","preview.json","application/json",parsed.data.content).sha256,trip:{id:value.trip.id,title:value.trip.title,starts_on:value.trip.starts_on,ends_on:value.trip.ends_on,time_zone:value.trip.time_zone},counts:{places:value.places.length,maps:value.maps.length,reservations:value.reservations.length,segments:value.segments.length,visits:value.visits.length,day_plans:value.day_plans.length,plan_versions:value.plan_versions.length,tracks:value.tracks.length}};}
  async libraryItem(context:RequestContext,id:string){if(!context.effects.has("library.item.read"))throw permissionDenied("library.item.read");const value=await this.unitOfWork.read(store=>store.libraryItem(context.subjectId,id));if(value===undefined)throw notFound("library item was not found");return value;}
  async libraryProcessingQueue(context:RequestContext,input:unknown={}){if(!context.effects.has("library.processor.write"))throw permissionDenied("library.processor.write");if(!context.effects.has("library.asset.read"))throw permissionDenied("library.asset.read");const parsed=libraryProcessingQueueInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("library processing queue query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return this.unitOfWork.read(store=>store.libraryProcessingQueue(context.subjectId,parsed.data.kind,parsed.data.limit));}
  async agentContextPack(context:RequestContext,input:unknown,threadId?:string){if(!context.effects.has("agent.run"))throw permissionDenied("agent.run");const parsed=agentContextPackInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("context pack query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const value=await this.unitOfWork.read(store=>store.agentContextPack(context.subjectId,parsed.data.context_pack_id,threadId)) as {object_refs?:Array<{kind:string}>}|undefined;if(!value)throw notFound("active context pack was not found");for(const ref of value.object_refs??[]){const effect=objectEffect(ref.kind);if(!context.effects.has(effect))throw permissionDenied(effect);}return value;}
  async agentMemories(context:RequestContext,input:unknown={}){if(!context.effects.has("agent.run"))throw permissionDenied("agent.run");const parsed=agentMemoriesInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("memory query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const values=await this.unitOfWork.read(store=>store.agentMemories(context.subjectId,parsed.data.category,parsed.data.limit));return{items:values.filter(value=>Array.isArray(value.evidence_refs)&&value.evidence_refs.every(ref=>ref&&typeof ref==="object"&&context.effects.has(objectEffect(String((ref as {kind?:unknown}).kind))))),as_of:new Date().toISOString()};}
  async notifications(context:RequestContext,input:unknown={}){
    if(!context.effects.has("notifications.read"))throw permissionDenied("notifications.read");
    const parsed=notificationsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("notification query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));
    let before:NotificationCursor|undefined;
    if(parsed.data.cursor){try{before=JSON.parse(Buffer.from(parsed.data.cursor,"base64url").toString("utf8")) as NotificationCursor;}catch{throw invalidInput("notification cursor is invalid",["cursor"]);}if(!before.at||!before.id||!before.as_of)throw invalidInput("notification cursor is invalid",["cursor"]);}
    const page=await this.unitOfWork.read(store=>store.notifications(context.subjectId,{limit:parsed.data.limit,...(before?{asOf:before.as_of,before:{at:before.at,id:before.id}}:{})})) as {items:Array<Record<string,unknown>&{id:string;_page_at:string}>;hasMore:boolean;preferences:unknown;asOf:string};
    const last=page.items.at(-1),next=page.hasMore&&last?Buffer.from(JSON.stringify({at:last._page_at,id:last.id,as_of:page.asOf} satisfies NotificationCursor)).toString("base64url"):null,items=page.items.map(({_page_at,...item})=>item);
    return notificationsResultSchema.parse({items,next_cursor:next,preferences:page.preferences,as_of:page.asOf});
  }
  async ownedItems(context:RequestContext,input:unknown={}){if(!context.effects.has("life.item.read"))throw permissionDenied("life.item.read");const parsed=ownedItemsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("owned item query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return ownedItemsResultSchema.parse(await this.unitOfWork.read(store=>store.ownedItems(context.subjectId,parsed.data.state,parsed.data.limit,{purchase:context.effects.has("life.meal.read"),library:context.effects.has("library.item.read"),money:context.effects.has("money.entry.read")})));}
  async lifeReviews(context:RequestContext,input:unknown={}){if(!context.effects.has("life.review.read"))throw permissionDenied("life.review.read");const parsed=lifeReviewsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("life review query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const effects={money:"money.entry.read",meals:"life.meal.read",health:"health.measurement.read",items:"life.item.read",library:"library.item.read"} as const,authorized=Object.entries(effects).filter(([,effect])=>context.effects.has(effect)).map(([domain])=>domain);return lifeReviewsResultSchema.parse(await this.unitOfWork.read(store=>store.lifeReviews(context.subjectId,parsed.data.limit,authorized)));}
  async lifeProjects(context:RequestContext,input:unknown={}){if(!context.effects.has("life.project.read"))throw permissionDenied("life.project.read");const parsed=lifeProjectsInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("life project query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const effects={trip:"travel.trip.read",health_plan:"health.measurement.read",recurring_plan:"money.entry.read",owned_item:"life.item.read",library_item:"library.item.read",money_entry:"money.entry.read",meal:"life.meal.read",recipe:"life.meal.read"} as const,kinds=Object.entries(effects).filter(([,effect])=>context.effects.has(effect)).map(([kind])=>kind);return lifeProjectsResultSchema.parse(await this.unitOfWork.read(store=>store.lifeProjects(context.subjectId,parsed.data.state,parsed.data.limit,kinds)));}
  async planningAgenda(context:RequestContext,input:unknown){const parsed=planningAgendaInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("planning agenda query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const visibility={includeProjects:context.effects.has("life.project.read"),includeMoney:context.effects.has("money.entry.read"),includeHealth:context.effects.has("health.measurement.read")};if(!Object.values(visibility).some(Boolean))throw permissionDenied("life.project.read");const value=await this.unitOfWork.read(store=>store.planningAgenda(context.subjectId,{fromOn:parsed.data.from_on,toOnExclusive:parsed.data.to_on_exclusive,timeZone:parsed.data.time_zone,limit:parsed.data.limit,...visibility}));return planningAgendaResultSchema.parse({from_on:parsed.data.from_on,to_on_exclusive:parsed.data.to_on_exclusive,time_zone:parsed.data.time_zone,items:value.items,truncated:value.truncated,as_of:value.asOf});}
  async mealPlanning(context:RequestContext,input:unknown={}){if(!context.effects.has("life.meal_plan.read"))throw permissionDenied("life.meal_plan.read");const parsed=mealPlanningInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("meal planning query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));return mealPlanningResultSchema.parse(await this.unitOfWork.read(store=>store.mealPlanning(context.subjectId,parsed.data.limit)));}
  async purchaseItems(context:RequestContext,query:string|undefined,limit=50){if(!context.effects.has("life.meal.read"))throw permissionDenied("life.meal.read");if(!Number.isInteger(limit)||limit<1||limit>100)throw invalidInput("limit must be between 1 and 100",["limit"]);if(query!==undefined&&query.length>200)throw invalidInput("query is too long",["q"]);return this.unitOfWork.read(store=>store.purchaseItems(context.subjectId,query?.trim().toLocaleLowerCase()||undefined,limit));}
  async foreignEntries(context:RequestContext,input:unknown={}){if(!context.effects.has("money.entry.read"))throw permissionDenied("money.entry.read");const parsed=foreignEntriesInputSchema.safeParse(input);if(!parsed.success)throw invalidInput("foreign entry query is invalid",parsed.error.issues.map(issue=>issue.path.join(".")));const includeTrip=context.effects.has("travel.trip.read");if(parsed.data.trip_id&&!includeTrip)throw permissionDenied("travel.trip.read");return this.unitOfWork.read(store=>store.foreignEntries(context.subjectId,parsed.data.trip_id,parsed.data.limit,includeTrip));}
  async agentPersonalContext(context:RequestContext){const aliasKinds=[...(context.effects.has("life.meal.read")?["food","meal_template"]:[]),...(context.effects.has("money.entry.read")?["merchant","payment_method"]:[])],includeMealTemplates=context.effects.has("life.meal.read");if(!aliasKinds.length&&!includeMealTemplates)return{aliases:[],mealTemplates:[]};return this.unitOfWork.read(store=>store.agentPersonalContext(context.subjectId,aliasKinds,includeMealTemplates));}
  private overviewDomains(context:RequestContext,requested?:readonly LifeOverviewDomain[]):LifeOverviewDomain[]{const available=(Object.keys(overviewEffects) as LifeOverviewDomain[]).filter(domain=>context.effects.has(overviewEffects[domain])).sort();if(!requested)return available;for(const domain of requested)if(!available.includes(domain))throw permissionDenied(overviewEffects[domain]);return[...new Set(requested)].sort();}
}
